### ISSUE TITLE
Memcached Web site has insecure .tar.gz download link - Firefox refuses to download it

### ISSUE THREAD

**Issue by rklrkl** [memcached/memcached#1009]
Firefox (and maybe other browsers?) cannot download the memcached tarball for the 1.6.19 release because the .tar.gz link on https://memcached.org/ is to http://www.memcached.org/files/memcached-1.6.19.tar.gz (an insecure download link cannot be downloaded by Firefox on a secure page).

Firefox's download dialogue pop-up actually displayed this in red:

"File not downloaded: Potential security risk - memcached.org"

It also dubiously left a zero-length memcached-1.6.19.tar.gz on the filestore (which I think is simply a bug that Firefox doesn't clean up itself properly). I then edited the download link to be
https://www.memcached.org/files/memcached-1.6.19.tar.gz and it downloaded fine with Firefox.

I'm using AlmaLinux 8 and Firefox 110.0.1 - apologies if this is the wrong place to report the issue...

**Comment by dormando** [comment]
Wow, I'm super sorry. I fixed that in a bunch of places but looks like I missed one on the website and one in the release notes. (ie; if you click into downloads from the top tab it was correct). Not sure how it took this long to get reported!

That's fixed now.
