### ISSUE TITLE
Memcache memory overflows configured limit

### ISSUE THREAD

**Issue by himanshusahu06** [memcached/memcached#1025]
**Describe the bug**
If memcache is running at it's peak (allocated_memory == numbytes) and new slab for a `non-existing slab class (p->slabs)` is requested then https://github.com/memcached/memcached/blob/1.6.19/slabs.c#L377 bypasses the memory limit check and allocated new page causing allocated_memory > numbytes which is not desirable.

Is this a **_bug of feature_**?

If this is a bug then following block should be 

```c
if (mem_limit && mem_malloced + len > mem_limit && p->slabs > 0 && g->slabs == 0) {
  ...
}
```

replaced with following piece of code.

```c
if (mem_limit && mem_malloced + len > mem_limit && g->slabs == 0) {
  ...
}
```

**_If it's a feature, can someone explain the reasoning behind this behaviour?_**

**To Reproduce**
1. start memcached server with -m parameter.
2. Keep filling a single slab till maxbytes != allocated_memory
3. Add a key in `non-existant slab-class` and compare the maxbytes and allocated_memory.

**Details**

Memcache version: 1.6.19
Command to run memcached: `docker run --rm -d --net=host memcached:1.6.19 memcached -m 6 -vvv`

<img width="500" alt="memory_exceed" src="https://user-images.githubusercontent.com/6474689/233174884-c196af7f-292d-41c4-9337-910d5c38220e.png">

**Comment by dormando** [comment]
It's a really old feature: people would set the memory limit very low, ie `-m 32`, run fine for a while, then one day completely break when an unused slab class tried to allocate a page. Then they would file a support ticket.

For any reasonable amount of memory assigned to the daemon this is usually an exact limit.
