### ISSUE TITLE
compile problem is found with gcc 7.3.0， memcached 1.4.33 

### ISSUE THREAD

**Issue by soulsoul** [memcached/memcached#1043]
**Describe the bug**
now compile problem is found with gcc 7.3.0， memcached 1.4.33 ,

uti1.c: In function歆[Oimuriencode_init缺
util.c:21:37: error:敛[o1msnprintf歆output may be truncated before the last format character [-werror=-format-truncation=-]
snprintf(str, 4，"%%%02x"，×);
util.c:21:13: note:[o1msnprintf歌output between 4 and 5 bytes into a destination of size 4
snpritf(str, 4, "%%%02x",' x);

**To Reproduce**
Any information useful for reproducing the bug or crash. Workload, changes in workload, versions affected. If seeing a new issue after an upgrade, please include both before and after versions.

**System Information**
 - OS/Distro:  linux 
 - Version of OS/distro:   
 - Version of memcached: 1.4.33
 - Hardware detail: libevent 2.0.22

**Detail (please include!)**
when  i compile the memcached  using 'make' cmd, then it show me the error info .  maybe show me that  the function  "snprintf"
2rd parameter is not suitable 。so  who can help me  ?

**Comment by dormando** [comment]
Does this happen with the latest version?

We don't provide fixes or support for older releases.

**Comment by dormando** [comment]
user never responded..
