### ISSUE TITLE
Question on `cmd_meta` counter in `STATS` response

### ISSUE THREAD

**Issue by QuChen88** [memcached/memcached#1060]
We noticed that in `STATS` response, the `cmd_meta` counter is not incremented when we execute the `mg` or `ms` commands. Instead, they only increment the `cmd_get` and `cmd_set` counters. Is this behavior expected or is it a bug?

**Comment by dormando** [comment]
there's a literal `meta` debug command that this counter represents (see doc/protocol.txt). Its usefulness is limited now that the meta protocol is complete so I might remove it.

**Comment by QuChen88** [comment]
OK understood. Thanks
