### ISSUE TITLE
Memcached Observed Generation field Feature

### ISSUE THREAD

**Issue by Dhru205** [memcached/memcached#1062]
Hi team,
I am running Memcached on kubernetes using OLM operator sdk as a operator approach.
So the feature I want to add in the Memcached is mentioned below.
I am attaching screenshots of one DB which has already in built feature of observed generation so that you can get the clarity of what exactly is the feature that I want to add in Memcached

![MicrosoftTeams-image (3)](https://github.com/apache/solr-operator/assets/69868710/d6470a1c-46b5-4eda-b8a6-183a149a3cdf)

As you can see in the above screenshot I checked the CR of Cassandra.

![MicrosoftTeams-image (4)](https://github.com/apache/solr-operator/assets/69868710/f404b730-64a0-4769-8d3e-9e06af2296b5)

The operator is in ready state and observed generation value is 1 since no changes are made in the configurations.

![MicrosoftTeams-image (5)](https://github.com/apache/solr-operator/assets/69868710/a3c2b4a5-f3a1-4396-aaf8-9ca3aaba2e43)
![MicrosoftTeams-image (6)](https://github.com/apache/solr-operator/assets/69868710/63d11c26-b459-4e59-b0a2-c1d0104432f4)

I  changed the CPU and resources of Cassandra and only after all the pods are up and running then only observed Gen value is changed from 1 to 2.

**Comment by dormando** [comment]
I'm sorry I have no idea what this is. Are you asking about a memcached kube connector operator thing? We don't have an official one of those (yet, I guess)

**Comment by dormando** [comment]
user never responded, closing.
