### ISSUE TITLE
Item deletion due to SET command with a large value

### ISSUE THREAD

**Issue by QuChen88** [memcached/memcached#1069]
I noticed that item is intentionally deleted when we try to `set` it with a very large value beyond the item size limit. See https://github.com/memcached/memcached/commit/5f54ede879939a160168fabbc8cfc462f28e0004

I noticed that other storage commands like `add/replace/append/prepend` with a large value won't delete the item. However, when using the meta command `ms`, it will always delete the item no matter which mode of operation it is in which is a bit inconsistent. Is this the intended behavior? i.e.

```
set key 0 0 1
a
STORED

replace key 0 0 1100000
<large-value>
SERVER_ERROR object too large for cache

get key
VALUE key 0 1
a
END

ms key 1100000 MR
<large-value>
SERVER_ERROR object too large for cache

get key
END
```

**Comment by dormando** [comment]
https://github.com/memcached/memcached/blob/master/proto_text.c#L2016

**Comment by dormando** [comment]
I tried to make it consistent with meta, it was inconsistent before.

**Comment by dormando** [comment]
Make sense? Should I close this?

**Comment by QuChen88** [comment]
Yes it is fine. I understand the current behavior now. Please close this.
