### ISSUE TITLE
Suggestion: flush_all_slow {timeinseconds} command

### ISSUE THREAD

**Issue by digirave** [memcached/memcached#1071]
We split memcached servers for various reasons including that in cases of needing to fluch cache, currently if we use only one server flush_all will have too high of an impact to empty the cache all at once. So we split memcached into several servers and run flush_all one at time to them and delay a short period in time.

I suggest a
flush_all_slow {timeinseconds}
command that empties the cache but slowly in {timeinseconds}

This could be helpful in many scenarios where the cache needs a reset, but reseting it all at once could cause "thundering herd" or other load problems.

Thank you.

**Comment by dormando** [comment]
First: Can you explain why you're having to flush your entire cache so often? That should be a very uncommon operation.

`flush_all` works by invalidating all of the pre-existing cache without touching the data. The next time an item is inspected (by fetch, lru crawler, or lru maintainer threads) it will be removed from cache. So there's no way to just say "invalidate everything but randomly and slowly" internally to memcached.

If you need this, please see the `lru_crawler metadump` command in `doc/protocol.txt`. You can write a program which fetches the key list and issues deletes at your desired rate.

**Comment by digirave** [comment]
Thank you for your reply.

Regarding "Can you explain why you're having to flush your entire cache so often? ".
Sometimes we change the way the data in our cache is parsed, and change all the cache values.
We don't do this often, but maybe a few times per year.

Of note, the current strategy we use is just making multiple memcached instances and then doing a staggered flush_all on them.

**Comment by dormando** [comment]
Thanks. Do you think my suggestion would work for you? Using `metadump` or `mgdump` to get a key list and delete as slowly as you want. You can even fetch and test the data to see if it's the old kind or new kind and only delete the old kind.

**Comment by digirave** [comment]
I would guess that, due to the sheer number of keys we have, that would not be a good strategy.
We do delete in less than a minute, just avoiding a total loss of cache that would cause sudden, huge performance problems if all caches were lost instantaneously.

**Comment by dormando** [comment]
It would be implemented the same exact way internally. There's no other way to slowly/partially invalidate keys. I don't follow how you expect this to work, sorry.

Are you saying you want the flush to take just a few seconds, but you have hundreds of millions of keys? Or are you doing this across many minutes?

**Comment by dormando** [comment]
closing since user never responded

**Comment by digirave** [comment]
Sorry for the late reply, I considered your late reply as it is not viable to develop.
What we do is split the requests to multiple memcached instances, then reset the instances one by one with a few seconds delay.
We found it much more stable server load wise then reseting all memcached at once.
