### ISSUE TITLE
./autogen.sh build script fails for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by vinita-pawar** [memcached/memcached#1113]
./autogen.sh script fails with autoconf errors on Ubuntu 22.04. 

**To Reproduce**
autoconf (GNU Autoconf) 2.71
automake (GNU automake) 1.16.1

Installation commands install the above latest versions for autotools. The autogen.sh script fails with macro errors.

**System Information**
 - OS/Distro: Ubuntu 22.04.4 LTS
 - Version of OS/distro:
 - Version of Memcached: 1.6.24

**Comment by dormando** [comment]
Did you install `build-essential` and other required packages?

**Comment by dormando** [comment]
user never responded
