### ISSUE TITLE
Libevent is required

### ISSUE THREAD

**Issue by iskyd** [memcached/memcached#1121]
**Describe the bug**
configure: error: libevent is required.

**To Reproduce**
```
curl -O https://memcached.org/files/memcached-1.6.26.tar.gz
tar zxvf memcached-1.6.26.tar.gz
cd memcached-1.6.26
./configure
```

**System Information**
 - OS/Distro: Ubuntu 
 - Version of OS/distro: 22.04
 - Version of memcached: 1.6.26
 - Hardware detail:

**Detail (please include!)**
During ./configure I got 
```
checking for libevent directory... configure: error: libevent is required.  You can get it from https://www.monkey.org/~provos/libevent/
      If it's already installed, specify its path using --with-libevent=/dir/
```

I have installed libevent doing apt install libevent-dev.
I also tried 
`./configure --with-libevent=/usr/lib/x86_64-linux-gnu/libevent.so`
but got the same result.

**Comment by dormando** [comment]
did any previous version of mc work or is this a new system?

I'm not sure how that could be broken for you unless libevent-dev didn't actually install, or you've messed with ld_config somehow.

**Comment by iskyd** [comment]
@dormando this is a new system. Also tried to re-install libevent-dev, and it seems everything is fine.

```
/usr/lib/x86_64-linux-gnu/libevent.so: symbolic link to libevent-2.1.so.7.0.1
usr/lib/x86_64-linux-gnu/libevent-2.1.so.7.0.1: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=4c26f7362d55dd3d9504a9fe94805a6235d480c7
```

**Comment by dormando** [comment]
Did you figure this out? I forgot to comment but I checked the tarball and a few other quick things and it's definitely something to do with the way your OS was installed.

**Comment by iskyd** [comment]
@dormando sorry for the late reply. I have now figured out that this is related to nix package manager. 
Just for reference to solve this problem using nix `libevent^out` must be installed.
