### ISSUE TITLE
Memcache behaves abnormally in windows php7 environment

### ISSUE THREAD

**Issue by Xiaohua-sky** [memcached/memcached#1131]
php7 memcached

```php
<?php
$memip='127.0.0.1';
$memport=11211;
$memdb = memcache_connect($memip, $memport);
$memdb->set("wjj2","ggggg",0,6000);
echo "good";


```

执行cmd

![img](https://img-mid.csdnimg.cn/release/static/image/mid/ask/bb73caec097347e0ad4f2b92bf184474.png "#left")

![img](https://img-mid.csdnimg.cn/release/static/image/mid/ask/58d76d9ba47d4941ae48ae551d3a9db2.png "#left")

使用ip访问,memcached set的key前面加了ip后两端

![img](https://img-mid.csdnimg.cn/release/static/image/mid/ask/0acd05a1d0aa450ba91c0243efb1d6b9.png "#left")

![img](https://img-mid.csdnimg.cn/release/static/image/mid/ask/3ac57054154548ac8be39bcbe0dd41e0.png "#left")

**Comment by dormando** [comment]
Sorry, I don't think I can help :(
