### ISSUE TITLE
macos - This server is not built with SASL support.

### ISSUE THREAD

**Issue by ArtemIsmagilov** [memcached/memcached#1143]
**Describe the bug**
- I'm trying to run memcached on macos with SASL authentication and I get the error - `This server is not built with SASL support`. How to solve this?
```bash
brew install memcached
memcached -d -p 11214 -S -Y ./tests/acceptance/data/auth_pwd.txt
```
```result
Run brew install memcached libmemcached
==> Downloading https://ghcr.io/v2/homebrew/core/memcached/manifests/1.6.27
==> Fetching memcached
==> Downloading https://ghcr.io/v2/homebrew/core/memcached/blobs/sha256:bbf5b1e791431a454dc810741ff6b9487d001b64db70bce6f3d8f1adf36aecd7
==> Downloading https://ghcr.io/v2/homebrew/core/libmemcached/manifests/1.0.[18](https://github.com/ArtemIsmagilov/emcache/actions/runs/9279648867/job/25532613863#step:7:19)_2-2
==> Fetching libmemcached
==> Downloading https://ghcr.io/v2/homebrew/core/libmemcached/blobs/sha256:652c9f9862e367e62acc5d2b1ddc[20](https://github.com/ArtemIsmagilov/emcache/actions/runs/9279648867/job/25532613863#step:7:21)d798e6f15c51bccbc69e642acd4df1be0a
==> Pouring memcached--1.6.27.arm64_sonoma.bottle.tar.gz
==> Caveats
To start memcached now and restart at login:
  brew services start memcached
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/memcached/bin/memcached -l localhost
==> Summary
🍺  /opt/homebrew/Cellar/memcached/1.6.27: 15 files, 530.8KB
==> Pouring libmemcached--1.0.18_2.arm64_sonoma.bottle.2.tar.gz
🍺  /opt/homebrew/Cellar/libmemcached/1.0.18_2: [23](https://github.com/ArtemIsmagilov/emcache/actions/runs/9279648867/job/25532613863#step:7:24)2 files, 2.5MB
==> Caveats
==> memcached
To start memcached now and restart at login:
  brew services start memcached
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/memcached/bin/memcached -l localhost
This server is not built with SASL support.
Error: Process completed with exit code 64.
```

**To Reproduce**
- look above

**System Information**
 - OS/Distro: Macos
 - Version of OS/distro: macos-latest(Github Action)
 - Version of memcached: 1.67
 - Hardware detail: standart on macos-latest(Github Action)

**Detail (please include!)**
Always include the output of `stats`, `stats settings`, and optionally `stats items` and `stats slabs`. These can be provided to a maintainer privately if necessary. Please sanitize anything secret from the data.
- Ok, I'll add this moment

If you have a segfault or crash, please try to resolve the crash with `addr2line`. If possible, get a core dump and include a full back trace.
- OK, I'll also add

**Comment by dormando** [comment]
I don't know, sorry. You need to tell brew to build it with sasl support and I'm not a brew expert. You need to add `--enable-sasl` to `configure` run and also install the dependency libraries.

**Comment by ArtemIsmagilov** [comment]
I installed the libraries and used these parameters, I still get all sorts of errors. On the forums they write that apparently this option is simply not supported

**Comment by dormando** [comment]
what forums? not supported by who?

**Comment by ArtemIsmagilov** [comment]
I tried with -S enabled, either I need to compile from sources or macos just doesn’t support it. It looks like you are also working with Linux, which does not need to download anything. You assume that the problem is in brew. I'm still figuring out how to somehow enable this feature for macos.

**Comment by dormando** [comment]
well you're not pointing out to "What people are saying" and you aren't providing any errors or info about what you're trying to do, so I can't really help you here. if you intend to solve it yourself that's fine.

**Comment by dormando** [comment]
user never supplied requested information, closing out.
