### ISSUE TITLE
No support in bash file for automake-1.15

### ISSUE THREAD

**Issue by Niteshvgupta** [memcached/memcached#115]
Automake 1.15 was released early this year. I believe this is now the default version on OSX (after installing XCode command line tools). 

I created a fork with a change, but wasn't sure if you wanted to deal with merging a whole repo for such a small change. So I figured I'd open up an issue. Let me know if you want me to create a pull request.

The change is here:

Former: `locate_binary automake-1.14 automake-1.13 automake-1.12 automake-1.11 automake-1.10 automake-1.9 automake-1.7`
New: `locate_binary automake-1.15 automake-1.14 automake-1.13 automake-1.12 automake-1.11 automake-1.10 automake-1.9 automake-1.7`

**Comment by dormando** [comment]
fixed this a better way in the 'next' branch. should go out in a release soon. thanks for pointing it out though.
