### ISSUE TITLE
memcached does not handling all passed arguments, even invalid ones

### ISSUE THREAD

**Issue by ArtemIsmagilov** [memcached/memcached#1155]
Simple example.

Incorrect
```text
Connected to 127.0.0.1
`watch` fetchers afsfds dsf sdf s df sd
OK
```
Incorrect
```text
Connected to 127.0.0.1
`stats` items afsfds dsf sdf s df sd
OK
```
Correct
```text
Connected to 127.0.0.1
`stats` fetchersafsfds dsf sdf s df sd
ERROR
```

However, if you simply pass it as indicated in the documentation with |(OR) and *(AND), then everything works. Maybe validation was not intended? This is mistake?

**Comment by dormando** [comment]
The parser ignores data in some instances. Some commands have a fixed number of tokens and it will error if you give it the wrong count, but stats and some commands have no technical limit on the amount of tokens the user can supply. It will ignore ones it doesn't end up using.

`watch` should probably error with unknown tokens, though.

**Comment by dormando** [comment]
```
watch fetchers afsfds dsf sdf s df sd
ERROR
```

I have no idea what you did here but watch does validate the input tokens and will throw an error.
