### ISSUE TITLE
watch command not show errors

### ISSUE THREAD

**Issue by ArtemIsmagilov** [memcached/memcached#1156]
i connected to memcached with watch mode
```text
watch fetchers
OK
```

I try send invalid command
```text
get aksldsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
CLIENT_ERROR bad command line format
```

But in watch mode no logs with this error - `CLIENT_ERROR bad command line format`

Did I understand the semantics of your `watch` mod correctly?

**Comment by dormando** [comment]
The watch fetchers/mutations commands are very limited. They only show successful commands and are mostly useful for inspecting a running instance (ie; looking at what keys are being accessed). Usually you don't have tons of malformed commands.

If you're developing client code and are trying to debug, running memcached with `-vvv` is probably more useful right now.
