### ISSUE TITLE
it's hard to understand the semantics of the misbehave command.

### ISSUE THREAD

**Issue by ArtemIsmagilov** [memcached/memcached#1160]
I would like to check the secure network using the misbehave command. After executing it, I get an ERROR error as expected. However, I don’t really understand, did the command work or is this command simply not there? Can we add some kind of message to be sure that this command worked?
Let me explain why I had difficulty. I enter dsads and get ERROR and that's how it should be. Then I enter misbehave\r\n and get ERROR. This is where I don’t understand whether this command worked or not. I’ll say right away that I’m new to using memcached and I really may not know something. Thanks in advance for your contributions to memcached and answers)

**Comment by dormando** [comment]
You should not use misbehave at all. That command is _only_ for the test suite. It's meant to force memcached to crash when testing its support of linux seccomp.

**Comment by ArtemIsmagilov** [comment]
Thank you very much for answering)
