### ISSUE TITLE
memcached does not support unix datagram type connection

### ISSUE THREAD

**Issue by ArtemIsmagilov** [memcached/memcached#1161]
I create memcached unix.
```bash
memcached -s unix_path
```
And I see that the unix socket type is STREAM.
Looks like you don't have the option to use datagram.

Also, I don’t get errors when I enter invalid arguments, for example
```bash
memcached -p asdklaskdlakdlsa
memcached -U asldaldalsdalsdas
...
```

It would be nice to receive errors and also use a Unix connection like Datagram to work over the UDP protocol. And since the unix connection works exclusively in the local visibility area, it will be safe and productive. Of course, I may not know something about the correctness of this approach, safety, feasibility and amount of work. What do you think?

**Comment by ArtemIsmagilov** [comment]
I would like to use the unix connection type `SOCK_DGRAM` https://en.wikipedia.org/wiki/Unix_domain_socket
Are you planning this feature?

**Comment by dormando** [comment]
No, not planned. This isn't actually useful. UDP isn't "faster" because some webpage said it is. SOCK_STREAM in a unix socket is _plenty_ fast. I've pulled over 80gbps via unix socket when fetching large values on modest hardware.

Not sure what that is about the error handling. guess I/someone can look at that before closing this...

**Comment by dormando** [comment]
Fwiw in general we don't do anything "for performance" without testing it first. If that thing increases the complexity it must pass a strict test to ensure it is a big performance gain.

**Comment by ArtemIsmagilov** [comment]
Thank you very much for answering)

**Comment by ArtemIsmagilov** [comment]
I wanted to find out why such a possibility exists at all. Here they basically write why https://stackoverflow.com/questions/13953912/difference-between-unix-domain-stream-and-datagram-sockets
