### ISSUE TITLE
Authentication Issue "CLIENT_ERROR unauthenticated"

### ISSUE THREAD

**Issue by Evanraisul** [memcached/memcached#1170]
I was trying to add authentication on Memcached using "--enable-sasl" flag. To set username and password, I was using --auth-file flag. Here, I mount a volume like "/usr/auth" and create a file named "auth.txt" where I used the format "username:password described in the official doc of Memcached. More formally, I used "-auth-file=/usr/auth/auth.txt" for storing username and password.
Now, my Memcached is running up. But, when I try to authenticate using this command "set foo 0 0 9\r\nuser pass\r\n", it is providing me "CLIENT_ERROR unauthenticated" error.
I want to know the actual way of Memcached authentication or is there something I am missing.

**Comment by dormando** [comment]
Sorry for the long response.

`--enable-sasl` is for a different security system (calls SASL) that the binary protocol uses. The auth you're trying to use is a basic text protocol authentication scheme that doesn't require any compilation changes.

If you could include you full start arguments that would be helpful. You can look at the test file in `t/ascii-auth.t` to see how this system is used. It uses an auth file at `t/authfile` from the tarball.

It starts memcached with `-Y t/authfile` and runs `set foo 0 0 7\r\nfoo bar\r\n` - note that these aren't literal \r\n's. If you're using telnet:

```
set foo 0 0 7
foo bar
```
hit enter after both lines.

You can use netcat/echo as well, make sure to use `echo -e` so the `\r\n`'s get interpreted.

**Comment by Evanraisul** [comment]
I am using Memcached with Kubernetes support. I am starting Memcached with "--auth-file=/usr/auth/auth.txt"  or "-Y /usr/auth/auth.txt" this flag by applying secret. This  is the only argument I am using before start Memcached. I used volume mount "/usr/auth/" in this path to store the auth.txt file. The auth.txt file is containing "foo:bar".

Then, I am using telnet command and connect through a Memcached's Pod:
Here, "demo" is namespace, "memcd-quickstart-0" is memcached's pod & port is 11211.

kubectl port-forward -n demo memcd-quickstart-0 11211
Forwarding from 127.0.0.1:11211 -> 11211
Forwarding from [::1]:11211 -> 11211
------
telnet 127.0.0.1 11211
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
set foo 0 0 7
foo bar
CLIENT_ERROR authentication failure

**Comment by dormando** [comment]
@Evanraisul  Can you try this from the directory of a compiled tarball? Without the k8s stuff:

```
$ ./memcached -Y ./t/authfile
[then from another terminal]
$ telnet localhost 11211
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
version
CLIENT_ERROR unauthenticated
set foo 0 0 7
foo bar
STORED
version
VERSION 1.6.31
```

Maybe your authfile is getting junk in it somehow? (windows line termination?)

I even tested this by deleting the second line in `t/authfile` so it was just `foo:bar` and still works.

**Comment by Evanraisul** [comment]
According to your say, I have tried that with k8s stuffs. But still getting "CLIENT_ERROR authentication failure".

The approach was :: [ I am using "Ubuntu 24.04 LTS" ][ Memcached version: 1.6.31 ]

First create the authfile -> /home/evan/authfile:
$ cat authfile
foo:bar⏎          

Then start the memcached with -Y flag:                        
$ memcached -Y /home/evan/authfile
---
Then from another window ->
$ telnet 127.0.0.1 11211
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
version
CLIENT_ERROR unauthenticated
set foo 0 0 7
foo bar
CLIENT_ERROR authentication failure

Don't getting the issue. Without "-Y flag", it working smoothly.

**Comment by dormando** [comment]
Can you use the actual authfile from the tarball for your test? memcached-1.6.x/t/authfile - do the same test avain but with literally this file from the source tarball

**Comment by Evanraisul** [comment]
I have tried several times. It is working perfectly when authfile contains more than one username:password.
But, it is not working when there is just one username:password in the authfile.

Is there any rule that the authfile must contain more than one username:password?
I only see that there is max-limit of username:password which is 8.

**Comment by dormando** [comment]
As noted in my comment I did try it with just one line and it was working. I'll check the code today to see if carriage returns could confuse it.

Would it be possible for you to hexdump one of your non-working files? I strongly suspect there's invisible junk in there.

**Comment by Evanraisul** [comment]
$ cat authfile
foo:bar⏎           

$ hexdump authfile > hexdump_authfile

$ cat hexdump_authfile
0000000 6f66 3a6f 6162 0072                    
0000007
.....
$ cat authfile
foo:bar⏎              

$ hexdump -C authfile > hexdump_authfile

$ cat hexdump_authfile
00000000  66 6f 6f 3a 62 61 72                              |foo:bar|
00000007

I think there is no invisible junk in the file & I tried with the both way. But, it is giving "CLIENT_ERROR authentication failure" when there is one username:password in the authfile.

**Comment by dormando** [comment]
Can you attach your failing authfile here? (using the file attachment feature, not copy/pasting)

I'll take a closer look as soon as I can.. I've tried similar things, and you can see there's a unit test that passes. I'm a bit confused as to how this is going wrong.

I took a look at the code and it's supposed to throw an error if it doesn't like the authfile for some reason.

**Comment by Evanraisul** [comment]
[auth.txt](https://github.com/user-attachments/files/17053871/auth.txt)

This is the file.

**Comment by dormando** [comment]
@Evanraisul Think I see that your authfile doesn't have a newline at the end of it. Thank you for providing the hex dumps, that lead me to the problem.

If I create the file with `echo -n "foo:bar" > ./t/authfile` it will fail to authenticate. However if I create the file with:
`echo "foo:bar" > ./t/authfile` it will authenticate just fine.

So the code bug on my end is a single line authfile without a newline of any kind at the end of it is failing to work.

Looks like a user submitted change fixing some security issue broke that this... I'll see if I can fix it without adding the security issue back.

In the authfile loader code `fgets` is being used to read lines from the file. The security fix makes it not attempt to load anything longer than the file, except `fgets` will return at most one fewer bytes than the size limit passed to it.

This means if you have `foo:bar\n` we will look at `foo:bar`. However if your file is _just_ `foo:bar` (without a newline), the program will load `foo:ba`

Thus, if you attempt to authenticate with `set key 0 0 6 foo ba` it might actually work... or just add a newline to your file for now.

I'll leave this issue open until I can fix the upstream code.

Thanks for the report! Sorry it was so weird.

**Comment by Evanraisul** [comment]
Anyway, thanks for your support.

**Comment by dormando** [comment]
Fixed for the next release finally, thanks!
