### ISSUE TITLE
Error trying to bind to an IPv6 address

### ISSUE THREAD

**Issue by lokedhs** [memcached/memcached#118]
When trying to bind memcached to the IPv6 localhost address, I get the following error:

```
$ memcached -l '[::1]'
Invalid port number: ":1]"failed to listen on TCP port 11211: Success
```

If I start memcached without arguments it properly binds using IPv6, so the problem seems to be in the parsing of the `-l` argument.

**Comment by dormando** [comment]
there's a PR with a fix in https://github.com/memcached/memcached/pull/98 - would you mind testing that branch and pinging back here? I've received a few complaints and it'd be nice to finally merge it.

**Comment by lokedhs** [comment]
I have confirmed that it works correctly. I was able to bind to the IPv6
localhost using the flag `-l '[::1]'`

**Comment by lokedhs** [comment]
I have confirmed that it works correctly. I was able to bind to the IPv6
localhost using the flag `-l '[::1]'`

**Comment by dormando** [comment]
cool beans. that patch is now in the 'next' tree and will be released soon.. I'll close this out.
