### ISSUE TITLE
TCP_NODELAY not set at accepted socket

### ISSUE THREAD

**Issue by dormando** [memcached/memcached#124]
https://code.google.com/p/memcached/issues/detail?id=377

seems to goof up when talking to windows clients? haven't validated.

**Comment by rmccullagh** [comment]
Adding this via setsockopt in `conn_listening` case would be easily done, no?

**Comment by dormando** [comment]
Can be done easily. Someone needs to validate and document that it's necessary and fixes the reported problem. I don't have windows anywhere so my best option would be internet digging.

**Comment by rmccullagh** [comment]
I have a windows machine, but I'm not sure about a "client" for windows except maybe the php memcached dll

**Comment by dormando** [comment]
I have no idea, I don't have windows and cannot confirm it myself.

**Comment by dormando** [comment]
going to close this. I don't think it's been reported ever since, and the only other time I've seen it was with libmemcached doing something silly.
