### ISSUE TITLE
Fix broken link of release notes 1.4.25

### ISSUE THREAD

**Issue by mckelvin** [memcached/memcached#134]
<img width="751" alt="screenshot 2015-12-17 16 50 33" src="https://cloud.githubusercontent.com/assets/865677/11865342/589e2286-a4de-11e5-8fe7-50db2b644caa.png">

https://code.google.com/p/memcached/wiki/ReleaseNotes1425 is broken, I guess https://github.com/memcached/memcached/wiki/ReleaseNotes1425 is the correct link. May be you should redirect https://code.google.com/p/memcached/wiki/ReleaseNotes1425 to the GitHub wiki page.

**Comment by dormando** [comment]
ah, my release script added that to the tag.. I updated it but missed a spot, thanks!
I can't actually redirect anything from google code. the old site has gone fully read-only. I'm slowly porting the wiki pages over during each release cycle.
