### ISSUE TITLE
failed cross-compilation

### ISSUE THREAD

**Issue by jinho10** [memcached/memcached#136]
While I was trying to cross-compile memcached for netbsd, but it failed in the test phase.. please help me! Full output is here...

./configure --prefix=/home/vagrant/rumprun-packages/pkgs --with-libevent=/home/vagrant/rumprun-packages/pkgs --host=x86_64-rumprun-netbsd
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-rumprun-netbsd
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for x86_64-rumprun-netbsd-strip... x86_64-rumprun-netbsd-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for x86_64-rumprun-netbsd-gcc... x86_64-rumprun-netbsd-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-rumprun-netbsd-gcc accepts -g... yes
checking for x86_64-rumprun-netbsd-gcc option to accept ISO C89... none needed
checking whether x86_64-rumprun-netbsd-gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of x86_64-rumprun-netbsd-gcc... gcc3
checking how to run the C preprocessor... x86_64-rumprun-netbsd-gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for icc in use... no
checking for clang in use... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether __SUNPRO_C is declared... no
checking for x86_64-rumprun-netbsd-gcc option to accept ISO C99... -std=gnu99
checking sasl/sasl.h usability... no
checking sasl/sasl.h presence... no
checking for sasl/sasl.h... no
checking for gcov... /usr/bin/gcov
checking for main in -lgcov... no
checking for library containing clock_gettime... none required
checking for library containing socket... none required
checking for library containing gethostbyname... none required
checking for libevent directory... /home/vagrant/rumprun-packages/pkgs
checking for library containing umem_cache_create... no
checking for library containing gethugepagesizes... no
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inttypes.h... (cached) yes
checking for sasl_callback_ft... no
checking for print macros for integers (C99 section 7.8.1)... yes
checking for an ANSI C-conforming const... yes
checking for socklen_t... yes
checking for endianness... configure: error: in `/home/vagrant/rumprun-packages/memcached/build':
configure: error: cannot run test program while cross compiling
See `config.log' for more details
Makefile:25: recipe for target 'build/Makefile' failed
make: *** [build/Makefile] Error 1

**Comment by rday** [comment]
@jinho10 I've got a couple patches which fix your issue in [my rumprun-packages repo] (https://github.com/CuriousLLC/rumprun-packages/tree/memcached_package/memcached)

You won't have ideal performance due to the NEED_ALIGN check. It is always set to 1 while cross-compiling. I'm still searching for a portable way to figure that out(ideas welcome!!). Then I can submit a PR.

**Comment by jinho10** [comment]
@rday thanks! I quickly tried your build.. but it did not work out for me in that the build failed with libevent errors..... is this my env problem? am I missing something?

x86_64-rumprun-netbsd-gcc -std=gnu99 -o conftest -g -O2 -pthread -pthread -I/home/jhwang/rumprun-packages/memcached/../pkgs/include  -I/home/jhwang/rumprun-packages/pkgs/include -L/home/jhwang/rumprun-packages/memcached/../pkgs/lib  -L/home/jhwang/rumprun-packages/pkgs/lib conftest.c -levent -lc
/home/jhwang/rumprun-packages/memcached/../pkgs/lib/libevent.a(select.o): In function `select_dispatch':
/home/jhwang/rumprun-packages/libevent/build/select.c:161: warning: warning: reference to compatibility select(); include <sys/select.h> to generate correct reference
/home/jhwang/rumprun-packages/memcached/../pkgs/lib/libevent.a(event.o): In function `gettime':
/home/jhwang/rumprun-packages/libevent/build/event.c:370: warning: warning: reference to compatibility clock_gettime(); include <time.h> to generate correct reference
/home/jhwang/rumprun-packages/memcached/../pkgs/lib/libevent.a(evutil.o): In function `evutil_ersatz_socketpair':
/home/jhwang/rumprun-packages/libevent/build/evutil.c:230: warning: warning: reference to compatibility socket(); include <sys/socket.h> for correct reference
/home/jhwang/rumprun-packages/memcached/../pkgs/lib/libevent.a(signal.o): In function `_evsig_set_handler':
/home/jhwang/rumprun-packages/libevent/build/signal.c:254: warning: warning: reference to compatibility sigfillset(); include <signal.h> for correct reference
/home/jhwang/rumprun-packages/memcached/../pkgs/lib/libevent.a(event.o): In function `gettime':
/home/jhwang/rumprun-packages/libevent/build/event.c:378: warning: warning: reference to compatibility gettimeofday(); include <sys/time.h> to generate correct reference
conftest: In function `evthread_notify_drain_eventfd':
/home/jhwang/rumprun-packages/libevent/build/event.c:2739: undefined reference to `__errno_location'
conftest: In function `evthread_notify_base_eventfd':
/home/jhwang/rumprun-packages/libevent/build/event.c:2019: undefined reference to `__errno_location'
conftest: In function `evthread_notify_base_default':
/home/jhwang/rumprun-packages/libevent/build/event.c:2006: undefined reference to `__errno_location'
conftest: In function `evthread_make_base_notifiable':
/home/jhwang/rumprun-packages/libevent/build/event.c:2783: undefined reference to `eventfd'
conftest: In function `fprintf':
/usr/include/x86_64-linux-gnu/bits/stdio2.h:97: undefined reference to `__fprintf_chk'
/usr/include/x86_64-linux-gnu/bits/stdio2.h:97: undefined reference to `__fprintf_chk'
/usr/include/x86_64-linux-gnu/bits/stdio2.h:97: undefined reference to `__fprintf_chk'
conftest: In function `event_mm_strdup_':
/home/jhwang/rumprun-packages/libevent/build/event.c:2697: undefined reference to `__strdup'
conftest: In function `fprintf':
/usr/include/x86_64-linux-gnu/bits/stdio2.h:97: undefined reference to `stderr'
/usr/include/x86_64-linux-gnu/bits/stdio2.h:97: undefined reference to `__fprintf_chk'
conftest: In function `event_err':
/home/jhwang/rumprun-packages/libevent/build/log.c:90: undefined reference to `__errno_location'
conftest: In function `event_warn':
/home/jhwang/rumprun-packages/libevent/build/log.c:101: undefined reference to `__errno_location'
conftest: In function `event_sock_err':
/home/jhwang/rumprun-packages/libevent/build/log.c:109: undefined reference to `__errno_location'
conftest: In function `event_sock_warn':
/home/jhwang/rumprun-packages/libevent/build/log.c:121: undefined reference to `__errno_location'
conftest: In function `open':
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:57: undefined reference to `__open_2'
conftest: In function `fstat':
/usr/include/x86_64-linux-gnu/sys/stat.h:469: undefined reference to `__fxstat'
conftest: In function `evutil_ersatz_socketpair':
/home/jhwang/rumprun-packages/libevent/build/evutil.c:210: undefined reference to `__errno_location'
/home/jhwang/rumprun-packages/libevent/build/evutil.c:222: undefined reference to `__errno_location'
/home/jhwang/rumprun-packages/libevent/build/evutil.c:281: undefined reference to `__errno_location'
/home/jhwang/rumprun-packages/libevent/build/evutil.c:226: undefined reference to `__errno_location'
conftest: In function `evutil_socket_connect':
/home/jhwang/rumprun-packages/libevent/build/evutil.c:482: undefined reference to `__errno_location'
conftest:/home/jhwang/rumprun-packages/libevent/build/evutil.c:516: more undefined references to `__errno_location' follow
conftest: In function `select_dispatch':
/home/jhwang/rumprun-packages/libevent/build/select.c:185: undefined reference to `__fdelt_chk'
/home/jhwang/rumprun-packages/libevent/build/select.c:187: undefined reference to `__fdelt_chk'
/home/jhwang/rumprun-packages/libevent/build/select.c:169: undefined reference to `__errno_location'
/home/jhwang/rumprun-packages/libevent/build/select.c:187: undefined reference to `__fdelt_chk'
conftest: In function `select_del':
/home/jhwang/rumprun-packages/libevent/build/select.c:302: undefined reference to `__fdelt_chk'
/home/jhwang/rumprun-packages/libevent/build/select.c:305: undefined reference to `__fdelt_chk'
conftest: In function `select_add':
/home/jhwang/rumprun-packages/libevent/build/select.c:277: undefined reference to `__fdelt_chk'
/home/jhwang/rumprun-packages/libevent/build/select.c:275: undefined reference to `__fdelt_chk'
conftest: In function `poll_dispatch':
/home/jhwang/rumprun-packages/libevent/build/poll.c:170: undefined reference to `__errno_location'
conftest: In function `epoll_init':
/home/jhwang/rumprun-packages/libevent/build/epoll.c:115: undefined reference to `epoll_create'
/home/jhwang/rumprun-packages/libevent/build/epoll.c:116: undefined reference to `__errno_location'
conftest: In function `epoll_apply_one_change':
/home/jhwang/rumprun-packages/libevent/build/epoll.c:265: undefined reference to `epoll_ctl'
/home/jhwang/rumprun-packages/libevent/build/epoll.c:298: undefined reference to `__errno_location'
/home/jhwang/rumprun-packages/libevent/build/epoll.c:266: undefined reference to `__errno_location'
/home/jhwang/rumprun-packages/libevent/build/epoll.c:271: undefined reference to `epoll_ctl'
/home/jhwang/rumprun-packages/libevent/build/epoll.c:280: undefined reference to `__errno_location'
/home/jhwang/rumprun-packages/libevent/build/epoll.c:288: undefined reference to `epoll_ctl'
conftest: In function `epoll_dispatch':
/home/jhwang/rumprun-packages/libevent/build/epoll.c:407: undefined reference to `epoll_wait'
/home/jhwang/rumprun-packages/libevent/build/epoll.c:412: undefined reference to `__errno_location'
conftest: In function `evsig_handler':
/home/jhwang/rumprun-packages/libevent/build/signal.c:371: undefined reference to `__errno_location'
conftest: In function `evsig_cb':
/home/jhwang/rumprun-packages/libevent/build/signal.c:145: undefined reference to `__errno_location'
collect2: error: ld returned 1 exit status

**Comment by jinho10** [comment]
hey, never mind. I got some time to look at this today, and found libevent was compiled with gcc for some reason. anyway, I will push README.md for the instruction.

**Comment by rday** [comment]
This package is released in rumpkernels now. You can probably close this issue out unless the maintainers have some ideas regarding the NEED_ALIGN piece.

**Comment by jinho10** [comment]
thanks, rday. I close the issue.
