### ISSUE TITLE
Evictions rate increased 3x  after enabling slab_automove and lru_maintainer at the same time 

### ISSUE THREAD

**Issue by mckelvin** [memcached/memcached#137]
I just upgraded a few memcached instances from version `1.4.5` to version [`1.4.24`](https://packages.gentoo.org/packages/net-misc/memcached), it works fine, but if I enable both slab_automove and lru_maintainer features (`-o slab_reassign,slab_automove,lru_crawler,lru_maintainer`) at the same time, the evictions rate increases from `N` to `4 x N`(and doesn't not increase anymore):

<img width="1154" alt="screenshot 2016-01-18 11 16 09" src="https://cloud.githubusercontent.com/assets/865677/12382485/3f125606-bdd5-11e5-8932-7126ff5cf699.png">

(the instance was started on 1/8)

I also tried a few permutations of these arguments:

(no image)
without `-o`: works fine (can not reproduce).

* * *

<img width="970" alt="screenshot 2016-01-18 11 29 29" src="https://cloud.githubusercontent.com/assets/865677/12382607/cbd6894e-bdd6-11e5-932d-8a1fa4d1216c.png">
with `-o lru_crawler`: works fine(the instance was started on 1/13).

* * *
<img width="915" alt="screenshot 2016-01-18 11 30 48" src="https://cloud.githubusercontent.com/assets/865677/12382635/1cf3b09a-bdd7-11e5-8732-a8cd692f2314.png">

with `-o lru_crawler,lru_maintainer`: works fine.(the instance was started on 1/13)

* * *
<img width="917" alt="screenshot 2016-01-18 11 32 38" src="https://cloud.githubusercontent.com/assets/865677/12382642/39c9b250-bdd7-11e5-8f1a-6e24466d514a.png">

with `-o slab_reassign`: works fine.(the instance was started on 1/15)

* * *
<img width="927" alt="screenshot 2016-01-18 11 33 41" src="https://cloud.githubusercontent.com/assets/865677/12382660/5bfff8a2-bdd7-11e5-9936-926094ee0b76.png">

with `-o slab_reassign,slab_automove`: works fine.(the instance was started on 1/15)

* * *

I noticed that the `slab_automove` is an experimental feature firstly introduced in [version 1.4.11](https://code.google.com/p/memcached/wiki/ReleaseNotes1411#Slab_Automove) and refactored in [version 1.4.25](https://github.com/memcached/memcached/wiki/ReleaseNotes1425) while not listed in the output `memcached -h` of version 1.4.24. Please close the issue if it's a known issue or already fixed in #113 .

**Comment by dormando** [comment]
the automover had a huge patch to it in .25 - you can read the changelog on the homepage about it.

any chance you could try that out?

**Comment by mckelvin** [comment]
@dormando I'll try `1.4.25` with `-o slab_reassign slab_automove lru_crawler lru_maintainer` later.

**Comment by mckelvin** [comment]
I failed to reproduce the issue in memcached 1.4.25! :smile: 

<img width="1141" alt="screenshot 2016-01-21 11 48 17" src="https://cloud.githubusercontent.com/assets/865677/12471065/e6eb308a-c034-11e5-9a58-0203c7b8bb31.png">
eviction rate of memcached 1.4.25 without -o (the instance was started on 1/18)

* * *

<img width="1141" alt="screenshot 2016-01-21 11 47 56" src="https://cloud.githubusercontent.com/assets/865677/12471064/e6d6a66a-c034-11e5-93ed-d932a9f537a1.png">
eviction rate of memcached 1.4.25 with `-o slab_reassign,slab_automove,lru_crawler,lru_maintainer` (the instance was started on 1/18)


* * *

I believe the issue could be reproduced in (or maybe before) 1.4.24 and it has been solved in 1.4.25 .

Good job @dormando !

**Comment by dormando** [comment]
Looks like your eviction rate is improved in the new code? I'm sure it could still use some tuning, so keep an eye on the new variables (as noted in doc/protocol.txt) and let me know if you see something worth improving on.

**Comment by mckelvin** [comment]
> Looks like your eviction rate is improved in the new code? 

<img width="840" alt="screenshot 2016-01-21 17 35 09" src="https://cloud.githubusercontent.com/assets/865677/12476584/5a093384-c065-11e5-8d4f-b0c17333716a.png">

(The green metric is the eviction rate of memcached 1.4.25 with `-o slab_reassign,slab_automove,lru_crawler,lru_maintainer`. The yellow is the eviction rate 3 days ago while running 1.4.24.)

@dormando Yes. As you can see, total evictions decreased a lot while max eviction rate every few hours doesn't change greatly.

**Comment by mnjul** [comment]
Sorry for bringing this up from the dead...but @mckelvin, could you tell me what graphical monitoring tool is it from your screenshots? Many, many thanks.
