### ISSUE TITLE
Make releases available over HTTPS

### ISSUE THREAD

**Issue by elithrar** [memcached/memcached#140]
Is there a desire to make release downloads available over HTTPS?

Although there are available via the [GitHub releases](https://github.com/memcached/memcached/releases) interface, there are no published SHA hashes for these releases. The published SHA-1's for the downloads via [memcached.org/downloads](http://memcached.org/downloads) don't match due to the way the tarballs are generated (modtimes differ, for starters).

I'd be more than happy to donate to cover the entire cost of TLS certs to make this happen (although there is obviously work to do beyond just buying certs). Alternatively, you could make the hashes available via a separate GitHub repository ([ala Redis](https://github.com/antirez/redis-hashes)) in a parseable format.

**Comment by dormando** [comment]
That's worth doing. I can add them to the SAN certificate already on the server when I refresh it soon... I also set up my GPG stuff on a yubikey so I can start dropping signatures with the releases.

not sure when I'll get to it but I'll definitely get to it.

**Comment by alager** [comment]
Just a note, there is a service for [free TLS certs](https://letsencrypt.org/) from Let's Encrypt.  No need to buy them for most use cases.

**Comment by dormando** [comment]
I was already using letsencrypt. Just refreshed the certificate and added memcached.org + www.memcached.org to it. Site seems to work okay over TLS now.
