### ISSUE TITLE
Google Code documentation is not available anymore

### ISSUE THREAD

**Issue by JelteF** [memcached/memcached#141]
This link is now dead: https://code.google.com/archive/p/memcached/wikis/NewStart.wiki

**Comment by dormando** [comment]
womp womp.

I started converting the wiki into github's format. There's a lot more to do though. Will try to do enough this weekend so I can convert more links?

**Comment by cbsmith** [comment]
Stung by this. Can't get to old release notes.

**Comment by rmccullagh** [comment]
+1 on this. I can't find the binary protocol documentation anywhere.

**Comment by JelteF** [comment]
I used "the way back machine" to get to the documentation. It works pretty
well.

**Comment by KomaBeyond** [comment]
so...now where could i can see the document?

**Comment by anavarre** [comment]
Also, only release notes are now available: https://github.com/memcached/memcached/wiki/ReleaseNotes

Those posted at https://code.google.com/archive/p/memcached/wikis/ReleaseNotesRID.wiki are no longer available.

**Comment by deimosfr** [comment]
http://wayback.archive.org/web/20160123131703/https://code.google.com/p/memcached/wiki/ReleaseNotes

**Comment by deimosfr** [comment]
Releases notes could be found here: http://wayback.archive.org/web/20160123131703/https://code.google.com/p/memcached/wiki/ReleaseNotes

**Comment by KomaBeyond** [comment]
@deimosfr That's great!! Well done!! Have a nice day!

**Comment by dormando** [comment]
I ported the release notes over to the new wiki and have been slowly porting/rewriting/updating pages from the old wiki into github. I've also uploaded the old wiki into a repo here: https://github.com/memcached/old-wiki/

Shouldn't take too long to get a majority of it up again. Feel free to submit PR's for missing information.
