### ISSUE TITLE
Support expiration time in float or milliseconds?

### ISSUE THREAD

**Issue by xanview** [memcached/memcached#143]
Currently the API says to list the expiration time in seconds. Could support for milliseconds or floats added? - e.g. expire every 0.2 seconds?

**Comment by dormando** [comment]
I don't think we'll get to do this. At least not in anywhere near-term. The internals pretty thoroughly assume whole seconds (and 32bit integers on relative timestamps) and a background thread updates ticks monotonically once per second, which is what the expiration times are checked against.

If you need super granular expiration, you can embed the data into your objects and check within the app.

sorry!
