### ISSUE TITLE
Google Code wiki link 404s

### ISSUE THREAD

**Issue by kmoe** [memcached/memcached#145]
The front page of the memcached [GitHub wiki](https://github.com/memcached/memcached/wiki) links to the following Google Code wiki: https://code.google.com/archive/p/memcached/wikis/NewStart.wiki

However, this page 404s. This is an issue as the GitHub wiki is missing several pages and directs the user to Google Code.

**Comment by dormando** [comment]
Apologies. I'm still trying to find enough time to finish converting the wiki over. :(

**Comment by kmoe** [comment]
That's okay! So is the wiki no longer publicly available?

**Comment by dormando** [comment]
You can view it via the wayback machine, but google code no longer displays it. Until I finish updating and porting it to github (much of it is out of date anyway).

**Comment by qcho** [comment]
Can't access https://code.google.com/archive/p/memcached/wikis/Tap.wiki

Wayback machine isn't helping:
Wayback Machine doesn't have that page archived.

Maybe you can upload the RAW stuff somewhere so the community can help you make the wikis up?

It's kind of weird not having the proper documentation anywhere on the internet.

**Comment by larryxiao** [comment]
The link for`API` on homepage is also pointing google code.

**Comment by dormando** [comment]
uploaded the raw old wiki here: https://github.com/memcached/old-wiki/

been porting pages over every couple days lately. shouldn't take too much longer.
