### ISSUE TITLE
Why slab class max is 64?

### ISSUE THREAD

**Issue by pensz** [memcached/memcached#147]
I find that `MAX_NUMBER_OF_SLAB_CLASSES ` was changed from 201 to 64 in commit https://github.com/memcached/memcached/commit/9bce42f27c88a88f94c5e5345ced205a0ab36e89.

```
/* slab class max is a 6-bit number, -1. */
#define MAX_NUMBER_OF_SLAB_CLASSES (63 + 1)
```

But why limit `MAX_NUMBER_OF_SLAB_CLASSES` to 64?

**Comment by dormando** [comment]
A change last year split the slab classes internally for the new LRU algorithm. There're now four using the same one-byte flag. The default factor had about 42 or 43 classes so it seemed reasonable to cap it there.

See: https://github.com/memcached/memcached/pull/97 for more technical details.

**Comment by pensz** [comment]
Thanks for your reply so quickly :)

But when `MAX_NUMBER_OF_SLAB_CLASSES` is limited to 64,  there will be a slab size explosion with small factor. such as :

```
slab class  59: chunk size     10944 perslab      95
slab class  60: chunk size     11824 perslab      88
slab class  61: chunk size     12776 perslab      82
slab class  62: chunk size     13800 perslab      75
slab class  63: chunk size   1048576 perslab       1
```

How to deal this situation ?

**Comment by dormando** [comment]
I don't have a solution for that yet. I'm hoping to be able to expand the slab class id to 16 bits at some point.. but it might need a backcompat mode for those who'd miss that extra byte.

Too many slab classes didn't work very well anyway; as your memory is spread too thin and you could end up unbalanced classes more easily. Improvements went in for that in the latest release, which was a big step for expanding it again.

**Comment by pensz** [comment]
em, so, It seems that the solution is set factor to default value.
Thanks!

**Comment by dormando** [comment]
You can set it slightly lower than default if that helps. like I said you can get an extra ~20 classes in there before you hit the limit. With the number you seemed to be trying to create you'll end up with slab class imbalance problems for sure.
