### ISSUE TITLE
build memcached error

### ISSUE THREAD

**Issue by Liqinhong** [memcached/memcached#148]
I use ./configure and make to build memcache.But fail：

[root@master memcached-1.4.25]# ./configure 
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for icc in use... no
checking for clang in use... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether __SUNPRO_C is declared... no
checking for gcc option to accept ISO C99... -std=gnu99
checking sasl/sasl.h usability... no
checking sasl/sasl.h presence... no
checking for sasl/sasl.h... no
checking for gcov... /usr/bin/gcov
checking for main in -lgcov... yes
checking for library containing clock_gettime... -lrt
checking for library containing socket... none required
checking for library containing gethostbyname... none required
checking for libevent directory... (system)
checking for library containing umem_cache_create... no
checking for library containing gethugepagesizes... -lhugetlbfs
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inttypes.h... (cached) yes
checking for sasl_callback_ft... no
checking for print macros for integers (C99 section 7.8.1)... yes
checking for an ANSI C-conforming const... yes
checking for socklen_t... yes
checking for endianness... little
checking for htonll... no
checking for library containing pthread_create... none required
checking for mlockall... yes
checking for getpagesizes... yes
checking for memcntl... no
checking for sigignore... yes
checking for clock_gettime... yes
checking for accept4... yes
checking for alignment... none
checking for GCC atomics... yes
checking for setppriv... no
checking umem.h usability... no
checking umem.h presence... no
checking for umem.h... no
checking for xml2rfc... /usr/bin/xml2rfc
checking for xsltproc... /usr/bin/xsltproc
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands

[root@master memcached-1.4.25]# make
make  all-recursive
make[1]: Entering directory `/root/memcached-1.4.25/memcached-1.4.25'
Making all in doc
make[2]: Entering directory `/root/memcached-1.4.25/memcached-1.4.25/doc'
make[2]: *** No rule to make target `.full', needed by `protocol-binary.txt'.  Stop.
make[2]: Leaving directory `/root/memcached-1.4.25/memcached-1.4.25/doc'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/memcached-1.4.25/memcached-1.4.25'
make: *** [all] Error 2

**Comment by Liqinhong** [comment]
memcached-1.4.25

**Comment by xl-liu** [comment]
I also met this error when i tried to 'make' in osx system.
A workaround is to bypass the make target for doc subdirectory.

In the generated Makefile, try to add following lines to bypass doc subdirectory under following lines in am__recursive_targets.
         `for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
         `
`	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "doc"; then \
	    continue; \
	  fi; \`

**Comment by dormando** [comment]
I'm a little confused as how you're getting that error. Can you give more background on your OS? distro version, make version, etc?

By default the toplevel 'make' doesn't do anything in the doc directory. You have to explicitly call make on the protocol-binary.txt file to get the error you listed:
```
$ make protocol-binary.txt
make: *** No rule to make target '.full', needed by 'protocol-binary.txt'.  Stop.
$ make protocol-binary.full
make: *** No rule to make target '.xml', needed by 'protocol-binary.full'.  Stop.
```

It's been so long since anyone's built that directory that I'm unsure how to make it work, even.

**Comment by dormando** [comment]
ah nevermind. if you have xml2rfc and xsltproc both installed configure will try to generate those files. I'll look into this.

**Comment by dormando** [comment]
Fix pushed to the next branch: https://github.com/memcached/memcached/commit/adb6a664a62989e5fd4585bb48be5df34a18bf31 will go out in the next release.

thanks!
