### ISSUE TITLE
Memcached urgent question.

### ISSUE THREAD

**Issue by tonyqs** [memcached/memcached#149]
Memcached urgent question:

i wants to know that when if memcached run-out the memory~ would it possibly conver the old data?

cuz we are fixing an tough case right now so  thanks for ur help!

**Comment by dustin** [comment]
This is not a bug report.

Fundamentally, you should never been in a situation where a [cache](https://en.wikipedia.org/wiki/Cache_(computing)) has any data in it that needs to be recovered, because it should never be a primary data store.
