### ISSUE TITLE
Adding a switch for the memlimit in item_cachedump

### ISSUE THREAD

**Issue by AlBundyLoves69** [memcached/memcached#153]
It is not really a bug but a feature request:

Could you consider to add a switch [for example -ml] for the variable memlimit in items.c which is used in item_cachedump()?

For the moment it is 2MB and because of this only a limited amount of keys is returned when running stats cachedump.

I don't really think it would negatively affect the program when you display a warning - like you already do when setting a higher value for the -I switch.

**Comment by dormando** [comment]
Since that's a debug command I don't think we'll be adding anything like that. Keep an eye on future development for new logging features which should help a lot. Also read over the wiki for ideas on how to do work without relying on cachedump.

sorry!
