### ISSUE TITLE
memcache.c:584 why not use allow_new_conns(false)

### ISSUE THREAD

**Issue by chenyufeng** [memcached/memcached#156]
in static void conn_close(conn *c) { } we modified allow_new_conns to false directly, is it different with using  use allow_new_conns(false)

**Comment by dormando** [comment]
I'm really sorry, I can't tell what you're asking for here. memcached.c:584 is setting allow_new_conns to true.

Are you asking about why the locks are in use? What exactly did you change and what is the diff? Is there a bug you ran into which you were trying to fix?

**Comment by dormando** [comment]
going to close this due to inactivity. re-open or open a new one if you can provide more detail.
