### ISSUE TITLE
memcached statistics total_items is less than cmd_set

### ISSUE THREAD

**Issue by christian-esken** [memcached/memcached#161]
The statistics on my memcached server show a strange relationship: total_items is less than cmd_set. I am not entirely sure that this is a bug, but it looks quite strange to me. I checked the statistics description in doc/protocol.txt and asked on http://stackoverflow.com/questions/37324108 without gaining further insight.

The only operations run on this server are "set" and "get", nothing else like "add", "replace", "delete" or CAS based operations.

When I go through the memcached source code, I see that any "normal" set (w/o CAS) will either replace or write the item, and both will increment total_items.

    do_store_item() {
        // ...
        if (old_it != NULL)
            item_replace(old_it, it, hv);
        else
            do_item_link(it, hv);
        // ...
    }

do_item_link() increases total_items, and item_replace() also calls  do_item_link(). Then how can total_items be less than cmd_set?

Excerpt from memcached stats (numbers indented for readability):

    STAT cmd_set          12827359728
    STAT total_items       4237422053
    STAT curr_items          60745375
    STAT expired_unfetched 9898430934
    STAT evicted_unfetched   30415090
    STAT evictions           30421532
    STAT reclaimed         9900995350

**Comment by dormando** [comment]
Any idea if you're issuing sets that fail? ie; key too long, OOM, value corruption, etc.

**Comment by christian-esken** [comment]
Key too long: no
Value corruption: no
OOM: Not on the OS level, but what if a Slab is full? This can be considered OOM as well. I haven't thought about that. I will dig into this.

Thanks for your answer. It has pointed me to some possible explanation. It would mean that we write only 1/3 of the items and the rest 2/3 are failing.

**Comment by dormando** [comment]
enable logging on one server and see what's coming through? It's possible I'm missing something, I haven't combed through the code yet.. I'll do that if you can't find anything. I'd be surprised if you had so many sets failing for some reason.

**Comment by christian-esken** [comment]
I will check whether "-v" or "-vv" options are enabled, and will post my findings. If you have other kinds of logging in mind, please let me know and I will also check that. I will have time this week to look into that and also the code.

**Comment by christian-esken** [comment]
Today I went through the memcached v1.2.25 code.  I only find "cmd_set" increments in  "complete_nread_ascii(conn *c), and one more for the binary protocol. So is the assumption correct that for an ASCII client each SET operation will go through "complete_nread_ascii()?

I only see few possible issues after incrementing the cmd_set statistics, and all are not likely. Allocations are already done (OOM should not happen), and either data is corrupted (no "\r\n") or store_item() fails.

**Comment by dormando** [comment]
I assume you mean 1.4.25?

**Comment by dormando** [comment]
Oh. I see it. This is pretty funny. This was introduced in 60d709425f570c684a17dd15c09d88888e2158a7 in 2003.

from items.c:
```
int do_item_link(item *it, const uint32_t hv) {
    [...]
    it->it_flags |= ITEM_LINKED;
    it->time = current_time;

    STATS_LOCK();
    stats.curr_bytes += ITEM_ntotal(it);
    stats.curr_items += 1;
    stats.total_items += 1;
    STATS_UNLOCK();
    [...]
}

void do_item_unlink(item *it, const uint32_t hv) {
    [...]
    if ((it->it_flags & ITEM_LINKED) != 0) {
        it->it_flags &= ~ITEM_LINKED;
        STATS_LOCK();
        stats.curr_bytes -= ITEM_ntotal(it);
        stats.curr_items -= 1;                                  <----------- note no decrement on total_items
        STATS_UNLOCK();
        assoc_delete(ITEM_key(it), it->nkey, hv);
        item_unlink_q(it);
        do_item_remove(it);
    }
}
```

But the code does things like:

```
void do_item_update(item *it) {
    [...]
    if (it->time < current_time - ITEM_UPDATE_INTERVAL) {

        if ((it->it_flags & ITEM_LINKED) != 0) {
            it->time = current_time;
            if (!settings.lru_maintainer_thread) {
                item_unlink_q(it);
                item_link_q(it);
            }
        }
    }
}
```

where each time something is bumped in the LRU it gets unlinked and then relinked, which increases total_items by one. So it has nothing to do with sets or sets failing, sorry for not checking this more closely. Seems like I have in the past and just not noticed it.

since total_items is defined as:
```
| total_items           | 32u     | Total number of items stored since        |
|                       |         | the server started                        |
```

... should probably move that increment somewhere else. Probably in memcached.c:do_store_item() but need to audit to double check that's the only path.

**Comment by dormando** [comment]
or I should sleep more... you said total_items is less than cmd_set... so this just makes it look like total_items should be *higher* than cmd_set.

nope, sorry. I'm stupid.

**Comment by dormando** [comment]
Here we go:

memcached.h:
```
struct stats {
    pthread_mutex_t mutex;
    unsigned int  curr_items;
    unsigned int  total_items;
```

it's just overflowing. but now I have two things to fix: one is to uint64_t both of those, and another is to call total_items++ less often.

**Comment by dormando** [comment]
deleted my other comment on account of it being completely wrong. rubbed the sleep from my eyes and saw the _q at the end of the other item_link's. item_link() is only called from do_store_item in memcached.c, either via direct call or via item_replace.

Just bumped a few of the stats from 32bit to 64bit uints and pushed to the 'next' branch for upcoming release. closing this out, thanks!

**Comment by christian-esken** [comment]
Yes, I was talking about 1.4.25.

**Comment by dormando** [comment]
keep an eye out for 1.4.26 (hopefully this week). that should fix it.

**Comment by christian-esken** [comment]
I see the release 1.4.26 has emerged. I will test it soon. Thanks for fixing.
