### ISSUE TITLE
Will memcached work reliably for implementing a locking mechanism?

### ISSUE THREAD

**Issue by varmanishant** [memcached/memcached#163]
http://stackoverflow.com/questions/37458587/can-memcached-be-used-for-locking

Is it possible that Memcache doesn't `get` reliably due to some performance reason even if the `key` is present i.e it is has been `set` before? Lets say the no: of concurrent users is 24, and the request load is higher for example.

How about `set`, is it possible that a `set None` i.e a delete operation can fail without a reason leaving the `key` intact in Memcache?  Will `add` help me in anyway better?

In other words can I Implement a locking Mechanism using Memcached? Name says 'memcached' and I have read that it might actually remove data if it thinks its too much using LRU algorithm which is bad already but it might impact only if the volume is huge. But if `get` and `set` is not reliable like Database then it will not work for any logical operations. For Caching it is fine but it usually doesn't work well if you have any logic assosiated with that.

For example, for locking we have a logic that checks if key is present then deny access to the end user. I am seeing that very rarely both users are able to access the resource and I am not able to understand why this is happening.

**Comment by dormando** [comment]
https://github.com/memcached/memcached/wiki/ProgrammingTricks#ghetto-central-locking
(plus some of the other Usage pages on the wiki might be helpful). If you're using it to block access to banned users memcached really should be caching the state from something more persistent underneath.

**Comment by dormando** [comment]
(to half answer your other questions: no, gets won't fail "for performance reasons" from the server itself. Also sets overwriting a key that fail remove the original key, acting as a delete).

If you're having random get failures, you'd also be having random set failures. You'd be having issues with your configuration somewhere: https://github.com/memcached/memcached/wiki/Timeouts but fundamentally it doesn't just break when you do those sorts of things.

**Comment by varmanishant** [comment]
Thanks @dormando for your response.

We are implementing a simple lock mechanism like this - suppose we have two admin users A and B trying to access a certain persons page, we need to give write access to only the first guy and deny it for the second guy. We do this by a simple logic like this - lookup if the patient key already exists in memcache i.e `get key`. If it exists, then the user requesting access is denied, else a key is `set` and access is given for that user.

So I think my doubt about `gets` and `sets` is clarified. We will have three scenarios where we do `set key = value` 1) no key is present in memcache - its a potential problem for us because it doesn't lock as expected 2) key is present in memcache - ideally this wont happen because a set will happen only if get returns empty so our logic should prevent this 3) value is None to delete the key - this will work just as expected even if its a miss because you say that the key will be deleted even if its a miss.
 
Now I will have a look at the configuration details things like cache expiry etc. I read that it might remove LRU contents for example. If this happens then I can't have a guaranteed lock right? I also need to think how we are handling the scenario where memcache server is disconnected and how our application is handling this.

**Comment by dormando** [comment]
Did you read the wiki page I linked? It uses add. Using get and set isn't reliable at all, there's a race condition between your get and your set. Also sets override sets, but an add will fail if it's already set (though some clients don't expose the failure to the client!).

And again; you really can't rely on memcached for doing that if there would be a data problem if the lock fails. Ghetto locks are useful for instances where you want *generally reduce* the number of concurrent users to a thing. IE: The number of users generating a heavyweight response, or rate limiting. See: https://github.com/memcached/memcached/wiki/ProgrammingTricks#avoiding-stampeding-herd

If you could corrupt or otherwise do any damage to data if the lock fails, you should really be using your database in some atomic manner. IE: marking user A's session in the DB and associating it with the person's page somehow (with a timeout value, probably), and then caching the session in memcached. If the key goes missing, user A gets their session back. User B still sees that the record is locked via the main datastore.

**Comment by varmanishant** [comment]
@dormando You mean this scenario right?

User A's thread:
```
if not memcache.get():
         memcache.set('key')

```
User B's thread
```
if not memcache.get():
         memcache.set('key')
```
Its possible that both the `get` returned no value so `set` happened for both users?

**Comment by dormando** [comment]
That is correct. That's the definition of a race condition.

https://github.com/memcached/memcached/wiki/ProgrammingTricks#ghetto-central-locking shows the safe pattern to avoid race conditions.

**Comment by varmanishant** [comment]
This helps me understand this problem. As a side note, I wrote a small script to simulate this race condition, not sure if it is 100% correct https://bpaste.net/show/47389fa01552. Can anyone have a double check on this and let me know if that proves the point? I just wanted to demonstrate the race condition to some of our team mates so that I convince them to move over the API to `add`. There seems to be no reason to use `get` and `set` when `add` is more safer.

**Comment by praveshkumar0105** [comment]
Hi,
I think we can use  setIfAbsent method to avoid the race condition and original solution provided by Nishant should work. Any thought?
