### ISSUE TITLE
memcached.org download invalid gzip file

### ISSUE THREAD

**Issue by centminmod** [memcached/memcached#168]
official site memcached.org version of download at http://www.memcached.org/files/memcached-1.4.26.tar.gz is not 100% valid see below screenshot the one at 1600KB is memcached.org downloaded one and below is one i redid a tar + gzip on

```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: memcached-1.4.26.tar.gz extraction failed.
```

![image](https://cloud.githubusercontent.com/assets/5899584/16250695/c3e6b9f0-3862-11e6-8b8e-6218f2352742.png)

problem is when i download from windows 8 as well as centos 6.8 and 7.2

**Comment by dormando** [comment]
what browser are you using to fetch? It seems like some browsers are auto-decompressing the file, but leaves the file extension with .gz on... so you end up with a tar file.

**Comment by centminmod** [comment]
chrome 51 and opera 38 on windows and wget on centos 6.8

**Comment by dormando** [comment]
should be fixed now. apparently my apache config that's been slowly modified since 1999 had some defaults which no longer make sense.

re-open if not fixed, but I just tested and chrome wasn't gunzipping the file for me.

thanks!
