### ISSUE TITLE
typos: gets not get in tutorial

### ISSUE THREAD

**Issue by rwehrli** [memcached/memcached#187]
http://www.tutorialspoint.com/memcached/memcached_cas.htm

Contains two instances where 'gets' is used instead of 'get'.  One in the textual description:

We use gets command to retrieve CAS number of any item.

...and one in the telnet 'code' session:

gets tp
VALUE tp 0 9 1
memcached
END

**Comment by dormando** [comment]
we don't run or own or are affiliated with that website. please submit this to them instead.
