### ISSUE TITLE
can you help to release memcached for windows

### ISSUE THREAD

**Issue by mmcer** [memcached/memcached#194]
I think it is necessary to release official build of memcached for windows.
Thanks.

**Comment by dormando** [comment]
Unfortuantely I don't have any clue how windows works, and none of the past ports of memcached were mergable or remotely maintainable.

Recently there may be another path: https://www.linux.com/learn/howdy-ubuntu-windows-getting-started - if you're serious about this, try this situation and see if the ubuntu packages run.

**Comment by knoxcard** [comment]
I am running memcached in my Windows dev environment, I used this.
https://commaster.net/content/installing-memcached-windows

**Comment by rmccullagh** [comment]
@knoxcard is the source for that binary available? Also, how is it's own implementation of the Memcached protocol, or a real port?
