### ISSUE TITLE
Test t/refhang.t failing on s390x

### ISSUE THREAD

**Issue by guikcd** [memcached/memcached#197]
The testsuite fail for the s390x on the buildd Debian system:

```
[...]
t/noreply.t ................. ok

#   Failed test 'some ooms happened'
#   at t/refhang.t line 51.

#   Failed test 'nonzero lrutail_reflocked'
#   at t/refhang.t line 53.
#          got: '0'
#     expected: anything else

#   Failed test 'nonzero total lrutail_reflocked'
#   at t/refhang.t line 56.
#          got: '0'
#     expected: anything else
# Looks like you failed 3 tests of 127.
t/refhang.t ................. 
Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/127 subtests 
t/slabs-reassign-chunked.t .. ok
[...]
```

I'll try to give an access to such box to try to investigate this issue, but i can't promise...
I've opened a Debian bug to follow-up this issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=835456

Source: https://buildd.debian.org/status/fetch.php?pkg=memcached&arch=s390x&ver=1.4.31-1&stamp=1471823136

**Comment by dormando** [comment]
He. There's even a TODO in there about the send buffers.

Looks like I need to add a test-env-var or similar to set the send buffers to a predictable size... then I can set the receive buffers to a predictable size. then the test shouldn't fail unpredictably.

**Comment by dormando** [comment]
Sorry it's taken so long for me to come back around to this... Apparently SNDBUF is only modified for UDP sockets. Wiring this in for the test will be more invasive than I hoped.

Can you test adjusting line 56? double the for loop (you'll get a "dubious" fail because of the number of tests changing), or increase it a few times and see if the test will pass at any form? (you probably have to change the "-m 6" there to "-m 64" or so. One option is for it to try a couple passes itself, but it'd be a lot better if I can figure a clean place to clamp the send buffer.

**Comment by sandrotosi** [comment]
@guikcd did you have a chance to try what @dormando suggested?

**Comment by dormando** [comment]
Poke?

**Comment by guikcd** [comment]
Sorry for the delay, the last build [success](https://buildd.debian.org/status/logs.php?pkg=memcached&ver=1.4.33-1&arch=s390x).

According to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=835456#18, the problem can be reproduced on amd64. I've tested it today against last `1.4.36`:

```
$ for i in $(seq 1 10); do echo $i; prove t/refhang.t ; done                                                                         
1
t/refhang.t .. ok       
All tests successful.
Files=1, Tests=127, 10 wallclock secs ( 0.06 usr  0.00 sys +  0.12 cusr  0.02 csys =  0.20 CPU)
Result: PASS
2
t/refhang.t .. ok       
All tests successful.
Files=1, Tests=127,  9 wallclock secs ( 0.06 usr  0.00 sys +  0.10 cusr  0.03 csys =  0.19 CPU)
Result: PASS
3
t/refhang.t .. ok       
All tests successful.
Files=1, Tests=127, 10 wallclock secs ( 0.06 usr  0.00 sys +  0.12 cusr  0.01 csys =  0.19 CPU)
Result: PASS
4
t/refhang.t .. 124/127 
#   Failed test 'some ooms happened'
#   at t/refhang.t line 51.

#   Failed test 'nonzero lrutail_reflocked'
#   at t/refhang.t line 53.
#          got: '0'
#     expected: anything else

#   Failed test 'nonzero total lrutail_reflocked'
#   at t/refhang.t line 56.
#          got: '0'
#     expected: anything else
# Looks like you failed 3 tests of 127.
t/refhang.t .. Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/127 subtests 

Test Summary Report
-------------------
t/refhang.t (Wstat: 768 Tests: 127 Failed: 3)
  Failed tests:  124, 126-127
  Non-zero exit status: 3
Files=1, Tests=127, 10 wallclock secs ( 0.05 usr  0.01 sys +  0.11 cusr  0.02 csys =  0.19 CPU)
Result: FAIL
```

I didn't reproduce anymore after all my other attempts in the evening...

**Comment by thedataking** [comment]
I'm also hitting this bug on a Ubuntu 14.04 amd64 system with memcached 1.4.36.

**Comment by dormando** [comment]
I've disabled this test in next. Sorry it took me so long to just make a decision; once I refactor the frontend a bit I should have the hooks to run the test properly.

should go out with the next release.
