### ISSUE TITLE
add a new command `keys` like redis to list all memcached keys 

### ISSUE THREAD

**Issue by shuxiang1990** [memcached/memcached#199]
In the general case, there is no way to list all the keys that a memcached instance is storing. If i had a warm cache and a cold cache, it would be simple to warm up the cold cache using like `keys` command. So, why memcached doesn't have like `keys` command to list all the keys?

**Comment by shuxiang1990** [comment]
There is a solution: https://groups.google.com/forum/#!topic/memcached/YyzonP9HUi0. But a `keys` command is much simpler.

**Comment by dormando** [comment]
https://github.com/memcached/memcached/wiki/ReleaseNotes1431

**Comment by kenorb** [comment]
Here is the workaround in Bash for the older versions:

```
function memcmd() {
  exec {memcache}<>/dev/tcp/localhost/11211
  printf "%s\n%s\n" "$*" quit >&${memcache}
  cat <&${memcache}
}
for id in $(memcmd stats items | grep -o ":[0-9]\+:" | tr -d : | sort -nu); do
    memcmd stats cachedump $id 0
done
```

Related: [Get all keys set in memcached](https://stackoverflow.com/a/51708912/55075).
