### ISSUE TITLE
Evictions without eviction counter being increased

### ISSUE THREAD

**Issue by raulferras** [memcached/memcached#207]
I'm suffering what I think is an acute attack of evictions, but `stats slabs` does not show evictions counter being increased (it remains at 0).

Basically this is what's happening to me: http://serverfault.com/questions/806361/memcached-keys-being-deleted-after-specific-number-of-items-inserted

In my php script, if after every insertion I check for the first key that is being removed in my scenario (`get` command), that specific key is not being removed.

Does this relate to the evictions? Or is this a different issue?

**Comment by dormando** [comment]
What version, can you post full stats output (stats/stats slabs/stats items), etc?
Or are you the poster of the serverfault thing?

stats items/slabs outputs are nice, but still also need the base output.

**Comment by raulferras** [comment]
Yes, I am the original poster of serverfault question.
By "base output" I guess you mean the output got by adding `-vvv`, here it is: [memcache-vvv.zip](https://github.com/memcached/memcached/files/508016/memcache-vvv.zip)

I'm using 1.4.24, I'm on OSX Yosemite 10.10.5 (but seen this behaviour also in the production server, Debian GNU/Linux 7.8).
On my machine, memcached is installed through `brew`.


Also, in case it helps, a minimum php script that can reproduce the problem: [Archive.zip](https://github.com/memcached/memcached/files/507978/Archive.zip)
It includes a txt file with the entries I am trying to save in memcache.  
When running the script, hopefully you can see the behaviour when reaching iteration number *24517*, after executing the get, the key `translations-cache:entity-501:id-1:profile-5:property-1` is not seen anymore, either issuing a `get` command nor by `memdump --servers=localhost | grep entity-501`.

**Comment by dormando** [comment]
I mean the output from a bare `stats` command. You have everything else, but missing that one (`stats settings` would be nice too)

**Comment by raulferras** [comment]
Ah ok, here you have.
Stats settings:

    stats settings
    STAT maxbytes 67108864
    STAT maxconns 1024
    STAT tcpport 11211
    STAT udpport 11211
    STAT inter NULL
    STAT verbosity 3
    STAT oldest 0
    STAT evictions on
    STAT domain_socket NULL
    STAT umask 700
    STAT growth_factor 1.25
    STAT chunk_size 48
    STAT num_threads 4
    STAT num_threads_per_udp 4
    STAT stat_key_prefix :
    STAT detail_enabled no
    STAT reqs_per_event 20
    STAT cas_enabled yes
    STAT tcp_backlog 1024
    STAT binding_protocol auto-negotiate
    STAT auth_enabled_sasl no
    STAT item_size_max 1048576
    STAT maxconns_fast no
    STAT hashpower_init 0
    STAT slab_reassign no
    STAT slab_automove 0
    STAT lru_crawler no
    STAT lru_crawler_sleep 100
    STAT lru_crawler_tocrawl 0
    STAT tail_repair_time 0
    STAT flush_enabled yes
    STAT hash_algorithm jenkins
    STAT lru_maintainer_thread no
    STAT hot_lru_pct 32
    STAT warm_lru_pct 32
    STAT expirezero_does_not_evict no
    END

This is stats just before inserting the item that removes another:

    STAT pid 34953
    STAT uptime 131
    STAT time 1475658699
    STAT version 1.4.24
    STAT libevent 2.0.22-stable
    STAT pointer_size 64
    STAT rusage_user 1.089531
    STAT rusage_system 2.028862
    STAT curr_connections 12
    STAT total_connections 15
    STAT connection_structures 14
    STAT reserved_fds 20
    STAT cmd_get 2
    STAT cmd_set 24117
    STAT cmd_flush 0
    STAT cmd_touch 0
    STAT get_hits 0
    STAT get_misses 2
    STAT delete_misses 0
    STAT delete_hits 0
    STAT incr_misses 0
    STAT incr_hits 0
    STAT decr_misses 0
    STAT decr_hits 0
    STAT cas_misses 0
    STAT cas_hits 0
    STAT cas_badval 0
    STAT touch_hits 0
    STAT touch_misses 0
    STAT auth_cmds 0
    STAT auth_errors 0
    STAT bytes_read 2211969
    STAT bytes_written 4631199
    STAT limit_maxbytes 67108864
    STAT accepting_conns 1
    STAT listen_disabled_num 0
    STAT threads 4
    STAT conn_yields 0
    STAT hash_power_level 16
    STAT hash_bytes 524288
    STAT hash_is_expanding 0
    STAT malloc_fails 0
    STAT bytes 3435142
    STAT curr_items 24089
    STAT total_items 24117
    STAT expired_unfetched 0
    STAT evicted_unfetched 0
    STAT evictions 0
    STAT reclaimed 0
    STAT crawler_reclaimed 0
    STAT crawler_items_checked 0
    STAT lrutail_reflocked 0
    END 

These are the stats just after the set that removes the item:

    stats
    STAT pid 34953
    STAT uptime 151
    STAT time 1475658719
    STAT version 1.4.24
    STAT libevent 2.0.22-stable
    STAT pointer_size 64
    STAT rusage_user 1.100656
    STAT rusage_system 2.032941
    STAT curr_connections 12
    STAT total_connections 16
    STAT connection_structures 14
    STAT reserved_fds 20
    STAT cmd_get 2
    STAT cmd_set 24118
    STAT cmd_flush 0
    STAT cmd_touch 0
    STAT get_hits 0
    STAT get_misses 2
    STAT delete_misses 0
    STAT delete_hits 0
    STAT incr_misses 0
    STAT incr_hits 0
    STAT decr_misses 0
    STAT decr_hits 0
    STAT cas_misses 0
    STAT cas_hits 0
    STAT cas_badval 0
    STAT touch_hits 0
    STAT touch_misses 0
    STAT auth_cmds 0
    STAT auth_errors 0
    STAT bytes_read 2213462
    STAT bytes_written 6850395
    STAT limit_maxbytes 67108864
    STAT accepting_conns 1
    STAT listen_disabled_num 0
    STAT threads 4
    STAT conn_yields 0
    STAT hash_power_level 16
    STAT hash_bytes 524288
    STAT hash_is_expanding 0
    STAT malloc_fails 0
    STAT bytes 3435275
    STAT curr_items 24090
    STAT total_items 24118
    STAT expired_unfetched 0
    STAT evicted_unfetched 0
    STAT evictions 0
    STAT reclaimed 0
    STAT crawler_reclaimed 0
    STAT crawler_items_checked 0
    STAT lrutail_reflocked 0
    END

**Comment by dormando** [comment]
Oh. I think I missed a keyword early on.

Your post says you're verifying with "memdump" - are you actually trying to fetch the key again to see if it exists?

The `stats cachedump` command is a limited debugging command with a cap of 1 megabyte of output. So around that many keys you'd hit that limit and won't see them anymore, but the extra keys are in the system and is fetchable directly.

The output you're giving me aligns with that as well. When you add the "missing" key curr_items increments. There's no code path for items leaving the cache without curr_items changing.

**Comment by dormando** [comment]
closing this out, since pretty sure that was your issue.

**Comment by raulferras** [comment]
Thank you, I will review the info you gave me and come back in case it didn't resolve it.
