### ISSUE TITLE
/bin/bash: prove: command not found

### ISSUE THREAD

**Issue by chaintng** [memcached/memcached#211]
I got below error after run `make test` on Debian 8 (Jessie)
```
ok 50 - binary_pipeline_hickup
Signal handled: Interrupt.
ok 51 - shutdown
ok 52 - stop_server
prove ./t
/bin/bash: prove: command not found
Makefile:1588: recipe for target 'test' failed
make: *** [test] Error 127
```

**Comment by dormando** [comment]
you need perl installed to run the main tests.

**Comment by chaintng** [comment]
Thank you :). Is there anyway i can help to update in the memcached official page ?

![image](https://cloud.githubusercontent.com/assets/2979072/19408212/dc64a31e-92e1-11e6-8697-c53fa3269996.png)

**Comment by Davidrjx** [comment]
@chaintng perl-Test-Harness is required
