### ISSUE TITLE
Missing download broken link

### ISSUE THREAD

**Issue by dmportella** [memcached/memcached#213]
Download link no longer works

http://memcached.googlecode.com/files/memcached-1.4.13.tar.gz

For release: https://github.com/memcached/memcached/wiki/ReleaseNotes1413

**Comment by dormando** [comment]
fixed, though I advise against running code so old :)

**Comment by dmportella** [comment]
thank you yeah i know hehe we have apps that rely on those version which is very sad T.T

**Comment by dmportella** [comment]
@dormando thank you

**Comment by dormando** [comment]
The newer versions are backwards compatible... :p well, good luck.

**Comment by dmportella** [comment]
thank you its not the server but the .net client we have issues with ... huge code base reliant on a specific version that will only work with that version :(

**Comment by dormando** [comment]
how could a client be stuck on a single version if the server is backwards compatible...?
