### ISSUE TITLE
Command line or compile option to disallow dumping a list of keys

### ISSUE THREAD

**Issue by JamesB7** [memcached/memcached#214]
Hello,

Could you please add a command line or compile time option to disallow dumping a list of keys?

I do not use the feature, and I worry that it could become a security liability, since I am using PHP, which will deserialize and possibly autoload classes based on Memcached's values. It would only allow an attacker to poke around. I'd really appreciate this!

Thank you!

James

**Comment by dormando** [comment]
released in 1.4.34
