### ISSUE TITLE
Unable to start when MAXCONN configured for > 1024

### ISSUE THREAD

**Issue by mwhahaha** [memcached/memcached#218]
Recently the centos package was updated to 1.4.33 and we found that if you configure MAXCONN to > 1024, the service fails to start with the following error:

Nov 02 18:41:04 localhost.localdomain systemd[1]: Started memcached daemon.
Nov 02 18:41:04 localhost.localdomain systemd[1]: Starting memcached daemon...
Nov 02 18:41:04 localhost.localdomain memcached[1078]: failed to set rlimit for open files. Try starting as root or requesting smaller maxconns value.
Nov 02 18:41:04 localhost.localdomain systemd[1]: memcached.service: main process exited, code=exited, status=71/n/a
Nov 02 18:41:04 localhost.localdomain systemd[1]: Unit memcached.service entered failed state.
Nov 02 18:41:04 localhost.localdomain systemd[1]: memcached.service failed

This seemed to be related to the CapabilityBoundingSet that was added to the systemd unit file as part of https://github.com/memcached/memcached/commit/6b52e0196ceb904570b2ae8cc9b38930d27e9f47#diff-e110ebc86dc6e8cf29c95a137ef11fa4R15

When we comment that line out, it works. Using a LimitNOFILE=8192 (for MAXCONN=8192) also seems to work but is not exactly user friendly if a user wants more than 8192.

**Comment by dormando** [comment]
weird. guessing that's dropping privileges too early? is systemd supposed to have fdlimit raised in some other way? I'm not terribly familiar with it.

**Comment by mwhahaha** [comment]
systemd manages the the fdlimit via the service file with LimitNOFILE (see systemd.exec(5) https://www.freedesktop.org/software/systemd/man/systemd.exec.html) but the issue is that the CapabilityBoundingSet change now causes a breakage when maxconn > 1024.

**Comment by dormando** [comment]
I understand what you're seeing; I'm saying the reason it fails is because it's trying to raise the fdlimit from within the application. If there's supposed to be some other way of doing that it might not be straightforward.

Otherwise I'll probably just back that out. Giving someone else a chance to look over this issue first.

**Comment by candrews** [comment]
There are a few things that can be done.

> Otherwise I'll probably just back that out.

That could be done, of course. But that removes a lot of the hardening - so I think that's a bad idea.

Another option is to add `CAP_SYS_RESOURCE` to the CapabilityBoundingSet, so the line would be:
`CapabilityBoundingSet=CAP_SETGID CAP_SETUID CAP_SYS_RESOURCE`
See http://man7.org/linux/man-pages/man7/capabilities.7.html for what capabilities CAP_SYS_RESOURCE adds.
My opinion is that this capability reduces the hardening quite a bit. It increases the things an attacker could do if they somehow get control of the memcache process. But, it's better than the first option (removing capability bounding entirely).

The third option is to document that when the user wants to increase the `MAXCONN` setting in the configuration file beyond 1024, they must also create a systemd override raising the limit. They would use the command `systemctl edit memcached.service` to create an override with these contents:
```
[Service]
LimitNOFILE=8192
```
This approach is the most secure.

**Comment by dormando** [comment]
Memcached itself is supposed to drop from root to a specific user and lose those privileges after adjusting the file limit... that's sort of the way it's always been, so there's an issue of Least Surprise.

I might like an idea of adding the extra cap so the maxconns change works by default, but leave comments in the file saying that extra hardening can be done if you do this other thing instead.

Sadly the bar has to be super low; it's impossible to tell how many people will run into issues and simply switch software (and probably to an even less secure model).

Any issues with this approach?

**Comment by candrews** [comment]
None from me!

**Comment by dormando** [comment]
released in 1.4.34
