### ISSUE TITLE
segfault in version 1.4.33

### ISSUE THREAD

**Issue by vuzilla** [memcached/memcached#222]
We found a memcached segfault in version 1.4.33.  memcached on that node had been running for 9 days without any issues-as far as I know.

memcached[3566]: segfault at 7fab86c29408 ip 0000000000417638 sp 00007fab6520ee80 error 6 in memcached[400000+22000]

addr2line -e memcached 417638
/src/memcached-1.4.33/crawler.c:210

**Comment by dormando** [comment]
Hi,

Can you provide more information about your configuration? `stats`, `stats settings`, `stats slabs`, `stats items`, etc. They can be sent privately if necessary.

Also anything you can share about the traffic pattern is helpful, though I can make some guesses based on the stats outputs.

thanks!

**Comment by vuzilla** [comment]
I've sent the information privately.  Thanks

**Comment by dormando** [comment]
resolved this in another issue
