### ISSUE TITLE
Problem with "out of memory storing object"

### ISSUE THREAD

**Issue by ljagiello** [memcached/memcached#224]
Hi,

Recently we've noticed again higher number of errors: "out of memory storing object".

Current configuration:
```
memcached -u nobody -m88064 -c9216 -p11000 -n 5 -f 1.05 -o modern,slab_chunk_max=8192
```

Version: memcached 1.4.31 (with fixes from https://github.com/memcached/memcached/issues/195)

```
:~# (echo stats items; echo quit) | netcat localhost 11000 | grep outofmemory
STAT items:4:outofmemory 0
STAT items:5:outofmemory 0
STAT items:6:outofmemory 0
[…]
STAT items:59:outofmemory 0
STAT items:60:outofmemory 0
STAT items:61:outofmemory 0
STAT items:62:outofmemory 0
STAT items:63:outofmemory 3380
```
Only last items with outofmemory errors.

```
STAT 63:chunk_size 8192
STAT 63:chunks_per_page 128
STAT 63:total_pages 63294
STAT 63:total_chunks 8101632
STAT 63:used_chunks 8101516
STAT 63:free_chunks 116
STAT 63:free_chunks_end 0
STAT 63:mem_requested 47395182258
STAT 63:get_hits 989163927
STAT 63:cmd_set 29607571
STAT 63:delete_hits 298573
STAT 63:incr_hits 0
STAT 63:decr_hits 0
STAT 63:cas_hits 0
STAT 63:cas_badval 0
STAT 63:touch_hits 0
STAT active_slabs 60
STAT total_malloced 92341796864
```

From our logs looks like the issue affects only objects over 64kb (8 x slab_chunk_max) and only when cache is full. Is it possible to Increase eviction rate a bit so there will be always free memory for bigger objects?

**Comment by dormando** [comment]
Ahh, I think you should leave the slab_chunk_max at the new default of 512k. I need to revisit the code before values that small work well.

You'll have a problem now where if it wants to create a chain long enough it has to loop enough times to free memory.. If there're small values mixed in with large values the odds of it not being able to make room are pretty high. I took a stab at it but it needs a better structure.

If you run at the newer defaults it should be fine.

**Comment by dormando** [comment]
Were you able to resolve this issue?

**Comment by ljagiello** [comment]
I'm still waiting until the cache will be full, but based on objects distribution across slabs it looks a lot better so I'm expecting it will be fine. Thanks for a great suggestion.

**Comment by dormando** [comment]
Great to hear! closing this out.
