### ISSUE TITLE
memcache core down

### ISSUE THREAD

**Issue by jim-yefeng** [memcached/memcached#225]
[root@nfjd-cb-msg13-99139 couchbase]# /opt/couchbase/bin/memcached -h
memcached 4.1.1-5914
-C file       Read configuration from file
-h            print this help and exit

(gdb) bt full
#0  0x00007fab3d9e35f7 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007fab3d9e4ce8 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007fab402a1c76 in cb_assert_die ()
   from /opt/couchbase/bin/../lib/libplatform.so.0.1.0
No symbol table info available.
#3  0x00007fab320d89a2 in CheckpointManager::queueDirty(RCPtr<VBucket> const&, SingleThreadedRCPtr<Item>&, bool) () from /opt/couchbase/lib/memcached/ep.so
No symbol table info available.
#4  0x00007fab32104c93 in EventuallyPersistentStore::queueDirty(RCPtr<VBucket>&, StoredValue*, LockHolder*, unsigned long*, bool, bool, bool, bool) ()
   from /opt/couchbase/lib/memcached/ep.so
No symbol table info available.
#5  0x00007fab32108c6a in EventuallyPersistentStore::setWithMeta(Item const&, unsigned long, unsigned long*, void const*, bool, bool, unsigned char, bool, ExtendedMetaData*, bool) () from /opt/couchbase/lib/memcached/ep.so
No symbol table info available.
#6  0x00007fab320f6f13 in PassiveStream::processMutation(MutationResponse*) ()
   from /opt/couchbase/lib/memcached/ep.so
No symbol table info available.
#7  0x00007fab320f77cb in PassiveStream::processBufferedMessages(unsigned int&)
    () from /opt/couchbase/lib/memcached/ep.so
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#8  0x00007fab320e6135 in DcpConsumer::processBufferedItems() ()
   from /opt/couchbase/lib/memcached/ep.so
No symbol table info available.
#9  0x00007fab320e631d in Processer::run() ()
   from /opt/couchbase/lib/memcached/ep.so
No symbol table info available.
#10 0x00007fab321448c1 in ExecutorThread::run() ()
   from /opt/couchbase/lib/memcached/ep.so
No symbol table info available.
#11 0x00007fab32144f19 in launch_executor_thread ()
   from /opt/couchbase/lib/memcached/ep.so
No symbol table info available.
#12 0x00007fab402a0ec8 in platform_thread_wrap ()
   from /opt/couchbase/bin/../lib/libplatform.so.0.1.0
No symbol table info available.
#13 0x00007fab3e9a3dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#14 0x00007fab3daa4ced in clone () from /lib64/libc.so.6
No symbol table info available.
(gdb)

**Comment by dormando** [comment]
sorry, that's not memcached. please talk to the couchbase people.
