### ISSUE TITLE
dtrace check doesn't work on FreeBSD

### ISSUE THREAD

**Issue by swills** [memcached/memcached#227]
The check for dtrace in configure.ac doesn't work on FreeBSD:

$DTRACE -G -o conftest.$$ -s memcached_dtrace.d

because the conftest file doesn't have any probes in it. The error message is:

dtrace: failed to link script memcached_dtrace.d: No probe sites found for declared provider

Also, it's good to pass -xnolibs to dtrace -G so that it doesn't processes the /usr/lib/dtrace scripts unnecessarily and then error out when it tries to talk to the DTrace kernel code, which happens when running in a jail currently. This isn't necessary on FreeBSD 11.0 or newer, but is a good idea until everyone has upgraded.

**Comment by dormando** [comment]
Not super sure how to fix? Want to give it a stab in a PR?

I still need to add a freebsd builder. should be in for the next major round, but right now it's still slightly difficult for me to validate/test stuff.

**Comment by dormando** [comment]
Ping? :) Something you want me to do or something you could help with?

**Comment by swills** [comment]
I can help, just haven't made it a priority. Will try to take a look, but if you happen to want to fix it, that's fine too.

**Comment by dormando** [comment]
The last few releases I hadn't had enough time set aside to get the *BSD builders running again.. so I haven't fixed this myself yet.

**Comment by dormando** [comment]
I do have a freebsd buildbot working now. not entirely sure how to fix if still relevant. A hint or a PR change would be good :) At least from now on I can prevent any testable regression.

**Comment by dormando** [comment]
I think this got fixed by @devnexen
