### ISSUE TITLE
segfault in version 1.4.33 while using key iterator

### ISSUE THREAD

**Issue by vuzilla** [memcached/memcached#229]
We encountered a memcached segfault in the following situation:
- an administrative app was connected to memcached (TCP connection), using the key iterator feature.
- administrative app was terminated; we believe it was still connected and using the key iterator
- memcached segfault

Here's the log from a system log.  I'm not sure how to get the source code line number from this since the segfault is actually in libc library, but may be caused by an argument passed in from memcached.

Dec  7 02:40:21 ubuntu kernel: [92078.128093] memcached[3870]: segfault at 0 ip 00007fa3993f113b sp 00007fa3962e0940 error 6 in libc-2.19.so[7fa3992e8000+1ba000]

memcached was actively handling get/set/touch traffic at the same time at this:
- get =~ 1600/sec
- set =~ 1300/sec
- touch =~ 2300/sec

Here are the command line parameters:
memcached -p 11211 -u evcache_map_lt -l 0.0.0.0 -m 56253 -C -c 100000 -o slab_chunk_max=524288 -o slab_reassign,slab_automove,lru_maintainer,lru_crawler,hash_algorithm=murmur3 -I 20m

I can send further information, if needed.

**Comment by dormando** [comment]
See #234 - pretty sure that's the bug.

**Comment by dormando** [comment]
released in 1.4.34

**Comment by vuzilla** [comment]
We've verified that this segfault doesn't happen anymore.  Sorry for the delay.

Thanks

Vu

**Comment by dormando** [comment]
Thanks for following up!
