### ISSUE TITLE
Memcached Tool dumping

### ISSUE THREAD

**Issue by AleksandrKuporosov** [memcached/memcached#230]
Hello!

I was tried to use memcached-tool for dumping my memcached content and try to restore cache from this dump. I have terrible results - some keys are not restored. It's look like dump command don't create valid dump.

1. We have 9 buckets with 11 items in cache
```
./memcached-tool localhost:11211 display
  #  Item_Size  Max_age   Pages   Count   Full?  Evicted Evict_Time OOM
  1      96B        25s       1       1     yes        0        0    0
  3     152B        25s       1       1     yes        0        0    0
  5     240B        25s       1       2     yes        0        0    0
  9     600B        25s       1       1     yes        0        0    0
 11     944B        25s       1       1     yes        0        0    0
 12     1.2K        25s       1       1     yes        0        0    0
 13     1.4K        25s       1       1     yes        0        0    0
 14     1.8K        25s       1       1     yes        0        0    0
 15     2.3K        25s       1       2     yes        0        0    0
```

2. Dump them
```
./memcached-tool localhost:11211 dump > ~/mem.dump
Dumping memcache contents
  Number of buckets: 9
  Number of items  : 11
Dumping bucket 1 - 1 total items
Dumping bucket 11 - 1 total items
Dumping bucket 12 - 1 total items
Dumping bucket 13 - 1 total items
Dumping bucket 14 - 1 total items
Dumping bucket 15 - 2 total items
Dumping bucket 3 - 1 total items
Dumping bucket 5 - 2 total items
Dumping bucket 9 - 1 total items
```

3. Restart memcached service, or flush cache if you prefer
4. Restore dump
```
nc localhost 11211 < ~/mem.dump
STORED
STORED
STORED
STORED
```
5. Look for items
```
./memcached-tool localhost:11211 display
  #  Item_Size  Max_age   Pages   Count   Full?  Evicted Evict_Time OOM
  3     152B        36s       1       1     yes        0        0    0
  5     240B        36s       1       1     yes        0        0    0
 15     2.3K        36s       1       2     yes        0        0    0
```

4 items in total. Where other items?

I was looked for this issue in internet and found some:
1. Similar issue on SO: http://stackoverflow.com/questions/31186384/how-to-restore-dump-of-all-memcache-keys-stored-in-a-file-using-memcache-tool-co
2. Mailing list with possible explanation: http://lists.danga.com/pipermail/memcached/2007-April/003906.html

**Comment by dormando** [comment]
The tool dump is a debug command; it's not meant to dump every item from the cache.

There's a new command which will dump all metadata, but done loosely: https://github.com/memcached/memcached/wiki/ReleaseNotes1431

Closing this out.
