### ISSUE TITLE
documentation - formatting in ServerMaint

### ISSUE THREAD

**Issue by richlv** [memcached/memcached#236]
see https://github.com/memcached/memcached/wiki/ServerMaint, the section starting with "# Monitor the global 'evictions' stat. If it starts going up."

those hashmarks look like they were meant to be numbered list items, but they are all in one line now.
some of the sentences seem to be slightly mangled, too - like "If it starts going up"

note that the bulletpoint that follows this paragraph also seems to have a formatting issue with a hashmark there.

**Comment by dormando** [comment]
Fixed, thanks!
