### ISSUE TITLE
How do I get key's remaining time, like redis's TTL API？

### ISSUE THREAD

**Issue by yangbo-true** [memcached/memcached#239]
How do I get key's remaining time, like redis's TTL API？

**Comment by dormando** [comment]
there's no API for that. the logging system includes the remaining TTL when watching evictions. You can also see it by dumping the full list via metadump, but no one-off checker is available.

**Comment by lostinplace** [comment]
for those landing on this after me, this is now available here:

[Meta Debug](https://github.com/memcached/memcached/blame/56dc81db316a0b957415e371d20c683fea9d7d2f/doc/protocol.txt#L456-L485)

**Comment by dormando** [comment]
The meta commands in general are a better place for this: https://github.com/memcached/memcached/wiki/MetaCommands the meta debug command is more for manual inspection.
