### ISSUE TITLE
Documentation: Increment, Decrement typo

### ISSUE THREAD

**Issue by elvio** [memcached/memcached#252]
The example code in https://github.com/memcached/memcached/wiki/BinaryProtocolRevamped#increment-decrement shows `exipration` as part of `Extras`, instead of `expiration`:

```
   ...
   Extras              :
     delta      (24-31): 0x0000000000000001
     initial    (32-39): 0x0000000000000000
     exipration (40-43): 0x00000e10
   Key                 : Textual string "counter"
   Value               : None
```

The same issue can be found in the `doc/protocol-binary.xml` file in the project. I submitted a PR fixing that: https://github.com/memcached/memcached/pull/253.

**Comment by dormando** [comment]
pulled the change and also fixed in the wiki. thanks!
