### ISSUE TITLE
Documentation: formatting bug causes wrong expiration time for 30 days

### ISSUE THREAD

**Issue by bellorap** [memcached/memcached#254]
The paragraph about expiration times in https://github.com/memcached/memcached/wiki/Programming#expiration says:

> to 30 days (60*60*24*30)

This is meant to be:

> to 30 days (60\*60\*24\*30)

But the first two `*` form italics instead. This causes the wrong value to rendered and even the italics are lost when quoted, for example on [this SO post](http://stackoverflow.com/a/1829545/697449).

**Comment by dormando** [comment]
Fixed, thanks.
