### ISSUE TITLE
BashOnWindows - and data memory limit of 8136 bytes 

### ISSUE THREAD

**Issue by spagu** [memcached/memcached#261]
Memcached seems to have hard limit for storing object larger than 8136 bytes. This was confirmed on several computers with windowsbash with ubuntu 14 and  ubuntu 16. 
Changing -I parameter has no effect. STATS looks normal and exactly the same as on clean linux machines.

version of memcached: 1.4.14 and 1.4.25 

PHP version: 7.0.16-2+2deb.sury.org~trusty+1 with standard extension php-memcached pecl version 3.0.3 (not old memcache)
```
<?php
$data = "generate string longer than 8136 characters";
$client = new Memcached();
$client->addServer('memcache', 11211, 0);
$client->set('mykey',$data);
echo $client->getResultCode();
?>
```

expected result:
0

actual result:
38

When using NC this works fine.

**Comment by dormando** [comment]
I wouldn't know where to start looking. :/ Try a different language/client or manually set some value via netcat? What php client is that, even?

**Comment by spagu** [comment]
This issue was moved to php-memcached-dev/php-memcached#332
