### ISSUE TITLE
stat "limit_maxbytes" broken after "cache_memlimit"

### ISSUE THREAD

**Issue by arodland** [memcached/memcached#267]
Before: `STAT limit_maxbytes 10737418240`
Command: `cache_memlimit 11237418240`
After: `STAT limit_maxbytes 2776087813685248`

That's got some of the right bits in it (0x9dcd650000000 vs. the correct 0x29dcd6500) but the alignment is all wrong.

Memcached 1.4.36.

**Comment by dormando** [comment]
cache_memlimit takes megabytes, same as the commandline -m parameter. It's getting multiplied out.

Apparently the documentation doesn't specific the unit type :/ I'll leave this open until the docs are patched.

**Comment by dormando** [comment]
(it takes megabytes because the pages are 1m no matter what anyway, can't specify any other value)

**Comment by arodland** [comment]
Ah, that makes sense. I probably would have recognized that if it came out as a number a million times too large, but since it wrapped around after 2^32 megabytes I missed the obvious and figured "memory corruption" :)

**Comment by dormando** [comment]
I'll double check the casting too. pretty sure I fixed that exact bug a couple releases ago and it should be casting to a size_t properly, but maybe not.

**Comment by dormando** [comment]
finally pushed a usability fix to 'next'. thanks again!
