### ISSUE TITLE
Build fails on SunOS

### ISSUE THREAD

**Issue by ptribble** [memcached/memcached#270]
On illumos (SunOS) building 1.4.36 fails with

memcached.c: In function 'conn_release_items':
memcached.c:629:13: error: implicit declaration of function 'do_cache_free' [-Werror=implicit-function-declaration]
             do_cache_free(c->thread->suffix_cache, *(c->suffixcurr));
             ^
memcached.c: In function 'process_get_command':
memcached.c:3323:19: error: implicit declaration of function 'do_cache_alloc' [-Werror=implicit-function-declaration]
                   suffix = do_cache_alloc(c->thread->suffix_cache);
                   ^
memcached.c:3323:26: error: assignment makes pointer from integer without a cast [-Werror]
                   suffix = do_cache_alloc(c->thread->suffix_cache);
                          ^

The problem appears to be in cache.h, where, if HAVE_UMEM_H is defined, then only cache_alloc and cache_free are defined, but not do_cache_alloc and do_cache_free.

**Comment by dormando** [comment]
I've pushed what I believe should fix this into 'next' branch. thanks! (and a quick test would be helpful).

thanks for the report and apologies for the delay!
