### ISSUE TITLE
Memcached with SASL port is going offline with wrong credentials

### ISSUE THREAD

**Issue by rajpilla32** [memcached/memcached#276]
Hi Team,

I am trying to setup Memcached(1.4.36) with SASL(memcached -S -B binary -vvv) support. After the setup, when I try to start my application using wrong username or password that is not configured in SASL-DB, Memcached running on that specific port is going offline.

Is this expected behaviour ? Can it be protected with property?

Or is there any config changes that I can do for the port not going offline when any wrong user trying to access memcached running on specific port. Please suggest.

Thanks

**Comment by dormando** [comment]
Hey,

Can you continue in the mailing list thread? I'd rather help you in one place than two places. I've responded with some information we need. I've tried to reproduce the problem and can't.

thanks
