### ISSUE TITLE
[Design discuss] Memcached over Marathon ideas

### ISSUE THREAD

**Issue by BarthV** [memcached/memcached#277]
__Original thread here : https://github.com/mesosphere/marathon/issues/5400__

---

Hi there and thanks for this awesome project !

Here is a short document about my toughts about a Marathon switch for Memcached.
Any comments are obviously welcomed and I will study with attention every submitted remark :)

## Context
In my company (@criteo) we're currently thinking about switching our critical memcached infrastructure from bare metal to our existing wide-scale Mesos/Marathon clusters.

_Our basic axioms are the following :_
* We're currently __not__ running any container technology in Mesos, so we decided to run Memcached process using Mesos native isolation and basic runtime environment.
* We're currently running Mesos 1.0.2 with Marathon 1.4.3, so we need to stay compatible with those versions.
* We want to keep things as simple as possible (descriptor file -> git -> update action (manual or auto) -> API -> update scheduled -> Mesos/Marathon actions).
* We want any needed additional tool to be stateless.
* We want to pilot every cluster independantly with a control over slave repatition with slave awareness (ex: for anticipated HW maintenance management).
* We want a nice API for that, with a useful feature set.
* We want (as much as possible) a specific scheduling policy that would allow to pace every operations (scaling, restart, updates, ...) to mitigate cache miss over time by giving some time for cache healing.
* Service Discovery will be handled by an existing Consul cluster bridged to Mesos/Marathon, but this is not totally written in stone and can be modular.

### Running in Marathon
_How :_
* By using every Marathon feature : applications, deployments, labels, API, ...

_Why :_
* Marathon is battle-tested and already widely used by almost every people running Mesos (including us).
* Marathon is exposing a nice API covering many standard use cases.
* A good webUI is always a nice-to-have.
* Memcached is a simple binary running with few parameters, it fits quite well with Marathon main purposes.
* Hooks quite well with Service Discovery mecanisms and dynamic DNS & LB

_Caveats :_
* Marathon updates strategies are really basic and can't pace scaling operations nor updates.
* Using `minimumHealthCapacity` & `maximumOverCapacitymaximumOverCapacity` is not flexible enough to fit our dynamic needs.
* Changing Marathon upgrade policy settings seems restarting every instance of the app, and this is __not__ OK. (https://github.com/mesosphere/marathon/issues/1635)
* There's no way in Marathon to start serving an instance without considering it as an healthy one. i.e. Marathon doesn't allow to pause a deployement with every existing instance in a healthy state like we would. (https://github.com/mesosphere/marathon/issues/2431)
* There's also no native way in Marathon to inhibit killing/spawning mecanism and do it using a custom third party tool for scheduling management. (https://github.com/mesosphere/marathon/issues/2766 + https://github.com/mesosphere/marathon/issues/2724 + https://github.com/mesosphere/marathon/issues/2766)
* Scheduled maintenance primitives exists in Mesos but are not available yet in Marathon (https://github.com/mesosphere/marathon/issues/4638)

### Using multiple Marathon applications for a single cluster
_How :_
* By creating multiple applications (from 1 to N)
* By only hosting a single instance in every Marathon Application.
* By registering every Application of a single cluster in the same service in Service Discovery

_Why :_
* Marathon can't give fine control upon its deployments (canary / migration steps / custom checks before continuing a deployment).
* Marathon API cannot target a single instance of an Application and triggers specific actions on it (to be confirmed).
* Labels are set on Application level while we may need it on instance level for selective operation (drain/maintenance/canary/...).

_Caveats :_
* Since Application only host a single instance, we won't rely anymore on Marathon scheduling for scaling and updates/restarts.
* Application inflation (is there any impact on Marathon perfs ?)
* We need to drive this kind of clusters by a custom external tool.
* We need to instensively make use of Application labels to distribute and persist cluster membership and other desired configuration.
* Some Marathon bridges to SD may not be tunable the way we want them to be :(. We need absolute trust on this mecanism.

__Note :__
* We also can build a more simple version of this by only using 2 Applications for a given cluster and relying on Marathon scaling and scheduling.
* By doing like this we would be able to run a progressive switch from an App conf to another and control how and when this switch is made.
* It surely won't cover everything we want, but it should be way shorter to release.

### Building a custom lightweight Memcached scheduling daemon over Marathon api
_How :_
* By running a service binding to Marathon API and listening to Marathon events.
* By making this service regularly checking Applications/Clusters configuration compliance & scheduled actions
* By using a label naming convention to discover Memcached applications for a given cluster
* By using specific application labels to store in Marathon scheduled actions (restart, conf/params updates & upgrades)
* By relying on Marathons timestamp this service will allow to schedule operation without requiring any statefulness
* By exposing a specialized REST API to control that allows to trigger actions and spawn Memcached clusters.

_Why :_
* Bypassing Marathons mecanisms implies building a tool to manage those aspects.
* This tool must wrap marathon API and be built as a dedicated trivial Memcached management API.
* This daemon needs to handle scheduling clusters updates/upgrades, planned restart & scaling operations.
* 100% stateless by relying on labels for cluster and actions + timestamps rules allowing to create time based scheduling strategy.
* Any more complex strategy can also be implemented (hit ratio, % memory allocation) but it's not our first target.

_Caveats:_
* Custom solution to maintain.
* Polling and filtering every Marathon Applications to grab tags and timestamps is maybe a bit "overkill" and not most efficient strategy to adopt.
* Maybe some "complex" scheduling rules to code
* No webUI, no ops tooling

## What now ?
* I'd like to confirm that this is not a stupid idea. And this can work.
* I'd like to confirm that Marathon will support this scenario and its performances will not be impacted by the Application inflation.
* I'd like to know how you guys & girls deal with this kind af issues and how did you manage to resolve this kind of custom & controlled scheduling problems.
* At last, I'd like to know if anyone here would be interessed in testing this solution during the early phases of our project !

Thanks a lot for spending time reading me and thinking about this architecture !
Barth.V

**Comment by dormando** [comment]
I'm not sure what this has to do with us? :) If you want wider feedback on a use case, you can post to the mailing list. This is mainly for bug reports for the daemon.

**Comment by dormando** [comment]
going to close this out since I don't see anything related to the daemon specifically.

good luck!

**Comment by BarthV** [comment]
Thanks :)
