### ISSUE TITLE
install from github repo

### ISSUE THREAD

**Issue by yanxurui** [memcached/memcached#279]
Hello, sorry to bother you. I am a newbie to automake and rpm.
Recently I want to build a rpm package for our centos machines from the lastest source.
I know if I want to mannully install I should first download the lastest release

    wget https://github.com/memcached/memcached/archive/1.4.36.tar.gz

Then `./autogen.sh && ./configure && make && make install`

My **first question** is how to generate spec file from `*.spec.in`.

I also notice the tarball file downloaded by the following command already includes the final configure and spec file

    wget https://memcached.org/latest

So my **second question** is what's the difference between tarball from github release and the one from https://memcached.org/latest.

I am really confused. Anyone who can help me?

**Comment by astierler** [comment]
From the memcached.spec.in (rename to memcached.spec in your SPECS folder), you just need to replace "@VERSION@", "@FULLVERSION@" with 1.4.36 -- and replace @RELEASE@ with 1.

Then you should just be able to `rpmbuild -ba memcached.spec`. I was just able to do this on my el6 build box without issue.

As for /latest, it is just a redirect to http://www.memcached.org/files/memcached-1.4.36.tar.gz

**Comment by dormando** [comment]
Sorry, you shouldn't fetch the tarball from that github link. that's just a rollup of the tag. The official releases are from: https://memcached.org/ - the download links on the right.

You don't need to generate the spec from from .spec.in. if you're fetching the tarball, it's already converted (should just be memcached.spec inside the tarball). You also don't need to run autogen from the tarball. Just run rpmbuild like @astierler says.

However, if you're using `git clone` and working from the source repo, I'll describe it below:

./autogen.sh generates the spec file.

autogen.sh runs version.pl, and version.pl rewrites the .spec.in file into a .spec file. You need to run autogen from within a `git clone` of the source repo.

**Comment by yanxurui** [comment]
Thank you @astierler for your reply. Your method does work.
Thank you @dormando for pointing out the right way. Follow your instructions  I successfully autogenerate spec file from spec.in.

diff shows that it simply 
> replace @VERSION@, @FULLVERSION@ with 1.4.36 -- and replace @RELEASE@ with 1.
    
    > diff memcached.spec memcached.spec.in
    2,3c2,3
    < Version:        1.4.36
    < Release:        1%{?dist}
    ---
    > Version:        @VERSION@
    > Release:        @RELEASE@%{?dist}
    9c9
    < Source0:        http://memcached.org/files/%{name}-1.4.36.tar.gz
    ---
    > Source0:        http://memcached.org/files/%{name}-@FULLVERSION@.tar.gz
    26c26
    < %setup -q -n %{name}-1.4.36
    ---
    > %setup -q -n %{name}-@FULLVERSION@ 


By the way, `version.pl` grabs version info from git command. That's why I can not generate spec file when I execute `autogen.sh` in the tarball from releases by github.

**Comment by dormando** [comment]
right. my point is that you are not supposed to download releases from github. you need to use the main website, or the links within the release notes.

The "releases" on github are just snapshots of the code repository. they haven't had the release scripts run on them and are not for end users. I don't know how to shut them off.
