### ISSUE TITLE
php7 sessions limiting to 62,000 session_ids

### ISSUE THREAD

**Issue by nuthankumarns** [memcached/memcached#282]
Hi,

Seems like a trivial issue, but I'm stuck here.
The total number of sessions created by php is not exceeding ~62,000. Literally, logging out authenticated users randomly once the count of keys reach this limit. 
We increased the memory limit, concurrent connections & slab page size. No luck.

`memcached -d -p 11211 -u memcached -m 256 -c 2048 -P /var/run/memcached/memcached.pid -I 5`

Is there any additional setting that needs to be configured?

Thanks,
Nuthan.

**Comment by dormando** [comment]
what's the output of the `stats` command?

**Comment by nuthankumarns** [comment]
Restarted memcached few minutes ago. Its 11000 session objects and increasing.

stats
STAT pid 18646
STAT uptime 681
STAT time 1496860713
STAT version 1.4.4
STAT pointer_size 64
STAT rusage_user 2.167670
STAT rusage_system 3.527463
STAT curr_connections 20
STAT total_connections 19384
STAT connection_structures 46
STAT cmd_get 17950
STAT cmd_set 24553
STAT cmd_flush 0
STAT get_hits 16385
STAT get_misses 1565
STAT delete_misses 0
STAT delete_hits 0
STAT incr_misses 0
STAT incr_hits 0
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT auth_cmds 0
STAT auth_errors 0
STAT bytes_read 3398816
STAT bytes_written 106142320
STAT limit_maxbytes 268435456
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT threads 4
STAT conn_yields 0
STAT bytes 1168554
STAT curr_items 10560
STAT total_items 24553
STAT evictions 0
END

**Comment by dormando** [comment]
please show the stats output again after you've experienced the problem.

also, that version (1.4.4) is from 2009 and there is limited support for it.

**Comment by nuthankumarns** [comment]
This time, stopped at 60746

stats
STAT pid 24985
STAT uptime 10766
STAT time 1496886961
STAT version 1.4.4
STAT pointer_size 64
STAT rusage_user 138.557935
STAT rusage_system 74.497674
STAT curr_connections 15
STAT total_connections 369837
STAT connection_structures 115
STAT cmd_get 344791
STAT cmd_set 441795
STAT cmd_flush 0
STAT get_hits 332312
STAT get_misses 12479
STAT delete_misses 0
STAT delete_hits 0
STAT incr_misses 0
STAT incr_hits 0
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT auth_cmds 0
STAT auth_errors 0
STAT bytes_read 64717587
STAT bytes_written 17454250811
STAT limit_maxbytes 268435456
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT threads 4
STAT conn_yields 0
STAT bytes 17027972
STAT curr_items 152860
STAT total_items 441795
STAT evictions 0
END

Memcached Version	3.0.3
libmemcached version	1.0.16

**Comment by nuthankumarns** [comment]
Again, Froze at 60729 sessions.

stats
STAT pid 7428
STAT uptime 3193
STAT time 1496890260
STAT version 1.4.4
STAT pointer_size 64
STAT rusage_user 68.408600
STAT rusage_system 41.963620
STAT curr_connections 18
STAT total_connections 225649
STAT connection_structures 205
STAT cmd_get 210767
STAT cmd_set 247787
STAT cmd_flush 0
STAT get_hits 201546
STAT get_misses 9221
STAT delete_misses 0
STAT delete_hits 0
STAT incr_misses 0
STAT incr_hits 0
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT auth_cmds 0
STAT auth_errors 0
STAT bytes_read 39057100
STAT bytes_written 7690466599
STAT limit_maxbytes 268435456
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT threads 4
STAT conn_yields 0
STAT bytes 8735429
STAT curr_items 76953
STAT total_items 247787
STAT evictions 0
END

**Comment by dormando** [comment]
there aren't any evictions, and you're only using 8 megabytes of memory. There's nothing tuning memcached would do to fix your session situation.

What is handling your sessions? Is this a module you're using or a php7 builtin?

**Comment by nuthankumarns** [comment]
Its on CentOS 6 and had to install this php7 extension.

php70w-pecl-memcached.x86_64 : Extension to work with the Memcached caching daemon

**Comment by dormando** [comment]
this module is how you've configured sessions? are you running any other code for your sessions, or how is it configured?

**Comment by nuthankumarns** [comment]
Application has session_start() [php](http://php.net/manual/en/book.session.php)  session management.
and It was handling session using files, changed it to memcached and the save_path.

#php_value session.save_handler "files"
#php_value session.save_path    "/var/lib/php/session"

php_value session.save_handler "memcached"
php_value session.save_path "10.140.0.5:11211"

memcached sysconfig:
`PORT="11211"
USER="memcached"
MAXCONN="2048"
CACHESIZE="256"
OPTIONS="-I 5m"`

**Comment by dormando** [comment]
what do you mean by "application has session_start()" ? is this custom logic in the application or a php language feature?

**Comment by nuthankumarns** [comment]
Its a language feature. The default method of starting, generating and maintaining sessions. It works well with file based sessions.

**Comment by dormando** [comment]
I don't believe this failure has anything to do with memcached, but I have no visibility into exactly how the session system is using memcached. You're not getting any evictions so there's no reason for sessions to be "lost" past some point.

from some googling it looks like session.gc_maxlifetime sets how long any session should live. that's set pretty high for you.

you'll have better luck asking php folks. since your version of memcached is so old I can't really help further. Newer versions have many more statistics and some logging which help troubleshoot this sort of thing.

you could start memcached with `-vvv` in the foreground or piped to a logfile to see how the app is interacting with it. that's a little unwieldy.

**Comment by nuthankumarns** [comment]
To test, session.gc_maxlifetime was set to pile up sessions on demand, Its a QA environment.

I just did `yum install memcached` on my machine, which installed memcached 3.0.3 and libmemcached 1.0.16

Do you want me to install it from the source to get the latest version? Will that help?

**Comment by dormando** [comment]
3.0.3 sounds like your client. I'm talking about the server; which is memcached 1.4.4 according to your stats output. I'm not sure how you installed that or how it's so old.

**Comment by nuthankumarns** [comment]
installed it using yum. If there's any other way to install the latest on centos, Kindly point to the right resources.

**Comment by dormando** [comment]
I don't have anything that's probably easy enough for you. you can build from source or use rpmbbuild -ba against the spec file in the source release (get from https://memcached.org).

you really do need to take this to PHP support forums. There's nothing evicting from memcached so changing its start paramters are not going to fix your problem.

**Comment by dormando** [comment]
did you figure this out?

**Comment by dormando** [comment]
just curious; it was easier to switch to redis than upgrade memcached?

**Comment by nuthankumarns** [comment]
Was testing redis possibilities side by side, did not freeze at any specific key limits. Production was critical, hence switched to Redis. For session store alone, we are using Redis.

Whilst, We have started testing for memcached, installed from source. If this works fine, will prefer memcached over redis, as our page caching is on memcached store.

**Comment by msporleder** [comment]
@nuthankumarns do you have your test script?

I did this and didn't have issues on my setup running with 100000, but php is pretty random in terms of builds and modules and stuff
```
<?php
ini_set("session.save_handler", "memcached");
ini_set("session.save_path", "127.0.0.1:11211");

//session_start();
for ($x = $argv[1]; $x > 0; $x--) {
        session_start();
        session_unset();
        session_destroy();
}
```

**Comment by sodabrew** [comment]
As the current maintainer for the php-memcached module, I'm watching this thread to see if there's something I can reproduce/fix on my end. (:wave: @dormando!)

**Comment by dormando** [comment]
Hey Aaron! :) Doesn't seem like anything normal would cause this. Hopefully the user shows up soon and can share some code.

**Comment by Momen6866** [comment]
This my phone be stone stolen,I hv full set and phone imei number under my name ,Pls contact me I pay u bonus

**Comment by Momen6866** [comment]
Momen +60192886866

**Comment by dormando** [comment]
Anyone have any clues on this? I'd love to resolve it but it's not clear anyone knows enough about the original environment to reproduce.

**Comment by msporleder** [comment]
I vote close; I can't reproduce.

**Comment by donatj** [comment]
We're currently fighting with what seems to be a similar problem.  We hit a certain number of sessions and then get mass failures.

**Comment by dormando** [comment]
@donatj can you give us as much information as possible? Exact number of sessions, php version, php memcache client library/version, how sessions are configured, app software, memcached stats counters, etc?

what exactly do the failures look like? any other logs?

**Comment by donatj** [comment]
@dormando 

I'll see what I can dig up for you. In the mean time we seem to have temporarily fixed it for the moment by sharding across multiple memcache instances. We are using AWS ElastiCache.

We never encountered the issue until we upgrade from 1.4.14 to 1.4.34 

It's worth noting as well that using a modified version of @msporleder 's script I am unable to cause it on the exact same memcache server we are seeing the issue.

<details>
<summary>Modified Script</summary>

```php
<?php

ini_set('session.save_handler', 'memcache');
ini_set('session.save_path', 'memcache:11211');

$max  = 4000;
$size = 800;

for( $i = 0; $i <= $max; $i++ ) {
	ob_start();
	echo $i . " ";
	session_id("sess:{$i}");
	echo (int)session_start();
	echo " ";
	echo (int)session_status();
	echo "\n";
	$_SESSION['id'] = str_repeat("id:{$i}", $size);
	session_write_close();
	$content = ob_get_contents();
	ob_end_clean();
	fwrite(STDERR, $content);
	//	usleep(20);
}

for( $i = 0; $i <= $max; $i++ ) {
	ob_start();
	echo $i . " ";
	session_id("sess:{$i}");
	echo (int)session_start();
	echo " ";
	echo intval($_SESSION['id'] == str_repeat("id:{$i}", $size));
	echo "\n";
	session_write_close();
	$content = ob_get_contents();
	ob_end_clean();
	fwrite(STDERR, $content);
	//	usleep(20);
}
```

</details>

**Comment by dormando** [comment]
so how, exactly are you doing sessions in the way that they don't work?

**Comment by msporleder** [comment]
@donatj Did you upgrade lib memcache for your php client and get the issue, or can you select the server version in ElastiCache?

**Comment by dormando** [comment]
@donatj friendly poke :)

**Comment by donatj** [comment]
@msporleder we can select within a given range in elasticache. It no longer goes back to 1.4.14 though, that option disappeared with our old instance.  We load balanced across two servers and that's solving it for now. Out DevOPs team was going to contact AWS, I'll talk to them in the morning to see if they've got anything else to go on.

**Comment by dormando** [comment]
@donatj any chance you could share the information I asked for?

I know it looks like it's a server problem, but there's something your client/configuration is doing which it's not supposed to. There's no legitimate way to get the behavior you're seeing without relying on a debug command, that I'm guessing the software is using somehow.

But I have no idea what you're running so I can't dig into it and report the bug. Can you please share exactly how your sessions are configured? versions of all related software and where you got them from would be greatly appreciated.

**Comment by donatj** [comment]
We literally just set the following in our ini, in PHP5.5 ~ using the memcache extension rather than the memcached extension. We have 50 some php “client” servers when we scale up fully so it seems unlikely it’s a purely client issue.

```ini
session.save_handler = 'memcache'
session.save_path = 'blah.cache.amazonaws.com:11211'
```

**Comment by donatj** [comment]
We are currently in process of upgrading to PHP7.1/memcached extension in the next few weeks.

**Comment by dormando** [comment]
@donatj what version of the mecache extension are you running? (and how was it installed?)

**Comment by donatj** [comment]
It was installed with `yum` as was php itself.

| memcache support | enabled             | 
|------------------|---------------------| 
| Version          | 3.0.8               | 
| Revision         | $Revision: 329835 $ | 

| Directive                      | Local Value | Master Value | 
|--------------------------------|-------------|--------------| 
| memcache.allow_failover        | 1           | 1            | 
| memcache.chunk_size            | 32768       | 32768        | 
| memcache.compress_threshold    | 20000       | 20000        | 
| memcache.default_port          | 11211       | 11211        | 
| memcache.hash_function         | crc32       | crc32        | 
| memcache.hash_strategy         | consistent  | consistent   | 
| memcache.lock_timeout          | 15          | 15           | 
| memcache.max_failover_attempts | 20          | 20           | 
| memcache.protocol              | ascii       | ascii        | 
| memcache.redundancy            | 1           | 1            | 
| memcache.session_redundancy    | 2           | 2            |

**Comment by tomekit** [comment]
Hey @donatj, did you manage to solve this issue somehow?
I am facing same problem after updating Memcached from 1.4.14 to 1.4.34 on AWS (Elasticache).
For the reference, I am running: `php 7.2.7-0ubuntu0.18.04.2` and compiled `libmemcached 1.0.18` with `igbinary` support.

**Comment by dormando** [comment]
@tomekit any chance you could help test some things?

need a list of: What OS/distro/etc (AMI?).
Any minimal code examples that reproduce the problem in your environment?
and if at all possible, if you can test against a memcached that you've compiled from source; either 1.4.34 or latest version. I'm highly interested in figuring out how this happens.

**Comment by dormando** [comment]
Thanks!

Is there any chance you could start an instance running vanilla memcached (either 1.4.34 or latest) from source? I don't have access to AWS's elasticache. If we can isolate it to being either with the client stack or something they've done to the server, we can contact them and get it sorted out.

so if you set your current system to point against a non-elasticache but normal memcached instance (which is what elasticache is supposed to be), and the problem goes away, etc.

thanks

**Comment by donatj** [comment]
@tomekit I’m afraid not. We ended up just switching to Redis.

**Comment by tomekit** [comment]
@dormando 
I can't promise, might try over the next few days. Will let you know if got something.

**Comment by tomekit** [comment]
@dormando 
I am running the Dockerized Memcached only for the purposes of memcached session handler:
`docker run -d --restart always --name memcached -p 127.0.0.1:11211:11211 memcached:1.4.34 memcached -m 512 -I 20m`, so far it's been 43 hours and no errors, but it's not a proof, as I could see previously even 2 days periods where error wasn't present.

I think if I don't spot this error by the end of next week it might mean something is wrong with the AWS Elasticache 1.4.34. There certainly is something wrong with the AWS, since from time to time I've experienced 4s wall time on `session_start()` (results from XHProf) on live environment, even though session server is almost idle all the time.

**Comment by dormando** [comment]
@tomekit thanks so much for trying that out! how did things work out over the last week?

**Comment by tomekit** [comment]
@dormando 
Right, so it's been 8 days now and the problem has gone. I think this might be something with the I/O connection limit on AWS side that for some reason started to be a problem on 1.4.34, but wasn't present on 1.4.14. I am running `micro` 512MB node on AWS, just because it's almost all of the time idle (2-3% CPU). My assumption is that some short traffic spikes cause significant delay, which causes e.g. 4s `session_start()` from time to time or the error on the PHP side: `Failed to create session ID`.

**Comment by dormando** [comment]
@tomekit thanks! any chance you could reach out to AWS? You can link back to this issue.

though I think this issue is two conflating problems... one of them being AWS doing (something?) and one potentially a php session handler issue. Both are mysteries to me and neither seem to be bugs in software I actually support :( :(

**Comment by dormando** [comment]
@tomekit been a couple weeks, everything still looking stable?

**Comment by tomekit** [comment]
@dormando 
Perfectly fine and stable.
Sorry, but I do not have a paid support for AWS, so as far I am concerned I would be limited to the AWS forum, where anyone can raise an issue.
I might have confused problems, because the php7 sessions limiting to 62,000 session_ids is different than my problem with the: `Failed to create session ID` error I was getting, however it's only affecting the AWS 1.4.34, whilst AWS 1.4.14 was fine.

**Comment by dormando** [comment]
Haven't had a ping about this in over a year. going to pray to the cloud gods that they upgraded past whatever they broke.

**Comment by donatj** [comment]
We switched to Redis and the problem went away.
