### ISSUE TITLE
"evictions" counter doesn't include evictions caused by slab reassignment

### ISSUE THREAD

**Issue by arodland** [memcached/memcached#284]
"evictions" is exclusive of "slab_reassign_evictions_nomem". Arguably it makes sense either way, but if someone is monitoring sets/deletes/evictions to get an idea of how items are flowing in or out of the cache, they would want to see these disappearing items counted as evictions.

**Comment by DerekMarshall** [comment]
I believe we were just caught by exactly the problem you describe in production.

**Comment by dormando** [comment]
@DerekMarshall ok, I'll see if I can toss this in the next release. If you're on newer versions you shouldn't see much evictions_nomem going on. would like to hear more if you've found an edge case

**Comment by dormando** [comment]
I'm going to close this out as it's being dealt with via other PR's/issues. The nomem case will go away entirely in not too long, and the slab mover's gotten some fixes.
