### ISSUE TITLE
How to close the debug log of memcached

### ISSUE THREAD

**Issue by Easy-Deng** [memcached/memcached#288]
in my eclipse console always print the log of this

10:29:14.257 [Xmemcached-Reactor-2] DEBUG n.r.xmemcached.impl.MemcachedHandler - Check session (%s) is alive,send heartbeat
10:29:14.257 [Xmemcached-Reactor-2] DEBUG c.g.c.y.core.impl.AbstractSession - After encodingversion

10:29:14.257 [Xmemcached-Reactor-2] DEBUG n.rubyeye.xmemcached.impl.Optimizer - Optimieze merge buffer:version

10:29:14.257 [Xmemcached-Reactor-2] DEBUG c.g.c.y.core.impl.AbstractSession - send buffers:
[
 buffer:position=0,limit=9,capacity=9
]

I am try to change the  level of log4j.properties，but it no effect . So how to close the debug the log.

**Comment by dormando** [comment]
Hey,

This is the repository for the server. You should talk to the owners of the xmemcached client, since the log appears to be coming from that.
