### ISSUE TITLE
memcached-1.5.0 fails test: t/whitespace

### ISSUE THREAD

**Issue by sockmonk** [memcached/memcached#290]
memcached-1.5.0 failed a test:

  t/whitespace................fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
skipped
        all skipped: Skipping tests probably because you don't have git.
Failed Test Stat Wstat Total Fail  List of Failed
-------------------------------------------------------------------------------
t/stats.t      1   256   108    1  30
5 tests skipped.
Failed 1/59 test scripts. 1/25710 subtests failed.
Files=59, Tests=25710, 180 wallclock secs (11.46 cusr +  5.30 csys = 16.76 CPU)
Failed 1/59 test programs. 1/25710 subtests failed.
make: *** [test] Error 255

First, I do have git installed at /usr/bin/git.  Second, I shouldn't need git to run memcached. Third, I can't find any information about the GIT_DISCOVERY_ACROSS_FILESYSTEM variable.

This does not happen with the memcached-1.4.39 version on the same Linux system.

**Comment by dormando** [comment]
Hey,

I think you may be misreading the output of the tests. First: it's not saying you don't have git, it's saying you're not in a git repository. If it sees that it doesn't run the whitespace tests; you can see that where it says "all skipped:"

then it lists t/stats.t as having failed. If you scroll up you'll probably see the output of stats.t as having broken.

you can run the tests independently by doing:
`$ prove t/whitespace.t`
`$ prove t/stats.t`

some of my builders have been seeing stats.t fail sometimes, but running it by hand isn't usually an issue. I probably made that test flaky in the update, which will be fixed.

Might also try to suppress that error output from git. It's just capturing the STDOUT, so STDERR is getting passed to the user.

**Comment by sockmonk** [comment]
Ok, after installing 1.5.0 and 1.4.39 on different linux systems that are supposed to be the same configuration/patch level:
I found that stats.t was failing some of the time on some of the machines, both 1.4.39 and 1.5.0.

I also found that chunked_items.t failed, with the error it died without outputting anything.  This was running "make test" and "prove t/chunked_items.t"; it failed the same way both times. 

I ran the "sudo make install" command by itself, and everything seems to be working based on first glance.  The "stats" command is showing hits and misses anyway.

I think you can close this ticket.  Thank you.

**Comment by dormando** [comment]
what distro/verison/etc? I haven't seen chunked_items.t fail.
