### ISSUE TITLE
What is the earliest versions that supports binary protocol?

### ISSUE THREAD

**Issue by duxing** [memcached/memcached#293]
I just read this article on memcached binary protocol:
https://github.com/memcached/memcached/wiki/BinaryProtocolRevamped

And i'd like to know since which version of memcached this was supported? 1.4.25 seems to be working fine but same test code failed for another service that's forked from an old version of memcached.

**Comment by dormando** [comment]
1.4.0, though it was buggy for a few rels after that.

what was the "old version" this other thing is forked from?

**Comment by duxing** [comment]
@dormando thanks for the information.
this old version Im referring to was last updated in 2010 but I don't know which version it's forked from. according to this: https://github.com/memcached/memcached/wiki/ReleaseNotes
I'm guessing it's something before 140 release.
