### ISSUE TITLE
what "hash_bulk_move" means in assoc_maintenance_thread?

### ISSUE THREAD

**Issue by cugblbs** [memcached/memcached#295]
![image](https://user-images.githubusercontent.com/8310816/29345948-c392340e-8274-11e7-9546-c86ab2d0fe01.png)

**Comment by dormando** [comment]
doesn't really mean anything anymore, and I should probably remove it.

It used to mean the number of buckets to move while holding the global item lock, but there's no global item lock anymore and no sleep outside of that loop.
