### ISSUE TITLE
cachedump doesn't work in 1.5.0

### ISSUE THREAD

**Issue by maxd** [memcached/memcached#296]
I am using `stats items` and `stats cachedump` commands for enumerate keys (FYI: I known about restrictions of this way). They works fine prior Memcached 1.5.0:

```
stats items
STAT items:1:number 1
STAT items:1:age 6
STAT items:1:evicted 0
STAT items:1:evicted_nonzero 0
STAT items:1:evicted_time 0
STAT items:1:outofmemory 0
STAT items:1:tailrepairs 0
STAT items:1:reclaimed 0
STAT items:1:expired_unfetched 0
STAT items:1:evicted_unfetched 0
STAT items:1:crawler_reclaimed 0
STAT items:1:crawler_items_checked 0
STAT items:1:lrutail_reflocked 0
END
stats cachedump 1 100
ITEM xxx [3 b; 0 s]
END
```

but since 1.5.0 the `stats cachedump` return noting:

```
stats items
STAT items:1:number 1
STAT items:1:number_hot 0
STAT items:1:number_warm 0
STAT items:1:number_cold 1
STAT items:1:age_hot 0
STAT items:1:age_warm 0
STAT items:1:age 20
STAT items:1:evicted 0
STAT items:1:evicted_nonzero 0
STAT items:1:evicted_time 0
STAT items:1:outofmemory 0
STAT items:1:tailrepairs 0
STAT items:1:reclaimed 0
STAT items:1:expired_unfetched 0
STAT items:1:evicted_unfetched 0
STAT items:1:evicted_active 0
STAT items:1:crawler_reclaimed 0
STAT items:1:crawler_items_checked 0
STAT items:1:lrutail_reflocked 0
STAT items:1:moves_to_cold 2
STAT items:1:moves_to_warm 2
STAT items:1:moves_within_lru 0
STAT items:1:direct_reclaims 0
STAT items:1:hits_to_hot 2
STAT items:1:hits_to_warm 0
STAT items:1:hits_to_cold 1
STAT items:1:hits_to_temp 0
END
stats cachedump 1 100
END
```

Is this a bug or this functionality was removed in 1.5.0?

**Comment by dormando** [comment]
unintentional, but there's also `lru_crawler metadump 1` which replaces it anyway.

I'll leave this open until I test it, though I don't think anything changed in 1.5.0 that would've caused that? what version were you on before?

**Comment by maxd** [comment]
I have used Memcached 1.4.36 installed from `brew` on macOS.

**Comment by dormando** [comment]
(note mostly for me) it does output stuff with -o no_modern, so one of the modern flags was doing it. dump_enabled is yes with on/off and it's not throwing an early error.

should be trivial to figure out.

**Comment by dormando** [comment]
"fixed" for next release. issue is under the segmented LRU, cachedump was defaulting to dumping just the HOT items. More recently the algorithm has been tuned to keep fewer items in HOT, and if you start with just a handful of items they'll end up balanced into COLD anyway..

so I just changed it to default to COLD since there should always be something in there. the lru_crawler metadump command dumps all of the LRU's though.

**Comment by dormando** [comment]
1.5.1 is up
