### ISSUE TITLE
Documentation: wrong expiry value

### ISSUE THREAD

**Issue by azihsoyn** [memcached/memcached#301]
The example code in 
https://github.com/memcached/memcached/wiki/BinaryProtocolRevamped#example-2
shows one hour( `0e10` ) expiry, instead of two ours ( `1c20` ):

> The following figure shows an add-command for with key = "Hello", value = "World", flags = 0xdeadbeef and expiry: in two hours.

```
 Extras              :
     Flags      (24-27): 0xdeadbeef
     Expiry     (28-31): 0x00000e10
```

thanks.

**Comment by dormando** [comment]
Indeed, that is correct! I've fixed. thanks!
