### ISSUE TITLE
Invalid delete response in binary protocal wiki document

### ISSUE THREAD

**Issue by aisk** [memcached/memcached#306]
The [wiki said](https://github.com/memcached/memcached/wiki/BinaryProtocolRevamped#delete):

> Response:
>
> MUST NOT have extras
> MUST NOT have key
> MUST NOT have value

Actually, if the key is not exists, the response of delete command **DO HAVE** a value "NOT FOUND".

**Comment by dormando** [comment]
that's an interesting point... while it doesn't return the *item value* it returns a message, which is a value...

I'll take a closer look at it when I can, thanks!

**Comment by aisk** [comment]
Thanks and it's really confused me while I wrote a client library that I got an invalid magic code "87" after I parsed a delete response. Actually it's the "N" letter from last delete response body "NOT FOUND".

**Comment by dormando** [comment]
Even if the spec says must this or must not that, you should still be parsing the header to see if there's an unexpected body length :)
