### ISSUE TITLE
Use of uninitialized variable vulnerability in function lru_maintainer_thread, file items.c

### ISSUE THREAD

**Issue by shqking** [memcached/memcached#310]
Hi all,
I found a potential use of uninitialized variable vulnerability in function `lru_maintainer_thread()`, at [items.c:L1547](https://github.com/memcached/memcached/blob/master/items.c#L1547).
The vulnerability code snippet is shown as below:
```
1491 static void *lru_maintainer_thread(void *arg) {
1492     int i;
1493     useconds_t to_sleep = MIN_LRU_MAINTAINER_SLEEP;
1494     useconds_t last_sleep = MIN_LRU_MAINTAINER_SLEEP;
1495     rel_time_t last_crawler_check = 0;
1496     rel_time_t last_automove_check = 0;
1497     useconds_t next_juggles[MAX_NUMBER_OF_SLAB_CLASSES];
1498     useconds_t backoff_juggles[MAX_NUMBER_OF_SLAB_CLASSES];
              ...
1545             int did_moves = lru_maintainer_juggle(i);
1546             if (did_moves == 0) {
1547                 if (backoff_juggles[i] != 0) {
1548                     backoff_juggles[i] += backoff_juggles[i] / 8;
1549                 } else {
1550                     backoff_juggles[i] = MIN_LRU_MAINTAINER_SLEEP;
1551                 }
1552                 if (backoff_juggles[i] > MAX_LRU_MAINTAINER_SLEEP)
1553                     backoff_juggles[i] = MAX_LRU_MAINTAINER_SLEEP;
1554             } else if (backoff_juggles[i] > 0) {
1555                 backoff_juggles[i] /= 2;
1556                 if (backoff_juggles[i] < MIN_LRU_MAINTAINER_SLEEP) {
1557                     backoff_juggles[i] = 0;
1558                 }
1559             }
```
Variable `backoff_juggles` is declared at line 1498, without initialization.
However, this **uninitialized** `backoff_juggles` is used directly at line 1547.
This may cause unspecified program behavior.

Regards,
shqking

**Comment by dormando** [comment]
Hey, thanks for the reports!

I'll give them a look through as soon as I can.

**Comment by dormando** [comment]
Fixed in https://github.com/memcached/memcached/commit/a906f77ebda87c339da6160fb01bf5694555d24d - the worst case from this is it ends up sleeping too long when the daemon is first launched, but it would settle within a few seconds. No major bug, but worth fixing, so thanks!

**Comment by shqking** [comment]
Glad to see it is fixed. Thanks.
