### ISSUE TITLE
Whether memcached only  support  PLAIN and CRAM-MD5 sasl authentication?

### ISSUE THREAD

**Issue by Summer402587242** [memcached/memcached#311]
I am trying to find out the list of authentication mechanisms that Memcached supports. I have looked at the documentation pages and found nothing.

Whether only PLAIN and CRAM-MD5 are supported.

 Is this true or does Memcached supports any other authentication mechanisms?

**Comment by dormando** [comment]
It's blindly passing SASL data to a SASL engine. honestly I'm not sure offhand which is possible to support, but I don't think anything is specifically restricting it.

**Comment by dormando** [comment]
if you need further help, please try the mailing list. the issues are for bug reports mainly.
