### ISSUE TITLE
Support transparent huge pages

### ISSUE THREAD

**Issue by wens** [memcached/memcached#313]
It seems memcached only supports huge pages under Solaris, under which memcntl exists.

With modern Linux and FreeBSD, the kernel supports transparent huge pages.
This means the kernel will merge and migrate normal pages into huge pages.
Note that this is a possibility, but not a certainty. If the system does not have
sufficient free pages available, depending on the OS, the allocation may either
fail or fall back to normal pages.

On FreeBSD this is done by using mmap() with MAP_ALIGNED_SUPER.
On Linux this is done by using madvise() with MADV_HUGEPAGE on an
existing mapping, likely allocated by mmap or posix_memalign.

From what I can understand of the code, nothing is needed at the parameter
check phase, though on Linux it would be a good idea to check
/sys/kernel/mm/transparent_hugepage/enabled . Otherwise
memcached.c:enable_large_pages() can just return 0 on Linux and FreeBSD.

In slabs.c:slabs_init(), malloc() in the prealloc block would need to be replaced
with mmap() and madvise() (on Linux only) with some #ifdefs. The fall back
path stays the same.

Does that sound like a plan?

**Comment by dormando** [comment]
Sounds about right. People will run into issues doing large mmap's, so there should be good error handling to communicate to the user as well.

you giving it a shot? :)

**Comment by wens** [comment]
I think so. Can't give any guarantees on any timeline though. :)

**Comment by dormando** [comment]
If you see how laggy I usually am here, you'll find yourself at home :P

not that I should be proud of that..

**Comment by dormando** [comment]
this went in, but I never closed the issue :)
