### ISSUE TITLE
feature: hasMapping() function that does not "freshen" the mapping for the LRU

### ISSUE THREAD

**Issue by andynuss** [memcached/memcached#321]
I am storing memcached mappings to correlate with lots of s3 objects that I have.  Some of the S3 objects are special in that they are temporaries of a sort, and not attached to any document.  When these s3 objects are created in a special bucket, a mapping is put into memcached, so that for a period of time, as long as not reclaimed by memcached, these S3 temporaries can be found and used, though still not incorporated into documents.

Because these s3 temporaries are not referenced in any document, once a week, once a day, etc, there must be a small long running ec2 process that iterates the special bucket, and if memcached has evicted the corresponding mapping, that temporary is deleted.  Otherwise, this bucket will grow and grow, indefinitely, and most of its s3 objects are just a waste of space.

Unfortunately, this iterator of the s3 bucket will have to call get(), which I do thru the spyware java library, and thus the memcached mapping, if it does still exist, will be seen to have been "accessed" in a cache-related way, making that object appear fresher to the LRU heuristic, than the more important non-temporary objects that are still in the cache, and not ever iterated from S3 in such a way.

The ideal solution would be for memcached to provide a hasMapping() function that does not count as a true get() for that mapping from the standpoint of the LRU, i.e. the hasMapping() function will not update ANY internal volatile timestamp fields in the mapped value held in memcached.

**Comment by dormando** [comment]
Hey,

I've gotten a request for something like this a few times; I'm inclined to add it when we can. I believe I added some internal structures for fetching items without bumping in the LRU recently so it should be possible. It'll probably take a while before I get to it..

I would like to point out that recent versions have a segmented LRU which makes this specific problem less impactful. There're some online tuning commands documented in doc/protocol.txt, you can even turn it off/on or change the queue caps on a live server. Should be easy to test if it's helping you or not.

It depends on how often that scanner is getting called, but it should help a bit.

**Comment by dormando** [comment]
This... actually exists now, as of #484 should be in experimental release for 1.5.19.

so... just under two years? :|
