### ISSUE TITLE
no need assert(...)?

### ISSUE THREAD

**Issue by wylazy** [memcached/memcached#324]
I'm browsing the memcached source code.  In crawler.c, I doubt there is no need to assert(search->slabs_clsid == 0). Because the memory is freed, and may be reused by other thread. Am I wrong ?
```
static void crawler_expired_eval(crawler_module_t *cm, item *search, uint32_t hv, int i) {
    ...
    do_item_unlink_nolock(search, hv);
    do_item_remove(search);  // the memory is freed to slabs.
    assert(search->slabs_clsid == 0);   // assert after the memory is freed ?
...
}
```

**Comment by dormando** [comment]
pretty sure you're correct. I've actually removed that assert twice while developing extstore, but it never made it into an actual commit. the assert will misfire sometimes.

**Comment by dormando** [comment]
this is getting removed in #342
