### ISSUE TITLE
Reducing syscalls / batching writes

### ISSUE THREAD

**Issue by ScottMansfield** [memcached/memcached#325]
In a previous communication (I forget where) @dormando mentioned a possibility of reducing the number of syscalls by batching the writes of responses using more iovs. In the code as it stands, there's a couple places that use an array already, but there's never more than one request's response in the iovec when the transition to the conn_mwrite state occurs.

I propose a couple solutions here that may work to reduce the number of writev calls made:

1) Introduce a timer to flush only every u microseconds, configurable on startup or dynamically. This should be in conjunction with some maximum number of iovs in the iovec.

2) Introduce an intermediate state (or state transition function that conditionally goes to conn_mwrite) to instead check if there's another request in the input buffer that can be serviced prior to transitioning to conn_mwrite. If there is, service that one up to reqs_per_event requests before transitioning the connection to conn_mwrite.

The real solution might be a combination of the two with an asynchronous flush at a certain time.

The idea here is that if the server has many requests waiting in the input buffer it can transition to a more throughput oriented mode of operation using the input buffer of the connection as a signal. This should reduce the number of syscalls needed when the server is under heavy load.

This modification was on the back burner in my mind for a while, but now with some performance reductions (that I don't have quantities for) from recent meltdown and spectre patches in AWS, the need has gotten somewhat greater to look at reducing our syscalls.

I can look at modifying the code to support the second behavior and look into a timer that would allow the first. I see there's a lot of activity around external storage that has recently been merged into master, so I'm not sure if starting from there or starting from tag 1.5.4 would make the most sense.

If this sounds like a good direction to head, let me know and I can start working on it in earnest.

**Comment by dormando** [comment]
1.5.4 has the extstore stuff merged in... you should always work from the 'next' branch though.

lets see if we can collaborate. Reworking the frontend to improve batching and buffer handling was already my next project, and as you said meltdown has made things notably more... necessary.

First, 2) is my vote. adding timers to everything will slow it down too much. instead what we want is more along the lines of reqs_per_event that already exists, or simply reusing it. bonus points for a server default and then a per-connection override, perhaps.

Second, this is probably a lot of typing. For ASCII protocol you can probably wedge it into working without too much effort; ie, skip conn_mwrite in certain conditions as you said. Binprot makes a base assumption that there is exactly one request being processed at a time, so connection datastructures and the entire protocol handler will need to be adjusted.

Errors and anything which uses c->wbuf would likely force a flush, until buffer handling can be redone.

That all said, I've read in the last few days about AWS updating something and the regression becoming less bad. Did you observe anything like that?

**Comment by dormando** [comment]
I'm on vacation this week as well, fwiw... what I can do is spend an hour or two splitting out issues for the major components of what I was going to do, then you can fill in any that are missing we can discuss on the individual issues.

**Comment by ScottMansfield** [comment]
We (Cassandra, actually, specifically) observed a reduced overhead in the last few days from performance patches rolled out by AWS. It definitely helped, but it's still now top of mind so I figured I'd bring it up. I don't believe we've seen the end of the changes, either. Besides, I think it's still a good change to make in the longer run to increase efficiency under load.

I wouldn't worry about doing too much on vacation, enjoy the time off :) I can spend the time grokking the buffer management in the binary protocol.

**Comment by dormando** [comment]
it's not too much trouble to split it out, and should give you a heads up. I probably won't do anything serious until next week, and I can only work on it off-hours. :/

and yeah.. like I said it was my next big thing to work on. if only meltdown stayed quiet another month, we'd probably be ready for it :) the frontend code is officially the oldest, cruftiest, and most generally untouched. most of the rest of the code I'm happy with feature wise, and more simply needs refactoring/simplification to clean up the interfaces over time.

**Comment by dormando** [comment]
https://github.com/memcached/memcached/milestone/1

threw the ones I remember thinking about into this milestone. I'm sure we'll come across more (killing off libevent is going to be a thing, but probably under a different set of changes..). Anyway, the order the work is done will be important as to getting it stable more quickly. Ideally broken into independent release friendly changes
