### ISSUE TITLE
ext storage in 1.5.4

### ISSUE THREAD

**Issue by panchenji** [memcached/memcached#326]
Hi,

I'm doing some evaluation on the ext storage option in 1.5.4. I'm not sure what is the recommended "-m" option when I turn on ext storage. Lets say if I set up max page number to be 1000, which consumes 64GB disk. What should be the recommended "-m" option? 
My understanding for the ext storage is that the memory will be competed between page cache and memory used by memcached process. And memcached still need memory for index and write buffer. So what is the best practice to estimate "-m" when turning on ext storage?

Chenji

**Comment by dormando** [comment]
You should be setting -m as high as is reasonable, just like a normal server. But like you said the page cache is currently used, so you need to leave a little more memory available than normal. IE; if you normally allocate everything but 1G, try 2G instead. The amount you need to leave free will depend on the workload, so you should run some experiments and adjust it if the system struggles.
