### ISSUE TITLE
Nullpointer while inserting cache values above 6mb

### ISSUE THREAD

**Issue by a2l007** [memcached/memcached#333]
I've configured memcached 1.4.22 and could see that every attempt to insert data sized more than ~6MB is giving me the following error:

```
2018-01-30 22:17:00.645 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to exception on {QA sa=/1.2.3.4.5:11211, #Rops=0, #Wops=1, #iq=0, topRop=null, topWop=Cmd: 1 O
paque: 505 Key: app:cceabea9aaeb58418912fb56762dc0c7c927e150:cceabea9aaeb58418912fb56762dc0c7c927e150 Cas: 0 Exp: 2592000 Flags: 2050 Data Length: 1902195, toWrite=0, interested=4}
java.lang.NullPointerException
        at net.spy.memcached.protocol.TCPMemcachedNodeImpl.fillWriteBuffer(TCPMemcachedNodeImpl.java:206)
```

The size value configured for memcached is 10000
Any comments on what could be the issue here?

**Comment by dormando** [comment]
That looks like an issue with spymemcached itself, not the server? Have you tried asking them?

What were the actual startup arguments to memcached?

**Comment by a2l007** [comment]
Turns out the issue was because the maxSize was configured to 1MB but the cache values were greater than that. Got fixed once the maxSize was changed.

**Comment by rohantandon96** [comment]
Btw, I received similar issue to @a2l007 but simply increasing the maxSize didnt work for me. I am inserting data of size ~12MB into memcached.

Issue: https://github.com/monix/shade/issues/64

**Comment by dormando** [comment]
@rohantandon96 please don't necro random old issues :(

It looks like you're setting the maxSize for spymemcached but probably not increasing the max item size for memcached itself, so the server would reject you.

**Comment by rohantandon96** [comment]
@dormando sorry about that.
I did increase the max item size on memcached itself and not for spyMemcached.

**Comment by dormando** [comment]
@anthonyryan1 you didn't show anything about what you changed with memcached, what version it's running/etc.

**Comment by rohantandon96** [comment]
![Screen Shot 2020-05-08 at 5 35 49 PM](https://user-images.githubusercontent.com/61017795/81451385-64a37080-9152-11ea-817e-5c61d823dbab.png)

**Comment by dormando** [comment]
Ah, we can't really support the AWS version. You could try opening a raw connection to the instance and SET a value of the size you want and see what happens. it's trivial to generate a raw text protocol request.

If you get an error it's something you'll have to take up with AWS, sorry.

**Comment by rohantandon96** [comment]
ah thanks for that @dormando. What version of memcached do you support? Maybe I can bump up/down the version based on your support and then try.

**Comment by dormando** [comment]
None of them. We can give some support but if you're using their tooling (and it's unclear if they've made modifications to the daemon like they have in the past) you're stuck with them. I support the actual project; the latest versions. If something's wrong you can't exactly upgrade to deal with it :)

What we can do: if you supply output of `stats` and `stats settings` and do what I suggested by writing a SET command to an instance and seeing what happens, we can troubleshoot a little bit. AWS's control panel means nothing to me though.

Also this is still the wrong venue; please open a new issue or try the mailing list/discord for support.
