### ISSUE TITLE
How is the item size being calculated?

### ISSUE THREAD

**Issue by JiumingShao** [memcached/memcached#334]
I know that entries in memcached have a length limitation by default is 1M. And this value is configurable by passing`-I`  when starting the daemon. When I write my client, I want to protect my user from passing in values that are too large to fit in. I ran some tests by putting in large value and found there is a `71 bytes` margin on my machine between the` item_size_max` and `key_length+value_length`. 

I have `STAT item_size_max 1048576` as default

If I put in `byte[] key = new byte[250]; byte[] value = new byte[1048255];` 

* success, and 1048576-250-1048255 =71 

If I put in` byte[] key = new byte[250]; byte[] value = new byte[1048256];`
*  failed. 

I tried with multiple total cache size, multiple max item size limitation  and multiple key lengths. There is always a 71 bytes margin between the  sum of the length of my key and value and the item_size_max.    

I am wondering how can I figure out what is the longest value I can put in, instead of the length of the entry.  And is this 71 bytes a constant value?

Cheers! Thanks in advance.

**Comment by dormando** [comment]
when you build from the repo there's a "./sizes" utility built which describes the overhead of various data structures. items use the item data structure, + key, + value, + a couple bytes (hard to describe, sorry), + 0 or 4 bytes depending on if there're client flags, and + 0 or 8 bytes depending on if CAS is enabled or not. some of this is version dependent.

It's probably safest to do something simple like setting max size to 1M -  2x the maximum key length (500). a little more future proof than getting an exact number.

**Comment by JiumingShao** [comment]
Thanks for the information and your fast response!
