### ISSUE TITLE
[Defect] Memory leak in memcached.c 

### ISSUE THREAD

**Issue by fangang190** [memcached/memcached#337]
Our tool Pinpoint has found a memory leak defect in memcachd.c. Here is the screenshot of this defect. 

The memory allocated on line 5958 is pointed by the pointer list. On line 5974, when e==Null, the program takes the true branch and returned to its caller without freeing the memory pointed by list. 

Suggest Fix: 
free(list) on line 5975. 

![image](https://user-images.githubusercontent.com/1679432/36096105-d261d32e-102f-11e8-9ad6-153e6f60f38c.png)
![image](https://user-images.githubusercontent.com/1679432/36096122-ea0c72fe-102f-11e8-97b7-0b5cee3ed0ef.png)

Gang
Sourcebrella & HKUST

**Comment by dormando** [comment]
went out in 1.5.6
