### ISSUE TITLE
[Defect] Memory leak in memcached.c:7757

### ISSUE THREAD

**Issue by fangang190** [memcached/memcached#338]
Our tool Pinpoint has found a memory leak defect in memcachd.c. The screenshots illustrate the detailed program steps that can trigger this memory leak defect. 

Description: 
The memory allocated on line 7676 is stored to pointer temp_portnumber_filename. If the fopen call fails on line 7681, which makes the pointer portnumber_file to be nullptr. In this case, the free call on line 7713 will be skipped and the memory leaked. 

![image](https://user-images.githubusercontent.com/1679432/36096406-3be8d49a-1031-11e8-9965-73f1c48c387d.png)
![image](https://user-images.githubusercontent.com/1679432/36096427-56e774fe-1031-11e8-8109-291610cc68a6.png)
![image](https://user-images.githubusercontent.com/1679432/36096444-657fd920-1031-11e8-9ed6-4152e6c19fe0.png)
![image](https://user-images.githubusercontent.com/1679432/36096458-74086976-1031-11e8-8caa-66fceabcb985.png)

Gang
Sourcebrella & HKUST

**Comment by phuongkt** [comment]
y

**Comment by dormando** [comment]
fixed in next. another non-issue, since that code is only executed from a specific test or two, and executes once in startup.

**Comment by dormando** [comment]
went out in 1.5.6
