### ISSUE TITLE
remove STATS_LOCK() around curr_bytes, curr_items, and total_items

### ISSUE THREAD

**Issue by dormando** [memcached/memcached#341]
In items.c: curr_bytes, curr_items, total_items are only used for stats output. they currently use a global lock to update global counters.

Also in items.c, sizes_bytes and sizes could do this job (but curr_bytes and sizes_bytes will differ under extstore; this is probably correct behavior). change the stats output to sum these up instead. Also need another per-lru counter for total_items. Those are updated within do_item_link_q and similar.

**Comment by dormando** [comment]
funnily enough, I tried just commenting out these counters/locks and set performance went down :) threads are probably going to sleep due to locks deeper down being held for longer amounts of time.

**Comment by vineelyalamarthy** [comment]
@dormando  are there other issues (bugs) in the project that some one new to the project can take ?

**Comment by dormando** [comment]
@vineelyalamarthy I'll post up a few more later today. I guess this one isn't very good since it'd cause a regression :)

**Comment by vineelyalamarthy** [comment]
sure @dormando  I look forward for them.

**Comment by dormando** [comment]
@vineelyalamarthy check the help wanted tag: https://github.com/memcached/memcached/labels/help%20wanted - I'll keep adding more but that's enough to start.
