### ISSUE TITLE
Memcached SASL

### ISSUE THREAD

**Issue by emrekeles** [memcached/memcached#343]
As described in the documentation, I follow the steps and installed the Memcached with SASL.
It looks work well but when I check the status with "systemctl status memcached" command, I'm seeing following errors.

Feb 14 10:33:35 xxx.sssss.com memcached[4529]: sql_select option missing
Feb 14 10:33:35 xxx.sssss.com memcached[4529]: auxpropfunc error no mechanism available
Feb 14 10:33:35 xxx.sssss.com memcached[4529]: _sasl_plugin_load failed on sasl_auxprop_plug_init for plugin: sql
Feb 14 10:33:35 xxx.sssss.com memcached[4529]: auxpropfunc error invalid parameter supplied
Feb 14 10:33:35 xxx.sssss.com memcached[4529]: _sasl_plugin_load failed on sasl_auxprop_plug_init for plugin: ldapdb
Feb 14 10:33:35 xxx.sssss.com memcached[4529]: ldapdb_canonuser_plug_init() failed in sasl_canonuser_add_plugin(): invalid parameter supplied
Feb 14 10:33:35 xxx.sssss.com memcached[4529]: _sasl_plugin_load failed on sasl_canonuser_init for plugin: ldapdb

I'm not sure, did I do something wrong? but I don't want to go production stage with these error logs.

Do you have any idea and suggestion about these?

yum install libevent-devel
wget https://memcached.org/latest
tar -zxf latest
cd memcached-1.5.5/
./configure --enable-sasl
make
make install

**Comment by emrekeles** [comment]
No

**Comment by dormando** [comment]
the errors look like your sasldb configuration just isn't valid, so when memcached tries to load/talk to it, it spits some errors out. are you intending to use sasl in prod?

If not, you can either compile without sasl support or disable it with the startup argument (you'll have to find where the systemd script is storing the startup parameters)

**Comment by dd5154** [comment]
do you still have to compile to use sasl or is it in the package now?

**Comment by dormando** [comment]
some distro's build it in by default, others have a "-sasl" package, and others don't build it in at all..

I'm going to close this. You can/should ask on the mailing list if you continue to run into issues, but I'm pretty sure what I said should be enough to get you going.

**Comment by emrekeles** [comment]
Hi everyone,

Info : Centos 7 with CloudLinux 7.4 and cPanel

I'm trying to run MEMCACHED with SASL on shared hosting (I'm the hosting provider).

without SASL I'm able to connect memcached successfully but when I'm trying it with SASL it's just not work.

When I start the memcache with following command, I'm seeing few error/warnings, but I'm not sure are these related with my problem.

> service memcached.service start

systemd[1]: Started Memcached.
systemd[1]: Starting Memcached...
memcached[13922]: sql_select option missing
memcached[13922]: auxpropfunc error no mechanism available
memcached[13922]: _sasl_plugin_load failed on sasl_auxprop_plug_init for plugin: sql
memcached[13922]: auxpropfunc error invalid parameter supplied
memcached[13922]: _sasl_plugin_load failed on sasl_auxprop_plug_init for plugin: ldapdb
memcached[13922]: ldapdb_canonuser_plug_init() failed in sasl_canonuser_add_plugin(): invalid parameter supplied
memcached[13922]: _sasl_plugin_load failed on sasl_canonuser_init for plugin: ldapdb

I follow the setup which described on github;

yum install libevent-devel
wget https://memcached.org/latest
tar -zxf latest
cd memcached-1.5.5/
./configure --enable-sasl
make
make install

After setup I'm editing the /usr/lib/systemd/system/memcached.service file


[Unit]
Description=Memcached
Before=httpd.service
After=network.target

[Service]
Type=simple
EnvironmentFile=-/etc/sysconfig/memcached
ExecStart=/usr/local/bin/memcached -u $USER -p $PORT -m $CACHESIZE -c $MAXCONN $OPTIONS -S                                           

[Install]
WantedBy=multi-user.target


Also I editing the /etc/sysconfig/memcached file


PORT="11211"
USER="root"
MAXCONN="1024"
CACHESIZE="64"
#OPTIONS="-l 127.0.0.1"
OPTIONS=""

Then, I use the following command for creating new user;

saslpasswd2 -a memcached -c username

and I'm trying to connect to it via some desktop clients or wordpress but none of them can't connect to it when the SASL enabled.

For seeing logs : /usr/local/bin/memcached -u root -p 11211 -m 64 -c 1024 -S -B binary -vvv (and without "-B binary", result is same)

<37 new binary client connection.
37: going from conn_new_cmd to conn_waiting
37: going from conn_waiting to conn_read
37: going from conn_read to conn_parse_cmd
37: going from conn_parse_cmd to conn_waiting
37: going from conn_waiting to conn_read
37: going from conn_read to conn_closing
<37 connection closed.
37: going from conn_closing to conn_closed
<37 new binary client connection.
37: going from conn_new_cmd to conn_waiting
37: going from conn_waiting to conn_read
37: going from conn_read to conn_parse_cmd
37: going from conn_parse_cmd to conn_waiting
37: going from conn_waiting to conn_read
37: going from conn_read to conn_closing
<37 connection closed.
37: going from conn_closing to conn_closed
<37 new binary client connection.
37: going from conn_new_cmd to conn_waiting
37: going from conn_waiting to conn_read
37: going from conn_read to conn_parse_cmd
37: going from conn_parse_cmd to conn_waiting
37: going from conn_waiting to conn_read
<38 new binary client connection.
38: going from conn_new_cmd to conn_waiting
38: going from conn_waiting to conn_read
38: going from conn_read to conn_parse_cmd
38: going from conn_parse_cmd to conn_waiting
38: going from conn_waiting to conn_read
37: going from conn_read to conn_parse_cmd
37: going from conn_parse_cmd to conn_waiting
37: going from conn_waiting to conn_read
37: going from conn_read to conn_closing
<37 connection closed.
37: going from conn_closing to conn_closed
38: going from conn_read to conn_parse_cmd
38: going from conn_parse_cmd to conn_waiting
38: going from conn_waiting to conn_read
38: going from conn_read to conn_closing
<38 connection closed.
38: going from conn_closing to conn_closed

**Comment by emrekeles** [comment]
ghfghfgh

**Comment by deneme1453** [comment]
sgddfsdfs
