### ISSUE TITLE
How to configure distribution cache?

### ISSUE THREAD

**Issue by hbobbala** [memcached/memcached#344]
I'm using xmemcached with 4 host addresses is working fine, with <5 addresses i'm not able see the memcache updates.

**Comment by dormando** [comment]
can you give more context? what errors are you seeing/etc?

also the mailing list is a much better place for this; more people see it.

**Comment by hbobbala** [comment]
What is the default distribution cache server limits.if I want to increase 4-6 what needs to be done. Each connection limit is 20,it works fine for 4 server and if we configure 6 th one randamoly disconnecting from one of the server.

**Comment by dormando** [comment]
I'm having a really hard time understanding you :(

**Comment by dormando** [comment]
I'm closing this, but taking a guess at what you're asking about:

1) memcached has no limits beyond connection limits (`-c` argument).
2) memcached is distributed by the clients. Either your client library is bad, or the machines running your clients are out of file descriptors, or some similar problem.

**Comment by hbobbala** [comment]
Our client library is xmemcached
