### ISSUE TITLE
CPU Climbs Until Evictions Occur, Then Stabilizes

### ISSUE THREAD

**Issue by amcrn** [memcached/memcached#353]
Memcached Version: `1.5.1`
Command Line Opts: `-m 82275 -t 4 -R 10000 -B ascii -o modern`
OS: Ubuntu Trusty (14.04.X)

Observation: Under sudden moderate read/write traffic, the CPU usage of memcached steadily increases indefinitely even though the rate of reads/writes is constant, until the LRU kicks in and starts evicting, at which point CPU drops and stabilizes.

Note the very consistent rate of reads/writes from 12:00 to 14:00, yet CPU climbs 50% during that same period. Only once evictions start occurring at 13:58 does CPU drop and begin to settle.

![image](https://user-images.githubusercontent.com/4933419/36925749-2ed05020-1e29-11e8-9e29-b3169e1c13ae.png)

![image](https://user-images.githubusercontent.com/4933419/36925783-64b044fc-1e29-11e8-80cf-66fa0aad05b8.png)

Any idea what would explain this behavior? Seems odd that under a very consistent rate of reads/writes that the CPU would continue to climb so dramatically.

Stats output (`stats`, `stats settings`, `stats items`, `stats slabs`) from one of these memcached machines is available at https://gist.github.com/amcrn/03296e0e8308f94b18034f051d541915

**Comment by dormando** [comment]
that is odd! there're a few things which can cause this, but I'm not offhand sure why it would drop when RAM fills. I've put a guess in an envelope and we'll see how it does.

1) How much CPU is this in more absolute terms? Is this busying a single core or multiple cores?

2) If you can reproduce, try connecting and running "lru mode flat\r\n". if that doesn't do it, you can try "lru_crawler disable". shouldn't be any other background threads doing anything significant given your stats outputs.

**Comment by dormando** [comment]
Pinging back; I'd love to understand this problem better, if you have some time.

**Comment by dormando** [comment]
@amcrn poking again :)

**Comment by amcrn** [comment]
Hey there @dormando , sorry about the delay.

1. Multiple cores.
2. I haven't been able to reproduce this again, but let me try harder today :)

**Comment by dormando** [comment]
Excellent, thanks for coming back :) It shouldn't be possible for the background threads to use more than two cores, and given the default delays in the LRU crawler, it's more like one core.

You might be able to create a https://github.com/memcached/mc-crusher config file by using the delay+pipeline arguments to roughly recreate your access patterns. If you can repro via that in your environment you can hand me the config. Otherwise I'm guessing mostly based on the screenshots and stats output you gave me. Haven't spent a lot of time on it myself yet, was hoping to hear back from your tests first.

**Comment by amcrn** [comment]
After a couple of hours of attempts, I was not able to re-create the issue. However, in all of these synthetic tests, `reclaimed` never went above 0 (even though evictions were occurring at a rapid rate). In the original bug report, `reclaimed` was at a steady rate of 200-300 per second, and as CPU began to climb, so did `reclaimed`. Therefore, I'm beginning to think that `reclaimed` is key to reproducing this issue.

Tips on how to configure a benchmark to start maximizing reclaims?

**Comment by dormando** [comment]
Weird, didn't get a notification for your response :(

Yeah; reclaims happen when when expired items are reaped. There are three ways expired items can be removed:

1) clasically, only when they're fetched again (and found to be expired), or when a new item is being inserted and the tail is found to be expired.
2) recently, the LRU maintainer thread frequently pokes the tails and will reclaim items it finds to be dead. the more dead items, the more frequently it wakes up to have a look-see, so this is part of why I was thinking this thread was being too aggressive.
3) the LRU crawler, which walks the entire LRU periodically. By default it's pretty rate limited and it only runs if it thinks it can reclaim a significant percentage of memory. I'd suggested above methods of disabling it if this is the case.

**Comment by dormando** [comment]
Friendly maintainer nag :)

**Comment by amcrn** [comment]
After re-testing with TTLs and verifying a steady clip of reclaims, I still couldn't reproduce the issue :/

For what it's worth `memtier_benchmark --random-data --data-size-range=1024-32768 --data-size-pattern=S --key-pattern=G:G --key-prefix=B --ratio=1:1 -s THE_HOST_NAME -p 11211 -P memcache_text --requests=1000000 --expiry-range=300-300 -c 8 -t 8` is fairly close to the workload.

If it occurs again in the wild, I'll definitely try `lru mode flat` and `lru_crawler disable` per your suggestions. Given that I can't reproduce, I'll go ahead and close this ticket. Really appreciate your feedback and assistance :)

**Comment by dormando** [comment]
@amcrn that is interesting. same version of memcached both times, or using the built-in?
