### ISSUE TITLE
Memcached 1.5.6 compile error

### ISSUE THREAD

**Issue by lj2007331** [memcached/memcached#356]
OS: CentOS6.8 64bit
kernel: 2.6.32-642.6.2.el6.x86_64
`gcc -std=gnu99 -DHAVE_CONFIG_H -I.  -DNDEBUG   -g -O2 -pthread -pthread -Wall -Werror -pedantic -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -fno-strict-aliasing -MT memcached-slab_automove.o -MD -MP -MF .deps/memcached-slab_automove.Tpo -c -o memcached-slab_automove.o `test -f 'slab_automove.c' || echo './'`slab_automove.c
mv -f .deps/memcached-slab_automove.Tpo .deps/memcached-slab_automove.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I.  -DNDEBUG   -g -O2 -pthread -pthread -Wall -Werror -pedantic -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -fno-strict-aliasing -MT memcached-cache.o -MD -MP -MF .deps/memcached-cache.Tpo -c -o memcached-cache.o `test -f 'cache.c' || echo './'`cache.c
mv -f .deps/memcached-cache.Tpo .deps/memcached-cache.Po
gcc -std=gnu99  -g -O2 -pthread -pthread -Wall -Werror -pedantic -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -fno-strict-aliasing   -o memcached memcached-memcached.o memcached-hash.o memcached-jenkins_hash.o memcached-murmur3_hash.o memcached-slabs.o memcached-items.o memcached-assoc.o memcached-thread.o memcached-daemon.o memcached-stats.o memcached-util.o memcached-bipbuffer.o memcached-logger.o memcached-crawler.o memcached-itoa_ljust.o memcached-slab_automove.o memcached-cache.o        -levent -lrt 
memcached-memcached.o: In function `main':
/root/oneinstack/src/memcached-1.5.6/memcached.c:7579: undefined reference to `event_config_new'
/root/oneinstack/src/memcached-1.5.6/memcached.c:7580: undefined reference to `event_config_set_flag'
/root/oneinstack/src/memcached-1.5.6/memcached.c:7581: undefined reference to `event_base_new_with_config'
/root/oneinstack/src/memcached-1.5.6/memcached.c:7582: undefined reference to `event_config_free'
memcached-thread.o: In function `setup_thread':
/root/oneinstack/src/memcached-1.5.6/thread.c:314: undefined reference to `event_config_new'
/root/oneinstack/src/memcached-1.5.6/thread.c:315: undefined reference to `event_config_set_flag'
/root/oneinstack/src/memcached-1.5.6/thread.c:316: undefined reference to `event_base_new_with_config'
/root/oneinstack/src/memcached-1.5.6/thread.c:317: undefined reference to `event_config_free'
collect2: ld returned 1 exit status
make[2]: *** [memcached] Error 1
make[2]: Leaving directory `/root/oneinstack/src/memcached-1.5.6'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/oneinstack/src/memcached-1.5.6'
make: *** [all] Error 2`

**Comment by dormando** [comment]
that's annoying. what version of libevent-devel do you have?

**Comment by dormando** [comment]
@qianl15 - want to figure this one out? :)

**Comment by qianl15** [comment]
Would you also please provide your version number? (By printing out `LIBEVENT_VERSION_NUMBER`)

I think I saw the same version number for different libevent versions, and that may be the problem.

**Comment by qianl15** [comment]
Your compiler will only see libevent new APIs if the condition:   
`#if defined(LIBEVENT_VERSION_NUMBER) && LIBEVENT_VERSION_NUMBER >= 0x02000101`  
is true.

**Comment by lj2007331** [comment]
I installed 2 versions of libevent.
THX
