### ISSUE TITLE
Regression in systemd-based sandboxing in 1.5.6

### ISSUE THREAD

**Issue by basak** [memcached/memcached#359]
#285 regressed systemd-based sandboxing in all builds not via RPM from the upstream spec file. The comment added to `scripts/memcached.service` says:

> Some security features are not in the older versions of systemd used by
> e.g. RHEL7/CentOS 7. The below settings are automatically edited at package
> build time to uncomment them if the target platform supports them.

However "at package build time" is incorrect in the current implementation unless you live in an RPM-only world, all distributions build from the spec file you ship and nobody ever builds from upstream source directly.

Therefore this change regressed security in every other distribution in the world as well as when building and installing directly from upstream source.

The right way to handle this is for packaging to patch or sed out what it cannot support when building against older versions of software, or alternatively to actually adjust the upstream build system to do the same at build time. Right now, the implementation is backwards, relying on packaging to enhance security at build time instead, and leaving the default upstream build less secure.

**Comment by dormando** [comment]
Thanks! I was curious about that, but time on my part is pretty limited. Tagging @elfchief to pull him into this conversation. To give context, these spec files lived in an rpm only world. I wasn't aware of upstream debian/etc actually using it.

Also to be clear; these security lockdowns are definitely not critical and themselves were added relatively recently. I'd rather they not be there than memcached be unusable, until we know when to safely enable it. The software doesn't rely on them to stay secure, it just helps if they're available.

So, lets improve things :) I'm not sure I follow along with your example in the last paragraph; "when building against older versions of software" - can you give the full context here? IE: is this a package build or etc? I don't think the systemd version can be known when the C code is compiled.

Alternatively the upstream build? Is that debian/ubuntu's build? In that case, isn't that what the RPM is doing?

**Comment by elfchief** [comment]
Hmmm. Interesting. I'm legit surprised that there's distributions using the unit files directly from the distribution, but I guess it's not actually that surprising -- unit files are far more portable than init scripts were.

Lemme take another look at things and see if I can sort this out.

**Comment by guikcd** [comment]
FYI, for Debian distribution, we directly use the `memcached.service` unit file, with minor specific changes: https://anonscm.debian.org/git/collab-maint/memcached.git/tree/debian/patches/02_service_wrapper.patch since version `1.5.1` (https://anonscm.debian.org/git/collab-maint/memcached.git/tree/debian/changelog?h=master#n27).

**Comment by basak** [comment]
@guikcd FYI, here's my workaround for this issue against 1.5.6: https://git.launchpad.net/~racb/ubuntu/+source/memcached/commit/?h=upstream-bump-1.5.6&id=f2d03d1d6d841fd02b6c7399ad7b3b881f4e8d7a

It's up for peer review with my team at the moment. I intend to send it to you once approved, as it's applicable to Debian as well.

**Comment by basak** [comment]
Here are some suggestions on how to resolve this.

> So, lets improve things :) I'm not sure I follow along with your example in the last paragraph; "when building against older versions of software" - can you give the full context here? IE: is this a package build or etc?

Traditionally, users could install upstream software with some variation of `./configure && make && sudo make install`. In that case, the configure script would make decisions based on your build host by default, including decisions about versions - but that can usually be overridden by providing answers for the target host instead. The configure script would arrange for `make install` to do the right thing - installing the correct init script into the right place as well as installing the binaries into `/usr/local` by default.

> I don't think the systemd version can be known when the C code is compiled.

It can - that can be arranged in autoconf. To do it absolutely right there are even provisions for people who aren't building on the target platform in autoconf (eg. for cross building) to supply the answer directly. But in this case it shouldn't matter - it's safe to assume the target system has a current version of systemd unless told otherwise or detected otherwise.

Packaging concerns are usually laid on top of this scheme by somewhat standard was of overriding this. For example `--prefix` is commonly used to configure the build for final installation into `/usr` instead of `/usr/local` and `DESTDIR` to override the target at `make install` stage so the packaging system can pack up the payload for unpacking on a different system.

Usually, then, it isn't expected that the upstream shipped service file already has elements disabled to accomodate the needs of a particular distribution. This would be expected to be done at the packaging stage - by the spec file in this case.

The use case that is currently broken is that if I build using `./configure && make && make install` from the upstream release on a current Debian or Ubuntu system, I'll end up with a `memcached.service` that has various security sandboxing options unintentionally disabled.

Separately, I think this is being done backwards. The generally accepted way to handle security related matters is to be more secure by default. I would expect, if anything, that the directives @elfchief needs removed to be flagged in the upstream source perhaps but not disabled there, and the sed in the spec file to pick up on these flags to disable them. For example, instead of:

    ##safer##MemoryDenyWriteExecute=true

I'd expect:

    # Not available in systemd < x.y:
    MemoryDenyWriteExecute=true

...with the sed in the spec file picking up on `# Not available in systemd < x.y:` and deleting the following line if required. Then upstream would still be shipping something complete, and distributions shipping the upstream file as-is wouldn't have their security compromised.

Even better, the upstream build could "build" `memcached.service` from a `memcahed.service.in`, with something like a `--disable-systemd-sandboxing` option to `./configure`. This would be ideal: packagers would see a `memcached.service.in` and understand that the upstream build preprocesses it, the upstream build would preprocess it appropriately by default, and @elfchief would be able to supply `--disable-systemd-sandboxing` in his spec file to get what he wants for his edge case.

**Comment by dormando** [comment]
You're definitely right for most packaged cases; ie debian, ubuntu, redhat upstreams, it's not going to be true for all use cases of the specs. I intend to add a PPA soon so folks can always grab the latest version in .deb format, but that binary will be likely used on more platforms than I have builds for. This is a surprisingly common thing to do now.

That said, I'm not really sure we have to optimize for it... but I will repeat that I value these particular security twiddle *much less* presently than the software actually starting. It's strictly not backwards to me because they're new and they're not well tested; until I'm confident they won't be a support burden I'd rather they disappear more often than they appear. We've already had some issues and users are likely to instead run some hack for their init scripts instead of figure out what to comment out, thus losing the features forever :( Worst case for the project, people are very likely to completely switch the software rather than figure out why something won't start.

This is compounded by enterprise-y folks intentionally running ancient software.

I wonder if something like your `./configure` compromise would work, but for my cross-platform builds I would simply ship with them disabled for another year or two; I was just hoping there'd be a way to ship cross-platform rpms/debs and still get the features when it's safe.

**Comment by elfchief** [comment]
My brain turned on for a brief moment, and I realized, we might be able to take care of this easily, though it would require upstreams to change their packaging slightly. Basically, do this:

  - memcached.service has the "extra" security options removed
  - supply a "extra security" systemd override file that can be dropped into `/usr/lib/systemd/system/memcached.service.d/extra-security.conf` in packages built for systems where these functions are supported

...if we wanted, we could even supply multiple files, perhaps with filenames indicating a minimum systemd version, that distributions can pull in as appropriate.

Like I said, does require additional upstream work, but is _way_ cleaner than trying to manage it in autoconf or do a bunch of sed-ing or whatever at package build time.

What do folks think about doing something like that?

**Comment by elfchief** [comment]
@basak @guikcd -- ping?

**Comment by elfchief** [comment]
@dormando -- Given lack of other responses, what do you think? Autoconfig this, or offer systemd dropins that distros can use for enhanced security?

**Comment by dormando** [comment]
@elfchief  if we want to do the latter we need to get their attention I think :/ I'm bug hunting so we can try for a few more days before the next cut, probably.

**Comment by guikcd** [comment]
If the only platform that don't support this option is RHEL/CentOS, i think we can just document the option so that they can disable it. In future release, they will activate (well, not disable) it to benefit of the protection.

@dormando for providing .deb with latest version, we (with Ubuntu folks ?) can discuss this to provide backports of memcached version considered as "stable" or LTS for stable Debian/Ubuntu distribution.

**Comment by basak** [comment]
Some great ideas here. I think a `memcached.service.d` directory would be fine assuming that systemd upstream support the use of upstreams shipping it that way. I have no reason to think that they don't.

I do think, however, that upstream should arrange for all security options to be turned on by default. It's normal for backports to have to patch or make build adjustments anyway. Using a provided mechanism to drop functionality should therefore be trivial for any backporting packager - whether for older distro releases for for a PPA. Different backport targets can have varying requiremnets, so in the general case doing it this way makes more sense, and it's the way round most upstreams operate.

Whether you use autoconf or do it with `.d` files, pulling something out will be trivial when backporting to something that doesn't have support, so I think either would work well.

By all means use automation or provide manual options to disable certain parts, and use these options in _your_ PPAs, etc.

In general then, I think it only makes sense to have everything on by default in upstream builds (except when detected as not possible at build time) as soon as you consider something production ready. That's the only way to get widespread use, as enhancements enabled manually, such as expecting distro maintainers to know to install particular files, are less likely to be noticed and actually done in practice.

Once something like this _has_ shipped by default, pulling it out again should be avoided if possible since doing so would be a feature regression.

**Comment by elfchief** [comment]
Haven't forgotten about this, hoping to get back to it perhaps this weekend.

**Comment by dormando** [comment]
Anyone want to think about this? I haven't had time :(

**Comment by dormando** [comment]
Going to close this out since I'm not personally motivated to deal with it, and it's possible by now everyone affected has upgraded. If someone wants to take it on we can re-open or start a new issue.
