### ISSUE TITLE
can't visit https://memcached.org/downloads to download package

### ISSUE THREAD

**Issue by penger** [memcached/memcached#364]
can't visit the site https://memcached.org/downloads in china 
can anyone give me a link to download the package? ths

**Comment by dormando** [comment]
Do you know if this used to work? I recently moved the site from linode to digitalocean...

**Comment by penger** [comment]
OK , hope it finish soon ...

**Comment by dormando** [comment]
Sorry, I was asking if you were able to download from memcached.org in the past?

**Comment by penger** [comment]
yes we can download everyday ,how long can the site be visit .

**Comment by dormando** [comment]
I will try to fix it. Where are you exactly?

**Comment by penger** [comment]
i'm in chengdu . china

**Comment by dormando** [comment]
if you use linux (like ubuntu or centos) you can install with package manager:
`sudo apt-get install memcached`
or
`sudo yum install memcached`
depending on which you use.

**Comment by penger** [comment]
For security we can't use yum command 
today we download  soucecode from github , make && make install it ,finished 
input 'memcache -V' it appareds 'Unknown'
i think there must someting goes wrong. 
sorry for my poor english.

**Comment by dormando** [comment]
Try:

`git clone [etc]`
`git checkout 1.5.6`
`./autogen.sh && ./configure && make && make test`
if okay:
`sudo make install`

**Comment by penger** [comment]
i'll try it later ,but i think there isn't any difference with download the zips

**Comment by dormando** [comment]
`memcached -V` will be wrong unless git is used :( sorry

**Comment by penger** [comment]
can visit now.
