### ISSUE TITLE
Fix SASL_CB_GETCONF detection , it is SASL_CB_GETCONFPATH on linux.

### ISSUE THREAD

**Issue by thatsafunnyname** [memcached/memcached#365]
Hello and thanks for memcached,

I was using and then building a memcached instance built with SASL support on linux (RHEL 5,6,7) and I noticed the support for detecting the SASL callback to read an alternative config path does not work on linux because the name differs from the name Sun used/uses.

I think Sun used SASL_CB_GETCONF ( see links 1, 2, 3 below), so in ```configure.ac```

```unsigned long val = SASL_CB_GETCONF;```

needs to be:

```unsigned long val = SASL_CB_GETCONFPATH;```

on RHEL7,EL6 and EL5.  I'd probably duplicate what exists for ```HAVE_SASL_CB_GETCONF``` to ```HAVE_SASL_CB_GETCONFPATH```.

Then in ```sasl_defs.c``` the first 2 ifdefs would check for either define being true and the 3rd would be changed from:

    #ifdef HAVE_SASL_CB_GETCONF
       { SASL_CB_GETCONF, sasl_getconf, NULL },
    #endif

to:

    #ifdef HAVE_SASL_CB_GETCONF
       { SASL_CB_GETCONF, sasl_getconf, NULL },
    #else
    #ifdef HAVE_SASL_CB_GETCONFPATH
       { SASL_CB_GETCONFPATH, (sasl_callback_ft)sasl_getconf, NULL },
    #endif
    #endif

Xref:
  (1.) https://github.com/memcached/memcached/wiki/ReleaseNotes145#sasl_pwdb-for-more-simple-auth-deployments
  (2.) https://github.com/memcached/memcached/commit/7a221d95a870bd01ba1c93650c63abd583b00d39
  (3.) http://comments.gmane.org/gmane.mail.postfix.devel/1537

I am building with:

    ./configure --enable-sasl --enable-sasl-pwdb

and because ```SASL_CB_GETCONF``` detection was not working...

    make CFLAGS='-DHAVE_SASL_CB_GETCONF=1 -DENABLE_SASL_PWDB=1'

If this is something you think is worth fixing then I can send a PR.

Thanks.

**Comment by dormando** [comment]
That sounds completely reasonable. Go ahead and send a PR!

**Comment by dormando** [comment]
released in 1.5.7
