### ISSUE TITLE
Add hardware crc support for aarch64

### ISSUE THREAD

**Issue by aparida1** [memcached/memcached#374]
Missing crc support verified to exist on :
Memcached version: 1.5.7
platform: QDF2400 ( aarch64 platform )
OS: Linux ( Redhat/Ubuntu)

Currently in memcached source code,  we are either utilizing crc hardware support for x86 platforms or it falls back to default sw implementation which uses matrix manipulation.
Hence, for platforms like aarch64, we can also use the available crc support to speeden up the crc computation.

Attached crc patch :
[crc32c.zip](https://github.com/memcached/memcached/files/1919206/crc32c.zip)
Made necessary changes in crc32c.c file.

Tested the patch with "make test" on both x86 and QDF2400.
Attached screenshots of "All tests successful" on both the platforms : 
![make-test-memcached](https://user-images.githubusercontent.com/31002057/38863877-990402ce-4256-11e8-8923-402e95a719c3.JPG)

Thanks,
Ashutosh Parida
Qualcomm Datacenter Technologies

**Comment by dormando** [comment]
Thanks for this! A real PR would be preferred for anything in the future but I can work with this for now. I have an aarch64 via a raspberry pi 3 and will validate this as soon as I get a chance.

**Comment by dormando** [comment]
I fixed this up a bit and merged it into the 'next' branch. Had some build/platform issues.

**Comment by aparida1** [comment]
Great. Thanks a lot!

**Comment by dormando** [comment]
@aparida1 still having some issues... I'm merging it in, but I had to add a `--enable-arm-crc32` option to re-disable this at compile time. Unless you specify `-march=armv8-a+crc` an aarch64 platform will get a compiler error, and I'm not familiar enough with arm to know if that should be defaulted if aarch64 is detected.

Any thoughts on this?

**Comment by aparida1** [comment]
The ARMv8 CRC32 instructions are optional ARMv8 ISA instructions. They require a compiler flag to enable so that the assembler recognizes them.
Hence, -march=armv8-a+crc  is needed.

https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html

**Comment by dormando** [comment]
I understand that much so far, my point is the patch you provided simply fails to compile on systems with aarch64 and I'm trying to figure out the best option for moving forward.

**Comment by aparida1** [comment]
That is strange. What is the arm version of that aarch64 platform you are using? 
crc is enabled after armv8.1 onwards by default. 
only for armv8-a, we have to enable explicitly.

**Comment by dormando** [comment]
apparently it's a HiSilicon Hi1616 system, discussion is going on here: https://github.com/docker-library/memcached/pull/38#issuecomment-391230411 - I don't think they've tried but I'm pretty sure if they added march it would work properly. Googling a bit showed several major projects (mongo, kafka? etc) received arm64 crc32 patches and then later had these same compilation issues for some users.

I don't personally have a platform to test any of this on, closest is an rpi3 but I need to get a new install for a full 64bit OS.

**Comment by dormando** [comment]
This is released now in 1.5.8, but I'd appreciate any ideas on how to improve the usability of this across portable systems :)

**Comment by aparida1** [comment]
Awesome @dormando , Thanks a lot !!!
Yup, will need your support and cooperation for aarch64 fixes and improvements!
