### ISSUE TITLE
session.save_handler and session.save_path no detect memcached

### ISSUE THREAD

**Issue by azcrusher** [memcached/memcached#375]
Hi everyone,

Please help me,

in picture, i have been installed, php-fpm 56, memcached & php-memcached in centos 6.9.

in case, why in http://ipaddress/info.php cannot loaded session.save_handler to "memcached" and session.save_path " to ipaddress:11211

pic:
https://ibb.co/k7S5rn

#cat /etc/sysconfig/memcached

PORT="11211"
USER="memcached"
MAXCONN="4096"
CACHESIZE="4096"
OPTIONS="-l 10.x.x.x"

and memcached extension is enabled:

#/etc/php.d/z-memcached.ini
; Enable memcached extension module
extension=memcached.so

kindly can help me, please advice..

Thank you,
Azrusher

**Comment by dormando** [comment]
This repo is for bugs about the memcached server daemon. You should try a PHP community on stackoverflow. Sorry, I can't help you :(
