### ISSUE TITLE
FastoNoSQL review

### ISSUE THREAD

**Issue by topilski** [memcached/memcached#376]
Hi, we working with Memcached about 3 years, can you review our solution, we using libmemcached for connection, here implementation: https://github.com/fastogt/fastonosql/blob/master/src/core/db/memcached/db_connection.cpp , thank you.

**Comment by dormando** [comment]
do you have a specific question? This file has no comments, and I'm not sure if you're looking for bugs, general usage issues, etc.

**Comment by topilski** [comment]
Hi thank you for reply, i think about code review, and may be some proposals from maintainers side. You can also download application here: https://fastonosql.com/anonim_users_downloads , how to use here: https://github.com/fastogt/fastonosql/wiki/Memcached
