### ISSUE TITLE
Arch Linux (stable) on Scaleway C1 ARMv7 (32 bits), it won't fully start

### ISSUE THREAD

**Issue by ChazyTheBest** [memcached/memcached#384]
Today I performed a full system upgrade and memcached stopped working, I can connect to it though, but it won't respond anything:

```
# telnet 127.0.0.1 11211
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
flush_all


quit

^C^X^Z^Z
```
I have to open another terminal (ssh) and use systemctl to stop memcached for it to release the other session.

It works if I manually build the latest tarball from https://memcached.org/.

**Comment by dormando** [comment]
@viraptor he's running 1.5.8 from arch upstream and it looks like seccomp again, as the journal logs have some seccomp prints. I'm confused as to how it could fail this way after the latest changes :(

**Comment by viraptor** [comment]
That's likely. I don't have an ARM system to test on unfortunately. I'd be happy to assist in debugging, but for now, making seccomp x86/64-only may be a better option.

**Comment by dormando** [comment]
I swear I tested it on my rpi's... I don't personally have access to whatever system this is, so I'll probably blacklist arm like you said.

**Comment by viraptor** [comment]
The thing is that the code depends on:
- architecture
- kernel version
- libc type
- libc version
Even if you tried on Rpi, it could have a differ in some way from Scaleway's platform :( I'd love to support as many as possible, but it's actually only doable if you have the platform available for testing. I'll submit a whitelist patch soon.

**Comment by dormando** [comment]
Yeah, this is not quite as fun as I was hoping. People are enabling this without much testing and we're probably losing users. :(

**Comment by ChazyTheBest** [comment]
@viraptor Sure, provided there's no omitted steps in that guide, I think I can manage. I'll start once I get home.

**Comment by ChazyTheBest** [comment]
This is what I get: http://termbin.com/u8fa Sorry I don't understand much, If i'm missing something please specify and I'll do it.

**Comment by SandyDong** [comment]
good project!

**Comment by dormando** [comment]
@viraptor anything I can help with? I'm planning on cutting another release in the next week, almost been a month already. would be excellent to nip this.

**Comment by dormando** [comment]
looks like I'll be blacklisting ARM from seccomp, fwiw.

**Comment by dormando** [comment]
ended up flipping the defaults in 1.5.9. leaving this open a little longer in case we want to try to understand what the delta was.

**Comment by dormando** [comment]
gonna close this out. no complaints on 1.5.9, and we're continuing to slowly work on it now that it's been moved to safer defaults.
