### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [memcached/memcached#385]
Would you like to add more error handling for return values from functions like the following?
- [pthread_cond_wait](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_wait.html "Wait on a condition") ⇒ [assoc_maintenance_thread](https://github.com/memcached/memcached/blob/5c0face158f1d0f9c6add22b8f027e468bbe5368/assoc.c#L199)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex") ⇒ [cq_init](https://github.com/memcached/memcached/blob/3b11d16b3f92c51bfedbb092147e1c2b225945ff/thread.c#L186)

**Comment by dormando** [comment]
don't care about cq_init, I think. assoc_maint_thread's cond should either have error checking or skip the expand if it spuriously woke.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software? :thinking:
