### ISSUE TITLE
Protect against spurious wakeups

### ISSUE THREAD

**Issue by elfring** [memcached/memcached#387]
I have seen that [no loop is used around a call](https://github.com/memcached/memcached/blob/95e6469bd2ceef92bcaaf140e2724fc73d556185/crawler.c#L484 "Update candidate: start_item_crawler_thread()") of the function “[pthread_cond_wait](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_wait.html "Wait on a condition")”.
Would you like to reuse anything from my message on the topic “[spurious wakeup](https://groups.google.com/d/msg/comp.programming.threads/Gpe38hgZlsQ/1_1SRoCZgrsJ)”?

**Comment by dormando** [comment]
not sure I follow? the specific code you linked is usually only run once when the thread starts.

**Comment by elfring** [comment]
Can the call of the function “pthread_cond_wait” return here before the desired system predicate is fulfilled?

**Comment by dormando** [comment]
In this particular case it's only there to help with race conditions during the tests, which are constantly starting/stopping the daemon, so it only happens on startup. I'd be open to a well tested patch but I don't think I'll spend effort on this myself. I'm going to close this out, but feel free to re-open with a PR if you feel strongly about it.

thank you though!

**Comment by elfring** [comment]
Which predicate should be checked [there](https://github.com/memcached/memcached/blob/95e6469bd2ceef92bcaaf140e2724fc73d556185/crawler.c#L484 "Update candidate: start_item_crawler_thread()")?
