### ISSUE TITLE
improve linux seccomp

### ISSUE THREAD

**Issue by dormando** [memcached/memcached#402]
This is marked "help wanted" - as if you run linux on an obscure platform (like some docker/alpine/arch/arm/something), I'd love if you'd attempt to build memcached with seccomp and run the tests:
`./configure --enable -seccomp && make && make test`
if it fails tests, drop a comment with more info (info on getting the trace is in HACKING).

Also tagging @viraptor one last time, since he's been invaluable in making this work all along :)

Now that I'm more caught up, I've taken a more careful look at how the linux seccomp stuff actually works, and I like it a lot less than was hoping. There're a few things I want to fix:

- [ ] SCMP_ACT_KILL kills the thread, not the process, which causes hangs. No way to process kill pre-4.11, so switch this to use the SIGSYS trap and exit the process after printing something useful.
- [ ] Add two starttime options for enabling seccomp: 1) log only, 2) kill process. simply compiling it in should not enable it, given so many distro users are getting screwed and have to make their own builds to work around it. Also gives us a second chance to drive the point home to people via documentation about this being experimental and not a must-have.
- [ ] Is there any way I'm missing on how to scan for deny actions? any way to live patch or startttime patch if shit's missing? I see there's a get_cap-ish thing, but you have to know all of the possible syscalls ahead of time which seems insane.

re the last point: if a user starts seccomp in log (well, any) mode and it fails, they currently have to patch C code and recompile. Are there any better options?

**Comment by dormando** [comment]
No worries! I at least want the startup options and perhaps the kill fix by tomorrowish (my time), but I can do that myself pretty easily. The rest could hit july's release.

Been thinking about self tests too but it seems pretty hard... you can set it to trap every syscall and build a profile, but then you need to ensure full test coverage + tests get run + load the profile + muh? Seems pretty broken :(

**Comment by dormando** [comment]
I got a little distracted by life, as is probably obvious :) hopefully you've had a chance to look at things.

**Comment by viraptor** [comment]
The last point is interesting. There could certainly be a way to add either a config profile, or a list of syscalls as a parameter (that would be added to the existing ones). I think that it would be a good option.

As long as everything has access to STDOUT/STDERR, the SIGSYS could also be an interesting option. I'll give it a go.

**Comment by viraptor** [comment]
And please, do tag me if anything comes up and I don't notice. I'd like to push this to fully stable, production status. :)

**Comment by viraptor** [comment]
https://github.com/memcached/memcached/pull/403 is a simple "people fix"

**Comment by viraptor** [comment]
I've got the SIGSYS kind-of-working. I'm just trying to figure out the details about how to be sure the whole process is killed. I believe `abort()` does the right thing, but due to being run inside a signal handler, there are no guarantees really.
I'm checking if it at least works in most cases...

**Comment by dormando** [comment]
in #342 I added a method of breaking out of the main loop safely via signal handlers. I'm aiming that for the july release (er, second july release...), so you can do it with abort() for this cut and improve it in the next one.

most important for right-now are run-time options, still.

**Comment by dormando** [comment]
okay, #407 for the defaults problem... I have a whole process for slowly changing the defaults and really ought to stick to it. I'd honestly completely forgotten it had a starttime kill switch :( if a distro adds this by default now, it should be much more obvious to the user since it'll be in the command line.

decided to not add anything wrt logging vs kill myself, I'll leave that up to you, @viraptor - also running really late on account of an extstore bughunt.

**Comment by dormando** [comment]
1.5.9 is out with #407 - one thing I didn't do was add an env var to ensure all of the tests run with drop_privileges enabled, so right now it just enables it for the misbehave.t test. Up to you for how to do that for now?

hopefully this reduces the support burden until this is figured out anyway.

**Comment by viraptor** [comment]
Added logging on kill to https://github.com/memcached/memcached/pull/408

**Comment by viraptor** [comment]
Thanks for changing the default. I'll have a look at running all tests with `drop_privileges` next.

**Comment by dormando** [comment]
#408 looks like an improvement, thanks! think you're still working out logging/warning modes?

people get audit lines in dmesg when things fail, too. not entirely sure how this is supposed to be consumed. ie; is it idiomatic to have an "ignore the failures" mode and people monitor via dmesg or something?

**Comment by dormando** [comment]
@viraptor about a week off from rolling up another release, anything I should include for sure?

**Comment by viraptor** [comment]
Apologies, ski season needed attention :(

So regarding the self-test, I don't think it's a good approach. Mainly it would have the same issues as the list has now, where we'd have to maintain the self-test "outside of the normal system". This is just going to lead to a drift and if the tests have good coverage, they should provide the same functionality.

Regarding logging, it looks like 4.14 added the possibility for a system-wide log for seccomp violation, which is great! It would have to use conditional compilation, but I'm just testing how useful is the log output and writing some better instructions for moving faults into exclusions in the code.

**Comment by viraptor** [comment]
Almost forgot - another issue with implementing the log action now is that libseccomp itself doesn't include this action, so that will have to go through upstream of that project first.

**Comment by dormando** [comment]
well, I'll close this out. If we get more reports I guess we'll do another round :) at least it's off by default so it can't cause too much damage.
