### ISSUE TITLE
cachedump returning inconsistent results? (very little data involved)

### ISSUE THREAD

**Issue by rafbm** [memcached/memcached#405]
I’ve read many posts saying that `stats cachedump` was unsupported, soon-to-be-removed, limited to dumping 1MB, etc. Yet, the command is still present in the latest version so I would expect it to be at least somewhat useful.

However, I’m getting extremely inconsistent results that are mostly impossible to rely on. See this example session where I clear everything then set three very small items (empty lines added for clarity):

```
flush_all
OK

set key1 0 0 3
aaa
STORED

set key2 0 0 3
bbb
STORED

set key3 0 0 3
ccc
STORED
```

Then `stats items` says there are 3 items in slab 1, as expected:

```
stats items
STAT items:1:number 3
STAT items:1:number_hot 0
STAT items:1:number_warm 0
STAT items:1:number_cold 3
STAT items:1:age_hot 0
STAT items:1:age_warm 0
STAT items:1:age 3
STAT items:1:evicted 0
STAT items:1:evicted_nonzero 0
STAT items:1:evicted_time 0
STAT items:1:outofmemory 0
STAT items:1:tailrepairs 0
STAT items:1:reclaimed 0
STAT items:1:expired_unfetched 0
STAT items:1:evicted_unfetched 0
STAT items:1:evicted_active 0
STAT items:1:crawler_reclaimed 0
STAT items:1:crawler_items_checked 0
STAT items:1:lrutail_reflocked 57
STAT items:1:moves_to_cold 23
STAT items:1:moves_to_warm 20
STAT items:1:moves_within_lru 0
STAT items:1:direct_reclaims 0
STAT items:1:hits_to_hot 0
STAT items:1:hits_to_warm 0
STAT items:1:hits_to_cold 23
STAT items:1:hits_to_temp 0
END
```

But when I try to list all items in slab 1, results are totally inconsistent, often listing 2 arbitrary keys out of 3, but sometimes listing all 3 (which proves no data has been evicted):

```
stats cachedump 1 0
ITEM key1 [3 b; 0 s]
ITEM key2 [3 b; 0 s]
END

stats cachedump 1 0
ITEM key3 [3 b; 0 s]
ITEM key2 [3 b; 0 s]
END

stats cachedump 1 0
ITEM key2 [3 b; 0 s]
ITEM key1 [3 b; 0 s]
END

stats cachedump 1 0
ITEM key2 [3 b; 0 s]
ITEM key1 [3 b; 0 s]
ITEM key3 [3 b; 0 s]
END

stats cachedump 1 0
ITEM key2 [3 b; 0 s]
ITEM key1 [3 b; 0 s]
ITEM key3 [3 b; 0 s]
END

stats cachedump 1 0
ITEM key2 [3 b; 0 s]
ITEM key3 [3 b; 0 s]
END
```

What to make of this? Is that the expected behavior? If not, a bug?

I’m using the latest memcached version 1.5.8 (installed through Homebrew) on macOS 10.13.5. Here is the output of my `stats settings`:

```
STAT maxbytes 67108864
STAT maxconns 1024
STAT tcpport 11211
STAT udpport 0
STAT inter localhost
STAT verbosity 0
STAT oldest 55074
STAT evictions on
STAT domain_socket NULL
STAT umask 700
STAT growth_factor 1.25
STAT chunk_size 48
STAT num_threads 4
STAT num_threads_per_udp 4
STAT stat_key_prefix :
STAT detail_enabled no
STAT reqs_per_event 20
STAT cas_enabled yes
STAT tcp_backlog 1024
STAT binding_protocol auto-negotiate
STAT auth_enabled_sasl no
STAT item_size_max 1048576
STAT maxconns_fast yes
STAT hashpower_init 0
STAT slab_reassign yes
STAT slab_automove 1
STAT slab_automove_ratio 0.80
STAT slab_automove_window 30
STAT slab_chunk_max 524288
STAT lru_crawler yes
STAT lru_crawler_sleep 100
STAT lru_crawler_tocrawl 0
STAT tail_repair_time 0
STAT flush_enabled yes
STAT dump_enabled yes
STAT hash_algorithm murmur3
STAT lru_maintainer_thread yes
STAT lru_segmented yes
STAT hot_lru_pct 20
STAT warm_lru_pct 40
STAT hot_max_factor 0.20
STAT warm_max_factor 2.00
STAT temp_lru no
STAT temporary_ttl 61
STAT idle_timeout 0
STAT watcher_logbuf_size 262144
STAT worker_logbuf_size 65536
STAT track_sizes no
STAT inline_ascii_response no
END
```

**Comment by dormando** [comment]
stats cachedump only dumps the HOT_LRU (IIRC?), which is managed by a background thread as activity happens. This means under a new enough version which the 2Q algo enabled, you'll get snapshot views of what's in just one of the LRU's.

If you want to view everything,`lru_crawler metadump 1` is the new mostly-officially-supported method that will asynchronously dump as many keys as you want. you'll get them out of order but it hits all LRU's, and unless you're deleting/replacing items multiple runs should yield the same results.

**Comment by dormando** [comment]
the memcached-tool in the tarball uses the newer method, fwiw. the syntax might change slightly before I stop labelling it experimental, but the feature's there to stay.

**Comment by rafbm** [comment]
Oh! Thanks so much. `lru_crawler metadump 1` (or `lru_crawler metadump all`) seems much more consistent indeed.
