### ISSUE TITLE
how is the right way to configure memcached to allow connection only from a ip list

### ISSUE THREAD

**Issue by luzfcb** [memcached/memcached#412]
Hello, how is the right way to configure memcached to allow connection only from a ip list ?

> this is probably a documentation bug

the [wiki](https://github.com/memcached/memcached/wiki/ConfiguringServer#networking) does not explain it clearly enough. (I, as a non-English speaker, could not understand with conviction)

supposing that the ips that I want to give access are: 10.0.0.50 and 10.0.0.70

I try put on `/etc/memcached.conf` in a debian 9.2 machine

```
-l 127.0.0.1,10.0.0.50,10.0.0.70
```
or
```
-l 127.0.0.1;10.0.0.50;10.0.0.70
```
or
```
-l 127.0.0.1 10.0.0.50 10.0.0.70
```
or
```
-l 127.0.0.1
-l 10.0.0.50
-l 10.0.0.70
```
but none of these seems to work. the memchached log is:

```
bind(): Cannot assign requested address
bind(): Cannot assign requested address
failed to listen on TCP port 11211: Cannot assign requested address

```

I put it `-l 0.0.0.0` and this seems to have worked, however, I'm not happy to give indiscriminate access to any machine in my network.

I probably doing something wrong or misunderstanding something.

if doing this is not possible with memcached, is there any technical explanation of why? (if yes, it probably should be in docs)

**Comment by dormando** [comment]
`-l` defines which IP addresses the server *listens* on. It does not limit which IP's can *connect* to memcached. If you want to limit which IP addresses can talk to memcached you need to use a firewall such as iptables.

**Comment by luzfcb** [comment]
@dormando Thank you for responding so quickly.

Another question: I can continue using `-l 0.0.0.0` and limit access with firewall?
(or `-l 0.0.0.0` it will result in some problem or is not considered good practice. )

a bit of context, of the problem I want to solve.

I have a django application and this application run some queries to the database, which are incredibly slow (I've optimized them the best way possible), but because the data changes very rarely, I decided to cache them

memcached works well for a single machine.

for reasons of performance, I had to scale horizontally.

so I have several instances of my application, but they share the same database, and should share the same instance of memcached, because unfortunately, I have very limited computational resources.

I'm trying to make the other instances of my application connect to a single instance of memcached. I'd like to prevent any machine off my white list, get memcached access.

**Comment by dormando** [comment]
I'm sorry but firewalls are outside of the scope of support I can give here.

I'll give you a hint: your server is on some sort of local network. You gave an example of 10.0.0.50 and .80, so I'm guessing your servers are on a 10.0.0.0/24 or 16 or 8 network.

on your memcached server, find the actual IP address it listens on for the 10* network, then use -l appropriately:

`-l 127.0.0.1,10.0.0.10` if 10.0.0.10 is an IP address that is *local* to the memcached server.

then you need to configure your clients to all connect to 10.0.0.10. you can use a firewall to limit it from there.

**Comment by jhonyvivianello** [comment]
Friend 

Correct is -l 127.0.0.1 SPACE IP-Address-Server

-l 127.0.0.1 10.0.0.50

**Comment by moveyourself** [comment]
The missing part appears to be that you need to include local host in the list or it fails. 

-l 127.0.01 IPADDRESS01 IPADDRESS02
