### ISSUE TITLE
Remove dead code in memcached.c 

### ISSUE THREAD

**Issue by gy741** [memcached/memcached#418]
Hello.

I think, The following line 2161 of memcached.c is useless.

Because the Since the value of outlen variable does not change.

So, I think, The if statement is always false.

what do you think?

Thanks.

https://github.com/memcached/memcached/blob/1ac5d63b9b027ad8951323108088ce8a8fcddd29/memcached.c#L2079-L2176

**Comment by dormando** [comment]
in the first switch statement, &outlen is passed to the sasl start functions. it can be changed by those functions.

**Comment by gy741** [comment]
@dormando 

Hello,

Thank you for your reply.

There's something I don't quite understand.

Does memcached use Cyrus SASL?

Thanks.
