### ISSUE TITLE
setrlimit(RLIMIT_NOFILE fails with EPERM when run under valgrind

### ISSUE THREAD

**Issue by thatsafunnyname** [memcached/memcached#420]
Hello and thanks for memcached,

I was running memcached as part of build system tests, the build system tests run under valgrind with --trace-children=yes, memcached is run from within these test processes, valgrind fails with EPERM when setrlimit(RLIMIT_NOFILE is called when the max/hard limit is changed:

With these ulimits for nofile:

    > ulimit -S -n ; ulimit -H -n
    1024
    4096

Without valgrind we set maxconns to 256:

    > /usr/bin/memcached -p 54321 -c 256
    ^CSignal handled: Interrupt.

With valgrind this fails because valgrind returns EPERM for setrlimit with a change to the hard/max nofile limit:

    > valgrind /usr/bin/memcached -p 54321 -c 256
    failed to set rlimit for open files. Try starting as root or requesting smaller maxconns value.

When maxconns is not passed, if the soft/current ulimit is not 1024 setrlimit fails:

    > ulimit -H -n ;ulimit -S -n
    2048
    2048

    > valgrind /usr/bin/memcached -p 54321
    failed to set rlimit for open files. Try starting as root or requesting smaller maxconns value.

This is with valgrind-3.13.0 on RHEL7 hosts and Valgrind-3.11.0 on Ubuntu 16.

I could not come up with a PR that I thought would be OK.  Always calling setrlimit for the soft/current limit, and only calling setrlimit for the hard/max limit when needed was the approach I thought would work best, but I didn't think the complexity was worth it for the benefit?

I plan to use the valgrind options ```--trace-children-skip*=patt1,patt2,..."```, for the tests that are testing client side libraries.

http://valgrind.org/docs/manual/dist.news.old.html
  "The setrlimit system call now simply updates the emulated limits as best
  as possible - the hard limit is not allowed to move at all and just
  returns EPERM if you try and change it."

**Comment by dormando** [comment]
That's frustrating. memcached has operated this way for 15 years. :/

I'll have to come back to this, unless someone else has a great idea. thanks for bringing it up with plenty of detail!
