### ISSUE TITLE
outofmemory errors using -modern with 1.4.39

### ISSUE THREAD

**Issue by thatsafunnyname** [memcached/memcached#421]
Hello and thanks for memcached,

  We enabled ```-o modern``` for some 1.4.39 instances around 7 weeks ago, and one of the instances just got into a bad state (LRU evictions not happening for some slabs) which looks a little like the states described in https://github.com/memcached/memcached/issues/195 and https://github.com/memcached/memcached/issues/224 

The instance was running with:

```
/usr/bin/memcached -d -p 11242 -U 0 -m 15000 -c 32700 -P pid.file 
  -o modern -R 100 -n 80 -C -f 1.5
```

outofmemory errors, 0 free_chunks in the slabs and high evicted_time values for the smaller items:

```
> grep outofmemory stats_items.txt
STAT items:1:outofmemory 0
STAT items:2:outofmemory 0
STAT items:3:outofmemory 0
STAT items:4:outofmemory 5
STAT items:5:outofmemory 0
STAT items:6:outofmemory 6
STAT items:7:outofmemory 4
STAT items:8:outofmemory 4
STAT items:9:outofmemory 2
STAT items:10:outofmemory 0
STAT items:11:outofmemory 0
STAT items:12:outofmemory 0
STAT items:13:outofmemory 0
STAT items:14:outofmemory 182
STAT items:15:outofmemory 65
STAT items:16:outofmemory 188
STAT items:17:outofmemory 0
STAT items:18:outofmemory 85
STAT items:19:outofmemory 37
STAT items:20:outofmemory 0
STAT items:21:outofmemory 140
```

```
> grep ':free_chunks ' stats_slabs.txt
STAT 1:free_chunks 8180
STAT 2:free_chunks 1
STAT 3:free_chunks 0
STAT 4:free_chunks 0
STAT 5:free_chunks 0
STAT 6:free_chunks 0
STAT 7:free_chunks 0
STAT 8:free_chunks 0
STAT 9:free_chunks 0
STAT 10:free_chunks 0
STAT 11:free_chunks 0
STAT 12:free_chunks 0
STAT 13:free_chunks 0
STAT 14:free_chunks 0
STAT 15:free_chunks 0
STAT 16:free_chunks 0
STAT 17:free_chunks 0
STAT 18:free_chunks 0
STAT 19:free_chunks 0
STAT 20:free_chunks 0
STAT 21:free_chunks 0
```

```
> grep 'evicted_time' stats_items.txt
STAT items:1:evicted_time 0
STAT items:2:evicted_time 43756
STAT items:3:evicted_time 37681
STAT items:4:evicted_time 11783
STAT items:5:evicted_time 32842
STAT items:6:evicted_time 26073
STAT items:7:evicted_time 25022
STAT items:8:evicted_time 17812
STAT items:9:evicted_time 3
STAT items:10:evicted_time 8638
STAT items:11:evicted_time 5361
STAT items:12:evicted_time 32298
STAT items:13:evicted_time 1254
STAT items:14:evicted_time 0
STAT items:15:evicted_time 0
STAT items:16:evicted_time 0
STAT items:17:evicted_time 32004
STAT items:18:evicted_time 0
STAT items:19:evicted_time 0
STAT items:20:evicted_time 14480
STAT items:21:evicted_time 0
```

stats are reset every 5mins.

I was wondering if anything can be done (other than not using ```-o modern```) to avoid the outofmemory events and large evicted_time values.
 
Thanks.

[settings.txt](https://github.com/memcached/memcached/files/2306566/settings.txt)
[stats.txt](https://github.com/memcached/memcached/files/2306567/stats.txt)
[stats_items.txt](https://github.com/memcached/memcached/files/2306568/stats_items.txt)
[stats_slabs.txt](https://github.com/memcached/memcached/files/2306570/stats_slabs.txt)
[stats_conns_redacted.txt](https://github.com/memcached/memcached/files/2306582/stats_conns_redacted.txt)

**Comment by dormando** [comment]
hmm. for what it's worth; evicted_time isn't "high" or "low", it's the age of the most recently evicted item. so technically the higher the better. evictions being high is worse. The rest of your counters just indicate it's out of memory, which can be normal but is probably due to background threads being jammed.

sadly there's not much I can recommend beyond upgrading. I can't recall exactly which release that went into but pretty sure some similar issues were fixed. Any chance you could try one instance on the latest release?

**Comment by dormando** [comment]
also, it looks like you're resetting the stats frequently? (`stats reset`), might want to stop doing that since it'll be harder to tell what's going on.

little more detail:
```
STAT slab_reassign_busy_items 182714
STAT slab_reassign_busy_deletes 0
STAT slab_reassign_running 1
STAT slabs_moved 0
```

page mover is jammed, hasn't moved a single page. got a few page mover fixes inbetween your version and current.

**Comment by thatsafunnyname** [comment]
Thanks for taking a look.  The instance is one of many that has been using ```-o modern``` for a few months now, it is a production instance so it will be going back to not using "-o modern" until we get around to the project to upgrade to 1.5.  It's good to know you are pretty sure some similar issues were fixed in more recent releases.
  Yes, the stats are reset every 5min when they are collected:

![image](https://user-images.githubusercontent.com/4728785/44417371-3ee4cb00-a56d-11e8-9db6-8ef682070d13.png)

![image](https://user-images.githubusercontent.com/4728785/44417399-52903180-a56d-11e8-8d28-98887e165f52.png)

![image](https://user-images.githubusercontent.com/4728785/44417415-5f148a00-a56d-11e8-9e64-3d1a9350c3f3.png)

**Comment by dormando** [comment]
you should use differential counters in your monitoring system and stop resetting stats in memcached, if you can.

**Comment by thatsafunnyname** [comment]
Yes, I know.
It stems from a legacy monitoring charting system that could not store that a series was a counter and remember to always display a rate for it (you had to keep applying a delta processor when building charts).  It was not my decision to reset the stats when collecting and then to continue with this behaviour as our monitoring systems evolved, I advocated no longer resetting them.

**Comment by dormando** [comment]
You do what you need to do :)

Mind if we close out this issue? You can reopen if it still happens under latest 1.5; though I hope you don't overthink upgrading from 1.4 to 1.5. if you're already testing `-o modern` under 1.4.39 it's extremely close to the latest 1.5 series. Most of the newer code is gated behind compile flags (extstore, seccomp).

**Comment by thatsafunnyname** [comment]
>> Mind if we close out this issue?
No, thanks for the help.  I have rolled back ```-o modern``` with 1.4.39 on the instances of the use case where the bug was hit, and initiated an upgrade to 1.5.X.  It will be at least a couple of months before 1.5.X is deployed on the same prod instance that hit the bug.  I will let you know if I see this again.
