### ISSUE TITLE
Autostart - chkserv.d

### ISSUE THREAD

**Issue by faca5** [memcached/memcached#422]
Hello.

How I can add "memcache" or "memcached" to auto start if stop working?

I have tried with "chkserv.d" but It doesn't work on UDP port?!

Any idea?

This are instructions which i have already tried.

Thank you.

Instructions:

CentOS 5 and 6
/etc/chkserv.d/memcached
service[memcached]=11211,version,VERSION,/etc/init.d/memcached restart,memcached,memcached

/scripts/restartsrv_memcached
#!/bin/bash
/etc/init.d/memcached restart

chmod +x /scripts/restartsrv_memcached

CentOS 7
/etc/chkserv.d/memcached
service[memcached]=11211,version,VERSION,/bin/systemctl restart memcached,memcached,memcached
/scripts/restartsrv_memcached
#!/bin/bash
/bin/systemctl restart memcached
chmod +x /scripts/restartsrv_memcached

**Comment by dormando** [comment]
how did you install memcached on these systems?

**Comment by faca5** [comment]
WHM, yum

I have solved this problem with custom bash script.

chkserv.d get false response and it restart memcached each 5-15 minutes.

**Comment by dormando** [comment]
sounds like you figured something out? so I'll close this.
