### ISSUE TITLE
How do we output size when using lru_crawler metadump

### ISSUE THREAD

**Issue by eft** [memcached/memcached#426]
Is there a flag or configuration setting that allows ` lru_crawler metadump` to output item size?  In my output I only see : key, exp, la, cas and fetch.  (We are on version 1.5.3 (2017-11-4).)

https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L548-L561

**Comment by dormando** [comment]
cls (class id) and byte size were added to the metadump output in ... 1.5.4 I think?

**Comment by eft** [comment]
@dormando thanks!
 
Found your commit ;)

https://github.com/memcached/memcached/commit/dd53b5e99a8fcc20d8b64f49ffc1516732855222#diff-0e357b8ba6db388f2ef0e1e5d20947b2R234

**Comment by dormando** [comment]
1.5.10 is a good version to upgrade to, IMHO :)

anything else you need or can we close this out?

**Comment by eft** [comment]
we can close - thanks !
