### ISSUE TITLE
assoc.c error

### ISSUE THREAD

**Issue by vaneyli** [memcached/memcached#434]
typedef  unsigned long  int  ub4;   /* unsigned 4-byte quantities */

on 64-bit machine the sizeof(unsigned long  int) is 8。

Fix:
typedef  uint32_t ub4;

**Comment by morteryler** [comment]
I tried to suggest a fix https://github.com/memcached/memcached/compare/master...morteryler:patch-1

**Comment by dormando** [comment]
apparently this doesn't actually matter (sorry I didn't ping the issue earlier).  It should probably just be hard-set to a uint32_t for code clarity, but if it's 8 bytes it doesn't actually affect anything.

**Comment by dormando** [comment]
out in 1.5.14
