### ISSUE TITLE
[Query] Amount of Memcached connections

### ISSUE THREAD

**Issue by nunoperalta** [memcached/memcached#435]
Hello,

This is a query and not a bug report.

On a busy website (500+ users simultaneously all the time), I'm using persistent connections to Memcached with PHP and php-memcached client.

I'm not sure if I'm doing it right, but the persistent connection ID is always the same.
I only open a connection per PHP request.

Two things I noticed is that "curr_connections" is always around ~10.
I believe this is the number of PHP requests that are running at a given "time snapshot". Once the PHP request has finished, I'd say the connection is being closed.

However, when I check "netstat", I see **loads** of TCP connections open on port 11211, in a "TIME_WAIT" state. And it seems to be both ways.

Example (2 lines):
tcp        0      0 127.0.0.1:11211             127.0.0.1:9699              TIME_WAIT
tcp        0      0 127.0.0.1:5065              127.0.0.1:11211             TIME_WAIT
.

At the moment, there are 7513 connections open in this state. I've been monitoring in the past 24 hours and it's been always around a number like this.

.
Any ideas if this is the expected for a healthy server, or am I doing something wrong?

In relation to persistent connections - is it ok that I'm always using the same persistent ID, or should I be having, say, 20 persistent connections that are chosen randomly when creating a Memcached object?

Thank you very much,
Nuno

**Comment by dormando** [comment]
Hey,

The TIME_WAIT connections means you're closing connections constantly and not actually using persistent connections. I'm not really familiar with php-memcached's semantics, you might have better luck on PHP support forums or digging through some code examples.

In the stats counters you should see "total_connections" increasing, if you're successfully using persistent connections curr_connections will probably be a bit higher and total shouldn't be growing very quickly.

If you're using something like php-fpm it's also possible your processes are dying off after requests and thus unable to reuse connections.

**Comment by nunoperalta** [comment]
Thanks very much Dormando.

Not using php-fpm (yet). My PHP processes do close after every request.

Well - I guess that's my answer then. A persistent connection would only make sense if my PHP processes stayed alive at the same time. If my PHP processes are killed after every request, then the connections are closed as well. It's not up to Memcached to keep those connections alive, if the other side has gone away.

Am I thinking correctly here?

Thank you,
Nuno

**Comment by dormando** [comment]
Hmm mostly. Some forms of PHP (like apache mod_php) have mechanisms for holding persistent connection objects inbetween requests, so it depends on how you're running PHP and if you (or the client library) are properly using that API. It's been too long since I've looked so, again, apologies.

**Comment by nunoperalta** [comment]
This was greatly improved/reduced after installing PHP-FPM and then enable persistent connections.
