### ISSUE TITLE
documentation - udp is disabled since 1.5.6

### ISSUE THREAD

**Issue by Seb35** [memcached/memcached#438]
Since #348 UDP is disabled by default, this should be documented [on the wiki page ConfiguringServer#udp](https://github.com/memcached/memcached/wiki/ConfiguringServer#udp), perhaps with something like 
```
defaulting to off since 1.5.6 (defaulting to on before)
```

I arrived on this through the [Cloudflare blog post](https://blog.cloudflare.com/memcrashed-major-amplification-attacks-from-port-11211/). Perhaps some warning about amplification attacks could be written on the wiki to warn users with older memcached versions.

**Comment by morteryler** [comment]
wiki cannot be edited, we are very limited in rights

**Comment by dormando** [comment]
I keep just not seeing this issue. Just fixed it.

At some point I'll find an ass to halve and put the wiki on its own github repo, since github's never found a way to let people make PR's against a project wiki... opening the rights just fills it with spam.
