### ISSUE TITLE
secure Memcached with TLS

### ISSUE THREAD

**Issue by tharanga** [memcached/memcached#441]
Deployments of Memcached in cloud environments may need to encrypting its network traffic. We can implement SSL/TLS on top of the TCP protocol to achieve this goal. TLS can also help with authentication and ensuring the data integrity.

**Comment by morteryler** [comment]
Good job

**Comment by Anakin-Hao** [comment]
So good to see TLS getting done. Security compliance very often depends all traffics, even internal, to be encrypted. 

Do you have a release date for this big feature?

**Comment by dormando** [comment]
No release date. I am finally getting time to properly review this this month though.

This might have two stages:
1) releasable but mixed/poor high end performance.
2) later optimized for the typical openssl lock scaling (maybe requiring something like amazon s2n) + interleaving handshake latency bubbles.

**Comment by dormando** [comment]
this is...  out in 1.5.13.
