### ISSUE TITLE
Possible bug in SASL documentation?

### ISSUE THREAD

**Issue by aristaeus** [memcached/memcached#443]
[The documentation](https://github.com/memcached/memcached/wiki/ReleaseNotes145#sasl_pwdb-for-more-simple-auth-deployments) suggests that the environment variable `SASL_CONF_PATH` should be set to the location of the SASL config for memcache (e.g. `/etc/sasl2/memcached.conf`). However this isn't the case. `SASL_CONF_PATH` is passed through to SASL as `SASL_CB_GETCONF`. [Other SASL documentation](https://docs.oracle.com/cd/E23824_01/html/819-2145/sasl.intro.20.html#sasl.intro-34) suggests that this is actually the path to the directory containing the SASL `memcached.conf` (in the example above, `/etc/sasl2`). In my testing this is the case - setting `SASL_CONF_PATH=/custom/sasl/directory/memcached.conf` doesn't load the config, but `SASL_CONF_PATH=/custom/sasl/directory/` does.

There's probably not many people who need to use a custom sasl config location, but I may as well save the next person a bit of time :)

**Comment by morteryler** [comment]
Check if the problem is in memcached 1.5.10

**Comment by dormando** [comment]
This finally got fixed a few months ago, hopefully not breaking too many installations in the process :(
