### ISSUE TITLE
make test : t/lru-maintainer.t failed at line 80 fail during installation

### ISSUE THREAD

**Issue by dranandrao** [memcached/memcached#445]
Hi, I'm trying to build from source. I have downloaded the latest source code, but facing error in **make test** execution.

I have followed the steps given in installation part of memcached GitHub repository.

_Following are the commands used._

wget https://memcached.org/latest
[you might need to rename the file]
tar -zxf memcached-1.x.x.tar.gz
cd memcached-1.x.x
./configure --prefix=/usr/local/memcached
 
I have attached the error file.
[error.txt](https://github.com/memcached/memcached/files/2698596/error.txt)

**Comment by dormando** [comment]
ahh, I need to fix the auto-updater for that /latest link :( Sorry. if you grab the tarball via the homepage, it should not have that bug. sorry for the late response.
