### ISSUE TITLE
how to dump sasl

### ISSUE THREAD

**Issue by ZhangZhuomin** [memcached/memcached#451]

**Comment by ZhangZhuomin** [comment]
memcached-tool use **lru_crawler metadump all** to dump the data, but sasl enabled memcached is not supported for ASCII protocol, and I can not found **lru_crawler metadump all** command in the [BinaryProtocol](https://github.com/memcached/memcached/wiki/BinaryProtocolRevamped),so how to back up data in the sasl enabled memcached?

**Comment by ZhangZhuomin** [comment]
> _No description provided._

**Comment by dormando** [comment]
Hey,

Sadly, there's no binprot equivalent for metadump yet :( there're a handful of what I'd considered debug/administrative commands that weren't ported to binprot. It's on the roadmap and issues like this helps me prioritize things.

**Comment by dormando** [comment]
ASCII has basic token based authentication now, and I'm deprecating the binary protocol in favor of the new meta commands... so unfortunately I should qualify this as a won't fix.

The newer protocols are much simpler so this'll be better for long term maintenance.
