### ISSUE TITLE
memcached supported OS

### ISSUE THREAD

**Issue by ethanhere** [memcached/memcached#457]
I like to install memcached 1.5.12 to CentOS 6.10. However I don't find supported OS in documents.
Can someone confirm the above combination works?
Thanks!

**Comment by dormando** [comment]
Something stopping you from trying? :) Just grab the source and build? 6 is pretty old and we don't have buildbots for it, but it might work still.

**Comment by ethanhere** [comment]
even we build it, we cannot test it. is there a way you can try?

**Comment by dormando** [comment]
I don't understand. Can you please explain "we cannot test it" ? Do the tests not run?

**Comment by ethanhere** [comment]
if memcached running on centos 6.1, we don't know how to run those tests.
you must have a suit of test that covers all the api, right? would you test them with centos 6.1?
thanks!

**Comment by dormando** [comment]
once you compile it, run "make test" in the source directory. it will run tests.

**Comment by ethanhere** [comment]
thanks.

**Comment by dormando** [comment]
I'm going to close this out. Good luck.
