### ISSUE TITLE
Memcached: Configuration of ip address and port

### ISSUE THREAD

**Issue by agarwalkirti** [memcached/memcached#459]
Hi,
I am not able to configure memcached 1.5.12 in my ubuntu 16.04. I installed memcached successfully using 
wget https://memcached.org/latest
tar -zxf memcached-1.5.12.tar.gz
cd memcached-1.5.12
./configure --prefix=/usr/local/memcached
make && make test && sudo make install
I am trying to start memcached service using "sudo service memcached start" command. I cannot see the memcached service whether it is up and running when i see the active servers using "sudo netstat -plunt" command. I dont know how to give our own ip and port for configuring memcached when installing from source. Please help me.

Thank you
Kirti

**Comment by dormando** [comment]
`make install` doesn't install start scripts for your OS distro. You can start memcached yourself, or look at the start scripts in the scripts/ directory of the tarball. You'll have to follow your distro's guide to manually adding a new service

**Comment by agarwalkirti** [comment]
how can i find the distro guide. Where it is present. Is there any installation summary just to verify my installation steps if they are wrong somewhere

**Comment by dormando** [comment]
https://serverfault.com/questions/785502/create-daemon-on-ubuntu-16-04
use the file from scripts/memcached.service in the mc tarball

**Comment by WSLUser** [comment]
Here: https://gist.github.com/BetsuNo/331f6ecc3b0bc5b3997bf2098235ae2e
