### ISSUE TITLE
memcached -L option

### ISSUE THREAD

**Issue by ethanhere** [memcached/memcached#460]
I run mamcached with the following options
PORT="11211"
USER="nobody"
MAXCONN="1024"
CACHESIZE="14336"
OPTIONS="-l 0.0.0.0 -I 2m -L"

memcached version is 1.4.4

-L is explained as:
    Try to use large memory pages (if available). Increasing the memory page size could reduce the number of TLB misses and improve the performance. In order to get large pages from the OS, memcached will allocate the total item-cache in one large chunk. Only available if supported on your OS. 

I used "-L" alone with "-I 2m" to use 2MB page size.

My question is that: what does "-L" option do? If I can specify large page size with "-I 2m".

**Comment by dormando** [comment]
-L is referring to memory pages, ie: https://wiki.debian.org/Hugepages - doesn't have anything to do with -I. -I just changes the maximum item size, and it works very poorly in versions prior to 1.5.0. it makes the memory subsystem much less efficient.

You should avoid using -L unless you are hyper optimizing a very highly loaded instance (millions of requests per second). Also avoid -I unless you upgrade

**Comment by ndvbd** [comment]
@ethanhere What is the link to the memcached documentation showing the -L text that you quoted? I tried to google the sentence you quoted, but coulnd't find any info.
