### ISSUE TITLE
memcached 1.5.12 + extstore

### ISSUE THREAD

**Issue by shahar-fleischman** [memcached/memcached#462]
Hi,

I'm doing a test of memc+extstore, and have encountered a few problems, I also have a few questions about metrics/defaults.

1. I'm having many evictions, even when lowering the ext_item_size beneath the smallest class(in my cases it was 110 bytes), and using ext_item_age=1.
2. SSD util is around 68%(based on 1 min polling graph), it might have higher peaks, and with 8.5k reads/sec + 40 writes/sec.
3. I'm using ext_threads=4.
4. The client is doing read, then add values if needed and writes them, there is no other client that reads, so in terms of rate # of reads=# of writes.

So there questions are:
1. how do I know why objects evicted?
2. do stats slabs(and other related metrics) give metrics only on what's in memory and not in extstore ?
3. Where can I find the defaults to settings ? I've found some of them, but not all.

thanks.

**Comment by shahar-fleischman** [comment]
Added all stats.
[stats_slabs.txt](https://github.com/memcached/memcached/files/2983475/stats_slabs.txt)
[stats_settings.txt](https://github.com/memcached/memcached/files/2983476/stats_settings.txt)
[stats_items.txt](https://github.com/memcached/memcached/files/2983477/stats_items.txt)
[stats.txt](https://github.com/memcached/memcached/files/2983478/stats.txt)

**Comment by dormando** [comment]
Hey,

https://github.com/memcached/memcached/wiki/Extstore#primary-tradeoffs as noted here, the item metadata + key are kept in RAM when using extstore.

In your slab stats:
STAT 2:total_pages 6900
STAT 3:total_pages 7046
STAT 4:total_pages 3
STAT 5:total_pages 2
STAT 6:total_pages 2
STAT 7:total_pages 3
STAT 8:total_pages 3
STAT 9:total_pages 2
STAT 10:total_pages 2
STAT 11:total_pages 3
STAT 12:total_pages 2
STAT 13:total_pages 3
STAT 14:total_pages 3
STAT 15:total_pages 2
STAT 16:total_pages 2
STAT 17:total_pages 3
STAT 18:total_pages 2
STAT 19:total_pages 3
STAT 20:total_pages 2
STAT 21:total_pages 3
STAT 22:total_pages 3
STAT 23:total_pages 2
STAT 24:total_pages 2
STAT 25:total_pages 2

... all your memory are in classes 2/3, which are where these item headers are likely kept. Extstore will evict old key headers in order to write newer data to disk. So in short you either need to use less disk space or more RAM for your workload (or try shortening the keys, if possible).

stats slabs/items are only about what's in memory, which will be a mix of extstore item headers and real items.

`stats settings` should show the defaults; what're you missing?

**Comment by shahar-fleischman** [comment]
Hi,

so you're saying that all the memory is allocated to keys+metadata ?
I can't save anymore new keys, because it filled all the RAM space allocated ?
About settings, I thought something was missing, I can't remember what it was.
Is there a metric thats can tell how much RAM space is used for key+metadata, and how much is used for values ?

Thank you for the fast reply !

**Comment by dormando** [comment]
Yes, either all your values are small already or all your memory is keys+metadata. all your RAM is used.

There's no metric that shows extstore item headers vs items, unfortunately. You can figure it out via "lru_crawler metadump" but it's not going to be straightforward.

**Comment by shahar-fleischman** [comment]
Got it, I will make the adjustments to RAM until evictions will stop.
One question about the lru_crawler metadump, If my slab 2 class size is 120, how can I see this in the dump? 
exp=-1 la=1553020851 cas=3515199448 fetch=yes cls=2 size=1616
Am I missing something or the slab class should not be above 120 ?

**Comment by dormando** [comment]
Looks like you figured it out :) That's how you spot an item header in the logger presently. If you see a size that doesn't fit in the slab class, that's an extstore item header.

**Comment by shahar-fleischman** [comment]
Oh, 
I see, still a bit confused why it will be 1616 bytes, what's in there that is so big ?

**Comment by dormando** [comment]
Fetch it and take a look? You have the key from metadump. I'm not sure what's confusing; that's how large the original item you stored is.

**Comment by shahar-fleischman** [comment]
If the item was 1616 bytes it shouldn't be in class 2 which is between 120-152 bytes in my case.
Or I don't understand stats slabs :(

**Comment by dormando** [comment]
Ah I wasn't clear enough:

You're looking at an item header. The item header fits in class 2, which is item metadata + the key. The rest is in extstore. The original item size is 1616 bytes, but the header that remains in RAM fits in class 2.

So if size > class_size, that item value is stored in extstore. if size <= class_size, it's a normal item that just fits in RAM.

**Comment by shahar-fleischman** [comment]
Ok, now I get it.
Thanks for the patience in explaining to me the whole thing.

**Comment by dormando** [comment]
is there anything you need here or can I close this out? seems like there's no fault in the software

**Comment by shahar-fleischman** [comment]
If I can ask just one last question,
How many bytes does the metadata take for each key(in case where object value is in RAM, and in case object value is in  extstore)?

**Comment by shahar-fleischman** [comment]
Great, I will add it to my calculations.
Thanks again for all the help.
BTW the performance is very good even though the objects are small, and the pattern of the test is not optimal(and mixing the test with mcrouter).
You can close it :)

**Comment by dormando** [comment]
Thanks! What kind of machine/vm/etc are you running this on?

**Comment by shahar-fleischman** [comment]
Using 4 physical hosts with 24 vcores/64G RAM/1 960G SSD.
The hosts are not new, from around 2015(cpu E5-2630).
mcrouter/memc procs are on the same hosts(1 mcrouter proc/1 memc proc per host) 

I just thought of another thing after you've explained me how the slab allocation is working with extstore, that the item/slab metrics can confuse, since I can't rely anymore on the numbers of objects in a slab class, item can can be larger because they are pushed to the slab class that fits key+meta.

**Comment by dormando** [comment]
that's correct. there's no easy way to see how large your actual values are via stats items/slabs with this. That's just how it is though. It still gives an accurate count on the number of objects stored and how much RAM they take up. The rest you can infer from the extstore disk usage counters.

**Comment by shahar-fleischman** [comment]
Got it.
Will it affect performance to open a second stats metric, like stats slabs but for key+meta+value ?

**Comment by dormando** [comment]
It would be pretty tough to do, yes. It's not terribly useful information either. All memcached's internals care about are the RAM values, and the RAM values are what limits extstore anyway.

**Comment by shahar-fleischman** [comment]
Thanks :)
