### ISSUE TITLE
Install memcached in XAMPP

### ISSUE THREAD

**Issue by giramos** [memcached/memcached#465]
Hello, I'm doing a job-summary about the Memcached tool. I have tested it on an Ubuntu system but when testing it on a Windows system I am not able to complete the installation using Xampp as the links are broken or broken. I have followed some of the tutorials available on the web, but without any success, such as for example https://www.miguelg.com/2013/04/instalar-memcache-en-xampp-windows-7.html
You could guide me or tell me some basic installation guide on windows computers,
Greetings and thanks in advance

**Comment by dormando** [comment]
Unfortunately there's no official windows support. The only windows builds are from really old versions that people had manually converted but never contributed upstream.

sorry :(
