### ISSUE TITLE
Incorrect info or inc/decr command in wiki

### ISSUE THREAD

**Issue by kevinglover** [memcached/memcached#475]
The wiki states:
> If an item stored is the string representation of a 64bit integer, you may run incr or decr commands to modify that number.
See: https://github.com/memcached/memcached/wiki/Commands#incrdecr

However, that's not entirely the case as seen in [documentation for increment-decrement on BinaryProtocolRevamped](https://github.com/memcached/memcached/wiki/BinaryProtocolRevamped#increment-decrement) where it's stated it returns a 64-bit **unsigned** response. 

Therefore incr/decr does not work for signed integers, which you wouldn't know from the commands page. 

All we need to do is amend the quoted sentence to:
> If an item stored is the string representation of an unsigned 64bit integer, you may run incr or decr commands to modify that number.

**Comment by dormando** [comment]
thanks!
