### ISSUE TITLE
Add sync or set time for internal clock mechanism

### ISSUE THREAD

**Issue by stupidkitty** [memcached/memcached#486]
Hi.
When working with a memcached, I ran into a problem of drifting internal clocks. Because of what the cache is invalid. Addititional info: https://github.com/anandlukade/memcached/issues/389
However, I did not find a way to synchronize the internal clock with the system clock. Maybe add a mechanism? This can be a time setting command or a synchronize with system clock option.

**Comment by dormando** [comment]
Are you using date-based time expiration? Usually with the monotonic clock any relative expiration will still work as advertised since the drift is slow.

**Comment by dormando** [comment]
poke. going to close if I don't hear back soon.
