### ISSUE TITLE
idle_timeout not working for binprot

### ISSUE THREAD

**Issue by smadappa** [memcached/memcached#491]
Active connections are getting closed when we set idle_timeout > 0 for binary protocol.

**Comment by dormando** [comment]
yup, looks like that never worked. There's nothing updating the last_cmd_time for binprot.

**Comment by dormando** [comment]
fix pushed for 'next' branch. testing is annoying since we never added binary protocol handling into the main test library :/ this is good enough for now, the fix was obvious.

**Comment by dormando** [comment]
fixed in 1.5.15
