### ISSUE TITLE
Missing docs for stats detail dump

### ISSUE THREAD

**Issue by mottosso** [memcached/memcached#503]
Hi memcached community!

I've been searching high and low for how to use this command, but come up blank except for one page in the [MySQL docs](https://dev.mysql.com/doc/refman/5.6/en/ha-memcached-stats-detail.html).

In there it states:

```bash
stats detail dump
PREFIX hykkey get 0 hit 0 set 1 del 0
PREFIX xyzkey get 0 hit 0 set 1 del 0
PREFIX yukkey get 1 hit 0 set 0 del 0
PREFIX abckey get 3 hit 3 set 1 del 0
END
```

However I can't actually get this to work. :(

```bash
$ telnet localhost 11211
> version
VERSION 1.4.33
> stats detail on
OK
> set MyKey 0 100 7
> MyValue
STORED
> stats detail off
OK
> stats detail dump
END
```

Here I was expecting..

```bash
> stats detail dump
PREFIX MyKey get 0 hit 0 set 1 del 0
END
```

Any ideas?

**Comment by dormando** [comment]
That feature actually bitrotted ages ago... I haven't been able to prioritize digging through it to see if it's worth saving or simple cut the code out at this point. Sorry for the confusion. Nobody seemed to actually use it and it slows things down a fair amount.

**Comment by dormando** [comment]
I skimmed the issue you linked to this from; I'm not quite sure what you're going after there, but it seems like an odd use of a key/value cache? The "stats cachedump" debug command doesn't do what you want either. It's limited to a megabyte worth of text results per slab class.

Are you trying to monitor/inspect something or shoehorn an old system into something else? I didn't read that closely, sorry.

**Comment by mottosso** [comment]
Thanks for getting back @dormando, that's a bummer but makes sense.

Re: "package localisation": yes you are right, it's as you suspect, shoehorning an old system into something else. The feature is unrelated to memcached, but as users of this software already have it setup it I'm exploring the option of avoiding another server-side application, but this looks to be the end of that road. Thanks anyway!

**Comment by dormando** [comment]
Ahh got it. Well, good luck.

If you have a minute and don't mind, I'd like to hear about what usage pattern you had which wasn't working out for you. There're some newer features that aren't as well known either. Else, no worries.

**Comment by mottosso** [comment]
> If you have a minute and don't mind, I'd like to hear about what usage pattern you had which wasn't working out for you.

I'm not the original author of this project, so I can't really help you there. However memcached has been used for nearly a decade by users of this project (many of which are 1000+ VFX organisations like MPC and Method), so there are likely some opinions and experience to draw from.

I would invite you to pose this question here: https://github.com/nerdvegas/rez

My guess is it hasn't crossed their mind to get involved with your project to try and resolve whatever issues they've been having, but it's possible they would if they knew that they could; they're all software engineers.
