### ISSUE TITLE
how to compress on the server side?

### ISSUE THREAD

**Issue by abalib** [memcached/memcached#506]
My processor has a zlib hardware. I can deflate/inflate largish blocks say 1KB or larger, almost for free and at high speed.  Goal is to have a larger effective memcached cache size.   Where would I insert the deflate/inflate calls in memcached.c?  (Not interested in client side compression; yes that will reduce network util but will also increase client's cpu util which I don't want)
  I am looking for some advice and pointers please.

**Comment by dormando** [comment]
That sounds like a neat processor! It's not as easy as a hook unfortunately. Item data is usually read directly into an allocated item for larger items. There's no standard "staging space" that it could be compressed out of. Further, you need the compressed length before allocating an item from the slabber... so you'd have to copy several times for sets, then completely rewrite the return logic for inflate. You end up losing a lot of the benefit from your CPU instructions.

Folks usually over estimate the impact to clients; it's not as bad as you'd think. it's almost always faster than not compressing at all, in fact.

1. inflate is many times faster than deflate, which is what clients spend most of their time doing. Gets should be more common than sets for a cache :)
2. the CPU usage is distributed, there're usually a lot more clients than memcached servers. In your case the compression might be "free" or close to free, but with required server changes it's still not free.
3. compressing/decompressing in the clients means the bytes on the wire are (often greatly) reduced. this can cut overall latency down even with the inflate stage for clients, improve capacity, reduce CPU overhead for irq's, etc.

Are you running the latest version of memcached already? Taken a look at extstore? Just running the latest software can improve storage space by 2-4x depending on the workload.

**Comment by abalib** [comment]
@dormando Thank you for the advice.  I did look at extstore and I thought about allocating extstore from memory (e.g. ramdisk instead of nvme) and compressing that. For example, suppose 1/4 ram is memcached and 3/4 ram as ramdisk is compressed extstore.  Not clear how much is the overhead of going to extstore and if there will be any benefit with my proposed approach.

**Comment by dormando** [comment]
it would certainly be easier to compress/decompress via the extstore interface, but that's got a ton of overhead to it. it's not exactly designed to run in a ramdisk, so there's tons of stuff it'll do thinking it's optimizing for a flash drive.

Without knowing a lot of detail about your use case it's hard to recommend anything else. I'd still push for giving more serious thought to client side compression; I've seen lots of even huge deployments of memcached toy with server side vs client side and it's never been worth it.

**Comment by abalib** [comment]
Thank you for the discussion.  Closing the issue now.
