### ISSUE TITLE
Source to cat-demon and logo?

### ISSUE THREAD

**Issue by muuvmuuv** [memcached/memcached#508]
Are the cat-demons from the header image or the logo somewhere accessible to download? 

I would need one cat-demon for a folder icon for the VS Code [vscode-icons](https://github.com/vscode-icons/vscode-icons/issues/650) extension.

**Comment by dormando** [comment]
I don't have an SVG source, sorry :(

**Comment by muuvmuuv** [comment]
Ahh, what a shame... They are really cute. I would have made a wallpaper for myself 😄 maybe someday some experienced Illustrator want to redraw them in Illustrator.

**Comment by dormando** [comment]
Best I have are these:
https://memcached.org/images/memcached_link_125.png
https://memcached.org/images/memcached_banner100.jpg

they're rabbits, btw. "fast, scalable, stupid"

**Comment by muuvmuuv** [comment]
Did u made those by yourself? I really like those demons/rabbits 😄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dormando** [comment]
Friend of mine did the illustrations a long time ago (along with the site color scheme, logo, etc). going to close this out
