### ISSUE TITLE
Memcache Client returns null even when cache is hit.

### ISSUE THREAD

**Issue by vbhosle** [memcached/memcached#511]
Hi,
   We are using following Memcached whalin client library. It returns null even though cache was hit ( found it through -v flag). It works fine when we use deprecated constructor that takes classloader argument or when we move Memcache jar in WEB-INF/lib from tomcat/lib
Could you please help us pinpoint the issue. 

<dependency>
	<groupId>com.whalin</groupId>
	<artifactId>Memcached-Java-Client</artifactId>
	<version>3.0.2</version>
</dependency>

Thanks,
Viraj

**Comment by dormando** [comment]
This repository is for issues with the server, I'm not familiar with the java clients. I don't think the whalin client has been maintained in a very long time. xmemcached and spymemcached are more likely to get support.

**Comment by vbhosle** [comment]
Thanks @dormando . We switched to spymemcached.
