### ISSUE TITLE
lru_bump_buf

### ISSUE THREAD

**Issue by Mistress-of-the-Blade** [memcached/memcached#513]
The code will go lru_bump_aync when we call do_item_get(). I wan't do know what is lru_bump_buf for . thank you.

**Comment by dormando** [comment]
The lru_bump_async stuff is part of the segmented LRU algorithm, which is explained in a blog post here: https://memcached.org/blog/modern-lru/

When items in the COLD LRU are accessed, they are asynchronously moved to the WARM LRU. bump_buf is used to queue items for this asynchronous move.

If bump_buf is full, the access bump is dropped. So when the server is overloaded with traffic it will not hang or pause while waiting for COLD items to be moved.

**Comment by dormando** [comment]
assuming I've answered your question. good luck
