### ISSUE TITLE
init script does not source /etc/default/memcached

### ISSUE THREAD

**Issue by phaoost** [memcached/memcached#515]
Hello,

memcached-init does not source /etc/default/memcached, as a result, directory for memcached socket cannot be created

**Comment by dormando** [comment]
how did you install memcached? what os/distro/package/version? from source?

**Comment by phaoost** [comment]
it's from debian buster, 1.5.6-1.1, running on devuan beovulf 3.0
/etc/init.d/memcached matches https://github.com/memcached/memcached/blob/master/scripts/memcached-init

**Comment by dormando** [comment]
You might want to file a bug with debian? I don't really control what they use for init scripts. /etc/default/* is generally a debian convention, but we could add it to the default script, maybe.

**Comment by RyanGrange** [comment]
If you installed the package from a Devuan repo (Beowulf), you should file a bug with Devuan.
If you installed the package from a Debian repo (Buster), you should uninstall it and use the Devuan repo (per https://devuan.org/os/).
If I'm stepping on any toes with this reply, my apologies.

**Comment by phaoost** [comment]
Ok, I filed bug report to debian, but https://github.com/memcached/memcached/blob/master/scripts/memcached-init does not create directory for socket. Should I submit another bug report here about this?

**Comment by dormando** [comment]
I'm not sure it should... it'd have to parse out the directory for the unix socket use case. I'm unaware of that being normal. usually the distro will give you a /var/run/packagename to use or something.
