### ISSUE TITLE
Can I use Extstore on HDD instead of SSD?

### ISSUE THREAD

**Issue by duclahoang** [memcached/memcached#516]
Hello guys, there's a line in a document I've read "Extstore is an extension to memcached which utilizes standard SSD/NVME devices to offload memory." So I wonder to know can I run Extstore feature on my HDD, I really want to test this feature.

I rebuild memcached like this document https://memcached.org/blog/extstore-cloud/ and run 
"memcached -p 11211 -m 2048 -o ext_path=/home/cpu11471/Code/memcached/memcached-1.5.16/log/extstore.txt:1G,ext_item_size=10"

I use libmemcached API(C/C++) to insert data, and data still on RAM. Do I make something wrong?

Thanks for reading my issue!

**Comment by dormando** [comment]
You can test extstore on an HDD, but it will not work with production traffic unless you have an SSD.

How did you validate data is still in RAM? You should write a few megabytes worth of values. There is a small write buffer that fills before extstore flushes to the disk file.

**Comment by duclahoang** [comment]
Thanks for your reply!

I start one instance memcached with extstore option and another without extstore. Insert the same data and they use the same amount of ram, so I know that "value" still on ram. 

You means I will see the extstore file increase when write buffer is full, right ? In my case, I only see the extstore file increase when the ram is full and start to evict item. My record have a key from 8 to 16 byte, a value from 512 to 1024 byte.
