### ISSUE TITLE
About storage of Extstore

### ISSUE THREAD

**Issue by duclahoang** [memcached/memcached#518]
Hello guys, I have some questions about Extstore's storage on disk.
1. Does Extstore have anything like partition? Example that you store 100gb data, it split into 4 files and each of that stores 25gb. I see only one file on disk when I used Extstore, I read document and quickly take a look on memcached's code, but I didn't see anything about partition. If it have anything like partition, please tell me !

2. What is the structure of data in a Extstore's file ? 
This is an example about structure of file in Kyoto Cabinet
![image](https://user-images.githubusercontent.com/43582276/62925103-ca3d1900-bddb-11e9-851d-fa244377dee0.png)
I really want to know memcached Extstore's structure.

Thanks for reading my issue!

**Comment by dormando** [comment]
it's just one file. There's a PR in progress for expanding on that: https://github.com/memcached/memcached/pull/432

the storage format is literally the same as in-memory object storage. it just copies the object to disk with some small modifications to the header. When being read back in the object is recombined with what was left in memory (some timestamp values mainly). After being written to disk a pointer remains in memory. The pointer knows the exact position of the original item in extstore, so there's no need for a tree or anything in the file itself.

It does split the file into pages of data (64m each), but within each page it's just items packed together.

There's no specific documentation, sorry.

What are you trying to accomplish?

**Comment by duclahoang** [comment]
Thanks for your reply, Mr.Dormando.
I just want to understand about Extstore, I read documents and some files of source code to understand, but there are many things which I can not understand well or can not make sure that I'm right, so I usually open issue to ask.

**Comment by duclahoang** [comment]
Yeah, I've read that document before, and it really good for tuning/running, it also has some technical things there. It a good one, thanks again, Mr.Dormando.
I will close the issue now!
Hope you have a nice day!
