### ISSUE TITLE
Tracking Memcached Max Item Size limit change

### ISSUE THREAD

**Issue by sumodirjo** [memcached/memcached#535]
HI,
Currently I'm trying to create document about memcached including important changes across versions.

From https://github.com/memcached/memcached/commit/50bdc9f3e134122e280031683f2b502f84e96624 I learned that max item size now is 1G

I tried to track changes related to `item_size_max` but so fare cannot figure out when memcached start supporting 128M max item size and when memcached max item size changed to 1 G. Thank you.

**Comment by dormando** [comment]
Should be here: https://github.com/memcached/memcached/wiki/ReleaseNotes1429

I didn't specifically advertise the new limit, maybe? It does work but limits in the 1-5 meg range still make more sense.

**Comment by dormando** [comment]
worth noting I did quickly change the chunk default from 16k to 512k, and it's been there ever since. that was too aggressive.

**Comment by dormando** [comment]
Going to close this out, since I think I answered the question :)
