### ISSUE TITLE
fail build 1.5.18 restart.c

### ISSUE THREAD

**Issue by micron10** [memcached/memcached#536]
I try to build latest version but get this error:

restart.c: In function 'restart_fixup':
restart.c:354:37: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  354 |                 it->next = (item *)((mc_ptr_t)it->next - (mc_ptr_t)orig_addr);
      |                                     ^
restart.c:354:58: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  354 |                 it->next = (item *)((mc_ptr_t)it->next - (mc_ptr_t)orig_addr);
      |                                                          ^
restart.c:354:28: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  354 |                 it->next = (item *)((mc_ptr_t)it->next - (mc_ptr_t)orig_addr);
      |                            ^
restart.c:355:37: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  355 |                 it->next = (item *)((mc_ptr_t)it->next + (mc_ptr_t)mmap_base);
      |                                     ^
restart.c:355:58: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  355 |                 it->next = (item *)((mc_ptr_t)it->next + (mc_ptr_t)mmap_base);
      |                                                          ^
restart.c:355:28: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  355 |                 it->next = (item *)((mc_ptr_t)it->next + (mc_ptr_t)mmap_base);
      |                            ^
restart.c:358:37: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  358 |                 it->prev = (item *)((mc_ptr_t)it->prev - (mc_ptr_t)orig_addr);
      |                                     ^
restart.c:358:58: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  358 |                 it->prev = (item *)((mc_ptr_t)it->prev - (mc_ptr_t)orig_addr);
      |                                                          ^
restart.c:358:28: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  358 |                 it->prev = (item *)((mc_ptr_t)it->prev - (mc_ptr_t)orig_addr);
      |                            ^
restart.c:359:37: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  359 |                 it->prev = (item *)((mc_ptr_t)it->prev + (mc_ptr_t)mmap_base);
      |                                     ^
restart.c:359:58: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  359 |                 it->prev = (item *)((mc_ptr_t)it->prev + (mc_ptr_t)mmap_base);
      |                                                          ^
restart.c:359:28: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  359 |                 it->prev = (item *)((mc_ptr_t)it->prev + (mc_ptr_t)mmap_base);
      |                            ^
restart.c:381:43: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  381 |                 ch->next = (item_chunk *)((mc_ptr_t)ch->next - (mc_ptr_t)orig_addr);
      |                                           ^
restart.c:381:64: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  381 |                 ch->next = (item_chunk *)((mc_ptr_t)ch->next - (mc_ptr_t)orig_addr);
      |                                                                ^
restart.c:381:28: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  381 |                 ch->next = (item_chunk *)((mc_ptr_t)ch->next - (mc_ptr_t)orig_addr);
      |                            ^
restart.c:382:43: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  382 |                 ch->next = (item_chunk *)((mc_ptr_t)ch->next + (mc_ptr_t)mmap_base);
      |                                           ^
restart.c:382:64: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  382 |                 ch->next = (item_chunk *)((mc_ptr_t)ch->next + (mc_ptr_t)mmap_base);
      |                                                                ^
restart.c:382:28: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  382 |                 ch->next = (item_chunk *)((mc_ptr_t)ch->next + (mc_ptr_t)mmap_base);
      |                            ^
restart.c:385:43: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  385 |                 ch->prev = (item_chunk *)((mc_ptr_t)ch->prev - (mc_ptr_t)orig_addr);
      |                                           ^
restart.c:385:64: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  385 |                 ch->prev = (item_chunk *)((mc_ptr_t)ch->prev - (mc_ptr_t)orig_addr);
      |                                                                ^
restart.c:385:28: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  385 |                 ch->prev = (item_chunk *)((mc_ptr_t)ch->prev - (mc_ptr_t)orig_addr);
      |                            ^
restart.c:386:43: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  386 |                 ch->prev = (item_chunk *)((mc_ptr_t)ch->prev + (mc_ptr_t)mmap_base);
      |                                           ^
restart.c:386:64: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  386 |                 ch->prev = (item_chunk *)((mc_ptr_t)ch->prev + (mc_ptr_t)mmap_base);
      |                                                                ^
restart.c:386:28: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  386 |                 ch->prev = (item_chunk *)((mc_ptr_t)ch->prev + (mc_ptr_t)mmap_base);
      |                            ^
restart.c:389:37: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  389 |                 ch->head = (item *)((mc_ptr_t)ch->head - (mc_ptr_t)orig_addr);
      |                                     ^
restart.c:389:58: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  389 |                 ch->head = (item *)((mc_ptr_t)ch->head - (mc_ptr_t)orig_addr);
      |                                                          ^
restart.c:389:28: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  389 |                 ch->head = (item *)((mc_ptr_t)ch->head - (mc_ptr_t)orig_addr);
      |                            ^
restart.c:390:37: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  390 |                 ch->head = (item *)((mc_ptr_t)ch->head + (mc_ptr_t)mmap_base);
      |                                     ^
mv -f .deps/memcached-itoa_ljust.Tpo .deps/memcached-itoa_ljust.Po
restart.c:390:58: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  390 |                 ch->head = (item *)((mc_ptr_t)ch->head + (mc_ptr_t)mmap_base);
      |                                                          ^
restart.c:390:28: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  390 |                 ch->head = (item *)((mc_ptr_t)ch->head + (mc_ptr_t)mmap_base);
      |                            ^
mv -f .deps/memcached-daemon.Tpo .deps/memcached-daemon.Po
mv -f .deps/memcached-slab_automove.Tpo .deps/memcached-slab_automove.Po
mv -f .deps/memcached-cache.Tpo .deps/memcached-cache.Po

make[5]: *** [Makefile:960: memcached-restart.o] Error 1
make[5]: *** Waiting for unfinished jobs....
mv -f .deps/memcached_debug-hash.Tpo .deps/memcached_debug-hash.Po
memcached.c: In function 'main':
memcached.c:8636:23: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
 8636 |         restart_fixup((void *)old_base);
      |                       ^
mv -f .deps/memcached_debug-murmur3_hash.Tpo .deps/memcached_debug-murmur3_hash.Po
mv -f .deps/memcached-thread.Tpo .deps/memcached-thread.Po
mv -f .deps/memcached-crawler.Tpo .deps/memcached-crawler.Po
memcached.c: In function 'main':
memcached.c:8636:23: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
 8636 |         restart_fixup((void *)old_base);
      |                       ^
mv -f .deps/memcached_debug-jenkins_hash.Tpo .deps/memcached_debug-jenkins_hash.Po
mv -f .deps/memcached-slabs.Tpo .deps/memcached-slabs.Po
mv -f .deps/memcached-logger.Tpo .deps/memcached-logger.Po
mv -f .deps/memcached-items.Tpo .deps/memcached-items.Po

**Comment by dormando** [comment]
Thanks! What platform/OS/distro/etc is that? what is "HAVE_64BIT_PTR" set to in config.h?

**Comment by micron10** [comment]
x86_64 AMD Ubuntu 18.04 i find a problem
Please close ticket

**Comment by dormando** [comment]
I think you're asking me to close the issue? If you're still having problems please let me know.
