### ISSUE TITLE
Memory leak with TLS termination enabled

### ISSUE THREAD

**Issue by LINKIWI** [memcached/memcached#538]
Hi, we have encountered a potential memory leak with TLS-enabled memcached in situations where connections are churned excessively. It might be difficult for me to provide a concrete minimally reproducible environment, as it would be non-trivial to replicate all the complexities of the way we run memcached (throughput, request pattern, proxy layer, etc.).

However, what we've observed is that when we overload memcached with enough throughput such that clients observe a higher rate of connection and request timeouts, we see the following errors populated in logs:

```
accept4(): Resource temporarily unavailable
Failed to write, and not due to blocking: Broken pipe
Failed to write, and not due to blocking: Broken pipe
SSL connection failed with error code : 5 : Success
SSL connection failed with error code : 5 : Broken pipe
SSL connection failed with error code : 5 : Broken pipe
SSL connection failed with error code : 5 : Success
SSL connection failed with error code : 5 : Broken pipe
SSL connection failed with error code : 5 : Success
SSL connection failed with error code : 5 : Broken pipe
SSL connection failed with error code : 5 : Success
Failed to write, and not due to blocking: Broken pipe
...
```

During this time, memcached RSS slowly grows beyond the maximum memory limit specified with -m until it is OOM'd by the kernel. The more memcached is stressed, connection churn happens more frequently, and memory usage grows more quickly.

`stats settings` is as follows:

```
STAT maxbytes 1048576000
STAT maxconns 32768
STAT tcpport 11211
STAT udpport 0
STAT inter 0.0.0.0
STAT verbosity 1
STAT oldest 0
STAT evictions on
STAT domain_socket NULL
STAT umask 700
STAT growth_factor 1.25
STAT chunk_size 48
STAT num_threads 16
STAT num_threads_per_udp 16
STAT stat_key_prefix :
STAT detail_enabled no
STAT reqs_per_event 20
STAT cas_enabled yes
STAT tcp_backlog 1024
STAT binding_protocol auto-negotiate
STAT auth_enabled_sasl no
STAT auth_enabled_ascii no
STAT item_size_max 1048576
STAT maxconns_fast yes
STAT hashpower_init 0
STAT slab_reassign yes
STAT slab_automove 1
STAT slab_automove_ratio 0.80
STAT slab_automove_window 30
STAT slab_chunk_max 524288
STAT lru_crawler yes
STAT lru_crawler_sleep 100
STAT lru_crawler_tocrawl 0
STAT tail_repair_time 0
STAT flush_enabled yes
STAT dump_enabled yes
STAT hash_algorithm murmur3
STAT lru_maintainer_thread yes
STAT lru_segmented yes
STAT hot_lru_pct 20
STAT warm_lru_pct 40
STAT hot_max_factor 0.20
STAT warm_max_factor 2.00
STAT temp_lru no
STAT temporary_ttl 61
STAT idle_timeout 0
STAT watcher_logbuf_size 262144
STAT worker_logbuf_size 65536
STAT track_sizes no
STAT inline_ascii_response no
STAT ssl_enabled yes
STAT ssl_chain_cert <scrubbed: chain cert path>
STAT ssl_key <scrubbed: private key path>
STAT ssl_verify_mode 3
STAT ssl_keyformat 1
STAT ssl_ciphers NULL
STAT ssl_ca_cert <scrubbed: ca cert path>
STAT ssl_wbuf_size 16384
END
```

I've spent a week digging through the TLS implementation and have tried various patches but haven't been able to trace down the root of the issue. Hoping to solicit some help here in the investigation.

cc @tharanga

**Comment by tharanga** [comment]
I suspect `conn_free`. It seems to be leaking the `ssl_wbuf`. Let me get a patch out.

**Comment by LINKIWI** [comment]
That was my suspicion as well, I tried a patch that `free`s `ssl_wbuf` during teardown, but I don't think it actually matters in this case. `conn_free` is only called during malloc allocation failure in `conn_new`, and at that time `ssl_wbuf` hasn't been `malloc`'d yet.

**Comment by tharanga** [comment]
Right, it's just a pointer, the actual buffer is allocated in worker threads, that's why it's not free'd.
You can get a detail report if you can run with `valgrind --leak-check=full ...`, probably with a graceful shutdown after running the load for a while.

**Comment by tharanga** [comment]
`c->rbuf` has to be at the connection level, not at worker threads. I assume you don't see the problem without TLS, is that correct?

**Comment by LINKIWI** [comment]
Right, the problem only occurs with TLS.

**Comment by dormando** [comment]
Thanks! Any chance you could include OS/distro/openssl versions? Also normal stats output is helpful since that gives a hint as to which features are being exercised. You can send that privately or partially scrubbed if that makes it easier.

**Comment by LINKIWI** [comment]
Sure:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
$ uname -a
Linux <scrubbed: hostname> 4.15.0-1041-aws #43-Ubuntu SMP Thu Jun 6 13:39:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ openssl version
OpenSSL 1.1.1  11 Sep 2018
```

Stats output, though this was from a different host than in the first post with a higher `-m`:

```
$ echo stats | nc localhost 11211
STAT pid 28887
STAT uptime 67183
STAT time 1569000870
STAT version 1.5.17_15_gff7b53f
STAT libevent 2.1.8-stable
STAT pointer_size 64
STAT rusage_user 62749.332640
STAT rusage_system 53487.173569
STAT max_connections 32768
STAT curr_connections 1313
STAT total_connections 17426
STAT rejected_connections 0
STAT connection_structures 1341
STAT reserved_fds 80
STAT cmd_get 3111041668
STAT cmd_set 426304916
STAT cmd_flush 0
STAT cmd_touch 0
STAT get_hits 2597352743
STAT get_misses 513688925
STAT get_expired 1526412
STAT get_flushed 0
STAT delete_misses 0
STAT delete_hits 0
STAT incr_misses 0
STAT incr_hits 0
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT touch_hits 0
STAT touch_misses 0
STAT auth_cmds 0
STAT auth_errors 0
STAT bytes_read 229133566155
STAT bytes_written 207520022936
STAT limit_maxbytes 5242880000
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT time_in_listen_disabled_us 0
STAT threads 16
STAT conn_yields 0
STAT hash_power_level 25
STAT hash_bytes 268435456
STAT hash_is_expanding 0
STAT slab_reassign_rescues 13767718
STAT slab_reassign_chunk_rescues 0
STAT slab_reassign_evictions_nomem 0
STAT slab_reassign_inline_reclaim 6468
STAT slab_reassign_busy_items 8220
STAT slab_reassign_busy_deletes 0
STAT slab_reassign_running 0
STAT slabs_moved 1671
STAT lru_crawler_running 1
STAT lru_crawler_starts 32350
STAT lru_maintainer_juggles 109970565
STAT malloc_fails 0
STAT log_worker_dropped 0
STAT log_worker_written 0
STAT log_watcher_skipped 0
STAT log_watcher_sent 0
STAT time_since_server_cert_refresh 581
STAT bytes 2769583990
STAT curr_items 24503451
STAT total_items 440072634
STAT slab_global_page_pool 112
STAT expired_unfetched 182038096
STAT evicted_unfetched 0
STAT evicted_active 0
STAT evictions 0
STAT reclaimed 292411563
STAT crawler_reclaimed 95482900
STAT crawler_items_checked 74995899909
STAT lrutail_reflocked 14
STAT moves_to_cold 346461555
STAT moves_to_warm 140615715
STAT moves_within_lru 772095
STAT direct_reclaims 0
STAT lru_bumps_dropped 0
END
```

**Comment by dormando** [comment]
Has the server you pulled stats from experienced a leak at all?

**Comment by LINKIWI** [comment]
Yeah, this one had been OOM'd by the kernel. Based on memory usage trends, it will probably be OOM'd again (alongside all other hosts in the cluster) within a few hours.

**Comment by dormando** [comment]
Apologies for the quick-fire questions; it's not clear what you've tried so far.

Do you know what your peak/antipeak curr_connections is? You've tried lowering the connection limit already? Connection structures are allocated the first time you use them. I notice two things:

1) max conns is 32k while curr_conns is 1.3k
2) you say this server is currently trending toward OOM, but total_connections is only 17k (and conn structures is 1341).

Does connection_structures trend upward with the memory bloat or just total_connections?

**Comment by LINKIWI** [comment]
Oh to clarify, the number of open connections tends to stay relatively constant while memory usage increases. The total number of open sockets reported by the kernel does not trend upwards either. I haven't tried lowering the connection limit; 32k max is a setting shared across several clusters, some of which serve much higher throughput that it is necessary.

> Does connection_structures trend upward with the memory bloat or just total_connections?

I just checked against our metrics, `connection_structures` stays constant while `total_connections` trends upwards.

**Comment by dormando** [comment]
Excellent, thanks! That's good to know. I may not get back to this for a while but that should help narrow down where to look (hopefully Tharanga has an idea). OpenSSL has a lot of its own buffers so it can be hard to tell where the memory's off to.

Also, what is the delta between your memory limit setting and available system memory? OpenSSL's buffers can be quite big

**Comment by LINKIWI** [comment]
For this specific cluster, `-m` is set to 5G while each host has 8G total memory. The memory usage trend I've noticed is that total host memory usage increases up to ~5G as memcached caches more objects in memory, and then continues to trend upwards but more slowly, until it is OOM'd by the kernel at just shy of 8G.

Thanks everyone for hopping on this issue; I appreciate it!

**Comment by LINKIWI** [comment]
@tharanga I ran Valgrind as suggested but the final output after SIGINTing the process was that all heap-allocated structured were freed. I'm not very familiar with Valgrind; are there any other runtime flags to try?

Anything else I can do to aid with investigation?

**Comment by dormando** [comment]
What've you tried to do to reproduce so far?

**Comment by dormando** [comment]
https://github.com/memcached/memcached/pull/539

@LINKIWI try this? This is definitely one leak; was able to grow a binary before but not after (though had to comment out some random lines to test it)

**Comment by tharanga** [comment]
+1 @dormando. I verified this with valgrind.

**Comment by dormando** [comment]
fix going out, thanks again!
