### ISSUE TITLE
Provide a config option to disable "watch" commands

### ISSUE THREAD

**Issue by robertmathews** [memcached/memcached#544]
As a feature enhancement, I'd like to suggest a configuration option to disable the "watch" commands.

In some cases, the "watch" commands can be a privacy/security issue, particularly on shared hosting. It's common for shared hosting companies to offer a single server-wide memcached instance on localhost as a convenience to sites on that server. Some software that stores data in memcache therefore uses private hashed/random keys to attempt to provide privacy-through-obscurity. However, the "watch" command reveals the keys to anyone who can connect, allowing one user on the server to bypass the "privacy" and view and alter another's data.

(A more general problem would be memcached instances unwisely exposed to the Internet, where anyone -- not just localhost users -- can connect and view keys.)

Two examples of software that uses memcache in a way that can be compromised if someone else views the key are the PHP/PECL memcached module that stores PHP sessions using unique random keys, and the "W3 Total Cache" WordPress plugin that stores cached pages using a randomly generated key based off a secret number. In the first case, the ability to view the keys allows PHP session hijacking; in the second case, it allows modification of pages displayed by other websites on the same server.

Yes, I know and agree that people shouldn't do this kind of thing on shared servers. But they do. Given that, an option to disable it seems useful. If a patch would be accepted for this, let me know.

**Comment by dormando** [comment]
This is an excellent suggestion, and a feature we already have for other ... features... there's a "don't allow dumping" and "don't allow flush_all" flag. While I hope some day we can multi-tenant more properly, for now I understand that people do this and that's alright.

I'll leave this open until I take care of it. Also note that now there's an ASCII based authentication mechanism, which would make it easier for shared hosts to at least run individual memcached's for users without anyone just being able to connect to them.

**Comment by dormando** [comment]
Fixed in 1.5.21
