### ISSUE TITLE
Connection refused on local environment.

### ISSUE THREAD

**Issue by Treslina** [memcached/memcached#548]
My company is using memcached on our backend.  I installed memcached to my local environment using Homebrew on macOS and memcached service has been running for like 7-8 months. However, since yesterday I can't connect to my local memcached service. When I try to connect using telnet it gives the following error:

```
>> telnet localhost 11211
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host
```

I restarted the service check the conf file but everything seems right, even restarting the computer didn't work 😊 I'm sure I didn't change anything about it. Also, I'm sure homebrew didn't update memcached. 

Have you encounter such problem or do you have any recommendations about that?

**Comment by dormando** [comment]
Hey sorry. That's probably outside the scope of this project; some forums on OS X or homebrew might be better. Do you have any coworkers who're running it as well?

All I'd ask here "is the daemon running?" and then poke around for whatever was supposed to start it. All the telnet tells me is nothing's listening on that port.

**Comment by Treslina** [comment]
Oh, I'm sorry you are right. I'll try other forums then 😊 And closing the issue 😊
