### ISSUE TITLE
Cross-compilation is broken

### ISSUE THREAD

**Issue by bkuhls** [memcached/memcached#550]
Hi,

this commit https://github.com/memcached/memcached/commit/9485db55edf2dc6b75b2024770ae41ad6b68de18 leads to an error during configure:

checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-buildroot-linux-musl
...
checking for sasl/sasl.h... no
configure: error: in /home/buildroot/buildroot/output/build/memcached-1.5.19:
configure: error: cannot run test program while cross compiling
See config.log for more details

**Comment by dormando** [comment]
Thanks! What was in config.log? Any more details about your setup?

**Comment by bkuhls** [comment]
https://github.com/memcached/memcached/pull/552 fixed the problem, thanks!
