### ISSUE TITLE
FAQ Entry "Can you persist cache between restarts" seems outdated

### ISSUE THREAD

**Issue by ankon** [memcached/memcached#551]
https://github.com/memcached/memcached/wiki/ProgrammingFAQ#can-you-persist-cache-between-restarts

But there's also https://github.com/memcached/memcached/wiki/WarmRestart saying: 
> Memcached 1.5.18 and newer can recover its cache between restarts. It can restart after upgrades of the binary, most changes in settings, and so on. It now also supports using persistent memory via DAX filesystem mounts.

**Comment by dormando** [comment]
Fixed, thanks!

That wiki page looks a bit out of date... should give it a scrub soon.
