### ISSUE TITLE
util.c

### ISSUE THREAD

**Issue by verdy-p** [memcached/memcached#558]
```
static char *uriencode_map[256];
static char uriencode_str[768];

void uriencode_init(void) {
    int x;
    char *str = uriencode_str;
    for (x = 0; x < 256; x++) {
        if (isalnum(x) || x == '-' || x == '.' || x == '_' || x == '~') {
            uriencode_map[x] = NULL;
        } else {
            snprintf(str, 4, "%%%02hhX", (unsigned char)x);
            uriencode_map[x] = str;
            str += 3; /* lobbing off the \0 is fine */
        }
    }
```
Why do you use the format "%%%02hhX" if you just care on keeping only the 3 first characters ("hhX" not needed).

And anyway, the code using NULL tests in uriencode() is not efficient, we should simply have a one-to-one string mapping instead of one-to-zero-or-one

This initialization should not depend at all on the localisation of isalnum(): safe URIs have a static set of safe characters not depending on any locale.

The uriencode_map static table (which should be const) may just be predeclared (and it's easy to autogenerate a static table initializer, with 4 characters always for every one of the 256 byte values, using null-byte padding, and a single static string should be 1024 bytes with null-padding); no need also of an extra level of indirection (256 pointers) when all can fit in a single char[1024] array, referenced by computed offset (byte*4) from a constant static base.

These static variables should also reference const chars, all living in the constant pool and not in the RSS and then protected.

**Comment by dormando** [comment]
patches welcome? :) patches with benchmarks even more welcome.

I don't fully remember why it was written that way anymore. I vaguely recall the reduced sized table did better for L1 cache hit rates. It's also not always four characters in uri encoding? it's usually 1.

**Comment by verdy-p** [comment]
L1 cache hit cannot be valid: an a 32-bit system the indirection table is
already 1024 bytes, it is 2048 bytes on 64-bit (plus the addition 768
bytes).

using a single char array is already smaller and better for L1; you still
need to copy the same amount of bytes when computing the URI, but you can
even test if the second byte is null to see if the character is encoded or
not, and otherwise it always a 3-character substring, so it can be
represented in 768 bytes only, without the additional indirection table,
without any code needed in the initialisation function (no longer needed at
all) for a preinitialized static constant array (for now this
initialization is making unnecessary dummy work).

But the main benefit of the change would be to store a preinitialized
768-char array in a constant pool rather than an unprotected array in RSS,
and also remove the dependency on "isalnum" which does not necessarily
validate the URI encoding in all locales and causes compilation/porting
difficulties: the URI encoding is independent of all locales.

**Comment by dormando** [comment]
Okay. Well, it's only used in the logger and metadump code which isn't a hot path, and it's not exactly slow as is. If you're running into a bug or problem with it please detail what that is. If the code just bothers you, please submit a PR with tests, as my hands are pretty full already.

Thanks.

**Comment by verdy-p** [comment]
The logger is a sensitive piece of code, any bug in it could become an easy
target of attacks. I do think it is "hot" in terms of security, even if in
normal operations (not under attacks) it is not very active. Reencoding
binary data into an URI can create very large objects.
