### ISSUE TITLE
Interest in a couple TLS-related patches: automatic reload and authorization

### ISSUE THREAD

**Issue by LINKIWI** [memcached/memcached#562]
We run a few in-house patches (one of which #540 was upstreamed recently) on our memcached fleet. I'm gauging any interest in potentially bringing the same changes to upstream:

* We launch a dedicated thread that calls the method to refresh all TLS certificates on disk at a regular (configurable) interval. We prefer an in-process reload (as opposed to an out-of-process cron routine that sends a `refresh_certs` command) since it reduces deployment complexity.
* Due to performance concerns, memcached is directly exposed to our internal infrastructure (without, for example, an out-of-process ingress proxy in front of it). We enforce TLS client authorization with [SPIFFE IDs](https://spiffe.io/spiffe/) supplied in the client's X509 certificate at handshake time. The current implementation is coupled a bit tightly to some in-house conventions, and I'm wondering if there is a more general-purpose way to provide TLS authorization support.

**Comment by dormando** [comment]
Thanks for reaching out!

1) Probably not? I try to not include too much which makes assumptions about people's infrastructure. You might want the thing to indirectly reload certs, but others would want to reload them as the result of another process doing something (ie; placing the certs on disk, validating that they changed immediately afterward, etc). We've already collected a good number of side threads too, but maybe I won't stick to this if others speak up about it.

I'd be a little worried about my infra if it's easier to ship a code patch than a local cron or post-update-hook, anyway :)

2) I've not heard of this.. it looks pretty complicated. What you can do is clean it up as much as possible, open a PR, and tharanga/myself can poke at it for ideas. It's hard to judge on "too complex" or "too specific" without seeing it in this case. IE; there might be a decent place to just hook in for a DL plugin. We might end up going in a different direction, but seeing what you've done and why is still very helpful in understanding how to deal with it.

**Comment by LINKIWI** [comment]
Thanks for the feedback.

Our motivation for (1) is to be consistent with our memcached client which uses the same convention of reloading certs in-process at regular intervals: https://github.com/facebook/mcrouter/blob/1f0249a33c5785a223e00e35e61d500274e42a3a/mcrouter/lib/network/ThreadLocalSSLContextProvider.cpp#L69 but I agree that it makes some assumptions around the use case.

Our implementation for (2) is indeed pretty complicated and also tightly coupled to our requirements. If I find the time to clean it up and generalize I'll open an exploratory PR.

**Comment by dormando** [comment]
Sounds good. Don't spend too much time on cleaning it up if we're aiming to have a discussion on it; what we'd end up going with may not look like it anyway.

Are you using mcrouter as an embedded C/C++ client or routing through it?

**Comment by dormando** [comment]
:) ?

**Comment by LINKIWI** [comment]
Sorry, I haven't had time to work on this and probably won't any time soon :/ We are using mcrouter in a standalone process as a sidecar.

**Comment by dormando** [comment]
I'm going to close this out, you can re-open with the code if you ever find the time. :)
