### ISSUE TITLE
Data Races in `assoc_start_expand`

### ISSUE THREAD

**Issue by danielschemmel** [memcached/memcached#567]
The `clock_handler` [calls](https://github.com/memcached/memcached/blob/1939cf9edc0656f7b1cfab6365f313b56b07a333/memcached.c#L7517) [`assoc_start_expand`](https://github.com/memcached/memcached/blob/1939cf9edc0656f7b1cfab6365f313b56b07a333/assoc.c#L143) without acquiring any specific locks. In there, `started_expanding` is both read and potentially written without locks or atomic/synch builtins.

At the same time, [`assoc_maintenance_thread`](https://github.com/memcached/memcached/blob/1939cf9edc0656f7b1cfab6365f313b56b07a333/assoc.c#L199) also [writes `started_expanding`](https://github.com/memcached/memcached/blob/1939cf9edc0656f7b1cfab6365f313b56b07a333/assoc.c#L249). This thread holds the `maintenance_lock`, but that does not help, as the other access ignores it.

Even though, this is "just" a boolean flag, there are still two properties required for it to be useful:
1. It needs to be ensured that the access is actually dispatched to main memory (or, more abstractly speaking, becomes visible to other threads) at all.
2. This memory operation may not be reorder w.r.t. certain other operations, such as those on `hashpower` (which similarly may be written in `assoc_maintenance_thread` and read in `assoc_start_expand`).

Note that the C11 standard (previous standards ignored the existence of multiple threads completely) considers data races to be UB (see e.g., $5.1.2.4/20). Therefore, although current compilers may oblige by performing these operations in a manner that does not conflict with the semantic idea, future compiler versions may cause problems.

A possible solution would be to implement the variables that need to be quickly accessed in the `clock_handler` as C11 atomics, or by way of compiler builtins ([which modern GCC versions also base on these atomics](https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html#g_t_005f_005fatomic-Builtins)).

This behavior was detected using Symbolic Execution techniques developed in collaboration by the SYMBIOSYS research project at COMSYS, RWTH Aachen University and Cesar Rodriguez (Diffblue, Ltd.). This research is supported by the European Research Council (ERC) under the EU's Horizon 2020 Research and Innovation Programme grant agreement n. 647295 (SYMBIOSYS).

**Comment by dormando** [comment]
I don't think we're C11-safe in this code (yet? completely?) but I haven't done an analysis... there're a lot of older systems which run this codebase so we've had to be conservative.

I have seen, exactly once, a suspicious crash in that code. Though that was when every single item insert could trigger assoc_start_expand. It's currently triggered just once per second by the clock so unlikely anyone would hit it.

It might actually be fixable by just having a trylock in assoc_start_expand for the maint_lock. If maint_lock is held it's never okay to start expanding. There's no reason to block on assoc_start_expand if it's already running, and then all the variables would be flipped inside barriers.

That's still another barrier in the clock handler which is unfortunate. I can see that there's a small chance started_expanding could get re-set to true when it should be false, so worth fixing.

**Comment by danielschemmel** [comment]
Your sketched idea about try_lock seems like a very good solution. Do you want me to write it out as a PR?

**Comment by dormando** [comment]
Go for it.

On re-read I can't trace out any actual bug, so maybe the problem I saw was elsewhere... If hashpower is wrong all it does is trigger the condition again. The only possible "real" problem is start_expanding being set to true while the maint thread is asleep, then it blocks expansion forever. That's still worth fixing but I had some hope that it was the crash I saw :(
