### ISSUE TITLE
Make test failed with memcached-1.5.16

### ISSUE THREAD

**Issue by kaitoan2000** [memcached/memcached#580]
Hi,
I face this error when compile memcached-1.5.16 in centos 7.
**Fact:**
cd memcached-1.5.16
 ./configure --prefix=/zserver/memcached-1.5.16
make
make test

> ...
> ok 42 - binary_flush
> ok 43 - binary_flushq
> ok 44 - binary_append
> ok 45 - binary_appendq
> ok 46 - binary_prepend
> ok 47 - binary_prependq
> ok 48 - binary_stat
> ok 49 - binary_illegal
> ok 50 - binary_pipeline_hickup
> Signal handled: Interrupt.
> ok 51 - shutdown
> ok 52 - stop_server
> t/00-startup.t .............. Can't locate Test/More.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at t/00-startup.t line 4.
> BEGIN failed--compilation aborted at t/00-startup.t line 4.
> t/00-startup.t .............. Dubious, test returned 2 (wstat 512, 0x200)
> No subtests run 
> t/64bit.t ................... Can't locate Test/More.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at t/64bit.t line 4.
> BEGIN failed--compilation aborted at t/64bit.t line 4.
> t/64bit.t ................... Dubious, test returned 2 (wstat 512, 0x200)
> ...
> t/watcher.t               (Wstat: 512 Tests: 0 Failed: 0)
>   Non-zero exit status: 2
>   Parse errors: No plan found in TAP output
> t/whitespace.t            (Wstat: 512 Tests: 0 Failed: 0)
>   Non-zero exit status: 2
>   Parse errors: No plan found in TAP output
> Files=73, Tests=0,  0 wallclock secs ( 0.16 usr  0.08 sys +  0.26 cusr  0.19 csys =  0.69 CPU)
> Result: FAIL
> make: *** [test] Error 1

Could you please give me a correct way to compile it?
Thanks,

**Comment by elukey** [comment]
Hi there, I think that you are missing the `Test::More` perl package...

**Comment by kaitoan2000** [comment]
> Hi there, I think that you are missing the `Test::More` perl package...
Try: yum install perl-Test-Simple
Thanks, you save my day!!
