### ISSUE TITLE
caching struct object

### ISSUE THREAD

**Issue by ond1** [memcached/memcached#582]
Hi,
I am new to memcached. I would like to use cache a struct object created in C/C++. Is this possible in memcached?

The project I am working on is to keep alive these objects in different application PHP request in my PHP C++ extension.

In C the struct is:

 */
typedef struct {
		JNIEnv *env;
		HANDLE myDllHandle;
		JavaVM *jvm;
	} sxnc_environment;

The variables creates several threads, which I would like to reuse. I would like to cache the object sxnc_environment.

**Comment by BubbaJoe** [comment]
If it can't be serialized, then it shouldn't be stored in memcache.

**Comment by dormando** [comment]
sorry; memcached only stores flat binary data. your struct there isn't something that can be serialized/deserialized.
