### ISSUE TITLE
While pulling image receiving error

### ISSUE THREAD

**Issue by rmdev1** [memcached/memcached#599]
Digest: sha256:bcc44549389adca171a598ef15917195a1de38093847e8688c101a818655af9b
Status: Downloaded newer image for edxops/devpi:latest
Pulling memcached (memcached:1.4.24)...
ERROR: unexpected EOF

**Comment by martin-g** [comment]
The Docker image is "Supported by the Docker community". See https://hub.docker.com/_/memcached
You should report this issue to https://github.com/docker-library/memcached/issues
