### ISSUE TITLE
RHEL 7 - Available Memcached Version

### ISSUE THREAD

**Issue by jsaccc75** [memcached/memcached#604]
Hello,
When installing Memcached on RHEL 7, the only version we can pull down with yum is 1.4.15. According to our Linux admin, 1.4.15 is the latest version available in RH's repository. Is someone able to confirm if this is true for RHEL 7?

**Comment by dormando** [comment]
RHEL does not update its packages inbetween major releases. They also hardly ever make major releases, so the version included will be very old.

You can use a 3rd party repo (remi, epel, etc) or build your own RPM of the latest version. This is easily done with rpmbuild as a spec file is included with the release tarball of memcached.
