### ISSUE TITLE
Metaget documentation in the wiki.

### ISSUE THREAD

**Issue by shivnagarajan** [memcached/memcached#611]
Reading through the [documentation](https://github.com/memcached/memcached/wiki/MetaCommands) for the meta commands in the wiki, there seems to be some inconsistency when compared to the [protocol](https://github.com/memcached/memcached/blob/master/doc/protocol.txt) specification.

Since I wasn't able to open a Pull Request on the repo for the wiki, I made some of the changes that I believe correspond to the actual behaviour (and protocol specification). 

The primary differences are essentially how the flags and tokens are specified. The protocol expected all the flags to be specified together and tokens to follow flags (separated by spaces, in the order the flags that require the tokens were previously requested).

Also for the `mg` (metaget) commands, the size in the response is provided only if the `s` flag is provided in the request.

I am not sure if the wiki documentation is intentionally meant to be descriptive/explanatory, while the authoritative documentation will always be the protocol specification itself. I thought I would provide an updated collection of the documentation anyway.

Thanks

@dormando

Actual diff

```diff

diff --git a/MetaCommands.md b/MetaCommands.md
index 8779160..5b22435 100644
--- a/MetaCommands.md
+++ b/MetaCommands.md
@@ -38,27 +38,27 @@ the new commands.
 Commands have a basic request/response headers which look like:

 set request:
- ms foo S2 T90 F1\r\n
+ ms foo STF 2 90 1\r\n
  hi\r\n
 response:
- ST\r\n
+ ST STF\r\n

 get request:
- mg foo t f v\r\n
+ mg foo stfv\r\n

 response:
- VA 2 s2 t78 f1\r\n
+ VA stfv 2 78 1\r\n
  hi\r\n

 delete request:
  md foo I\r\n

 response:
- DE\r\n
+ DE I\r\n

 Commands are 2 characters, followed by key, flags, and tokens requested by
-flags.
+flags. Tokens are to be provided in the order set by the flags requiring them.
 Responses are a 2 character code, any
 additional flags added (for mg), and any requested tokens. Flag responses
 are in the order set by the order in the client request.
@@ -71,27 +71,27 @@ documentation.

 Standard GET:

-`mg foo t f v`
+`mg foo tfv`

 GETS (get with CAS):

-`mg foo t f c v`
+`mg foo tfcv`

 TOUCH (just update TTL, no response data):

-`mg foo T30`
+`mg foo T 30`

 ... will update the TTL to be 30 seconds from now.

 GAT (get and touch):

-`mg foo t f v T90`
+`mg foo tfvT 90`

 ... will fetch standard data and update the TTL to be 90 seconds from now.

 GATS (get and touch with CAS):

-`mg foo t f c v T100`
+`mg foo tfcvT 100`

 ... same as above, but also gets the CAS value for later use.

@@ -113,9 +113,9 @@ protection with a minimal number of round trips to the server:


 request:
- mg foo f c v N30\r\n
+ mg foo fcvN 30\r\n
 response:
- VA 0 f0 c2 W\r\n
+ VA WfcvN 0 11\r\n
 \r\n


@@ -132,9 +132,9 @@ different response:


 request:
- mg foo f c v N30\r\n
+ mg foo fcvN 30\r\n
 response:
- VA 0 f0 c2 Z\r\n
+ VA ZfcvN 0 12\r\n
 \r\n


@@ -155,9 +155,9 @@ accessed objects. Infrequently accessed objects can be left to expire.


 request:
- mg foo v t R30\r\n
+ mg foo svtR 30\r\n
 response:
- VA 2 t29 W\r\n
+ VA svtR 2 29\r\n
 hi\r\n


@@ -177,16 +177,16 @@ received.


 get request:
- mg foo v c R30\r\n
+ mg foo vcR 30\r\n
 response:
- VA 0 c999\r\n
+ VA vcR 999\r\n
 \r\n

 set request:
- ms foo S3 C999
+ ms foo SC 3 999\r\n
  new\r\n
 response:
- ST\r\n
+ ST SC\r\n


 ## Serve Stale
@@ -203,9 +203,9 @@ We use the meta delete command to mark an item as stale.


 request:
- md foo I T30\r\n
+ md foo IT 30\r\n
 response:
- DE\r\n
+ DE IT\r\n


 We also optionally change the TTL. In this instance stale data will be served
@@ -214,9 +214,9 @@ number.


 request:
- mg foo t c v
+ mg foo stcv
 response:
- VA 4 t29 c777 W X\r\n
+ VA WXstcv 4 29 777
  data\r\n


@@ -233,10 +233,10 @@ via the 'I' flag with metaset.


 request:
- ms foo S3 T360 C777 I\r\n
+ ms foo STC 3 360 25\r\n
  new\r\n
 response:
- ST\r\n
+ ST STC\r\n


 The next metaget will continue to see the item as stale, with its previous
@@ -244,9 +244,9 @@ TTL and previous CAS:


 request:
- mg foo t c v\r\n
+ mg foo stcv\r\n
 response:
- VA 3 t25 c778 X\r\n
+ VA stcv 3 25 778\r\n
  new\r\n


@@ -301,9 +301,9 @@ There are two options for optimizing pipelined requests:


 request:
- mg foo t c v q k\r\n
+ mg foo stcvqk\r\n
 response:
- VA 2 s2 t-1 c2 kfoo\r\n
+ VA stcvqk 2 -1 26 foo
  hi\r\n


@@ -321,9 +321,9 @@ likely the common use case.


 request:
- mg foo v q Oopaque\r\n
+ mg foo svqO opaque\r\n
 response:
- VA 2 Oopaque\r\n
+ VA svqO 2 opaque\r\n
  hi\r\n


@@ -338,13 +338,13 @@ processed if they were all misses. There are two options:

 1) Send the final mg without the 'q' flag, which will add an EN response code.
 2) Use the `mn` meta no-op command. All this command does is respond with a
-bare MN code.
+bare EN code.


 request:
  mn\r\n
 response:
- MN\r\n
+ EN\r\n


 Stick it at the end of a pipeline:
@@ -375,9 +375,9 @@ and how many seconds it's been since it was last hit. Lets combine these:


 request:
- mg foo v h l\r\n
+ mg foo svhl\r\n
 response:
- VA 4 h1 l5\r\n
+ VA svhl 4 1 5\r\n
  data\r\n


@@ -412,9 +412,9 @@ intensive to deserialize, is to periodically revalidate items.


 request:
- mg foo v h l c\r\n
+ mg foo svhlc\r\n
 response:
- VA 4 h1 l5 c500\r\n
+ VA svhlc 4 1 5 500\r\n
  data\r\n


@@ -426,10 +426,10 @@ items without the value.
 request:
  mg foo c\r\n
 response:
- HD c500
+ VA c 500


-(the `HD` status code indicates no value is being received; only a header)
+(the response indicates no value is being received; only the requested CAS id.)

 In this case, we only care about finding if the CAS value is identical.
```

## Contents

- [Command Basics](#command-basics)
- [Replacing GET/GETS/TOUCH/GAT/GATS](#replacing-getgetstouchgatgats)
- [New MetaData Flags](#new-metadata-flags)
- [Atomic Stampeding Herd Handling](#atomic-stampeding-herd-handling)
- [Early Recache](#early-recache)
- [Serve Stale](#serve-stale)
- [Pipelining Quiet mode with Opaque or Key](#pipelining-quiet-mode-with-opaque-or-key)
- [Quiet mode semantics](#quiet-mode-semantics)
- [Probabilistic Hot Cache](#probabilistic-hot-cache)
    - [Hot Key Cache Invalidation](#hot-key-cache-invalidation)

# Memcached Text Protocol Meta Commands

NOTE: This is presently an _experimental_ feature. Please experiment with the
feature, but keep an eye on the release notes for significant protocol
changes. After a short period we will stop making incompatible changes and
only create additional flags or commands.

Memcached has additional commands which are used to reduce bytes on the wire,
reduce network roundtrips required for complex queries (such as anti-dogpiling
techniques), expose previously hidden item information, and add many new
features. These are in addition to the existing Text Protocol, and can do
everything the Binary Protocol could do before.

The full description of the Meta commands are available in the Text Protocol
documentation:
 * [Text Protocol](http://github.com/memcached/memcached/blob/master/doc/protocol.txt)

This wiki serves as a companion to protocol.txt with use cases and examples of
the new commands.

## Command Basics

Commands have a basic request/response headers which look like:
```
set request:
 ms foo STF 2 90 1\r\n
 hi\r\n
response:
 ST STF\r\n

get request:
 mg foo stfv\r\n

response:
 VA stfv 2 78 1\r\n
 hi\r\n

delete request:
 md foo I\r\n

response:
 DE I\r\n
```

Commands are 2 characters, followed by key, flags, and tokens requested by
flags. Tokens are to be provided in the order set by the flags requiring them.
Responses are a 2 character code, any
additional flags added (for mg), and any requested tokens. Flag responses
are in the order set by the order in the client request.

For full detail please see [Text
Protocol](http://github.com/memcached/memcached/blob/master/doc/protocol.txt)
documentation.

## Replacing GET/GETS/TOUCH/GAT/GATS

Standard GET:

`mg foo tfv`

GETS (get with CAS):

`mg foo tfcv`

TOUCH (just update TTL, no response data):

`mg foo T 30`

... will update the TTL to be 30 seconds from now.

GAT (get and touch):

`mg foo tfvT 90`

... will fetch standard data and update the TTL to be 90 seconds from now.

GATS (get and touch with CAS):

`mg foo tfcvT 100`

... same as above, but also gets the CAS value for later use.

## New MetaData Flags

- `l` flag will show the number of seconds since the item was last
accessed.
- `h` flag will return 0 or 1 based on if the item has ever been fetched since
being stored.
- `t` flag will return the number of seconds remaining until the item expires
(-1 for infinite)

Others will be documented in protocol.txt

## Atomic Stampeding Herd Handling

We can use the CAS value and some new flags to do stampeding herd (dogpiling)
protection with a minimal number of round trips to the server:

```
request:
 mg foo fcvN 30\r\n
response:
 VA WfcvN 0 11\r\n
\r\n
```

The `N` flag instructs memcached to automatically create an item on miss, with
a supplied TTL, which is 30 seconds in this example.

In the flags returned a new flag `W` has been added. This is instructing the
client that it has received a miss and has "Won" the right to recache the
item. The client may then directly update the value once it has been fetched
or calculated, or set back using the CAS value it retrieved.

If a different client requests the same item in this time, it will see a slightly
different response:

```
request:
 mg foo fcvN 30\r\n
response:
 VA ZfcvN 0 12\r\n
\r\n
```

The `Z` flag indicates to the client that a `W` flag has already been sent,
and this is a special non-data item. The client may then retry, wait, or take
a different approach.

This approach was done in the past by having clients race with
an `add` command after a miss, using special response values, or so on. It is
now collapsed into the normal request/response workflow, and has additional
features.

## Early Recache

The 'R' flag can be used to do an anti-herd early recache of objects nearing
their expiration time. This can be used to reduce misses for frequently
accessed objects. Infrequently accessed objects can be left to expire.

```
request:
 mg foo svtR 30\r\n
response:
 VA svtR 2 29\r\n
hi\r\n
```

In this example, the R flag is supplied a token of '30', meaning if the TTL
remaining on an item is less than 30 seconds, attempt to refresh the item.

In the response we see the extra 'W' (win) flag has been returned, indicating
to this client that it should recache the item. Any further clients will
instead see a 'Z' flag, indicating a request has already been sent.

We also see the TTL remaining, via the 't' flag, confirming that the TTL is
below 30 seconds.

The CAS value may also be requested via the 'c' flag, which allows honoring
the recache only if the object hasn't changed since the win token was
received.

```
get request:
 mg foo vcR 30\r\n
response:
 VA vcR 999\r\n
\r\n

set request:
 ms foo SC 3 999\r\n
 new\r\n
response:
 ST SC\r\n
```

## Serve Stale

Intentionally serving stale but usable data is possible with the meta commands, similar to Stale-While-Revalidate
or Stale-While-Error in HTTP.

In some cases you would want to actively mark an
in-memory item as stale. You can then either have the first client fetching
the stale value also handle revalidation, or kick off an asynchronous recache
but still inform clients that the data may not be up to date.

We use the meta delete command to mark an item as stale.

```
request:
 md foo IT 30\r\n
response:
 DE IT\r\n
```

We also optionally change the TTL. In this instance stale data will be served
for a maximum of 30 seconds. Marking an item as stale also changes its CAS ID
number.

```
request:
 mg foo stcv
response:
 VA WXstcv 4 29 777
 data\r\n
```

The next metaget gets the 'W' flag, indicating it has rights to exclusively
recache the item. It also gets the 'X' flag, indicating that the item is
stale. How this is handled is up to the application; it can use the data
as-is, adjust it, warn a user, or quietly re-fetch later.

If another metadelete comes in before the item above is recached, the CAS will
change to 778 (or higher), and the later metaset call will fail.

However, it is possible to still update the item but keep it marked as stale,
via the 'I' flag with metaset.

```
request:
 ms foo STC 3 360 25\r\n
 new\r\n
response:
 ST STC\r\n
```

The next metaget will continue to see the item as stale, with its previous
TTL and previous CAS:

```
request:
 mg foo stcv\r\n
response:
 VA stcv 3 25 778\r\n
 new\r\n
```

The CAS value must be _lower_ than the real CAS value for this to apply. Once
a set matching the CAS value comes in, all data is overwritten and the TTL is
updated properly.

## Pipelining Quiet mode with Opaque or Key

Pipelining with meta commands is done with combinations of the 'q', 'O', and
'k' flags. These flags work for all of the metaget, metaset, and metadelete
commands.

In the normal text protocol, the requested key is reflected back to the
client. This makes it possible to differentiate responses when requesting many
keys.

```
get bar foooooooooooooooooooooooooooooooo baz
VALUE foooooooooooooooooooooooooooooooo 0 2
hi
END
```

In the above, only foo+ exists. The rest of the values don't have lines
indicating a miss, only the END token after all keys are fetched.

This is still true even when fetching a single key:

```
get foooooooooooooooooooooooooooooooo
VALUE foooooooooooooooooooooooooooooooo 0 2
hi
END
```

Metagets do not have a multi-key interface. Requesting many keys at once
requires pipelining the commands:

```
mg foo v\r\nmg bar v\r\nmg baz v\r\n
```

Metaget will also not return the key by default. Clients should look for the
response codes to count responses.

It's possible to optimize fetching many keys by using the 'q' flag, which will
hide the "EN" code on miss. There is a problem with this: you can no longer
differentiate the responses to match item data to requested keys.

There are two options for optimizing pipelined requests:

```
request:
 mg foo stcvqk\r\n
response:
 VA stcvqk 2 -1 26 foo
 hi\r\n
```

The 'k' flag will add the key as a token in the response. This works for `mg`,
as well as `ms` and `md`.

This is still not ideal if your keys are very long, especially if the data
stored is very small (perhaps even 0 bytes!). Returning 200 byte keys with 8
bytes of data is a lot of extra bytes on the wire.

There is one more option, the 'O' (opaque) flag. Tokens supplied with this
flag are reflected back in the response as-is. Opaque tokens can be up to 32
bytes in length as of this writing. They can be alphanumeric but numbers are
likely the common use case.

```
request:
 mg foo svqO opaque\r\n
response:
 VA svqO 2 opaque\r\n
 hi\r\n
```

In this example the string "opaque" is used as a token to make it stand out
more in the response. This can be any (short) ascii string. A simple approach
would be to simply count the number of outstanding requests, using numerics
and resetting after receiving the responses. This keeps the numbers short,
with some benefit from hex encoding if desired.

Finally, it's still impossible to tell when all of the keys have been
processed if they were all misses. There are two options:

1) Send the final mg without the 'q' flag, which will add an EN response code.
2) Use the `mn` meta no-op command. All this command does is respond with a
bare EN code.

```
request:
 mn\r\n
response:
 EN\r\n
```

Stick it at the end of a pipeline:

`mg [etc]\r\nmg [etc]\r\nmg [etc]\r\nmn\r\n`

## Quiet mode semantics

The 'q' flag is described briefly in the section about Pipelining, but what
else does it do?

In general, the 'q' flag will hide "nominal" responses. If you wish to
pipeline a bunch of sets together but don't want all of the "ST" code
responses, pass the 'q' flag with it. If a set results in a code other than
"ST" (ie; "EX" for a failed CAS), the response will still be returned.

Any syntax errors will still result in a response as well (CLIENT_ERROR).

## Probabilistic Hot Cache

A new technique made possible with the meta commands is a probabilistic
client-side hot key cache. This means a coordination-free method of populating
a local cache to avoid making requests to memcached for very frequently
accessed items.

Using the new `h` and `l` flags, we can see if an item has been hit before,
and how many seconds it's been since it was last hit. Lets combine these:

```
request:
 mg foo svhl\r\n
response:
 VA svhl 4 1 5\r\n
 data\r\n
```

Breaking down the flags:
- `s` is data size, getting a 4 in the response.
- `v` means return the value, getting "data\r\n" in the response block.
- `h` means return a 0 or 1 depending on if the item has been requested since
  it was stored.
- `l` means the time in seconds since last access, which here shows 5 seconds.

We can weight these values to create a probabilistic cache:
`if (h == 1 && l < 5 && random(1000) == 0) { add_to_local_cache(it); }`

The random factor here is a weight that could be other factors (database/network/system load/local cache hit rate/etc). Keys which suddenly get a lot of traffic will filter in slowly, with the highest traffic keys being cached very quickly.

This approach requires no live coordination between servers to discover or
communicate "hot keys". Implementations of this method do need to make a
decision on how validation is done.

### Hot Key Cache Invalidation

For truly hot keys, the simplest approach is to only cache them in a client
for a couple seconds. A "shadow key" with a slightly longer expiration time
(30 seconds or so) could be left in its place to signal to a
client to immediately recache a key if seen again, This covers a wide number
of use cases. The total number of requests to memcached will be higher than in
a perfect system, but the zero coordination effort and natural key discovery
without server overhead is a huge bonus.

Another approach, especially useful for items which are large or are CPU
intensive to deserialize, is to periodically revalidate items.

```
request:
 mg foo svhlc\r\n
response:
 VA svhlc 4 1 5 500\r\n
 data\r\n
```

This time we also request the CAS value. A client could schedule asynchronous
periodic revalidations for hot keys in the background. Metaget can fetch
items without the value.

```
request:
 mg foo c\r\n
response:
 VA c 500
```

(the response indicates no value is being received; only the requested CAS id.)

In this case, we only care about finding if the CAS value is identical.

We may add support for conditionally fetching the value if CAS does or does
not match, to further improve this use case. Check doc/protocol.txt with your
tarball for the most up to date information.

**Comment by shivnagarajan** [comment]
@ndurks

**Comment by dormando** [comment]
Ah nuts... I thought I left a note at the top there the last time I edited it.

The MetaCommands wiki page is up to date, as per the `next` branch, from this PR: https://github.com/memcached/memcached/pull/597 - I meant to leave a note at the top to check `next`. The changes have been staged for an unusually long time as I've been in the middle of moving and we had a crash fix bughunt (1.5.22)

**Comment by dormando** [comment]
Also really need to get the wiki off onto hugo in its own repo but that is hard to motivate for. Sad GH never figured out how to do PR's for wikis :( I had to lock down after some vandals.

**Comment by shivnagarajan** [comment]
Cool, I can close this. Do we know when `next` will become a release? We are starting to look at the meta commands, and  would like to use them in production.

**Comment by dormando** [comment]
Soon! Honestly it would help cut the time down if you folks built from next and played around with it. There's a pipelining change queued in next which could use some more validation as well, if you have any CI or development pipelines. I've been waiting for some folks to get back to me on tests with the latest `next` stuff.

As far as meta goes; I like the way it is now, and it shouldn't change much at this point. Unless I missed something big (which your review would be helpful for), the last thing I want to do is comb the response codes again to see if they could be combined or made more generic.

You can see some quick/hacky implementation of the newest meta here as well: https://github.com/memcached/mctester/blob/master/protocol.go - a generic response parser, and for the most part the commands don't actually need to be individually implemented, but they are in that code anyway.

**Comment by shivnagarajan** [comment]
That's perfect. Happy to review, and I can some other folks here to help as well.  We will probably look to adding support for this into `mcrouter`, `libmemcached` (and then into the `memcached-gem`). So happy to help as required.

**Comment by dormando** [comment]
Great! Just let me know somewhere/somehow that you've looked at it, or open any issues to discuss changes. My own follow-up/discussions are here: https://github.com/memcached/memcached/issues/546 - so you can just throw comments in there as necessary.

There's also a discord chat: https://discord.gg/8yVxuJY and #memcached on freenode if you want.

**Comment by shivnagarajan** [comment]
Closing, as `next` branch is up to date with protocol.

**Comment by martin-g** [comment]
> if you have any CI or development pipelines. I've been waiting for some folks to get back to me on tests with the latest `next` stuff

FWIW I use nightly builds of `next` in our smoke tests. Since we are moving to ARM64 based servers we've created an application that runs smoke tests on the some software products, Memcached is one of those. The application is Java based and uses Spymemcached 2.12.3. Although Spymemcached seems to be abandoned (last release is 3 years ago) so far I haven't faced any issues.

**Comment by dormando** [comment]
@martin-g that's good to know, thanks! I hope you run the main test suite too. I only have an rpi3 for my local ARM64 tests.

**Comment by martin-g** [comment]
Sure thing:

```
...
/unixsocket.t .............. ok
t/watcher.t ................. ok
t/watcher_connid.t .......... ok
t/whitespace.t .............. ok
All tests successful.
Files=76, Tests=63872, 275 wallclock secs ( 6.49 usr  0.53 sys + 40.28 cusr  9.14 csys = 56.44 CPU)
Result: PASS
File 'assoc.c' Lines executed:88.89% of 117 Creating 'assoc.c.gcov' File '/usr/include/stdlib.h' Lines executed:0.00% of 1 Creating 'stdlib.h.gcov' File '/usr/include/aarch64-linux-gnu/bits/stdio2.h' Lines executed:0.00% of 1 Creating 'stdio2.h.gcov'
File 'authfile.c' Lines executed:86.36% of 44 Creating 'authfile.c.gcov' File '/usr/include/aarch64-linux-gnu/sys/stat.h' Lines executed:100.00% of 1 Creating 'stat.h.gcov' File '/usr/include/aarch64-linux-gnu/bits/stdio2.h' Lines executed:50.00% of 4 Creating 'stdio2.h.gcov'
...
```

**Comment by martin-g** [comment]
Also there is https://travis-ci.com/memcached/memcached/

But I see that the last 3 builds have failed, e.g. https://travis-ci.com/memcached/memcached/jobs/287545146:

```
#   Failed test 'correctly logged cas command'
#   at t/watcher.t line 122.
#          got: '0'
#     expected: '1'
# Looks like you failed 1 test of 13.
t/watcher.t ................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/13 subtests 
t/watcher_connid.t .......... ok
t/whitespace.t .............. ok
Test Summary Report
-------------------
t/watcher.t               (Wstat: 256 Tests: 13 Failed: 1)
  Failed test:  12
  Non-zero exit status: 1
Files=76, Tests=63842, 316 wallclock secs (26.21 usr  1.88 sys + 48.72 cusr 22.15 csys = 98.96 CPU)
Result: FAIL
make: *** [test] Error 1
Makefile:1963: recipe for target 'test' failed
```

It runs against `master` branch. I will test `master` on my machine now!
@dormando Did you receive any notifications about these failures ? I can add email notifications like at https://github.com/apache/tomcat/blob/900ed3ef96080ec378fea452dcd748bf3bfa0ec0/.travis.yml#L81-L83 and switch to `next` branch

**Comment by martin-g** [comment]
I've ran 4 builds of `master` and there was just one test failure:

```
t/expirations.t ............. 3/15 
#   Failed test 'foo == 'foov+1''
#   at /home/ubuntu/git/memcached/memcached/t/lib/MemcachedTest.pm line 95.
#          got: 'END
# '
#     expected: 'VALUE foo 0 6
# foov+1
# END
# '
t/expirations.t ............. 14/15 # Looks like you failed 1 test of 15.
t/expirations.t ............. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/15 subtests 
```

I was not able to reproduce the problem in watcher.t so there is no need of a new ticket, I think.

**Comment by shivnagarajan** [comment]
We've been running the `memcached` docker image build with a dockerfile where we build memcached from source and run `configure`, `make`, `make test` each time as part of some CI runs. 

Recently we have also started running this on the `memcached-next` branch. One specific test that does seem to fail if we enable the `ext-store` in `configure`

```
	&& gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
	&& enableExtstore="$( \
# https://github.com/docker-library/memcached/pull/38
		case "$gnuArch" in \
# https://github.com/memcached/memcached/issues/381 "--enable-extstore on s390x (IBM System Z mainframe architecture) fails tests"
			s390x-*) ;; \
			*) echo '--enable-extstore' ;; \
		esac \
	)" \
```

Is the `t/restart.t` test.

The failure is typically 

```

[2020-02-18T16:23:56Z] [restart] Failed to read a tag from metadata file
--
  | [2020-02-18T16:23:57Z] [restart] no metadata save file, starting with a clean cache
  | [2020-02-18T16:23:58Z] # Set some values, various sizes.
  | [2020-02-18T16:23:58Z] # load enough items to change hash power level
  | [2020-02-18T16:24:08Z] # Load a couple chunked items
  | [2020-02-18T16:24:08Z] # Data that should expire while stopped.
  | [2020-02-18T16:24:09Z] # killed, waiting
  | [2020-02-18T16:24:09Z] Gracefully stopping
  | [2020-02-18T16:24:20Z] Failed to connect to unix domain socket: No such file or directory '/tmp/memcachetest.3359.2' at t/restart.t line 108.
  | [2020-02-18T16:24:20Z] # Tests were run but no plan was declared and done_testing() was not seen.
  | [2020-02-18T16:24:20Z] # Looks like your test exited with 2 just after 49.
  | [2020-02-18T16:24:20Z] t/restart.t .................

```

I don't know yet if this is something about running things within the container/docker or something else. Seems pretty easy to repro the failure though. This is the [Dockerfile](https://gist.github.com/shivnagarajan/f8303d43bd3377d044229c117c743f84) we use. I don't think this is necessarily a problem only on the `memcached-next` branch though, since we have seen it occasionally on the `released` versions also.
 It could be a timing thing about the restart of the memcached taking longer (/variable amount of time?) in this environment making the test a little more flaky.

I just re-ran this using the above Dockerfile under docker-for-mac.

```
[restart] Failed to read a tag from metadata file
[restart] no metadata save file, starting with a clean cache
# Set some values, various sizes.
# load enough items to change hash power level
# Load a couple chunked items
# Data that should expire while stopped.
# killed, waiting
Gracefully stopping
Failed to connect to unix domain socket: No such file or directory '/tmp/memcachetest.3359.2' at t/restart.t line 108.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 49.
t/restart.t .................
```

```
Test Summary Report
-------------------
t/restart.t               (Wstat: 512 Tests: 49 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=76, Tests=102032, 392 wallclock secs (10.92 usr  0.95 sys + 26.85 cusr 17.17 csys = 55.89 CPU)
Result: FAIL
make: *** [Makefile:2233: test] Error 1
```

I can look into this a little more.

**Comment by dormando** [comment]
watcher, I think restart, and extstore-binary.t (maybe one other) all have a race condition that seems to only occur when being tested on slow/VM machines. Travis seems to fail more often because it takes 20+ minutes to run all the tests. They don't fail for me locally so I haven't been motivated to fix. It's slightly time consuming because to fix properly I might have to add a few more stats counters that the test script can poll for.. or extra debug commands. Or change the test approach :P

If it's getting obnoxious for you folks, please open specific issues for the tests and maybe we can beg for volunteers to help :) I'm also setting up a new VM test machine and (hopefully?) it'll be slow enough to reproduce these more easily.

**Comment by dormando** [comment]
Fwiw it may seem a bit odd but I don't rely on the travis bits for my own development work, which is why I've ignored the failures for a while. I always test locally and have a buildbot farm. Once my new VM system is set up I'm going to try to see if I can integrate it into github a bit...

that all said these flaky tests are flaky and should be fixed :) just want to point out that I'm extremely thorough about testing on a bunch of platforms and the CI failures doesn't mean that I deprioritize the tests at all.
