### ISSUE TITLE
Find/fix flaky tests

### ISSUE THREAD

**Issue by dormando** [memcached/memcached#617]
While I've fixed a lot of them, there are still a number of flaky tests. These seem to flake out more on memory and/or CPU count and/or CPU speed limited systems. I hardly ever see them myself.

@shivnagarajan @martin-g - if you want to start gathering the errors you see into this issue we can track and kick off PR's to repair them. Perhaps some of the newer eager helpers can give a stab at it with some of my optional guidance :)

Another thing we should try to fix with this: a lot of the printouts you get from errors are "res != val" tests. When these values are very large it can cause a huge log spew.  Should add either something specific for large tests to cut that down or see if there's a better Test::More facility for dealing with them.

**Comment by shivnagarajan** [comment]
One of the most common failures I see are with the `restart` test. Primarily when I run the tests within a docker container.

```
[restart] Failed to read a tag from metadata file
[restart] no metadata save file, starting with a clean cache
# Set some values, various sizes.
# load enough items to change hash power level
# Load a couple chunked items
# Data that should expire while stopped.
# killed, waiting
Gracefully stopping
Failed to connect to unix domain socket: No such file or directory '/tmp/memcachetest.3359.2' at t/restart.t line 108.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 49.
t/restart.t .................
```

**Comment by martin-g** [comment]
From https://travis-ci.com/memcached/memcached/jobs/287545146:

```
#   Failed test 'correctly logged cas command'
#   at t/watcher.t line 122.
#          got: '0'
#     expected: '1'
# Looks like you failed 1 test of 13.
t/watcher.t ................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/13 subtests 
t/watcher_connid.t .......... ok
t/whitespace.t .............. ok
Test Summary Report
-------------------
t/watcher.t               (Wstat: 256 Tests: 13 Failed: 1)
  Failed test:  12
  Non-zero exit status: 1
Files=76, Tests=63842, 316 wallclock secs (26.21 usr  1.88 sys + 48.72 cusr 22.15 csys = 98.96 CPU)
Result: FAIL
make: *** [test] Error 1
Makefile:1963: recipe for target 'test' failed
The command "make test" exited with 2.
```

This is failing on ARM64. TravisCI ARM64 VMs have lower [concurrency](https://docs.travis-ci.com/user/multi-cpu-architectures/) than their AMD64 VMs.

**Comment by martin-g** [comment]
From https://travis-ci.com/memcached/memcached/jobs/287651995:

```
#   Failed test 'stored size 941056'
#   at t/getset.t line 95.
#          got: 'SERVER_ERROR Out of memory during read
# '
#     expected: 'STORED
# '
# Looks like you failed 1 test of 37991.
t/getset.t .................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/37991 subtests 
...
Test Summary Report
-------------------
t/getset.t                (Wstat: 256 Tests: 37991 Failed: 1)
  Failed test:  481
  Non-zero exit status: 1
Files=76, Tests=63842, 268 wallclock secs (22.86 usr  1.43 sys + 42.94 cusr 16.90 csys = 84.13 CPU)
Result: FAIL
Makefile:1963: recipe for target 'test' failed
make: *** [test] Error 1
The command "make test" exited with 2.
```

This is failing on ARM64. TravisCI ARM64 VMs have lower [concurrency](https://docs.travis-ci.com/user/multi-cpu-architectures/) than their AMD64 VMs.

**Comment by martin-g** [comment]
From https://travis-ci.com/memcached/memcached/jobs/282510751:

```
t/expirations.t ............. 3/15 
#   Failed test 'foo == 'foov+1''
#   at /home/travis/build/memcached/memcached/t/lib/MemcachedTest.pm line 95.
#          got: 'END
# '
#     expected: 'VALUE foo 0 6
# foov+1
# END
# '
t/expirations.t ............. 14/15 # Looks like you failed 1 test of 15.
t/expirations.t ............. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/15 subtests 
...
Test Summary Report
-------------------
t/expirations.t           (Wstat: 256 Tests: 15 Failed: 1)
  Failed test:  7
  Non-zero exit status: 1
Files=76, Tests=26307, 210 wallclock secs ( 4.90 usr  0.32 sys + 10.43 cusr  6.11 csys = 21.76 CPU)
Result: FAIL
Makefile:1963: recipe for target 'test' failed
make: *** [test] Error 1
The command "make test" exited with 2.
```

This failed on **AMD64**, not ARM64.

**Comment by martin-g** [comment]
From https://travis-ci.com/memcached/memcached/jobs/278120560:

```
#   Failed test 'stored size 1010688'
#   at t/getset.t line 95.
#          got: 'SERVER_ERROR Out of memory during read
# '
#     expected: 'STORED
# '
# Looks like you failed 1 test of 539.
t/getset.t .................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/539 subtests 
...
Test Summary Report
-------------------
t/getset.t                (Wstat: 256 Tests: 539 Failed: 1)
  Failed test:  515
  Non-zero exit status: 1
Files=76, Tests=26306, 262 wallclock secs (13.81 usr  0.99 sys + 31.31 cusr 16.76 csys = 62.87 CPU)
Result: FAIL
make: *** [test] Error 1
Makefile:1963: recipe for target 'test' failed
The command "make test" exited with 2.
```

This is failing on ARM64. TravisCI ARM64 VMs have lower [concurrency](https://docs.travis-ci.com/user/multi-cpu-architectures/) than their AMD64 VMs.

**Comment by shivnagarajan** [comment]
> One of the most common failures I see are with the `restart` test. Primarily when I run the tests within a docker container.
> 
> ```
> [restart] Failed to read a tag from metadata file
> [restart] no metadata save file, starting with a clean cache
> # Set some values, various sizes.
> # load enough items to change hash power level
> # Load a couple chunked items
> # Data that should expire while stopped.
> # killed, waiting
> Gracefully stopping
> Failed to connect to unix domain socket: No such file or directory '/tmp/memcachetest.3359.2' at t/restart.t line 108.
> # Tests were run but no plan was declared and done_testing() was not seen.
> # Looks like your test exited with 2 just after 49.
> t/restart.t .................
> ```
> 
> Also, this tests fails when `ext-store` is enabled.
> 
> ```
> && gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
> 	&& enableExtstore="$( \
> # https://github.com/docker-library/memcached/pull/38
> 		case "$gnuArch" in \
> # https://github.com/memcached/memcached/issues/381 "--enable-extstore on s390x (IBM System Z mainframe architecture) fails tests"
> 			s390x-*) ;; \
> 			*) echo '--enable-extstore' ;; \
> 		esac \
> 	)" \
> ```

This is essentially a result of the double free causing a SIGSEGV of memcached in some cases, with https://github.com/memcached/memcached/commit/0d4901071c74f9c3b63162ef5887a5c5b981f385  having fixed that.

**Comment by dormando** [comment]
@shivnagarajan what is that second "test" coming from?

**Comment by shivnagarajan** [comment]
> @shivnagarajan what is that second "test" coming from?

Sorry, I should have been more clear in my original message. 

`restart.t` was the single flaky test I was encountering, and the scenario was when we ran our tests in a `docker container`, with ext-store enabled. 

so the part of my earlier message about

> Also, this tests fails when ext-store is enabled.

```
&& gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
	&& enableExtstore="$( \
# https://github.com/docker-library/memcached/pull/38
		case "$gnuArch" in \
# https://github.com/memcached/memcached/issues/381 "--enable-extstore on s390x (IBM System Z mainframe architecture) fails tests"
			s390x-*) ;; \
			*) echo '--enable-extstore' ;; \
		esac \
	)" \
```

Was essentially related to the arguments we used for `configure` that enabled `ext-store` and then ran the tests.

With the latest fix for the potential double `free` in this [change](https://github.com/memcached/memcached/commit/0d4901071c74f9c3b63162ef5887a5c5b981f385) this problem no longer happened. 

I had earlier verified that the test failure was in fact during restart when the new instance of `memcached` after the graceful shutdown would try to load the data from the metadata file, it would crash because it tried to `free` something that had already been freed, because `c->line` was not `NULL`.

**Comment by dormando** [comment]
Got it, thanks!

**Comment by dormando** [comment]
Adding to this: binary-extstore.t fails with some frequency on my VM builders.

**Comment by dormando** [comment]
t/chunked-extstore.t was also flaky (though this time moreso on faster systems). https://github.com/memcached/memcached/commit/23c6cf0daa835b81f5ecbd62769efb86eb47bef0 should fix.

**Comment by dormando** [comment]
t/binary-extstore.t should be fixed: https://github.com/memcached/memcached/commit/0551c9ad86781e9b2346b413ab6e078b25de71ab

**Comment by dormando** [comment]
t/getset.t should be improved by: https://github.com/memcached/memcached/commit/15aae94eaed4f0655148ab9ba129cd5fd73c4e30 - though I also can't get that to fail locally. Eyeballing it seems sort of obvious.

**Comment by dormando** [comment]
t/expirations.t should be mitigated by: https://github.com/memcached/memcached/commit/f162a5ceebb6550bfa44a28643491b806fd5b5a1 - if not I'll disable it harder until we have the right infrastructure.

Most other test fixes should be more final; removed lazy sleep testing where possible.

This seems to be all of the reports in here. @martin-g @shivnagarajan - have you seen any other flaky tests? If not I'll close this out.

**Comment by dormando** [comment]
Ok, pushed a real fix for chunked-extstore.t. I haven't looked at the restart one, but I'm done fiddling with tests for now.

If you folks haven't seen any other common ones, we'll close this out and open individual issues to more aggressively deal with them from now on.

**Comment by shivnagarajan** [comment]
I haven't seen any other failures in a while. I agree, we can probably track new failures separately. 

Thanks for all the work fixing the flaky tests. :-)

**Comment by dormando** [comment]
Great, thanks!

chunked-extstore.t is still not fixed because I've completely lost the ability to read, apparently. Will have to come up with a compaction off switch if next attempt doesn't work.

**Comment by dormando** [comment]
fixed now.

**Comment by martin-g** [comment]
The build is back to stable for me too after fixing the extstore tests.
I will open new issues if I notice new failures!
Thanks, @dormando !
