### ISSUE TITLE
Rejected Connection Reporting Issue in 1.5.22

### ISSUE THREAD

**Issue by eddyadarsh** [memcached/memcached#619]
**Describe the bug**
After upgrading to 1.5.22, we noticed that there is a huge increase in the number of rejected connections per memcached instance. In total, we use ~60-70 connections but rejected connections is matching the total connections count.

Below is the stats output:

STAT max_connections 1024
STAT curr_connections 69
STAT total_connections 867
STAT rejected_connections 865

**To Reproduce**
Upgrade to 1.5.22

**System Information**
 - OS/Distro: CentOS 7
 - Version of OS/distro: CentOS Linux release 7.6.1810 (Core) 
 - Version of memcached: 1.5.22
 - Hardware detail: 512GB RAM, 48 cores

**Detail (please include!)**
Always include the output of `stats`, `stats settings`, and optionally `stats items` and `stats slabs`. These can be provided to a maintainer privately if necessary. Please sanitize anything secret from the data.

STAT max_connections 1024
STAT curr_connections 69
STAT total_connections 867
STAT rejected_connections 865

If you have a segfault or crash, please try to resolve the crash with `addr2line`. If possible, get a core dump and include a full back trace.

**Comment by dormando** [comment]
Ah sorry; didn't mean you had to go open an issue, but thanks :)

A fix is pushed for the next release. I should also add more tests..

**Comment by eddyadarsh** [comment]
thanks @dormando
