### ISSUE TITLE
Floating point exception when specifying <100 conn-limit and idle_timeout is enabled

### ISSUE THREAD

**Issue by jefyt** [memcached/memcached#628]
**Describe the bug**
Floating point exception(division by zero) when specifying <100 conn-limit (total of <100 max_fds) and idle_timeout is enabled.

**To Reproduce**
Execute: memcached -c 50 -o idle_timeout=5
Result: Floating point exception (core dumped)

**System Information**
 - OS/Distro: Ubuntu
 - Version of OS/distro: 19.10
 - Version of memcached: 1.6.1
 - Hardware detail: VirtualBox

**Detail**
Crash location: https://github.com/memcached/memcached/blob/1.6.1/memcached.c#L344

**Comment by dormando** [comment]
Thanks! That's a weird one.

**Comment by dormando** [comment]
released in 1.6.3
