### ISSUE TITLE
Caveats with statically linked binary

### ISSUE THREAD

**Issue by LINKIWI** [memcached/memcached#630]
Hi, I'm curious if there are known caveats/gotchas involved in running memcached as a statically compiled binary. When configured with default features + `--enable-tls` and compiled with the `-static` gcc flag, the binary is much larger (as expected), but there seems to be no performance regressions and no other issues. Wanted to ask if there are any known potential caveats I should consider?

I also have a relatively simple patch to `configure.ac` to add support for optional static linking which I'm happy to submit a PR for if we're interested in exposing such support in the official build.

**Comment by dormando** [comment]
Works fine. I've run large clusters statically compiled. Feel free to submit the patch, but for some reason I thought it was already an option (or easy to do).
