### ISSUE TITLE
NULL pointer reference conduct DoS

### ISSUE THREAD

**Issue by NB-zhibin** [memcached/memcached#636]
memcached maintainer, 

I found a NULL pointer reference bug in code of memcached, which could conduct DoS by remote artificial command.

The affected memcached version: >1.6.0.

The bug location is at file: memcached.c, detailed information as the following:

In the function "process_mget_command", the local variable "errstr" is defined as a char*, which is not initialized.
![image](https://user-images.githubusercontent.com/62643867/77742729-e2ebfd80-7051-11ea-8421-8ca62bf4cab8.png)

In certain condition, the function "_meta_flag_preparse" is called in "process_mget_command", and the address of "errstr" is the 4th param. 
In the function "_meta_flag_preparse", there is chances that the "*errstr" is not initialized while command is "F" or "S". 
![image](https://user-images.githubusercontent.com/62643867/77742808-08790700-7052-11ea-895a-61a77b72af93.png)

then, out_errstring->out_string->strlen referencing a NULL pointer, conduct a crash.

BR
Zhibin

**Comment by dormando** [comment]
Hi @NB-zhibin 

You reached out over discord and I didn't hear back; you didn't submit this privately. May I ask what your motivation is? Is this for a class at school?

**Comment by dormando** [comment]
@NB-zhibin 

我之前在discord上有跟您聯系，並沒有得到你的回複，而你也沒有私底下提交這個bug。想問你提交這個request是否與學校作業有關。（如果比較方便的話，您可以用中文回複。）

**Comment by dormando** [comment]
released in 1.6.3
