### ISSUE TITLE
Incorrect stats `uptime` and `time` values

### ISSUE THREAD

**Issue by Doc999tor** [memcached/memcached#637]
Windows server 2012,  v1.4.5, installed as a service - I know you don't support Windows build officially but maybe some of you're familiar with the bug
`telnet 127.0.0.1 11211` - `stats`
After service restart
```
STAT uptime 3054537854
STAT time 344901278
STAT version 1.4.4-14-g9c660c0
```

**Comment by dormando** [comment]
Sorry, the windows version is an unsupported fork. It's both ten+ years old and I can't do anything about it. :(

**Comment by dormando** [comment]
I'm going to close this; you can try the memcached mailing list (see the main site). Someone seems to have posted an updated fork of a windows port that might work better for you.
