### ISSUE TITLE
version 1.4.15 ,query expired key dosent make it remove

### ISSUE THREAD

**Issue by yester354** [memcached/memcached#640]
**DO NOT SUBMIT SECURITY REPORTS HERE**

If you have a security vulnerability, _please report it to the maintainers
privately_. You will be able to file your bug and claim credit once we have a
fix implemented.

**Describe the bug**

version 1.4.15 ,query expired key dosent make it remove

**To Reproduce**
Any information useful for reproducing the bug or crash. Workload, changes in workload, versions affected. If seeing a new issue after an upgrade, please include both before and after versions.

STAT version 1.4.15

echo 'stats cachedump 6 1' |nc xx.xxx.xx.xxx 12001                                        
ITEM CC_SERVER_pro_xx.xxx.xx.xx:8080 [144 b; 1416824560 s]
END
echo 'get CC_SERVER_pro_xx.xxx.xx.xx:8080' |nc xx.xxx.xx.xx 12001                            
VALUE CC_SERVER_pro_xx.xxx.xx.xx:8080 2048 144
{"id":1268,"server":"xx.xxx.xx.xx:8080","host":1,"modules":"[\"mapi\",\"configcenter\"]","createTime":1480407349114,"updateTime":1480407349114}
END
echo 'get CC_SERVER_pro_xx.xxx.xx.xx:8080' |nc xx.xxx.xx.xx 12001
VALUE CC_SERVER_pro_xx.xxx.xx.xx:8080 2048 144
{"id":1268,"server":"xx.xxx.xx.xx:8080","host":1,"modules":"[\"mapi\",\"configcenter\"]","createTime":1480407349114,"updateTime":1480407349114}
END

i had tried many times to query the same expired key,it diden't make it remove,but not all the expired key work like this ,some of them removed as expected.

**System Information**
 - OS/Distro:
 - Version of OS/distro:
 - Version of memcached:
 - Hardware detail:

**Detail (please include!)**
Always include the output of `stats`, `stats settings`, and optionally `stats items` and `stats slabs`. These can be provided to a maintainer privately if necessary. Please sanitize anything secret from the data.

If you have a segfault or crash, please try to resolve the crash with `addr2line`. If possible, get a core dump and include a full back trace.

**Comment by yester354** [comment]
STAT pid 46674
STAT uptime 168974402
STAT time 1585798962
STAT version 1.4.15
STAT libevent 2.0.15-stable
STAT pointer_size 64
STAT rusage_user 789620.698407
STAT rusage_system 1755071.322603
STAT curr_connections 19
STAT total_connections 52997981
STAT connection_structures 4049
STAT reserved_fds 20
STAT cmd_get 15157933
STAT cmd_set 110972
STAT cmd_flush 0
STAT cmd_touch 0
STAT get_hits 2279136
STAT get_misses 12878797
STAT delete_misses 0
STAT delete_hits 0
STAT incr_misses 0
STAT incr_hits 0
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT touch_hits 0
STAT touch_misses 0
STAT auth_cmds 0
STAT auth_errors 0
STAT bytes_read 437938486925
STAT bytes_written 832640877153
STAT limit_maxbytes 8589934592
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT threads 4
STAT conn_yields 0
STAT hash_power_level 16
STAT hash_bytes 524288
STAT hash_is_expanding 0
STAT bytes 58788760
STAT curr_items 38493
STAT total_items 110972
STAT expired_unfetched 2324
STAT evicted_unfetched 0
STAT evictions 0
STAT reclaimed 2335
END

**Comment by yester354** [comment]
STAT items:3:number 1295
STAT items:3:age 145214808
STAT items:3:evicted 0
STAT items:3:evicted_nonzero 0
STAT items:3:evicted_time 0
STAT items:3:outofmemory 0
STAT items:3:tailrepairs 0
STAT items:3:reclaimed 346
STAT items:3:expired_unfetched 335
STAT items:3:evicted_unfetched 0
STAT items:4:number 101
STAT items:4:age 147813041
STAT items:4:evicted 0
STAT items:4:evicted_nonzero 0
STAT items:4:evicted_time 0
STAT items:4:outofmemory 0
STAT items:4:tailrepairs 0
STAT items:4:reclaimed 0
STAT items:4:expired_unfetched 0
STAT items:4:evicted_unfetched 0
STAT items:5:number 112
STAT items:5:age 166989050
STAT items:5:evicted 0
STAT items:5:evicted_nonzero 0
STAT items:5:evicted_time 0
STAT items:5:outofmemory 0
STAT items:5:tailrepairs 0
STAT items:5:reclaimed 0
STAT items:5:expired_unfetched 0
STAT items:5:evicted_unfetched 0
STAT items:6:number 476
STAT items:6:age 166384099
STAT items:6:evicted 0
STAT items:6:evicted_nonzero 0
STAT items:6:evicted_time 0
STAT items:6:outofmemory 0
STAT items:6:tailrepairs 0
STAT items:6:reclaimed 0
STAT items:6:expired_unfetched 0
STAT items:6:evicted_unfetched 0
STAT items:7:number 15
STAT items:7:age 166397204
STAT items:7:evicted 0
STAT items:7:evicted_nonzero 0
STAT items:7:evicted_time 0
STAT items:7:outofmemory 0
STAT items:7:tailrepairs 0
STAT items:7:reclaimed 0
STAT items:7:expired_unfetched 0
STAT items:7:evicted_unfetched 0
STAT items:8:number 1506
STAT items:8:age 149024785
STAT items:8:evicted 0
STAT items:8:evicted_nonzero 0
STAT items:8:evicted_time 0
STAT items:8:outofmemory 0
STAT items:8:tailrepairs 0
STAT items:8:reclaimed 818
STAT items:8:expired_unfetched 818
STAT items:8:evicted_unfetched 0
STAT items:9:number 5
STAT items:9:age 157743492
STAT items:9:evicted 0
STAT items:9:evicted_nonzero 0
STAT items:9:evicted_time 0
STAT items:9:outofmemory 0
STAT items:9:tailrepairs 0
STAT items:9:reclaimed 0
STAT items:9:expired_unfetched 0
STAT items:9:evicted_unfetched 0
STAT items:10:number 1672
STAT items:10:age 158352717
STAT items:10:evicted 0
STAT items:10:evicted_nonzero 0
STAT items:10:evicted_time 0
STAT items:10:outofmemory 0
STAT items:10:tailrepairs 0
STAT items:10:reclaimed 0
STAT items:10:expired_unfetched 0
STAT items:10:evicted_unfetched 0
STAT items:11:number 4
STAT items:11:age 135460422
STAT items:11:evicted 0
STAT items:11:evicted_nonzero 0
STAT items:11:evicted_time 0
STAT items:11:outofmemory 0
STAT items:11:tailrepairs 0
STAT items:11:reclaimed 22
STAT items:11:expired_unfetched 22
STAT items:11:evicted_unfetched 0
STAT items:12:number 553
STAT items:12:age 139865926
STAT items:12:evicted 0
STAT items:12:evicted_nonzero 0
STAT items:12:evicted_time 0
STAT items:12:outofmemory 0
STAT items:12:tailrepairs 0
STAT items:12:reclaimed 1149
STAT items:12:expired_unfetched 1149
STAT items:12:evicted_unfetched 0
STAT items:13:number 2096
STAT items:13:age 165275677
STAT items:13:evicted 0
STAT items:13:evicted_nonzero 0
STAT items:13:evicted_time 0
STAT items:13:outofmemory 0
STAT items:13:tailrepairs 0
STAT items:13:reclaimed 0
STAT items:13:expired_unfetched 0
STAT items:13:evicted_unfetched 0
STAT items:14:number 30071
STAT items:14:age 162665108
STAT items:14:evicted 0
STAT items:14:evicted_nonzero 0
STAT items:14:evicted_time 0
STAT items:14:outofmemory 0
STAT items:14:tailrepairs 0
STAT items:14:reclaimed 0
STAT items:14:expired_unfetched 0
STAT items:14:evicted_unfetched 0
STAT items:15:number 566
STAT items:15:age 163201919
STAT items:15:evicted 0
STAT items:15:evicted_nonzero 0
STAT items:15:evicted_time 0
STAT items:15:outofmemory 0
STAT items:15:tailrepairs 0
STAT items:15:reclaimed 0
STAT items:15:expired_unfetched 0
STAT items:15:evicted_unfetched 0
STAT items:17:number 12
STAT items:17:age 163979752
STAT items:17:evicted 0
STAT items:17:evicted_nonzero 0
STAT items:17:evicted_time 0
STAT items:17:outofmemory 0
STAT items:17:tailrepairs 0
STAT items:17:reclaimed 0
STAT items:17:expired_unfetched 0
STAT items:17:evicted_unfetched 0
STAT items:18:number 2
STAT items:18:age 157324392
STAT items:18:evicted 0
STAT items:18:evicted_nonzero 0
STAT items:18:evicted_time 0
STAT items:18:outofmemory 0
STAT items:18:tailrepairs 0
STAT items:18:reclaimed 0
STAT items:18:expired_unfetched 0
STAT items:18:evicted_unfetched 0
STAT items:19:number 3
STAT items:19:age 152638992
STAT items:19:evicted 0
STAT items:19:evicted_nonzero 0
STAT items:19:evicted_time 0
STAT items:19:outofmemory 0
STAT items:19:tailrepairs 0
STAT items:19:reclaimed 0
STAT items:19:expired_unfetched 0
STAT items:19:evicted_unfetched 0
STAT items:21:number 2
STAT items:21:age 105302251
STAT items:21:evicted 0
STAT items:21:evicted_nonzero 0
STAT items:21:evicted_time 0
STAT items:21:outofmemory 0
STAT items:21:tailrepairs 0
STAT items:21:reclaimed 0
STAT items:21:expired_unfetched 0
STAT items:21:evicted_unfetched 0
STAT items:22:number 1
STAT items:22:age 67983834
STAT items:22:evicted 0
STAT items:22:evicted_nonzero 0
STAT items:22:evicted_time 0
STAT items:22:outofmemory 0
STAT items:22:tailrepairs 0
STAT items:22:reclaimed 0
STAT items:22:expired_unfetched 0
STAT items:22:evicted_unfetched 0
STAT items:23:number 1
STAT items:23:age 166470857
STAT items:23:evicted 0
STAT items:23:evicted_nonzero 0
STAT items:23:evicted_time 0
STAT items:23:outofmemory 0
STAT items:23:tailrepairs 0
STAT items:23:reclaimed 0
STAT items:23:expired_unfetched 0
STAT items:23:evicted_unfetched 0
END

**Comment by yester354** [comment]
STAT maxbytes 0
STAT maxconns 65535
STAT tcpport 12001
STAT udpport 12001
STAT inter NULL
STAT verbosity 0
STAT oldest 0
STAT evictions on
STAT domain_socket NULL
STAT umask 700
STAT growth_factor 1.25
STAT chunk_size 48
STAT num_threads 4
STAT num_threads_per_udp 4
STAT stat_key_prefix :
STAT detail_enabled no
STAT reqs_per_event 20
STAT cas_enabled yes
STAT tcp_backlog 1024
STAT binding_protocol auto-negotiate
STAT auth_enabled_sasl no
STAT item_size_max 1048576
STAT maxconns_fast no
STAT hashpower_init 0
STAT slab_reassign no
STAT slab_automove 0
END

**Comment by yester354** [comment]
STAT 3:chunks_per_page 6898
STAT 3:total_pages 1
STAT 3:total_chunks 6898
STAT 3:used_chunks 1295
STAT 3:free_chunks 5603
STAT 3:free_chunks_end 0
STAT 3:mem_requested 164223
STAT 3:get_hits 826
STAT 3:cmd_set 1642
STAT 3:delete_hits 0
STAT 3:incr_hits 0
STAT 3:decr_hits 0
STAT 3:cas_hits 0
STAT 3:cas_badval 0
STAT 3:touch_hits 0
STAT 4:chunk_size 192
STAT 4:chunks_per_page 5461
STAT 4:total_pages 1
STAT 4:total_chunks 5461
STAT 4:used_chunks 101
STAT 4:free_chunks 5360
STAT 4:free_chunks_end 0
STAT 4:mem_requested 17258
STAT 4:get_hits 678
STAT 4:cmd_set 101
STAT 4:delete_hits 0
STAT 4:incr_hits 0
STAT 4:decr_hits 0
STAT 4:cas_hits 0
STAT 4:cas_badval 0
STAT 4:touch_hits 0
STAT 5:chunk_size 240
STAT 5:chunks_per_page 4369
STAT 5:total_pages 1
STAT 5:total_chunks 4369
STAT 5:used_chunks 112
STAT 5:free_chunks 4257
STAT 5:free_chunks_end 0
STAT 5:mem_requested 26150
STAT 5:get_hits 16053
STAT 5:cmd_set 4944
STAT 5:delete_hits 0
STAT 5:incr_hits 0
STAT 5:decr_hits 0
STAT 5:cas_hits 0
STAT 5:cas_badval 0
STAT 5:touch_hits 0
STAT 6:chunk_size 304
STAT 6:chunks_per_page 3449
STAT 6:total_pages 1
STAT 6:total_chunks 3449
STAT 6:used_chunks 476
STAT 6:free_chunks 2973
STAT 6:free_chunks_end 0
STAT 6:mem_requested 118193
STAT 6:get_hits 2057941
STAT 6:cmd_set 5315
STAT 6:delete_hits 0
STAT 6:incr_hits 0
STAT 6:decr_hits 0
STAT 6:cas_hits 0
STAT 6:cas_badval 0
STAT 6:touch_hits 0
STAT 7:chunk_size 384
STAT 7:chunks_per_page 2730
STAT 7:total_pages 1
STAT 7:total_chunks 2730
STAT 7:used_chunks 15
STAT 7:free_chunks 2715
STAT 7:free_chunks_end 0
STAT 7:mem_requested 5171
STAT 7:get_hits 90375
STAT 7:cmd_set 181
STAT 7:delete_hits 0
STAT 7:incr_hits 0
STAT 7:decr_hits 0
STAT 7:cas_hits 0
STAT 7:cas_badval 0
STAT 7:touch_hits 0
STAT 8:chunk_size 480
STAT 8:chunks_per_page 2184
STAT 8:total_pages 1
STAT 8:total_chunks 2184
STAT 8:used_chunks 1506
STAT 8:free_chunks 678
STAT 8:free_chunks_end 0
STAT 8:mem_requested 644956
STAT 8:get_hits 3290
STAT 8:cmd_set 5875
STAT 8:delete_hits 0
STAT 8:incr_hits 0
STAT 8:decr_hits 0
STAT 8:cas_hits 0
STAT 8:cas_badval 0
STAT 8:touch_hits 0
STAT 9:chunk_size 600
STAT 9:chunks_per_page 1747
STAT 9:total_pages 1
STAT 9:total_chunks 1747
STAT 9:used_chunks 5
STAT 9:free_chunks 1742
STAT 9:free_chunks_end 0
STAT 9:mem_requested 2734
STAT 9:get_hits 12514
STAT 9:cmd_set 5
STAT 9:delete_hits 0
STAT 9:incr_hits 0
STAT 9:decr_hits 0
STAT 9:cas_hits 0
STAT 9:cas_badval 0
STAT 9:touch_hits 0
STAT 10:chunk_size 752
STAT 10:chunks_per_page 1394
STAT 10:total_pages 2
STAT 10:total_chunks 2788
STAT 10:used_chunks 1672
STAT 10:free_chunks 1116
STAT 10:free_chunks_end 0
STAT 10:mem_requested 1230125
STAT 10:get_hits 8681
STAT 10:cmd_set 4549
STAT 10:delete_hits 0
STAT 10:incr_hits 0
STAT 10:decr_hits 0
STAT 10:cas_hits 0
STAT 10:cas_badval 0
STAT 10:touch_hits 0
STAT 11:chunk_size 944
STAT 11:chunks_per_page 1110
STAT 11:total_pages 1
STAT 11:total_chunks 1110
STAT 11:used_chunks 4
STAT 11:free_chunks 1106
STAT 11:free_chunks_end 0
STAT 11:mem_requested 3199
STAT 11:get_hits 10064
STAT 11:cmd_set 66
STAT 11:delete_hits 0
STAT 11:incr_hits 0
STAT 11:decr_hits 0
STAT 11:cas_hits 0
STAT 11:cas_badval 0
STAT 11:touch_hits 0
STAT 12:chunk_size 1184
STAT 12:chunks_per_page 885
STAT 12:total_pages 1
STAT 12:total_chunks 885
STAT 12:used_chunks 553
STAT 12:free_chunks 332
STAT 12:free_chunks_end 0
STAT 12:mem_requested 577586
STAT 12:get_hits 19844
STAT 12:cmd_set 3938
STAT 12:delete_hits 0
STAT 12:incr_hits 0
STAT 12:decr_hits 0
STAT 12:cas_hits 0
STAT 12:cas_badval 0
STAT 12:touch_hits 0
STAT 13:chunk_size 1480
STAT 13:chunks_per_page 708
STAT 13:total_pages 3
STAT 13:total_chunks 2124
STAT 13:used_chunks 2096
STAT 13:free_chunks 28
STAT 13:free_chunks_end 0
STAT 13:mem_requested 2835055
STAT 13:get_hits 11982
STAT 13:cmd_set 4914
STAT 13:delete_hits 0
STAT 13:incr_hits 0
STAT 13:decr_hits 0
STAT 13:cas_hits 0
STAT 13:cas_badval 0
STAT 13:touch_hits 0
STAT 14:chunk_size 1856
STAT 14:chunks_per_page 564
STAT 14:total_pages 54
STAT 14:total_chunks 30456
STAT 14:used_chunks 30071
STAT 14:free_chunks 385
STAT 14:free_chunks_end 0
STAT 14:mem_requested 52005503
STAT 14:get_hits 42485
STAT 14:cmd_set 76592
STAT 14:delete_hits 0
STAT 14:incr_hits 0
STAT 14:decr_hits 0
STAT 14:cas_hits 0
STAT 14:cas_badval 0
STAT 14:touch_hits 0
STAT 15:chunk_size 2320
STAT 15:chunks_per_page 451
STAT 15:total_pages 2
STAT 15:total_chunks 902
STAT 15:used_chunks 566
STAT 15:free_chunks 336
STAT 15:free_chunks_end 0
STAT 15:mem_requested 1057032
STAT 15:get_hits 3291
STAT 15:cmd_set 2824
STAT 15:delete_hits 0
STAT 15:incr_hits 0
STAT 15:decr_hits 0
STAT 15:cas_hits 0
STAT 15:cas_badval 0
STAT 15:touch_hits 0
STAT 17:chunk_size 3632
STAT 17:chunks_per_page 288
STAT 17:total_pages 1
STAT 17:total_chunks 288
STAT 17:used_chunks 12
STAT 17:free_chunks 276
STAT 17:free_chunks_end 0
STAT 17:mem_requested 40342
STAT 17:get_hits 204
STAT 17:cmd_set 14
STAT 17:delete_hits 0
STAT 17:incr_hits 0
STAT 17:decr_hits 0
STAT 17:cas_hits 0
STAT 17:cas_badval 0
STAT 17:touch_hits 0
STAT 18:chunk_size 4544
STAT 18:chunks_per_page 230
STAT 18:total_pages 1
STAT 18:total_chunks 230
STAT 18:used_chunks 2
STAT 18:free_chunks 228
STAT 18:free_chunks_end 0
STAT 18:mem_requested 8331
STAT 18:get_hits 43
STAT 18:cmd_set 2
STAT 18:delete_hits 0
STAT 18:incr_hits 0
STAT 18:decr_hits 0
STAT 18:cas_hits 0
STAT 18:cas_badval 0
STAT 18:touch_hits 0
STAT 19:chunk_size 5680
STAT 19:chunks_per_page 184
STAT 19:total_pages 1
STAT 19:total_chunks 184
STAT 19:used_chunks 3
STAT 19:free_chunks 181
STAT 19:free_chunks_end 0
STAT 19:mem_requested 14988
STAT 19:get_hits 148
STAT 19:cmd_set 4
STAT 19:delete_hits 0
STAT 19:incr_hits 0
STAT 19:decr_hits 0
STAT 19:cas_hits 0
STAT 19:cas_badval 0
STAT 19:touch_hits 0
STAT 21:chunk_size 8880
STAT 21:chunks_per_page 118
STAT 21:total_pages 1
STAT 21:total_chunks 118
STAT 21:used_chunks 2
STAT 21:free_chunks 116
STAT 21:free_chunks_end 0
STAT 21:mem_requested 15849
STAT 21:get_hits 623
STAT 21:cmd_set 4
STAT 21:delete_hits 0
STAT 21:incr_hits 0
STAT 21:decr_hits 0
STAT 21:cas_hits 0
STAT 21:cas_badval 0
STAT 21:touch_hits 0
STAT 22:chunk_size 11104
STAT 22:chunks_per_page 94
STAT 22:total_pages 1
STAT 22:total_chunks 94
STAT 22:used_chunks 1
STAT 22:free_chunks 93
STAT 22:free_chunks_end 0
STAT 22:mem_requested 8940
STAT 22:get_hits 94
STAT 22:cmd_set 1
STAT 22:delete_hits 0
STAT 22:incr_hits 0
STAT 22:decr_hits 0
STAT 22:cas_hits 0
STAT 22:cas_badval 0
STAT 22:touch_hits 0
STAT 23:chunk_size 13880
STAT 23:chunks_per_page 75
STAT 23:total_pages 1
STAT 23:total_chunks 75
STAT 23:used_chunks 1
STAT 23:free_chunks 74
STAT 23:free_chunks_end 0
STAT 23:mem_requested 13125
STAT 23:get_hits 0
STAT 23:cmd_set 1
STAT 23:delete_hits 0
STAT 23:incr_hits 0
STAT 23:decr_hits 0
STAT 23:cas_hits 0
STAT 23:cas_badval 0
STAT 23:touch_hits 0
STAT active_slabs 19
STAT total_malloced 79562528
END

**Comment by dormando** [comment]
Hey,

Unfortunately we can't provide support for such an old version. :( The old versions are missing stats counters which would help troubleshoot an issue, and it's likely most issues were fixed since 1.4.15 was released many years ago.

**Comment by yester354** [comment]
> Hey,
> 
> Unfortunately we can't provide support for such an old version. :( The old versions are missing stats counters which would help troubleshoot an issue, and it's likely most issues were fixed since 1.4.15 was released many years ago.

thanks
