### ISSUE TITLE
Segfaulting when using Memcached

### ISSUE THREAD

**Issue by ibrierley** [memcached/memcached#645]
**DO NOT SUBMIT SECURITY REPORTS HERE**

If you have a security vulnerability, _please report it to the maintainers
privately_. You will be able to file your bug and claim credit once we have a
fix implemented.

**Describe the bug**
Regularly intermittent Segfault/core dump when calling Memcached. NOTE this is accessed via Perl API (which is quite old now, so it's possible it's no longer supported and if the problem is feasible to there, I'm happy to close). The memcached daemon doesn't crash, so it's possible it's the Perl API, any way to tell?)

In an strace I see the following as well, which is likely related 
writev(2, [{iov_base="corrupted double-linked list", iov_len=28}, {iov_base="\n", iov_len=1}], 2corrupted double-linked list

I appreciate it may not be Memcached itself. Just trying to get some pointers...

**To Reproduce**
Any information useful for reproducing the bug or crash. Workload, changes in workload, versions affected. If seeing a new issue after an upgrade, please include both before and after versions.

**System Information**
 - Centos 8
 - Memcached (perl version 5.30, perl cache::memcached 1.30)
 - Version of memcached: 1.5.9
 - Hardware detail: Dell server 128Gig ram.
Kernel 4.18.0-147.5.1.el8_1.x86_64 #1 SMP Wed Feb 5 02:00:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Detail (please include!)**
Always include the output of `stats`, `stats settings`, and optionally `stats items` and `stats slabs`. These can be provided to a maintainer privately if necessary. Please sanitize anything secret from the data.

If you have a segfault or crash, please try to resolve the crash with `addr2line`. If possible, get a core dump and include a full back trace.

stats
STAT pid 1441
STAT uptime 3111558
STAT time 1586344690
STAT version 1.5.9
STAT libevent 2.1.8-stable
STAT pointer_size 64
STAT rusage_user 4430.999003
STAT rusage_system 7159.366258
STAT max_connections 1024
STAT curr_connections 12
STAT total_connections 20166
STAT rejected_connections 0
STAT connection_structures 82
STAT reserved_fds 20
STAT cmd_get 1152584874
STAT cmd_set 763162499
STAT cmd_flush 0
STAT cmd_touch 0
STAT get_hits 355488535
STAT get_misses 797096339
STAT get_expired 0
STAT get_flushed 0
STAT delete_misses 0
STAT delete_hits 0
STAT incr_misses 0
STAT incr_hits 0
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT touch_hits 0
STAT touch_misses 0
STAT auth_cmds 0
STAT auth_errors 0
STAT bytes_read 481930494602
STAT bytes_written 224180844504
STAT limit_maxbytes 67108864
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT time_in_listen_disabled_us 0
STAT threads 4
STAT conn_yields 30796210
STAT hash_power_level 16
STAT hash_bytes 524288
STAT hash_is_expanding 0
STAT slab_reassign_rescues 1400246
STAT slab_reassign_chunk_rescues 0
STAT slab_reassign_evictions_nomem 92581782
STAT slab_reassign_inline_reclaim 89642487
STAT slab_reassign_busy_items 92582726
STAT slab_reassign_busy_deletes 0
STAT slab_reassign_running 0
STAT slabs_moved 61002
STAT lru_crawler_running 0
STAT lru_crawler_starts 227715
STAT lru_maintainer_juggles 116613533
STAT malloc_fails 0
STAT log_worker_dropped 0
STAT log_worker_written 0
STAT log_watcher_skipped 0
STAT log_watcher_sent 0
STAT bytes 55944868
STAT curr_items 86910
STAT total_items 764562745
STAT slab_global_page_pool 0
STAT expired_unfetched 0
STAT evicted_unfetched 555044004
STAT evicted_active 72372
STAT evictions 670153278
STAT reclaimed 0
STAT crawler_reclaimed 0
STAT crawler_items_checked 72579478
STAT lrutail_reflocked 89071
STAT moves_to_cold 756727761
STAT moves_to_warm 39600875
STAT moves_within_lru 27300786
STAT direct_reclaims 670153278
STAT lru_bumps_dropped 0

STAT maxbytes 67108864
STAT maxconns 1024
STAT tcpport 11211
STAT udpport 0
STAT inter 127.0.0.1,::1
STAT verbosity 0
STAT oldest 0
STAT evictions on
STAT domain_socket NULL
STAT umask 700
STAT growth_factor 1.25
STAT chunk_size 48
STAT num_threads 4
STAT num_threads_per_udp 1
STAT stat_key_prefix :
STAT detail_enabled no
STAT reqs_per_event 20
STAT cas_enabled yes
STAT tcp_backlog 1024
STAT binding_protocol auto-negotiate
STAT auth_enabled_sasl no
STAT item_size_max 1048576
STAT maxconns_fast yes
STAT hashpower_init 0
STAT slab_reassign yes
STAT slab_automove 1
STAT slab_automove_ratio 0.80
STAT slab_automove_window 30
STAT slab_chunk_max 524288
STAT lru_crawler yes
STAT lru_crawler_sleep 100
STAT lru_crawler_tocrawl 0
STAT tail_repair_time 0
STAT flush_enabled yes
STAT dump_enabled yes
STAT hash_algorithm murmur3
STAT lru_maintainer_thread yes
STAT lru_segmented yes
STAT hot_lru_pct 20
STAT warm_lru_pct 40
STAT hot_max_factor 0.20
STAT warm_max_factor 2.00
STAT temp_lru no
STAT temporary_ttl 61
STAT idle_timeout 0
STAT watcher_logbuf_size 262144
STAT worker_logbuf_size 65536
STAT track_sizes no
STAT inline_ascii_response no

**Comment by martin-g** [comment]
Do you face the same problem with latest Memcached (1.6.3) ?
Can you share a mini application that reproduces the problem ? I use XMemcached (for Java) and Cache::Memcached (for Perl) and I haven't faced such problems here.

**Comment by dormando** [comment]
sorry, can you clarify; what exactly is crashing? I don't think there's any reason for Cache::Memcached to segfault an application, and if the server is stable that should also be fine..

**Comment by dormando** [comment]
@ibrierley poke?

**Comment by ibrierley** [comment]
Hi, it's a Perl script which is segfaulting when it retrieves some data
from memcached (via a Perl Memcached module that's been around a very long
time), the previous strace showing "corrupted double-linked list".

My main question is naturally why that is happening (or if there's some way
to prevent it and let it fail gracefully), I don't have the skills to
ascertain if that's because of Memcached, or the Perl module accessing it.

Thanks,

Ian

**Comment by dormando** [comment]
Well I can safely say it's not the daemon causing your client to crash. As in there isn't anything the server should or shouldn't be doing; no matter what the client shouldn't crash.

Sadly I'm not sure where to point you from there. I'd need a great deal of information to debug it and it's not really on topic here :(

**Comment by ibrierley** [comment]
No problem, I was just wondering if anyone had come across the "corrupted double-linked list" when using it (I think that's a glibc error). For example a long time ago with php (I'm using Perl) I spotted the error mentioned here https://bugs.php.net/bug.php?id=57329 with Memcached.

Alas I'm guessing it will probably get no further (it's very difficult for me to isolate as it's intermittent and we have so much going on on the machine), so feel free to close, and I will reopen if I track it down further to Memcached.
