### ISSUE TITLE
memchased inservice authentication

### ISSUE THREAD

**Issue by sivag9** [memcached/memcached#652]
Hi Memchased community,

Heard that, memchased is having inservice-auth support.

https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L176

But the above link does n't have any sample code w.r.t the usage of the commands. Can you please share the sample code on how to use the inservice auth.

Thanks,
Samba.

**Comment by dormando** [comment]
that's the underlying protocol. If you use a client and simply run a "set" command it will authenticate.

`client.set('any key works', 'username password')`
