### ISSUE TITLE
Make ssl cerificate keys longer

### ISSUE THREAD

**Issue by TomasKorbar** [memcached/memcached#659]
**Describe the bug**
Hi, i'm the maintainer of memcached package on fedora and RHEL. I would like to use your test suite with enabled ssl testing. That is unfortunately impossible at this time when default system wide crypto policy has seclevel of CipherString 2 and thus rsa keys shorter than 2048 bits are not allowed. This keeps memcacheds testing instance from starting. I want to test memcached in environment which has hardened crypto policy so i would like to not change it because of the test.

**To Reproduce**
1. Set your seclevel of cipher string to 2 in your openssl configuration. On debian in
`/etc/ssl/openssl.cnf`, in Fedora `/etc/crypto-policies/back-ends/opensslcnf.config`
2. try to run the test suite with enabled ssl testing.
(in memcached source directory)
$./configure --enable-tls
$make
$export SSL_TEST=1
$make test

**Expected result**
Test suite successfully finishes.
**Actual result**
Test suite hangs and must be interupted with sigint.

**System Information**
 - OS/Distro: any distro with hardened crypto policy but for example Fedora
 - Version of OS/distro: Rawhide
 - Version of memcached: 1.6.3

**Solution**
Please regenerate the ssl certificates used for testing and use rsa keys at least 2048 bites long.
I would send pull request but i was not able to generate the exact same subject for these certificates.

**Comment by martin-g** [comment]
Which setting exactly do you change in openssl.cnf ?
I don't find any occurrence of `seclevel` or `cypher` here.

**Comment by jefyt** [comment]
Just wanna add, **_debian:testing_**  can also replicate this issue. See https://github.com/jefyt/memcached-windows/runs/604710616?check_suite_focus=true. **_Test TLS_** hangs up and forcibly terminated by timeout alarm. "**_In Debian the defaults are set to more secure values by default. This is done in the /etc/ssl/openssl.cnf config file._**" See https://wiki.debian.org/ContinuousIntegration/TriagingTips/openssl-1.1.1 for the details.

**Comment by dormando** [comment]
Thanks!

Related to https://github.com/memcached/memcached/issues/586 - so known but nobody's fixed yet.

**Comment by dormando** [comment]
@tharanga - another report for this one

**Comment by dormando** [comment]
Fwiw this fails on ubuntu 20.04.

**Comment by TomasKorbar** [comment]
Hi dormando,
I managed to regenerate your testing certificates with longer keys a few days ago. I can create pull request if you want to. I did not because i thought that you will want to do it yourself.

**Comment by dormando** [comment]
Go ahead and open if you want. I left this to @tharanga as IIRC he generated the certs and I forgot to get the invocation from him at the time :) If you've managed it we can just use that for now.
