### ISSUE TITLE
Potential Races

### ISSUE THREAD

**Issue by PeimingLiu** [memcached/memcached#662]
Hi, we are developing a static race detector tool and we scanned your project using our tool. It reports several suspicious races.

Here are detailed reports:
```
Thread 1:
 160|    pthread_mutex_lock(&d->lock);
 161|    d->crawlerstats[slab_cls].end_time = current_time;
>162|    d->crawlerstats[slab_cls].run_complete = true;
 163|    pthread_mutex_unlock(&d->lock);
 164|}
>>>Stacktrace:
>>>pthread_create [crawler.c:505]
>>>  item_crawler_thread [crawler.c:505]
>>>    lru_crawler_class_done [crawler.c:378]
>>>      crawler_expired_doneclass [crawler.c:350]
Thread 2:
 1462|        crawlerstats_t *s = &cdata->crawlerstats[i];
 1463|        /* We've not successfully kicked off a crawl yet. */
>1464|        if (s->run_complete) {
 1465|            char *lru_name = "na";
 1466|            pthread_mutex_lock(&cdata->lock);
>>>Stacktrace:
>>>pthread_create [items.c:1703]
>>>  lru_maintainer_thread [items.c:1703]
>>>    lru_maintainer_crawler_check [items.c:1647]
```

Although the write @ `crawler.c:162` is protected by the lock, the first read on `crawler.c:1464` is not protected by the same lock (the lock was acquired two lines after at line 1466). 

Similiar issues were observed in logger.c
```
Thread 1:
 171|    for (l = logger_stack_head; l != NULL; l=l->next) {
 172|        pthread_mutex_lock(&l->mutex);
>173|        l->eflags = f;
 174|        pthread_mutex_unlock(&l->mutex);
 175|    }
>>>Stacktrace:
>>>pthread_create [logger.c:562]
>>>  logger_thread [logger.c:562]
>>>    logger_thread_read [logger.c:536]
>>>      logger_thread_write_entry [logger.c:377]
>>>        logger_thread_poll_watchers [logger.c:304]
>>>          logger_thread_close_watcher [logger.c:462]
>>>            logger_set_flags [logger.c:346]
Thread 2:
 1510|                    break;
 1511|            }
>1512|            LOGGER_LOG(l, LOG_SYSEVENTS, LOGGER_CRAWLER_STATUS, NULL,
 1513|                    CLEAR_LRU(i),
 1514|                    lru_name,
>>>Stacktrace:
>>>pthread_create [items.c:1703]
>>>  lru_maintainer_thread [items.c:1703]
>>>    lru_maintainer_crawler_check [items.c:1647]
```

Where you acquire a lock @ `logger.c:172` before you update the `l->eflags`, while the `LOGGER_LOG` macro can read the flag without the lock.

```
#define LOGGER_LOG(l, flag, type, ...) \
    do { \
        logger *myl = l; \
        if (l == NULL) \
            myl = GET_LOGGER(); \
        if (myl->eflags & flag) \
            logger_log(myl, type, __VA_ARGS__); \
    } while (0)
```

There are a few more similar cases where concurrent write-write accesses are protected by locks while concurrent read-write accesses are not. Let me know if you need more information.

Please let us know your opinions! It would be valuable for us as well!

**Comment by dormando** [comment]
I'll have to double check the crawler one, but LOGGER_LOG() is done deliberately. Writes to the flag are protected but it's completely fine for the read to be wrong for a while, at least right now. It does that to avoid having to kick a mutex or pipeline stall for all of the logger calls.

**Comment by PeimingLiu** [comment]
Okay!

Just let me know if you have new findings!

**Comment by dormando** [comment]
I think the crawler one is legitimate, but doesn't affect much. It immediately locks the data structure and re-checks after that point, but it should lock before checking run_complete as there's no performance implication there.

**Comment by PeimingLiu** [comment]
Okay, Thanks so much for your time!

We have a few similar cases detected as well. If you are interested, I can post them as well.

**Comment by dormando** [comment]
Uhh what do I get out of this? :)

I guess you can post them; but I might only skim unless they're serious looking. There are a lot of cases where the settings structure has raw reads or I've done something a bit odd because it doesn't matter. Someone else with a static analyzer caused some bugs fixing correctness issues which kind of didn't matter in the grand scheme of things, so I'm trying to be more careful now.

Perhaps some passers-by can review as well.

**Comment by PeimingLiu** [comment]
Totally Understandable!

We took a closer look at the reported race, and we thought the following races **might** be important. 

The detailed report is as follow:
```
 1249|        if (cur == dst)
 1250|            continue;
>1251|        if (slabclass[cur].slabs > 1) {
 1252|            return cur;
 1253|        }
>>>Stack Trace:
>>>      process_mget_command [memcached.c:6053]
>>>        item_alloc [memcached.c:4392]
>>>          do_item_alloc [thread.c:669]
>>>            do_item_alloc_pull [items.c:286]
>>>              lru_pull_tail [items.c:187]
>>>                slabs_reassign [items.c:1216]
>>>                  do_slabs_reassign [slabs.c:1297]
>>>                    slabs_reassign_pick_any [slabs.c:1268]
```

You can see that the in `slab_reassign_pick_any`, the access on `slabclass[cur].slabs` are not protected by a lock, while there are many other memory accesses on other threads.

E.g., in slabs.c
```
 394|
>395| p->slab_list[p->slabs++] = ptr;
 396| MEMCACHED_SLABS_SLABCLASS_ALLOCATE(id);
```
(Note that there are other places that access `p->slabs` as well).

We noticed that you protected the read with lock a few lines after in `do_slabs_reassign`.
```
    if (src == -1) {
        src = slabs_reassign_pick_any(dst);
        /* TODO: If we end up back at -1, return a new error type */
    }

    if (src < SLAB_GLOBAL_PAGE_POOL || src > power_largest ||
        dst < SLAB_GLOBAL_PAGE_POOL || dst > power_largest)
        return REASSIGN_BADCLASS;

    pthread_mutex_lock(&slabs_lock);
    if (slabclass[src].slabs < 2)
        nospare = true;
    pthread_mutex_unlock(&slabs_lock);
```

Since it is related to memory allocation in memcached, we think it worth to be reported. Please let us know if you have any comment.

**Comment by dormando** [comment]
Going to close this out.

In this case: the pick_any() feature called inline from pull_tail should be removed. I added it in anger a long time ago and it's never the right thing to do... but I dunno if anyone uses it.

In this case it does a dirty check on the slab to find a source, then does a lock and validates that the slab is actually valid to pull pages from. It certainly looks wrong but it's not actually doing anything wrong.
