### ISSUE TITLE
Buildbot reboot

### ISSUE THREAD

**Issue by dormando** [memcached/memcached#664]
I've been responding to a lot of issues/PR's with "once I get the buildbots... etc" for a while now. For the last week I've been doing just that. It's far enough along that I want to track progress publicly. Hopefully we'll get some drive-by feedback.

I've had a private buildbot master up for years, but now the build status is public again:
https://build.memcached.org/#/
on a proper port with TLS, even.

The old setup:

- Private buildbot master.
- A bunch of VM's on a cloud service snapshotted after being configured as buildbot workers.
- A script to start the VM's on demand.
Better than zero but sucked because:
- Expensive. Can't leave them running all the time.
- Very hard to configure buildbot to run the VM's on command.
- At the mercy of which OS's are available on the cloud vendor.
- Slow. Starting instances takes a while, the instances are min-sized and really slow.
- Adding more builders is a big pain. Have to install some basics, but also ensure python/etc is new enough, git is new enough, and that the worker will successfully start on its own with the OS.

The new setup:

- Public build status works now (had the wrong ACL this whole time?)
- An old intel NUC (for now) dedicated to running a worker.
- A single worker on this NUC with many builds.
- A "fast" build which uses compile and test parallelism on an ubuntu 20.04 host; when builds are kicked off this build runs first, takes 1-2 minutes.
- Once "fast" is done, all other tests are run.

The bulk of builds are assembled in VM's through some tiny custom scripts because virsh's config system is too complex for my ignorance. The worker kicks off a VM in snapshot mode, runs the build over SSH, then stops the VM afterward. Other builds may be done via chroot's (bigendian tests/etc).

Benefits:
- Don't have to install git or buildbot onto any of the builders, just the main worker.
- Faster. Takes just a few seconds to boot up a VM.
- Can run any OS or weird hardware platform I want.
- Can extend this for auto packaging as well. Not happening immediately though, need to build up the builders first.

Work to do:
- [x] Add my RPI3 back in as a 32bit arm builder. (or dig out the rpi2 again?)
- [ ] Some small config cleanups/tweaks.
- [x] Switch from git poller to git event hook
- [ ] Add a bunch more builders (see below)
- [x] Ensure at least some builders are running `--enable-tls`
- [x] Ensure as many builders as possbile are running `--enable-sasl`
- [ ] Have most linux builders `--enable-seccomp`
- [ ] Perhaps a secondary fast test to ensure `--disable-extstore` (and all other optionals disabled) still works?
- [ ] Add specialized valgrind builder
- [ ] Add specialized ASAN builder?
- [ ] Add specialized debian testing builder (fully updated? pull from nightly build?)
- [ ] Add specialized big endian chroot builder (qemu-user since full qemu on mips is ungodly slow)
- [ ] Periodic scheduler to run some of the builds 4x a day to help sniff out flaky tests.
- [ ] Add ability to kick full builds for PR's

Builders I want off the top of my head:
centos8, debian 9 (8?), ubuntu 16/18/20 (fast is already 20)
freebsd (latest), openbsd (latest). Will add more builders as stable versions come out in the future and keep the old ones. Add older builders if someone opens a bug report.
Any others will be on request.

If someone has a special platform builder (like hppa or something) they can add a buildbot worker and connect to our master.

**Pull Requests**
For security reasons I don't think it's plausible to automatically run tests for arbitrary PR's, but I want to make it easy for me (or other trusted project contributors) to kick it off after a quick code review.
At the end it should post a comment/status update or just use the Changes API.
I think this isn't too hard but is a little time consuming to set up, so I'm going to do this part later I think.

I'll convert this to a wiki page once we're a bit further along.

**Comment by martin-g** [comment]
I vote for ARM64!
1) RPi4 ?!
2) if you prefer a dedicated free VM with your preferred Linux distro & version just let me know!
3) ...

**Comment by dormando** [comment]
if I can have root on the VM and it won't go away for a while (years) I wouldn't mind. I'm personally prioritizing a 32bit ARM because I've had some failures that were on that specific platform (it's missing some odd atomic operations).

latest debian is best.

**Comment by dormando** [comment]
(I don't yet have any rpi4's. the rpi3 will do 64bit but then etc.)

**Comment by dormando** [comment]
Heh. this already bitrotted! Then I fixed it again!

I never went back to add all the dreamy ASAN/valgrind/etc things here. that all sounds nice.
