### ISSUE TITLE
t/ssl_verify_modes.t fails when tests are run in parallel 

### ISSUE THREAD

**Issue by martin-g** [memcached/memcached#666]
As suggested at https://github.com/memcached/memcached/pull/653#issuecomment-622555648 I've tried `PARALLEL=...` on the VMs I use for testing Memcached.

```
===(   81975;131  18088/?  24/?   28/130  4/?  1/? )====================
#   Failed test 'client cert is verified'
#   at t/ssl_verify_modes.t line 20.
#          got: undef
#     expected: '1'
# Looks like you failed 1 test of 1.
t/ssl_verify_modes.t ........ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
```

On the ARM4 VM it fails for parallelism>4.
On the x86_64 VM it fails for parallelism>3

**Comment by dormando** [comment]
fwiw I only use parallel for non-tls... which should be obvious because it doesn't work otherwise :) if you set parallel for normal tests, it runs a few basic TLS tests sequentially then does the rest in parallel.

**Comment by martin-g** [comment]
OK. I see!
Closing ...

**Comment by jefyt** [comment]
#670 PR fixed this issue.

**Comment by martin-g** [comment]
Thanks for letting me know!
I just confirmed that all tests pass with PARALLEL=5 now!
Awesome!

**Comment by dormando** [comment]
I thought the parallel breakage was at least partly to do with `t/ssl_cert_refresh.t`, which actually overwrites/shuffles the test certs around. So if another test runs at the same time it might fail to validate.

That test should probably be fixed to copy into temp files and then swap those around first.
