### ISSUE TITLE
Race condition in ssl_read function on signal handling

### ISSUE THREAD

**Issue by TomasKorbar** [memcached/memcached#669]
**Describe the bug**
Hi,
there is a race condition in ssl_read function from tls.c.
Unfortunately when tls support has been introduced, new race condition on signal handling has been introduced with it.
I found this after i managed to set up your testsuite on RHEL, because there is a system called ABRT which tracks crashes.
In your testsuite there are tests which check signal handling. We noticed that sometimes abrt catches sigsegv crash of memcached-debug executable.
I've investigated this and found out that openssl library registers atexit function which destroys rand_meth_lock before exit function is called. atexit functions are called before threads are killed. This causes that when signal handler calls exit and thread just called SSL_read from tls.c:35, rand_meth_lock is destroyed and after that memcacheds thread will sometimes manage to lock it before it is killed which obviously results in segfault.

The offending part of code is in openssl crypto/rand/rand_lib.c in RAND_get_rand_method function (CRYPTO_THREAD_write_lock) call.

[backtrace.txt](https://github.com/memcached/memcached/files/4579313/backtrace.txt)

**To Reproduce**
Run memcacheds signal handling tests with enabled tls support on machine which has cpu with more than 4 threads (the more the better). The problem does not occur every time so you will have to maybe run it multiple times. If you have enabled core dumping then you should get some core dumps (on redhat systems coredumpctl can verify).

**System Information**
 - OS/Distro: RHEL
 - Version of OS/distro: 8
 - Version of memcached: 1.5.16
 - Version of openssl: 1.1.1c
 - Hardware detail: i used CPU with 16 cores 32 threads

**Comment by TomasKorbar** [comment]
I posted pull request with changes that managed to fix this bug in my testing environment.

**Comment by dormando** [comment]
Neat, thanks! Most people run with the default `-t 4` - did you have to change the number of worker threads for the test or just more cores in the system seemed to help?

**Comment by TomasKorbar** [comment]
More cores seemed to help. Now i realize that with -t bigger than 4 this could happen even more often.

**Comment by dormando** [comment]
Out in 1.6.6
