### ISSUE TITLE
"Out of memory during read" raised when max memory usage (-m) reach

### ISSUE THREAD

**Issue by handlespeed** [memcached/memcached#672]
**Describe the bug**
When memory usage almost reach to value of (-m), if there are coming **concurrent** set request (value size == 4MB), memcached server will send error "Out of memory during read". 
(I have set -I 5M for that 4MB big value data). 
If big set request comes sequentially, there will be no error.

**To Reproduce**
100% reproduce by description as above.

**System Information**
Official memcached docker image: memcached:latest (1 instance)
docker for windows or azure AKS, both can reproduce this error.

I just configure 2 argument for sending big 'set' value data: 
1. -I 5M, 
2. -m 1024 (actually, any valid data here will produce this error)

Is there any other argument I should adjust for this big data case? Thanks.

**Comment by dormando** [comment]
Hey,

First; I don't know what specific version that is. We don't supply a docker image directly, or azure anything. `stats` output always helps.

Many parallel large item uploads are an edge case for large items. The workaround is to add more memory, more or less. For the specifics:

- When an item is being written to, its memory is "locked" in place and cannot be evicted or moved.
- When memory is mostly full, the amount of RAM will be assigned spread across the different slab classes (100b, 1k, 100k, 512k, etc).
- Large items work by stitching chunks together; a 4MB item is one small header (~150b or so) and 8 512k chunks.
- If the 512k slab class doesn't have enough RAM in it to satisfy all of these uploads at the same time, they will fail with the error you see.
- It also allocates the chunk memory as it reads the item from the network. 

I haven't revisited this recently so not sure if there are better options now. You can modify the slab page memory mover algorithm (scripts/memcached-automove) to keep more RAM in the high slab class or add RAM to the system until you have enough available for all of the uploads.

I'll leave this issue open as a reminder to revisit when possible.

**Comment by handlespeed** [comment]
@dormando Thanks for reply. I just found seems this error occurs even memcached is restarted, and first 10 concurrent big (4MB) data are sent to memcached.

**Comment by dormando** [comment]
I'll double check but it will work so long as there's memory. attach output of `stats` and `stats slabs` from one run?

**Comment by handlespeed** [comment]
I can only 'stats' it by my code running in k8s pod. Is there any other easier way to do that?

**Comment by dormando** [comment]
Telnet to an instance and type `stats` and `stats slabs`. sorry, can't make it much easier than that :)

**Comment by handlespeed** [comment]
I can stats to my local memcached container by telnet but cannot connect to the remote pod, maybe network issue. 
However, here is stats log from local memcached when that oom log occurs:

stats
STAT pid 6
STAT uptime 24
STAT time 1588916933
STAT version 1.6.5
STAT libevent 2.1.8-stable
STAT pointer_size 64
STAT rusage_user 0.016730
STAT rusage_system 0.056354
STAT max_connections 1024
STAT curr_connections 2
STAT total_connections 13
STAT rejected_connections 0
STAT connection_structures 13
STAT response_obj_bytes 11680
STAT response_obj_total 10
STAT response_obj_free 9
STAT response_obj_oom 0
STAT read_buf_bytes 163840
STAT read_buf_bytes_free 147456
STAT read_buf_oom 0
STAT reserved_fds 20
STAT cmd_get 0
STAT cmd_set 15
STAT cmd_flush 0
STAT cmd_touch 0
STAT cmd_meta 0
STAT get_hits 0
STAT get_misses 0
STAT get_expired 0
STAT get_flushed 0
STAT delete_misses 0
STAT delete_hits 0
STAT incr_misses 0
STAT incr_hits 0
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT touch_hits 0
STAT touch_misses 0
STAT auth_cmds 0
STAT auth_errors 0
STAT bytes_read 100002441
STAT bytes_written 2934
STAT limit_maxbytes 20971520
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT time_in_listen_disabled_us 0
STAT threads 4
STAT conn_yields 0
STAT hash_power_level 16
STAT hash_bytes 524288
STAT hash_is_expanding 0
STAT slab_reassign_rescues 0
STAT slab_reassign_chunk_rescues 1
STAT slab_reassign_evictions_nomem 0
STAT slab_reassign_inline_reclaim 0
STAT slab_reassign_busy_items 0
STAT slab_reassign_busy_deletes 0
STAT slab_reassign_running 0
STAT slabs_moved 1
STAT lru_crawler_running 0
STAT lru_crawler_starts 255
STAT lru_maintainer_juggles 82
STAT malloc_fails 0
STAT log_worker_dropped 0
STAT log_worker_written 0
STAT log_watcher_skipped 0
STAT log_watcher_sent 0
STAT bytes 8000256
STAT curr_items 2
STAT total_items 15
STAT slab_global_page_pool 1
STAT expired_unfetched 0
STAT evicted_unfetched 13
STAT evicted_active 0
STAT evictions 13
STAT reclaimed 0
STAT crawler_reclaimed 0
STAT crawler_items_checked 0
STAT lrutail_reflocked 0
STAT moves_to_cold 15
STAT moves_to_warm 0
STAT moves_within_lru 0
STAT direct_reclaims 126
STAT lru_bumps_dropped 0
END

stats slabs
STAT 4:chunk_size 192
STAT 4:chunks_per_page 5461
STAT 4:total_pages 1
STAT 4:total_chunks 5461
STAT 4:used_chunks 2
STAT 4:free_chunks 5459
STAT 4:free_chunks_end 0
STAT 4:get_hits 0
STAT 4:cmd_set 0
STAT 4:delete_hits 0
STAT 4:incr_hits 0
STAT 4:decr_hits 0
STAT 4:cas_hits 0
STAT 4:cas_badval 0
STAT 4:touch_hits 0
STAT 38:chunk_size 394840
STAT 38:chunks_per_page 2
STAT 38:total_pages 1
STAT 38:total_chunks 2
STAT 38:used_chunks 2
STAT 38:free_chunks 0
STAT 38:free_chunks_end 0
STAT 38:get_hits 0
STAT 38:cmd_set 0
STAT 38:delete_hits 0
STAT 38:incr_hits 0
STAT 38:decr_hits 0
STAT 38:cas_hits 0
STAT 38:cas_badval 0
STAT 38:touch_hits 0
STAT 39:chunk_size 524288
STAT 39:chunks_per_page 2
STAT 39:total_pages 17
STAT 39:total_chunks 34
STAT 39:used_chunks 14
STAT 39:free_chunks 20
STAT 39:free_chunks_end 0
STAT 39:get_hits 0
STAT 39:cmd_set 15
STAT 39:delete_hits 0
STAT 39:incr_hits 0
STAT 39:decr_hits 0
STAT 39:cas_hits 0
STAT 39:cas_badval 0
STAT 39:touch_hits 0
STAT active_slabs 3
STAT total_malloced 20971520
END

**Comment by handlespeed** [comment]
@dormando Please help specify if our following case is good to use memcached:
We need to send 4 MB value size per-Request (set type and get type) to cache, there are 240 concurrent connection (so at most there may be 240 Requests coming at same time).

Should we use memcached as our cache for this case?

**Comment by dormando** [comment]
Is there a reason why you set the memory limit to 20 megabytes? I thought you were using `-m 1024`

**Comment by handlespeed** [comment]
Because I would make this error occur soon. It is little hard to repro issue in my local container if use -m 1024, but it can.

**Comment by dormando** [comment]
I completely believe you and it's well known that it happens if you don't give it enough memory :) Some RAM is reserved for slab classes, so setting very low values (less than 64 megs) won't work as you expect.

It is possible to make it not happen for larger amounts of RAM, but you have to modify the memory mover algorithm as I mentioned perviously. If you're not up for this I would recommend you either split these values into smaller chunks (< half a megabyte) or use something other than memcached.

**Comment by dormando** [comment]
Were you able to solve your problem?

**Comment by handlespeed** [comment]
Hi Dormando, no, still found that error log even in big RAM (8G ram). We were estimating cache solution for our case, we have to keep big size value so maybe need to find other proper solution for us, thanks for help.

**Comment by dormando** [comment]
Ok, good luck. I'll keep this in mind next time I revisit the large item code.
