### ISSUE TITLE
mamcache upgrade from 3.0.3 to 3.1.4

### ISSUE THREAD

**Issue by rampratap2020** [memcached/memcached#673]
hi team ,

 i am planing to uppgrade mamcache from 3.0.3 to 3.1.4 version on RHL 6.
can you please suggest how to upgrade rom 3.0.3 to 3.1.4 version on RHL 6.

thanks,
Ram pratap

**Comment by dormando** [comment]
That sounds like the php version. You should ask a PHP help forum for support: this is for bugs related to the server.
