### ISSUE TITLE
Data race in items.c and memcached.c

### ISSUE THREAD

**Issue by JZuming** [memcached/memcached#676]
Dear memcached developers:

I used my fuzz-testing tool, connzer, to detect data race in memcached . Here is a data race found by connzer. I wish you can help me confirm the race, thanks!!

The following is the race report.

## Race report ##
**OS:** Linux 5.4, Ubuntu 16.04
**Memcached version:** 1.5.20
**Execute command:** `./memcached -p 11211 -d`, `memcslap --server=127.0.0.1:11211 --concurrency=2`, `pkill memcached`

### Thread 1
**Race variable:** `current_time`
**Access:** `cold_age = current_time - tails[slabs_clsid|COLD_LRU]->time;`
**Line number:** items.c, 1401
**Call stack:**
1. `lru_maintainer_juggle`
2. `lru_maintainer_thread`

**Lock:** None

### Thread 2
**Race variable:** `current_time`
**Access:** `current_time = (rel_time_t) (ts.tv_sec - monotonic_start);`
**Line number:** memcached.c; 7535
**Call stack:**
1. `clock_handler`
2. `main`

**Lock:** None

My fuzzer finds that these 2 accesses can be executed concurrently, and they are not protected by any lock, so my fuzzer report this race.

## Note ##

To prove the data race is real, I set breakpoints before these two accesses when they are running in the call stack described above. I find that the breakpoints can be activated simultaneously, and the addresses of race variables are same. I think these result can prove that the race is real.

**Comment by dormando** [comment]
Why is that a race? current_time is a volatile global variable that's updated in a single place. It's a clock...

**Comment by dormando** [comment]
Also your line numbers don't line up with 1.6.5

**Comment by dormando** [comment]
Actually the more I look at this the weirder it is. You're reporting two unrelated uses of current_time but not the code that updates current_time. I think your detector is bunk :(

**Comment by JZuming** [comment]
> Also your line numbers don't line up with 1.6.5 - did you modify the code or is this a different version?

Ohhhh, sorry, I make a mistake.  The testing version is 1.5.20. And the access in thread 2 is modified. It should be `current_time = (rel_time_t) (ts.tv_sec - monotonic_start);`.

**Comment by JZuming** [comment]
> Actually the more I look at this the weirder it is. You're reporting two unrelated uses of current_time but not the code that updates current_time. I think your detector is bunk :(

Sorry. I made a mistake when I was writting the report.

**Comment by JZuming** [comment]
> Why is that a race? current_time is a volatile global variable that's updated in a single place. It's a clock...

Ok, It may be a benign race. But it is actually a race, because these two instructions access same variable concurrently, and one of them is write operation.

**Comment by dormando** [comment]
Cool, thanks for updating the report.

It's still not a data race though :) `current_time` is used all over the codebase as a cached clock variable, marked as volatile. It's always been this way and is very central to how the code works.

**Comment by JZuming** [comment]
> Cool, thanks for updating the report.
> 
> It's still not a data race though :) `current_time` is used all over the codebase as a cached clock variable, marked as volatile. It's always been this way and is very central to how the code works.

Thanks for your response, and I learn something interesting about data race :)

**Comment by dormando** [comment]
Look carefully at how it's used: updated centrally from a single place. marked volatile to avoid compiler optimizations. every read is a direct comparison and it's a 32bit variable. In all places where it is read, having the exact value at that time isn't necessary. If it were we would use atomic load/stores.

Further, it's only updated once per second and only affects item expiration. At most it'll stray from reality by milliseconds.

**Comment by JZuming** [comment]
> Look carefully at how it's used: updated centrally from a single place. marked volatile to avoid compiler optimizations. every read is a direct comparison and it's a 32bit variable. In all places where it is read, having the exact value at that time isn't necessary. If it were we would use atomic load/stores.
> 
> Further, it's only updated once per second and only affects item expiration. At most it'll stray from reality by milliseconds.

Yes, you are right. The impact seems very small.

**Comment by JZuming** [comment]
After referring to some materials about `volatile` in C programs, I still think it is a data race though it has little impact. In my opinion, the key word `volatile` only tell the compiler that it can't optimize memory reads from the variable. The `volatile` does not affect threading behavior. So it cannot prevent data race.

I don't mean the way you use `current_time` is wrong. On the contrary, I am convinced that It is right. But I think it is a data race, a benign data race which has not impact (or little impact).

**Comment by dormando** [comment]
No, not quite right. May I close out this issue? There's no fault. I'm a bit strapped on time so I don't want to do a lot of back and forth to explain this more.

Sorry, good luck with your school project.

**Comment by JZuming** [comment]
> No, not quite right. May I close out this issue? 

Yes. Thank you very much for spending such time responding me.
