### ISSUE TITLE
Data race in memcached.c

### ISSUE THREAD

**Issue by JZuming** [memcached/memcached#678]
Dear memcached developers:

I used my fuzz-testing tool, connzer, to detect data race in memcached . Here is a data race found by connzer. I wish you can help me confirm the race, thanks!!

The following is the race report.

## Race report ##
**OS:** Linux 5.4, Ubuntu 16.04
**Memcached version:** 1.5.20
**Execute command:** `./memcached -p 11211 -d`, `memcslap --server=127.0.0.1:11211 --concurrency=2`, `pkill memcached`

### Thread 1
**Race variable:** `current_time`
**Access:** `c->last_cmd_time = current_time;`
**Line number:** memcached.c; 6334
**Call stack:**
1. `try_read_command_ascii`
2. `drive_machine`
3. `event_handler`
4. `worker_libevent`

**Lock:** None

### Thread 2
**Race variable:** `current_time`
**Access:** `current_time = (rel_time_t) (ts.tv_sec - monotonic_start);`
**Line number:** memcached.c; 7535
**Call stack:**
1. `clock_handler`
2. `main`

**Lock:** None

My fuzzer finds that these 2 accesses can be executed concurrently, and they are not protected by any lock, so my fuzzer report this race.

## Note ##

To prove the data race is real, I set breakpoints before these two accesses when they are running in the call stack described above. I find that the breakpoints can be activated simultaneously, and the addresses of race variables are same. I think these result can prove that the race is real.

**Comment by dormando** [comment]
Your fuzzer is detecting a clock variable. this isn't a race.

**Comment by JZuming** [comment]
> Your fuzzer is detecting a clock variable. this isn't a race.

Ok, It may be a benign race. But it is actually a race, because these two instructions access same variable concurrently, and one of them is write operation.

My report had some mistake, and I have modified it.

**Comment by dormando** [comment]
It's not actually a race; the variable is a volatile variable that's only ever written to in one place. This is just how the internal clock works.
