### ISSUE TITLE
[support] data persistency with memcached-util and systemd

### ISSUE THREAD

**Issue by atesin** [memcached/memcached#701]
hi... i want to add basic data persistency to my memcached server between restarts, but i had found NO WAY to enable it, i have centos8 x86_64 with systemd .. what i had tried in systemd memcached unit file is:

ExecStartPost=ncat localhost 11211 < /some/path/memcached-dump.bak
ExecStopPre=memcached-util localhost dump > /some/path/memcached-dump.bak

- seems ExecStopPre is not fully implemented or compatible
- unit file does not have 'ExecStop=' directive either, so its use and behavior with above additions is uncertain
- 'memcached' user has no console (/sbin/nologin in /etc/passwd) so i cant login/su to do tests
- systemd dont support redirection chars (>, >>, <, |) so it fails
- with "sh -c 'my compound command' it fails with file permission error, i had tried with every directory and file permissions
- i tried replacing some 'Exec' command with 'mount', 'ls -l /' etc, and view logs to view environment, permissions, etc and try

every thing i'd tried didn't worked, i understand the security is important, but how can make it work in the 'right' way?, please help me anyone .. will be a nice addition to memcacied and i am sure more people will want to do this ...

i think data persistence is a strong feature that drives many users to choose redis over memcached, would be fantastic if memcached would have persistence at lest beetween service restarts, will make memcached even more useful, and will make many users to rethink their choice

**Comment by dormando** [comment]
Hey,

I'm not completely clear on what you're doing here (using -util to dump data then reload?)

There's an official feature for this, if you can upgrade to the latest version:
https://github.com/memcached/memcached/wiki/WarmRestart

A discussion on how to use it with systemd was on the mailing list recently:
https://groups.google.com/g/memcached/c/DPbsosU1HFY

**Comment by atesin** [comment]
thanks for your early response....
what i am doing:

- on stop:
  - dump memory data to a file
  - stop

- on start:
  - start
  - restore memory data from previous file

the official feature:
my distro (centos8 x86_64) hsa a pretty old memcached package (1.5.9) and i don't dare to compile another myself, i always prefer to install *official* pachages for ease, to avoid compatibility problems (libs, dependencies, etc) and to have a clean system... anyway, i dont have a non volatile ram

my question was really pointed on how to *unlock* memcached systemd unit file to be able of run programs and files (any) in pre/post start/stop process, that could be useful for example: to auto reconfigure firewall rules, to mount/unmount memcached installed partition, bring up/down nic/vpn memcached listens, or for example use memcached-tool to basic backup/restore ram data

**Comment by dormando** [comment]
Sorry, I'm not familiar enough with systemd to help you out here.

**Comment by dormando** [comment]
Also for what it's worth; the restartable mode in newer versions doesn't use nvram or flash. it uses a tmpfs mount to support restarts without reboots, but can _also_ use nvram directly if available.

**Comment by atesin** [comment]
hi dormando ... isn't tmpfs volatile??  (TMPfs?) ... so data won't survive on server restart

to me it looks more like a systemd file permission/privileges error , funny is with systemd unit-file i cant read/write any file

**Comment by dormando** [comment]
Yes, tmpfs is volatile. If you look at the google groups thread I initially linked, the user had modified his systemd script to copy the contents of the tmpfs to disk and restore it on stop/start.

**Comment by atesin** [comment]
in that google groups page you wrote...,

> This will _not_ survive reboots. This will survive software upgrades,
> which ubuntu isn't going to do anyway :)
> 
> To survive reboots you need a few more steps:
> 
> 1) once memcached has stopped, copy the files created in
> /tmpfs_mount_memcached/ to an actual harddrive somewhere. . . . . ( ### see note below)
> 2) reboot.
> 3) copy the datafiles back in place. . . . . . (### see note below)
> 4) start memcached again.

(###) note below: that's the problem... i think to accomplish that (file operations along service) you anyway need to set ExecStartPost and ExecStopPre in systemd unit file :/

**Comment by dormando** [comment]
Can you please read the full thread?

https://groups.google.com/g/memcached/c/DPbsosU1HFY/m/-_LKAUqNAQAJ - the guy got it to work. With systemd. He says how.

**Comment by dormando** [comment]
and to reiterate, I don't know systemd. I'm here to answer questions about memcached; you might have better luck in a centos forum or chat if you're trying to solve a systemd problem.

**Comment by atesin** [comment]
I HAD FINALLY DONE!!!

yes i did read the thread now .. nice approach, mine is a little different, sadly even.o didn't describe the specific steps he did... in addition...
- my memcached build that comes with the official distro package (centos8 x86-64) doesnt seem to come with '-e' option
- i dont know if even.o had peoblems with file permissions and how he resolved them, as i had my solution points maiinly to this
- i dont know if '-o tmpfs' feature is better than mine in the sense of performance and data reliability, i tend to think that tmpfs could be slower than bare ram because of filesystem data strctures, but more reliable because dump/set lost a lot of meta info like access times, etc

anyway here is my solution ...  you could add this to your wiki together with even.o's one , for people like us that couldnt access the cooler features latests memcached versions have:

after a lot of tests and head heating, i concluded the most reliable directory to store data has to be some subdir of '/var', like '/var/lib/*' used by many other services, so this is what i did:


### plain version

mkdir /var/lib/memcached
systemctl edit memcached

```
# basic data persistence by atesin (@github), be aware of requisites

[Service]
ExecStartPost=sh -c 'ncat -C localhost 11211 < /var/lib/memcached/service-data.bak'
ExecStop=+sh -c 'memcached-tool localhost dump > /var/lib/memcached/service-data.bak'
```

- if memcached is running
systemctl restart memcached
- if memcached is NOT running
touch /var/lib/memcached/service-data.bak
systemctl start memcached


### compressed version

mkdir /var/lib/memcached
systemctl edit memcached

```
# basic data persistence by atesin (@github), be aware of requisites

[Service]
ExecStartPost=sh -c 'gunzip -c /var/lib/memcached/service-data.bak.gz | ncat -C localhost 11211'
ExecStop=+sh -c 'memcached-tool localhost dump | gzip > /var/lib/memcached/service-data.bak.gz'
```

- if memcached is running
systemctl restart memcached
- if memcached is NOT running
echo | gzip > /var/lib/memcached/service-data.bak.gz
systemctl start memcached


findings:

- i choose the folder based on service file permissions i debugged
- there is no 'ExecStop' present in unit-file, so by default systemd kills the service with a signal (configurable)
- 'ExecStopPre' is not aplicable to services, just sockets :(, but because of unit type luckly if i add a custom 'ExecStop' directive the signal is still being sent
- there are permission issues in writing files, but can be overriden by prefixing command with '+' https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStart=
- i also recommend to schedule a regular data backup just in case, this is what i did:

crontab -e

```
# plain version
0 4 * * * memcached-tool localhost dump > /var/lib/memcached/daily-data.bak'

# compresed version
0 4 * * * memcached-tool localhost dump | gzip > /var/lib/memcached/daily-data.bak.gz
```

**Comment by dormando** [comment]
To any future readers: mmap'ing a file in a tmpfs mount is exactly the same performance as a normal instance. Shared memory in linux is implemented by mmap'ing hidden files in tmpfs mounts. The "extra data structures" only exist when managing files or handling POSIX operations.

Also fwiw, if your memcahed-tool (and memcached) aren't new enough to use the "metadump" feature (just grep for metadump in the file), you will not be fetching all of your keys from the instance. The older version uses a debug command (cachedump) that was used to sample 'up to a megabyte worth' of key headers per slab class. Instances of any decent size will lose data.

Glad you got this worked out. May I close out the issue?

**Comment by atesin** [comment]
yes i saw my memcached-tool source (i realized is a perl script) and noticed it get keys through 'lru_crawler metadump all' command, seems to be more efficient and reliable than old 'cachedump'

to put it all together, i think there is enough info for a help page on data persistence through many memcached versions, for people that hasn't the latest one (the most i guess) i a way of scaling down, i.e.:

- v1.5.18: warm restart (requires '-e' option), additional file backup on service changes (even.o solution)
- v1.5.4: extstore (requires '-o ext_path' option)
- v1.4.31?: memcached-tool + backup on service changes (requires 'lru_crawler metadump' command)  (my solution)
- version?: some custom script that uses cachedump or meta commands? (what version?)
- other creative solution? (post it)

as i think there is little more to add here i will believe you agree i close the thread....  thanks for your time :)
