### ISSUE TITLE
Build fail with new glibc 2.32

### ISSUE THREAD

**Issue by micron10** [memcached/memcached#707]
Hi
after upgrade to libc 2.32, memcached not build with this error:

memcached.c: In function 'main':
memcached.c:9999:9: error: 'sigignore' is deprecated: Use the signal function instead [-Werror=deprecated-declarations]
 9999 |         if (sigignore(SIGHUP) == -1) {
      |         ^~
In file included from memcached.h:22,
                 from memcached.c:16:
/ct/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sysroot/usr/include/signal.h:349:12: note: declared here
  349 | extern int sigignore (int __sig) __THROW
      |            ^~~~~~~~~
memcached.c:10149:5: error: 'sigignore' is deprecated: Use the signal function instead [-Werror=deprecated-declarations]
10149 |     if (sigignore(SIGPIPE) == -1) {
      |     ^~
In file included from memcached.h:22,
                 from memcached.c:16:
/ct/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sysroot/usr/include/signal.h:349:12: note: declared here
  349 | extern int sigignore (int __sig) __THROW
      |            ^~~~~~~~~
memcached.c: In function 'main':
memcached.c:9999:9: error: 'sigignore' is deprecated: Use the signal function instead [-Werror=deprecated-declarations]
 9999 |         if (sigignore(SIGHUP) == -1) {
      |         ^~
In file included from memcached.h:22,
                 from memcached.c:16:
/ct/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sysroot/usr/include/signal.h:349:12: note: declared here
  349 | extern int sigignore (int __sig) __THROW
      |            ^~~~~~~~~
memcached.c:10149:5: error: 'sigignore' is deprecated: Use the signal function instead [-Werror=deprecated-declarations]
10149 |     if (sigignore(SIGPIPE) == -1) {
      |     ^~
In file included from memcached.h:22,
                 from memcached.c:16:
/ct/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sysroot/usr/include/signal.h:349:12: note: declared here
  349 | extern int sigignore (int __sig) __THROW
      |            ^~~~~~~~~
cc1: all warnings being treated as errors
cc1: all warnings being treated as errors

**Comment by dormando** [comment]
Hey,

Sorry! The fix for this is queued up for the next release already. I'm running a little late on that.

**Comment by micron10** [comment]
oki Thanks
i will fix manual for now

Best Regards

**Comment by dormando** [comment]
You can build from the `next` branch if you want, too.

**Comment by dormando** [comment]
Released in 1.6.7!
