### ISSUE TITLE
Query about License

### ISSUE THREAD

**Issue by Evelyn-9** [memcached/memcached#713]
Hi,
Sorry to bother you. 

I am Evelyn from Websoft9 company. We have read the license file, but we have some questions regarding integration and redistribution of Memcached software. We’d like to check with you to avoid improper use.

It would be great if we could have a communication on email and we could share more details.
Thanks a lot!

Evelyn
evelyn.zhu@websoft9.com

**Comment by dormando** [comment]
Hey,

The software itself is BSD licensed. If you want to know how to reuse or distribute BSD licensed software you will have to consult with other websites or lawyers as I'm not a legal expert :) Generally it is very easy as it is not a restrictive license.

What is restricted are usage of the memcached logo's and artwork. You need specific permission to use them.

Feel free to e-mail me if you still need to discuss: dormando [at] rydia dot nety.

**Comment by Evelyn-9** [comment]
Hi Dormando,

Thanks for your reply. I'd sent an email for discussion about the "Memcached" word mark use.
We'd would appreciate it if you could, by any chance, give some help.

**Comment by dormando** [comment]
We discussed this over e-mail. Closing.
