### ISSUE TITLE
Config file seems not recognized in osx

### ISSUE THREAD

**Issue by simongcc** [memcached/memcached#715]
I am using memcached 1.6.6 installed through brew in OSX 10.14.
Since OSX environment is a little bit different which use launch plist to startup if installing with brew.
I have tried to put `logfile` statement in memcached.conf and put it /etc or /usr/local/etc
Both seems not to work. 
I have also tried to assume it is working in the plist file but it doesn't seems to work either.

How to set the logfile parameter for memcached in OSX?

Many thanks.

**Comment by dormando** [comment]
I'm not very familiar with OS X (don't have a machine to run it, even). You might have better luck asking on the mailing list where there's a wider audience.
