### ISSUE TITLE
Add an option to change default group ownership of the '/var/run/memcached' directory and of the '/var/run/memcached/memcached.sock' file (Feature request)

### ISSUE THREAD

**Issue by Fred-Zweig** [memcached/memcached#718]
Please consider adding an option in the `memcached.conf` configuration file, to allow us to change the default group ownership of the `/var/run/memcached` directory and of the `/var/run/memcached/memcached.sock` file created by Memcached when configured to use Unix sockets. I know that for security reasons, the default ownership which is `memcache:memcache` is considered the best, but there are users that use Memcached for WordPress object caching, and the best method in this case is to configure Memcached to use Unix sockets instead of TCP connections on port 11211. It works much faster with Unix sockets. Yet, in this case, the web server user, `www-data` has to be the group owner of the `/var/run/memcached` directory and has to have read and write access to the `/var/run/memcached/memcached.sock` file, otherwise caching won't work. So, please consider adding an option in the `memcached.conf` file to allow administrators to change the default group ownership for the mentioned directory and socket file. Thank you!

For the moment I manually changed ownership and permissions like this:
```
chown -R memcache:www-data /var/run/memcached
chmod 2755 /var/run/memcached
```
Also, in the `/etc/memcached.conf` file I added the `-a 770` option to make Memcached create the socket file with 770 permissions. I also had to create a script to change the ownership and permissions after startup, because after reboot they were changed back to default.

**Comment by dormando** [comment]
Hey,

memcached itself can't do much with this, since it's creating the file after it drops root privileges, slightly dangerous otherwise.
```-s, --unix-socket=<file>  UNIX socket to listen on (disables network support)
-a, --unix-mask=<mask>    access mask for UNIX socket, in octal (default: 700)
```

you could set the mask to let it be world-writeable rather than www-data. not great for a shared service but, probably not shared in this instance?

or you can add memcache to www-data's group list?

**Comment by Fred-Zweig** [comment]
Thank you for your reply. Ok, if Memcached is creating the socket file after dropping root privileges it means it can't be configured to create the file with `www-data` as the group owner. I'll keep using the method that I described above to set the right ownership for the `/var/run/memcached` directory and for the `/var/run/memcached/memcached.sock` file.

Thank you for developing and maintainig Memcached. Keep up the good work.

It's a pity that many people use Redis for object caching thinking that if Redis is newer, it means it's better. Unfortunately, in the tech world like anywhere else people confuse 'newer' with 'better'. In my experience Memcached is much better than Redis because it's more lightweight, faster and multithreaded.
