### ISSUE TITLE
Crash due to an atomicity violation bug in item_stats_sizes_add()

### ISSUE THREAD

**Issue by uditagarwal97** [memcached/memcached#728]
**Describe the bug**
There is a possibility of a null pointer dereference at line number 913 in the method: 'item_stats_sizes_add()'in items.c. This is due to the atomicity violation.

Consider the following scenario: 
Worker thread, W1, is in item_stats_sizes_add() method and right before dereferencing the 'stats_sizes_hist' field at line 913, items.c, another worker thread, W2, sets stats_sizes_hist to NULL by executing item_stats_sizes_disable() method at line 901, items.c. This can cause a NULL pointer dereference. 

**To Reproduce**
Consider the following exemplary test case:

my $server = new_memcached("-m 2 -t 4 -o track_sizes"); 
my $sock = $server->sock; 
my $sock1 = $server->new_sock; 
my $i = 0; 

while($i < 10000){
      $i ++; 
      print $sock "set foo 0 0 6\r\nfooval\r\n"; 
      print $sock1 "stats sizes_disable\r\n"; 
      print $sock1 "stats sizes_enable\r\n"; 
} 
      $server->stop; 

I'm able to reproduce the bug with the above test case. In order to increase the chances of triggering the buggy program path, you can put a call to sleep(1) after line 912, items.c and a call to sleep(5) after line 904, items.c. Also, try compiling Memcached with '-fsanitize=address' option to get the detailed stack trace of the segmentation fault. 

**System Information**
 - OS/Distro: Ubuntu 18
 - Memcached Commit id: ad8dfd265523e0, Branch: Master
 - Hardware architecure: x86_64

**Remarks**
This behavior was detected using a systematic concurrency testing tool being developed at Microsoft Research.

Thanks,
Udit Agarwal

**Comment by dormando** [comment]
Thanks!

I reviewed this before it got posted; it's an unlikely crash as you have to keep turning the stats sizes feature on/off. it's only used for tuning and people don't typically turn it on/off constantly. so the impact is relatively minor.

fixing it is harder; adding a global lock protecting the pointer could crater performance. code would also need significant reworking to allow broadcast notify to update the pointer. will have to give it a think. Worst case I remove the online disable feature. :(
