### ISSUE TITLE
Memcache QQ

### ISSUE THREAD

**Issue by Natarajan77** [memcached/memcached#730]
Hi, Can you please help to answer below points if they are available in Opensource or enterprise (GCP)? Thanks

    TLS
    ACL
    RBAC
    Data Storage Limiations
    Aggregation queries
    Max writes per second
    Max reads per second
    Read through
    Read - Write to MongoDB
    Read - Write to PostgreSQL
    Persistence to disk

**Comment by dormando** [comment]
please use the wiki in this repo and doc/protocol.txt inside the repository to learn about memcached. ask the mailing list if you have a specific question.
