### ISSUE TITLE
Can't make on CentOS 6.8 Error: implicit declaration of function ‘clock_handler’

### ISSUE THREAD

**Issue by aaalexby** [memcached/memcached#732]
./configure
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for icc in use... no
checking for clang in use... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether __SUNPRO_C is declared... no
checking for gcc option to accept ISO C99... -std=gnu99
checking sasl/sasl.h usability... yes
checking sasl/sasl.h presence... yes
checking for sasl/sasl.h... yes
checking for gcov... /usr/bin/gcov
checking for main in -lgcov... yes
checking size of void *... 8
checking for library containing clock_gettime... -lrt
checking for library containing socket... none required
checking for library containing gethostbyname... none required
checking for libevent directory... (system)
checking for library containing gethugepagesizes... no
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inttypes.h... (cached) yes
checking for sasl_callback_ft... no
checking for print macros for integers (C99 section 7.8.1)... yes
checking for an ANSI C-conforming const... yes
checking for socklen_t... yes
checking whether byte ordering is bigendian... no
checking for htonll... no
checking for library containing pthread_create... none required
checking for mlockall... yes
checking for getpagesizes... no
checking for sysconf... yes
checking for memcntl... no
checking for clock_gettime... yes
checking for preadv... yes
checking for pread... yes
checking for accept4... yes
checking for getopt_long... yes
checking for alignment... none
checking for GCC atomics... yes
checking for GCC 64bit atomics... yes
checking for setppriv... no
checking for pledge... no
checking for cap_enter... no
checking for xml2rfc... no
checking for xsltproc... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: executing depfiles commands

`
make
make  all-recursive
make[1]: Entering directory `/root/memcached-1.6.8'
Making all in doc
make[2]: Entering directory `/root/memcached-1.6.8/doc'
make  all-am
make[3]: Entering directory `/root/memcached-1.6.8/doc'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/root/memcached-1.6.8/doc'
make[2]: Leaving directory `/root/memcached-1.6.8/doc'
make[2]: Entering directory `/root/memcached-1.6.8'
gcc -std=gnu99 -DHAVE_CONFIG_H -I.  -DNDEBUG   -g -O2 -pthread -pthread -Wall -Werror -pedantic -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -fno-strict-aliasing -MT memcached-memcached.o -MD -MP -MF .deps/memcached-memcached.Tpo -c -o memcached-memcached.o `test -f 'memcached.c' || echo './'`memcached.c
cc1: warnings being treated as errors
memcached.c:99: error: type defaults to ‘int’ in declaration of ‘evutil_socket_t’
memcached.c:99: error: expected ‘;’, ‘,’ or ‘)’ before ‘fd’
memcached.c:163: error: type defaults to ‘int’ in declaration of ‘evutil_socket_t’
memcached.c:163: error: expected ‘;’, ‘,’ or ‘)’ before ‘fd’
memcached.c: In function ‘conn_worker_readd’:
memcached.c:526: error: ‘event_handler’ undeclared (first use in this function)
memcached.c:526: error: (Each undeclared identifier is reported only once
memcached.c:526: error: for each function it appears in.)
memcached.c: In function ‘conn_new’:
memcached.c:707: error: ‘event_handler’ undeclared (first use in this function)
memcached.c: In function ‘update_event’:
memcached.c:2704: error: ‘event_handler’ undeclared (first use in this function)
memcached.c: In function ‘do_accept_new_conns’:
memcached.c:2750: error: implicit declaration of function ‘maxconns_handler’
memcached.c: At top level:
memcached.c:3580: error: type defaults to ‘int’ in declaration of ‘evutil_socket_t’
memcached.c:3580: error: expected ‘;’, ‘,’ or ‘)’ before ‘fd’
memcached.c:4012: error: type defaults to ‘int’ in declaration of ‘evutil_socket_t’
memcached.c:4012: error: expected ‘;’, ‘,’ or ‘)’ before ‘fd’
memcached.c: In function ‘main’:
memcached.c:6286: error: implicit declaration of function ‘clock_handler’
make[2]: *** [memcached-memcached.o] Error 1
make[2]: Leaving directory `/root/memcached-1.6.8'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/memcached-1.6.8'
make: *** [all] Error 2
`

**Comment by dormando** [comment]
what version of libevent is on there? you need at least version 2. the fix for version detection is queued for the next release, sorry

**Comment by aaalexby** [comment]
Thanks for your answer! 

You are right. After `yum remove libevent-devel` and `yum install libevent2-devel` memcached successfully compiled and all tests passed.
