### ISSUE TITLE
Online command for graceful shutdown

### ISSUE THREAD

**Issue by LINKIWI** [memcached/memcached#739]
Currently, the `--enable-shutdown` flag enables the use of the `shutdown` command to raise a `SIGINT` to the process: https://github.com/memcached/memcached/blob/8335dd84ca85651115d518d7e3d963de9d82e22f/proto_text.c#L2353

I'm wondering if there is any interest in exposing another text command (maybe `shutdown graceful` or just `graceful`?) to instead trigger a graceful shutdown with `SIGUSR1`.

My use case is allowing application logic to control the memcached process lifecycle with warm restart enabled. I'm happy to submit a patch if there's interest in this functionality.

**Comment by dormando** [comment]
Yeah, sounds good. Still has to be not-by-default as shutdown already is, but I don't see a reason not to.

**Comment by dormando** [comment]
released in 1.6.9!
