### ISSUE TITLE
Invoking pthread_mutex_unlock() on an already unlocked mutex

### ISSUE THREAD

**Issue by uditagarwal97** [memcached/memcached#741]
Description of the bug 
---------------------- 

Commit id: 8335dd84ca856511, Branch: Master

This bug is due to misuse of pthread APIs where we unnecessarily invoke pthread_mutex_unlock() on 'lru_crawler_lock'[1] in lru_crawler_crawl() function. This bug will happen when we give the 'lru_crawler crawl #' command to MC with an invalid slab ID. This bug can have one of the following dangerous consequence:

(a) Undefined behavior - When the LRU crawler thread isn't working, i.e., when 'lru_crawler_lock' is already unlocked, calling pthread_mutex_unlock again will result in undefined behavior[3].<br>
(b) Deadlock - Consider the following sequence of events (similar to the deadlock bug in slab rebalancer during shutdown that I previously reported):<br>
               

1. LRU crawler thread is working, i.e., 'lru_crawler_lock' is locked.
2. Worker thread triggers this bug and unlocks 'lru_crawler_lock' mutex.
3. Another or same worker thread gives a shutdown command to MC, and the dispatcher thread now tries to shut down all background threads
4. While shutting down LRU crawler thread, dispatcher thread will take 'lru_crawler_lock' mutex and signals LRU crawler thread[2]... But the LRU Crawler thread isn't waiting on pthread_cond_wait(), so the signal will be missed.<br>

(c) Data races and atomicity violations - Consider the following sequence of events:<be>

 1.  Assoc maintainer thread wants to expand the hash table, and now it tries to pause all the threads
 2.  Assoc maintainer thread will first pause the LRU crawler thread by taking 'lru_crawler_lock' mutex.
 3.  Just after this, the worker thread triggers this bug and unlocks 'lru_crawler_lock' mutex.
 4.  Assoc maintainer thread will now pause all worker threads and continue in assoc_expand(void) function. LRU crawler can simultaneously try to remove any expired item and can race over global variables like 'primary_hashtable,' 'hashpower,' 'expanding,' etc.

Note that pthread's implementation allows unlocking a mutex that the caller thread doesn't own. This should ideally result in undefined behavior, according to POSIX.

Steps to reproduce this bug 
--------------------------- 

It is very easy to reproduce this bug. Just issue the 'lru_crawler crawl -1' command. You may or may not notice any assertion failure, crash, or any other weird stuff depending on the scenarios given above. The major problem is that pthread's implementation of mutex lock/unlock won't throw any fatal error when these types of bugs happen, and it is not feasible to check the return values of pthread_mutex_lock/unlocks everywhere. While testing, I use a home-grown implementation of pthread APIs, which strictly conforms to POSIX and throws fatal errors during these undefined" behaviors.

Possible fixes 
--------------- 

Just remove 'pthread_mutex_unlock(&lru_crawler_lock);' statement on line 663 in crawler.c file[1].

Remarks
--------

This behavior was detected by a systematic concurrency tool being developed at Microsoft Research.

References 
----------- 

[1] https://github.com/memcached/memcached/blob/master/crawler.c#L663
[2] https://github.com/memcached/memcached/blob/master/crawler.c#L470
[3] https://linux.die.net/man/3/pthread_mutex_unlock

**Comment by dormando** [comment]
So many words for "you forgot to delete a line here" :) Given how narrow and specific the races are here I don't think it is something that would ever be seen in production. Regardless the fix is easy so I will do it soon.

Thanks!

**Comment by dormando** [comment]
released in 1.6.9!
