### ISSUE TITLE
Windows libraries for memcached

### ISSUE THREAD

**Issue by krishnakittu** [memcached/memcached#747]
**DO NOT SUBMIT SECURITY REPORTS HERE**

If you have a security vulnerability, _please report it to the maintainers
privately_. You will be able to file your bug and claim credit once we have a
fix implemented.

**Describe the bug**
HI Team,
How can i get latest Memcached binaries for windows. Is there any documentation for it.

**To Reproduce**
Any information useful for reproducing the bug or crash. Workload, changes in workload, versions affected. If seeing a new issue after an upgrade, please include both before and after versions.

**System Information**
 - OS/Distro:
 - Version of OS/distro:
 - Version of memcached:
 - Hardware detail:

**Detail (please include!)**
Always include the output of `stats`, `stats settings`, and optionally `stats items` and `stats slabs`. These can be provided to a maintainer privately if necessary. Please sanitize anything secret from the data.

If you have a segfault or crash, please try to resolve the crash with `addr2line`. If possible, get a core dump and include a full back trace.

**Comment by dormando** [comment]
Sorry, there aren't any official windows binaries. Someone was updating 3rd party binaries recently but he seems to have disappeared.

**Comment by udayrajluhar** [comment]
any plans or roadmap to enable them for Windows?

**Comment by bert126** [comment]
Check this : https://github.com/jefyt/memcached-windows

**Comment by bert126** [comment]
or this : https://github.com/nono303/memcached
