### ISSUE TITLE
Memcached Failed to write, and not due to blocking: Connection reset by peer

### ISSUE THREAD

**Issue by it-creed** [memcached/memcached#749]
Hi,

has anyone experienced Memcached crashing? We have around 100 users on the website and intermittently some members get logged out automatically after a few minutes. 

Any information you can give I would really appreciate it.

Not sure If I added all relevant info for others to give some idea would love to add more info if required. 

Thank you so much in advance.

This is what I'm getting from Syslog:
systemd-memcached-wrapper[2045]: Failed to write, and not due to blocking: Connection reset by peer
systemd-memcached-wrapper[2045]: Failed to write, and not due to blocking: Broken pipe

Here's the Memcached config 
memcached -v -m 2048 -p 11211 -u memcache -l 127.0.0.1  -P /var/run/memcached/memcached.pid

System Information
PHP Version =5.6.40-29+ubuntu18.04.1+deb.sury.org+1
memcache support => enabled
Version => 3.0.9-dev
Directive => Local Value => Master Value
memcache.allow_failover => 1 => 1
memcache.chunk_size => 32768 => 32768
memcache.compress_threshold => 20000 => 20000
memcache.default_port => 11211 => 11211
memcache.hash_function => crc32 => crc32
memcache.hash_strategy => consistent => consistent
memcache.lock_timeout => 15 => 15
memcache.max_failover_attempts => 20 => 20
memcache.protocol => ascii => ascii
memcache.redundancy => 1 => 1
memcache.session_redundancy => 2 => 2

memcached

memcached support => enabled
Version => 2.2.0
libmemcached version => 1.0.18
SASL support => yes
Session support => yes
igbinary support => yes
json support => yes
msgpack support => yes

Directive => Local Value => Master Value
memcached.compression_factor => 1.3 => 1.3
memcached.compression_threshold => 2000 => 2000
memcached.compression_type => fastlz => fastlz
memcached.serializer => php => php
memcached.sess_binary => 0 => 0
memcached.sess_connect_timeout => 1000 => 1000
memcached.sess_consistent_hash => 0 => 0
memcached.sess_lock_expire => 0 => 0
memcached.sess_lock_max_wait => 0 => 0
memcached.sess_lock_wait => 150000 => 150000
memcached.sess_locking => 1 => 1
memcached.sess_number_of_replicas => 0 => 0
memcached.sess_prefix => memc.sess.key. => memc.sess.key.
memcached.sess_randomize_replica_read => 0 => 0
memcached.sess_remove_failed => 0 => 0
memcached.sess_sasl_password => no value => no value
memcached.sess_sasl_username => no value => no value
memcached.store_retry_count => 2 => 2
memcached.use_sasl => 0 => 0

**Comment by acsfer** [comment]
Take a look at https://github.com/memcached/memcached/issues/458 (specially https://github.com/memcached/memcached/issues/458#issuecomment-493236403)

**Comment by dormando** [comment]
what version of memcached is that? How are you validating that the server is crashing?

The 'stats' output from memcached will show uptime and other useful metrics. I need at least that. what you've shared so far is the PHP configuration.

**Comment by dormando** [comment]
closing this out, as user never responded.
