### ISSUE TITLE
Log format documentation

### ISSUE THREAD

**Issue by jsirianni** [memcached/memcached#755]
Is there any documentation on the log format? For example: 

```
memcached_refresh<0.211.0>:ns_memcached:connect:1105]Unable to connect: {error,{badmatch,{error,econnrefused}}}.
```

I am trying to parse this with a log agent, but I have no idea what each field is.

**Comment by dormando** [comment]
that looks like a stack trace from your client, not a log from memcached itself. talk to whomever supplied your client or knows that language.

good luck!
