### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by romather** [memcached/memcached#757]
Windows Defender detects file as trojan:
![image](https://user-images.githubusercontent.com/47756883/104112707-1c37e600-52d1-11eb-8d62-696d4a45752a.png)
![Screenshot_1](https://user-images.githubusercontent.com/47756883/104112710-23f78a80-52d1-11eb-8393-b78f088dcd93.png)

VirusTotal detect:
![image](https://user-images.githubusercontent.com/47756883/104112768-5b663700-52d1-11eb-860c-cb29cdfcb8c1.png)

Windows 10 2009 
Language: pt-br
Browser: Chrome

**Comment by dormando** [comment]
not our binary.
