### ISSUE TITLE
Install memcached on IBM Cloud

### ISSUE THREAD

**Issue by mahsandu** [memcached/memcached#765]
This documentation will describe how to Install Memcached on IBM Cloud.

# Requirements/Prerequisites
You will need an IBM Cloud Pay-As-You-Go or Subscription Account type which can be found [here](https://cloud.ibm.com/docs/account?topic=account-accounts). 

# Introduction
This docs will describe how to install memcached on IBM Cloud. These four steps will be needed as follows:

- Step 1: Provision Kubernetes Cluster
- Step 2: Deploy IBM Cloud Block Storage plug-in
- Step 3: Deploy memcached
- Step 4: Verify Installation

So let's get started.

##  Step 1: Provision Kubernetes Cluster

* Search for **Kubernetes** and select **Kubernetes Service** from the list.
![image](https://user-images.githubusercontent.com/8035032/105907020-a52f7b00-604e-11eb-819d-fa97c1fa2f3e.png)

> You will be redirected to the [Kubernetes cluster creation](https://cloud.ibm.com/kubernetes/catalog/create) page.

### Option A: Create free Kubernetes Engine:

* Price Plan: Free

![image](https://user-images.githubusercontent.com/8035032/105908265-33583100-6050-11eb-9d1b-1dcf98a69a79.png)

> Enter the cluster name of your choice then click **Create** to provision the free Kubernetes Cluster.
> Please wait for few moments to provision the cluster.

### Option B: Create Standard Kubernetes Engine with the following attributes: 

* Price Plan: Standard

![image](https://user-images.githubusercontent.com/8035032/105909832-43711000-6052-11eb-9633-1b61c53d14cd.png)

* Infrastructure: Classic
* Availability: Multi Zone
* Metro: Dallas
* 4 VCPU
* 16 GB RAM
* Worker nodes per zone: 3

![image](https://user-images.githubusercontent.com/8035032/105909001-2c7dee00-6051-11eb-9785-e990b71ea111.png)

> Enter the cluster name of your choice then click **Create** to provision.

![image](https://user-images.githubusercontent.com/8035032/105909673-13c20800-6052-11eb-9863-8a2718922886.png)

> Please wait for a few moments to provision the cluster.

##  Step 2: Deploy IBM Cloud Block Storage plug-in

* Just like in step 1, search for "Block Storage" and Click on it.

![image](https://user-images.githubusercontent.com/8035032/105910051-964ac780-6052-11eb-87ac-908391bb85fb.png)

* On the Block Storage page click on **Create**

![image](https://user-images.githubusercontent.com/8035032/105910564-546e5100-6053-11eb-8059-3a66c705e098.png)

* Now input the storage details

> N.B. Select location as the cluster location.

* Location > Europe > London > LON02
* Billing Method > Monthly > 20 GB
* OS type > Linux
* IOPS > 2 IOPS/GB
![image](https://user-images.githubusercontent.com/8035032/105910989-df4f4b80-6053-11eb-9c02-bbd16b7ea021.png)

* Click on “I have agreed to the terms and conditions listed below”.

> Now a storage plugin will be available in the dashboard.

##  Step 3: Deploy memcached

* Again Search for **memcached** and Click on it.

![image](https://user-images.githubusercontent.com/8035032/106034015-90a9bc00-60fc-11eb-84a0-2d81ca4869d4.png)

> You will be taken to the **memcached** deployment page.

In the memcached creation page add the details below:

* Target: IBM Kubernetes Service
* Method: Helm chart
* Kubernetes cluster: mycluster-free (eu-de)
* Target namespace: memcached
* Workspace: memcached
* Resource group: Default

![image](https://user-images.githubusercontent.com/8035032/106034749-791f0300-60fd-11eb-9913-901d51a2f1a0.png)

* Check on “I have agreed to the terms and conditions listed below”.

> Click **Install** to deploy memcached.
> Please wait for all the process to complete.

![image](https://user-images.githubusercontent.com/8035032/106035501-65c06780-60fe-11eb-9d06-3e39df80c955.png)

##  Step 4: Verify Installation

* Go to Left Navigation Menu.
* Click on Kubernetes

![verification](https://user-images.githubusercontent.com/8035032/106024720-458aab80-60f2-11eb-8bc3-7c592c07a5a3.png)

* Click on your Cluster "mycluster-free".
 
![image](https://user-images.githubusercontent.com/8035032/106024886-6b17b500-60f2-11eb-8863-85844f916ba5.png)

> You will be taken to your clusters overview page where you will see the details of your cluster as well.

* To verify the installation find the Actions.. 
* Click on it and select `Web terminal` from the dropdown menu.
 
![image](https://user-images.githubusercontent.com/8035032/106023003-98fbfa00-60f0-11eb-998c-a860a42b116c.png)

> Click install, then wait for a couple of minutes to finish the process.

![image](https://user-images.githubusercontent.com/8035032/106023384-f2fcbf80-60f0-11eb-88f7-4dccc973dff3.png)

* After completing the installation click on Actions > Web terminal again.

> A command line terminal will appear. Type the command below:

#### Get the list of pods: 
`kubectl get ns`

![image](https://user-images.githubusercontent.com/8035032/106036066-06168c00-60ff-11eb-985b-a94caa8c0645.png)

#### See if it is running:
` kubectl get pod -n memcached -o wide `

![image](https://user-images.githubusercontent.com/8035032/106036975-3dd20380-6100-11eb-9ae3-7cde31b32def.png)

The Installation is now done! Enjoy !

**Comment by dormando** [comment]
What is your goal with filing this issue? This sounds like something that should be on a personal blog?
