### ISSUE TITLE
Memcached GET much slower than MariaDB query

### ISSUE THREAD

**Issue by ghnp5** [memcached/memcached#775]
Hello,

This is a question, not a bug report (for now!).

I run PHP, Memcached and MariaDB on the same server. Enough RAM for the whole database, plenty of RAM for Memcached, and NVMe disks.

I have a piece of code that does the following (summary/pseudo-code):

```
$key = $type.$id;
if (!isset($dict[$key])) {
	$value = $memcacheWrapper->get($key);
	if ($value === false) {
		$value = array();
		$result = mysqli_query('SELECT...');
		while ($row = mysqli_fetch_assoc($result)) {
			$value[] = $row;
		}
		some_sort($value);
		$memcacheWrapper->set($key, $value);
	}
	$dict[$key] = $value;
}
```

I put some profiling logs between each of the instructions in the code above, using `hrtime(true)`, to see where most of the time is being taken, on a big loop.

I noticed that, surprisingly, the Memcached "GET" queries are taking much longer than simply going to the database to get the data. See below:

![sshot-2021-03-09-00-01-25-1](https://user-images.githubusercontent.com/57591332/110547020-3d794f00-8127-11eb-9365-ef111cf49b16.jpg)

If the data is cached in Memcached, it won't take long to GET. However, I'm not sure why missed GET queries take so long if the key isn't there.

1) It is not a Network issue, since both Memcached and MariaDB are on the same server as PHP.

2) Is Memcached doing something like a "full table scan"-equivalent, trying to find the Key in a big list and eventually not finding it?

3) I understand Memcached works on an LRU basis, but isn't that only relevant for evictions? If Memcached puts everything in the RAM, shouldn't the accesses be O(1) ?

Notes:  
- Using Memcached 1.6.9 (libevent: 2.0.21-stable) on CentOS 7.
- MariaDB 10.5; PHP 7.4 with whatever latest php-memcached extension.
- I use the following options for Memcached's connection: `OPT_COMPRESSION`, `OPT_LIBKETAMA_COMPATIBLE`, `OPT_BINARY_PROTOCOL`
  - I've read in https://github.com/acquia/memcache-settings/issues/3 that Binary Protocol makes things slower, while I've seen around here that Binary Protocol is good for performance. What do you think/recommmend ?
- `$memcachedWrapper` does a `getResultCode()` call right after `get()`, to check if the 'server is dead'.  
- 8 threads are used by Memcached. Large memory pages (-L) are enabled. Max connections / Backlog is far from being on limits.

(if `stats` are relevant, please let me know)

**Comment by ghnp5** [comment]
Thank you very much @dormando.

> PHP has several clients, which are you using exactly?

I'm using "php74-php-pecl-memcached" from the Remi repository:
https://centos.pkgs.org/7/remi-x86_64/php74-php-pecl-memcached-3.1.5-1.el7.remi.x86_64.rpm.html

> Have you tried disabling the binary protocol?

I haven't tried, but I can give it a try! (will have to prepare a release for that)

> I've actually deprecated it in favor of an extended text protocol.

Is "extended text protocol" something I need to enable, or just disable Binary Protocol will do it?

> Connecting/reconnecting (if you enabled SASL with binprot this can add a lot of time)

Every PHP process will connect only once (at the beginning) to Memcached.
What I saw is the loops taking some time retrieving from Memcached.
I'm not familiar with SASL/binprot, so I assume I don't have those enabled!

> Slow/weird data serializer (but these are misses?)

Yeah, these are misses. When the data is already cached, it works quite fast.

I'm using PHP serializer. Would you recommend me using igbinary or something like that? (even if it's not related to this issue)

> A database under low load

The database is actually quite read & write intensive.
We've recently moved to this "powerful" server, which I believe is the reason we may be seeing this difference now, while on the previous servers we had, we didn't have enough RAM for the database, so the scenario was different.


```
# stats
                        Field         Value
              accepting_conns             1
                    auth_cmds             0
                  auth_errors             0
                        bytes     685738663
                   bytes_read  284778091308
                bytes_written 1550852348807
                   cas_badval             0
                     cas_hits             0
                   cas_misses             0
                    cmd_flush             0
                      cmd_get    2691042804
                     cmd_meta             0
                      cmd_set     248255248
                    cmd_touch             0
                  conn_yields             0
        connection_structures           188
        crawler_items_checked   17473569370
            crawler_reclaimed     110613721
             curr_connections            99
                   curr_items       3728571
                    decr_hits       1124820
                  decr_misses             0
                  delete_hits       2301515
                delete_misses      14569940
              direct_reclaims             0
               evicted_active             0
            evicted_unfetched             0
                    evictions             0
            expired_unfetched      67257162
                  get_expired       4024558
                  get_flushed             0
                     get_hits    2441947920
                   get_misses     249094884
                   hash_bytes      33554432
            hash_is_expanding             0
             hash_power_level            22
                    incr_hits       3913602
                  incr_misses             0
                     libevent 2.0.21-stable
               limit_maxbytes    3221225472
          listen_disabled_num             0
             log_watcher_sent             0
          log_watcher_skipped             0
           log_worker_dropped             0
           log_worker_written             0
            lru_bumps_dropped             0
          lru_crawler_running             0
           lru_crawler_starts        432750
       lru_maintainer_juggles     270511994
            lrutail_reflocked         47617
                 malloc_fails             0
              max_connections          3000
                moves_to_cold      45008079
                moves_to_warm      10638079
             moves_within_lru       6296867
                          pid         59351
                 pointer_size            64
               read_buf_bytes        393216
          read_buf_bytes_free        245760
               read_buf_count            24
                 read_buf_oom             0
                    reclaimed        387460
         rejected_connections             0
                 reserved_fds            40
           response_obj_bytes        131072
           response_obj_count             1
             response_obj_oom             0
         round_robin_fallback             0
                rusage_system  82113.080495
                  rusage_user  33661.811785
        slab_global_page_pool            30
   slab_reassign_busy_deletes             0
     slab_reassign_busy_items             8
  slab_reassign_chunk_rescues           268
slab_reassign_evictions_nomem             0
 slab_reassign_inline_reclaim         48431
        slab_reassign_rescues       7581924
        slab_reassign_running             0
                  slabs_moved          3207
                      threads             8
                         time    1615334641
   time_in_listen_disabled_us             0
            total_connections        863339
                  total_items     255890604
                   touch_hits             0
                 touch_misses             0
          unexpected_napi_ids             0
                       uptime       2627939
                      version         1.6.9


# settings
                   Field       Value
      auth_enabled_ascii          no
       auth_enabled_sasl          no
        binding_protocol auto-negotiate
             cas_enabled          no
              chunk_size          48
          detail_enabled          no
           domain_socket        NULL
            dump_enabled         yes
               evictions          on
       ext_compact_under           0
          ext_drop_under           0
         ext_drop_unread          no
            ext_item_age  4294967295
           ext_item_size         512
             ext_low_ttl           0
            ext_max_frag        0.80
        ext_recache_rate        2000
           ext_wbuf_size     4194304
           flush_enabled         yes
           growth_factor        1.25
          hash_algorithm     murmur3
          hashpower_init           0
             hot_lru_pct          20
          hot_max_factor        0.20
            idle_timeout           0
   inline_ascii_response          no
                   inter        NULL
           item_size_max     1048576
             lru_crawler         yes
       lru_crawler_sleep         100
     lru_crawler_tocrawl           0
   lru_maintainer_thread         yes
           lru_segmented         yes
                maxbytes  3221225472
                maxconns        3000
           maxconns_fast         yes
             memory_file      (null)
            num_napi_ids      (null)
             num_threads           8
     num_threads_per_udp           8
                  oldest           0
      read_buf_mem_limit           0
          reqs_per_event          20
           slab_automove           1
 slab_automove_freeratio       0.010
     slab_automove_ratio        0.80
    slab_automove_window          30
          slab_chunk_max      524288
           slab_reassign         yes
         stat_key_prefix           :
        tail_repair_time           0
             tcp_backlog        3000
                 tcpport       11211
                temp_lru          no
           temporary_ttl          61
             track_sizes          no
                 udpport           0
                   umask         700
               verbosity           1
            warm_lru_pct          40
         warm_max_factor        2.00
     watcher_logbuf_size      262144
      worker_logbuf_size       65536

```

**Comment by ghnp5** [comment]
By the way, we use PHP-FPM, and use the "pid" as the identifier for Memcached connections, so persistent connections are (re)used.

**Comment by dormando** [comment]
To answer another question I missed; misses are faster than gets. There're no non-O(1) commands in memcached. 


> Is "extended text protocol" something I need to enable, or just disable Binary Protocol will do it?

If you're just doing gets and sets you don't need to do anything. Binprot enabled some advanced features but hardly anyone used them. The new protocol extensions are new enough that very few libraries support them. If you're curious: https://github.com/memcached/memcached/wiki/MetaCommands - generally stuff you don't need to worry about unless you're large enough to spend a lot of time thinking about the cache :)

> Every PHP process will connect only once (at the beginning) to Memcached.
> What I saw is the loops taking some time retrieving from Memcached.

What does "the loops" mean? I don't see anything in stats that would indicate an issue (And certainly misses don't block)

> Yeah, these are misses. When the data is already cached, it works quite fast.
> 
> I'm using PHP serializer. Would you recommend me using igbinary or something like that? (even if it's not related to this issue)

Not sure. Honestly I don't use php much myself.
 
> The database is relativelly read & write intensive.
> We've recently moved to this "powerful" server, which I believe is the reason we may be seeing this difference now, while on the previous servers we had, we didn't have enough RAM for the database, so the scenario was different.

If I'm reading this right, it's almost a 39ms ding on a miss? There's certainly no reason for the server to take that long; are you able to reproduce with a standalone minimal script?

**Comment by ghnp5** [comment]
Thank you @dormando.

Yeah, the "miss" doesn't take THAT much that a user would notice, but, when doing 100 times in a row (on a page where 100 things need to be cached), it was taking significant time.
Once it's cached, the page loads instantly.

But removing the cache overall in that region, and simply going to the database every time (which does a GROUP BY, and then PHP sorts it), it takes less time than getting a MISS in Memcached !

That's the main issue I'm trying to understand -- why a MISS on a O(1) system would take longer than going to the database do a GROUP BY and then a sort :)

Thank you very much.
I will look into removing the binary protocol.

**Comment by dormando** [comment]
Hey,

Well to give you a clear answer here: misses should be returned on the order of microseconds. There's no code that could make it run slowly at all. Your total roundtrip time after syscalls should be less than a millisecond for a miss.

So you've probably got something else to debug. Disabling binprot might fix it, but if it doesn't I'd reiterate on creating a standalone minimal script (just raw PHP + the mc librar) then if the problem goes away slowly add your libraries/wrappers back in until you hit it.

**Comment by ghnp5** [comment]
Thanks @dormando 
That's the kind of confirmation I was looking for!
I'll definitely proceed with both suggestions, to narrow down the issue.
Have a very great day.

**Comment by dormando** [comment]
Sorry thought I was more clear on that from the start. There's also the wiki page: https://github.com/memcached/memcached/wiki/Performance

**Comment by ghnp5** [comment]
Hey @dormando 
I noticed I have a comment in the code, that "OPT_BINARY_PROTOCOL must be ON" when using "increment/decrement".
Unfortunately it doesn't say more than this, like what problem we had at the time we were testing.

Do you know if there are any concerns, known bugs, etc, if the binary protocol isn't used on increment/decrement?

Thank you very much!

**Comment by ghnp5** [comment]
I'm doing some research, but to be honest, I'm seeing that having it ON can cause issues with the data returned after increment/decrement, but also that if there's no value yet, it can give an error 38 - INVALID ARGUMENTS.

I guess I'll have to do some tests around this, to see if any of these behaviors happen...

**Comment by dormando** [comment]
Have you written a standalone page to test with first? I worry you're expending too much effort to do the binary test.

The issue here is binprot lets you seed a value to incr/decr on a miss. This is probably the only binprot specific feature anyone used. Meta also fixes this (but sadly no support yet).

In ascii for incr/decr you need a wrapper pattern:
```
if ($mc->incr('key', 1) == miss) {
  if ($mc->add('key', $INITIAL_VALUE) == exists) {
    $mc->incr('key', 1);
  }
}
```

if miss on incr, run an add. if add returns key exists (lost the race), run the incr again. Can skip that last part if you don't care.

**Comment by ghnp5** [comment]
Hey! Sorry, I did test with a minimal script, and got the same results.

And I'm not wasting time, no :) if you say you're going to deprecate the binary protocol, then I might as well just stop using it.
(I just take time to reply because I'm always doing so many things.... apologies)

I went ahead and put the hrtime(true) right before "->get()", after "->get()", and after "->getResultCode()",
and closely looked at the timings when there's a MISS and when the value was cached.

Here are 4 examples, but the numbers are all around the same, consistently.

![image](https://user-images.githubusercontent.com/57591332/111527045-58674700-8757-11eb-875e-793e94f6ca8b.png)

Misses are significantly slower than non-misses.


Then, I spawned a new instance of Memcached, to test the connections without binary protocol, and here are the results..........

![image](https://user-images.githubusercontent.com/57591332/111528578-3e2e6880-8759-11eb-8e9f-2d632f19b826.png)


Seems we have a winner!

**Comment by dormando** [comment]
Sounds good. You should also take this minimal test case/comment over to the php-memcached github project and report it (along with versions of everything). Seems like it's waiting on a timeout when it shouldn't.

**Comment by nunoperalta** [comment]
Promoted to production, and there's a HUGE performance boost!
Thanks very much @dormando .
Have a very great day! :)

**Comment by ghnp5** [comment]
Promoted to production, and there's a HUGE performance boost!
Thanks very much @dormando .
Have a very great day! :)
