### ISSUE TITLE
Is it possible to save memcached key permently?

### ISSUE THREAD

**Issue by SHUFIL** [memcached/memcached#777]
**DO NOT SUBMIT SECURITY REPORTS HERE**

If you have a security vulnerability, _please report it to the maintainers
privately_. You will be able to file your bug and claim credit once we have a
fix implemented.

**Describe the bug**

**To Reproduce**
Any information useful for reproducing the bug or crash. Workload, changes in workload, versions affected. If seeing a new issue after an upgrade, please include both before and after versions.

**System Information** 
 - OS/Distro: ubuntu
 - Version of OS/distro: 16.04
 - Version of memcached: 1.6.0
 - Hardware detail: 4 core, 8GB, 160GB Disk space

**Detail (please include!)**
I have installed memcached-1.6.0 in ubuntu and started with external disk option, Is it possible get stored key permanently , right now all the data removing automatically when I restart memcached.

I believe if we start memcached with disk option, that will be help us to store key inside the disk and will get the key even restart service? is it possible ? or what method I need to use for this purpose.

**Comment by dormando** [comment]
Hey, sorry for the slow response.

Extstore doesn't turn memcached into a database, it splits data between RAM and disk; so if the RAM portion is lost it still can't recover from disk (or if it could, it would be extremely slow).

If your goal is to just avoid losing cache in most scenarios, you can use the Warm Restart feature: https://github.com/memcached/memcached/wiki/WarmRestart - note this doesn't presently work with Extstore, but that should be fixed soon.

Thanks.
