### ISSUE TITLE
t/whitespace.t testcase is failing for intel and power

### ISSUE THREAD

**Issue by dthadi3** [memcached/memcached#778]
Need help in resolving the issue
FYI,
https://travis-ci.com/github/dthadi3/memcached/builds/219575652

$ make test is failing 
--------------------------------------
t/whitespace.t .............. 1/212 
#   Failed test '.travis.yml (see devtools/clean-whitespace.pl)'
#   at t/whitespace.t line 48.
# Looks like you failed 1 test of 212.
t/whitespace.t .............. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/212 subtests 
Test Summary Report
-------------------
t/whitespace.t            (Wstat: 256 Tests: 212 Failed: 1)
  Failed test:  5
  Non-zero exit status: 1
Files=80, Tests=174765, 482 wallclock secs (17.39 usr  1.18 sys + 25.51 cusr  7.40 csys = 51.48 CPU)
Result: FAIL
Makefile:2085: recipe for target 'test' failed
make: *** [test] Error 1
The command "make test" exited with 2.
Done. Your build exited with 1.

waiting for your inputs..... Thanks in advance!

**Comment by dormando** [comment]
not sure what to do with this. we don't really use travis anymore, I guess I'll make sure the file's deleted?

**Comment by dormando** [comment]
Closing this out. Not sure what the user wanted, sorry :(
