### ISSUE TITLE
AttributeError: module 'memcache' has no attribute 'Client'

### ISSUE THREAD

**Issue by happykayy** [memcached/memcached#782]
>>> import memcache
>>> mc = memcache.Client(['127.0.0.1:11211'], debug=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'memcache' has no attribute 'Client'
>>> 

I installed memcache by sudo apt-get install memcache
and the version is 1.5.22

can anyone help me with this please? Thanks!!

**Comment by martin-g** [comment]
This repo is for Memcache**d** - the server.
It seems you try to use PHP Memcache - a client library. You need to consult with its [documentation](https://www.php.net/manual/en/book.memcache.php)

**Comment by dormando** [comment]
Going to close this out; I think that's python though. You'll need to ask a language-specific community for help, sorry.
