### ISSUE TITLE
Get "recent" keys

### ISSUE THREAD

**Issue by ghnp5** [memcached/memcached#784]
Hey,

This is just a question -- is there any way to get a list of "recent" keys?

In other words, the last 10 'sets' performed against Memcached.
A full list of keys doesn't help much especially on large databases.

I would find this helpful for analysis in general, e.g. debugging, detecting attacks, finding problems, etc...

Thank you very much.

**Comment by dormando** [comment]
telnet to memcached and run `watch mutations` which will stream the writes. then write a program to filter out/summarize what you want out of it.
