### ISSUE TITLE
Impact of item_size_max on memcached performance.

### ISSUE THREAD

**Issue by jaisharma639** [memcached/memcached#801]
How does `-I` flag impact the performance of memcached in terms of efficiency? Could not find any documentation that describes the impact of item_size_max on efficiency (mem_requested / (chunks_per_page * chunk_size)) for a slab.

Additionally, what's the right way to calculate % efficiency per slab to see what's the wastage memory % as per [this](https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L1473).

**Comment by dormando** [comment]
Looks like this is yet another thing that needs to be documented better. `-I` doesn't change memory efficiency, `-o slab_chunk_max` does, see: https://github.com/memcached/memcached/wiki/ReleaseNotes1429#new-features

If you lower the `slab_chunk_max` from the default of 512k to 256k, and adjust `-f` to have a spread of ~60 slab classes, the slab classes get closer together and you waste less memory in overhead. If you have very few items over a certain size, you can set the chunk max down closer to that.

I've very rarely seen it benefit people to optimize the slab overhead, though. it's typically 10% and a lot of effort to reduce.

**Comment by jaisharma639** [comment]
Is it recommended to increase the `-I` flag beyond 1MB? I read recommendations on tuning memcache that `-I` shouldn't generally be tweaked to a very large number as it can have performance implications. Can you comment on the workings and trade-off that occurs on increasing the max item size?

**Comment by dormando** [comment]
Hi,

I answered this above; please read more carefully. That advice changed after version 1.4.29. The link I gave explains how it works.
