### ISSUE TITLE
Potential error (e.g., deadlock ) due to the unreleased lock &p->mutex

### ISSUE THREAD

**Issue by anson-lo** [memcached/memcached#804]
Hi, developers, the lock `&p->mutex` may not be correctly released in the method `extstore_write_request` method, if the method returns in that branch. Thank you for your checking!

https://github.com/memcached/memcached/blob/c472369fed5981ba8c004d426cee62d5165c47ca/extstore.c#L546
https://github.com/memcached/memcached/blob/c472369fed5981ba8c004d426cee62d5165c47ca/extstore.c#L571

```
int extstore_write_request(void *ptr, unsigned int bucket,
        unsigned int free_bucket, obj_io *io) {
    store_engine *e = (store_engine *)ptr;
    store_page *p;
    int ret = -1;
    if (bucket >= e->page_bucketcount)
        return ret;

    pthread_mutex_lock(&e->mutex);
    p = e->page_buckets[bucket];
    if (!p) {
        p = _allocate_page(e, bucket, free_bucket);
    }
    pthread_mutex_unlock(&e->mutex);
    if (!p)
        return ret;

    pthread_mutex_lock(&p->mutex);

    ...;
    
    if (p->wbuf && !p->wbuf->full && p->wbuf->free >= io->len) {
        io->buf = p->wbuf->buf_pos;
        io->page_id = p->id;
        return 0;  // return without releasing
    }

    pthread_mutex_unlock(&p->mutex);
    // p->written is incremented post-wbuf flush
    return ret;
}
```

**Comment by dormando** [comment]
There's a comment directly above 571 saying it leaves the mutex locked.

Look at the callers for write_request(). The page lock is held while the caller writes to it. The caller must complete the write so the lock is then unreleased.

**Comment by anson-lo** [comment]
OK, thank you for your checking!
