### ISSUE TITLE
wiki Commands section: stats list needs to be updated

### ISSUE THREAD

**Issue by ToMakeSense** [memcached/memcached#807]
I am newer to `memcached`, I need to refer to the official wiki to learn sometimes, but I found the `stats` section of the [wiki Commands](https://github.com/memcached/memcached/wiki/Commands) is not completed/updated, for example, below command is not mentioned at least:
```bash
stats cachedump
stats detail
stats malloc
stats reset
```
BTW, I don't know if any way to get the completed list and the corresponding instructions.

**Comment by dormando** [comment]
`doc/protocol.txt` in the tarball is supposed to be the complete documentation for the protocol. Some of those commands are for debugging and not end users though.
