### ISSUE TITLE
web site: replace Packet logo with Equinix Metal logo

### ISSUE THREAD

**Issue by vielmetti** [memcached/memcached#808]
Hi @dormando and crew -

I notice that the https://memcached.org web site has a logo thanking Packet for support.

As you may know, Packet was acquired by Equinix and rebranded as "Equinix Metal" about a year ago. I'd love it if you could replace the logo.

https://github.com/packethost/metal-logo has a whole bunch of "Equinix Metal" brand stuff in a variety of suitable formats and sizes, which should make this an easy swap.

thanks

Ed

**Comment by dormando** [comment]
Ah shoot! I have a super old e-mail about doing this too. I'll get to this soon, apologies.

**Comment by vielmetti** [comment]
Thanks @dormando ! The repo with the logos and icons should make this process more straightforward than it was a while ago, but if you run into any issues with finding an image the right size just let me know.

**Comment by dormando** [comment]
Hey,

So sorry about not getting back to this sooner. I just took the SVG of your suggested picture and shrank it to something that fit. It looks a little small so if you want something specific please go ahead and supply a specific png for me to add.

**Comment by vielmetti** [comment]
Looks good to me! Thanks for taking care of this.
