### ISSUE TITLE
Windows Memcached with Django, report [warn] select: No error

### ISSUE THREAD

**Issue by BUERGER123** [memcached/memcached#818]
I'm using django with memcached store realtime data maybe reset key-value per 1min , however sometimes memcached will crash with problem "[warn] select: No error", and then django will miss getting data from memcached. how can i fix it?
![image](https://user-images.githubusercontent.com/24760171/132616054-2ca9dedd-3c09-4573-abea-c41aea7235b4.png)

**Comment by dormando** [comment]
sorry we don't support the a windows version of memcached. if you want to use it, try from the WSL.
