### ISSUE TITLE
Memory Leak on RHEL 8.4

### ISSUE THREAD

**Issue by heyyo-droid** [memcached/memcached#820]
It seems we have a memcached memory leak. We are using RedHat Enterprise Linux 8.4.
Memcached is the last stable one 1.6.10 compiled.
Libevent is the one provided by RHEL 2.1.8-5-el8 ( we are thinking to compile with last source)

We have 16GB on this server.
Memcached is configured to use 12GB max.

Memcached is reporting using 6.37GB but htop showing the server is already 12.5GB, so around 5.5 GB are not reported at all. cf htop screenshot. https://ibb.co/JxjPrp7

CPU is really low, Load average 0.01

The server started 2 days and 8 hours ago. For around 2 days and 4/5 hours, the system memory was normal. Now memory is maybe leaking around 100MB every minute. So the server will swap really soon.

I attached all logs that I know (I'm still trying to learn memcached)

Let me know if you need anything else, we are running out of ideas.
Thanks in advance.

![memcached-htop](https://user-images.githubusercontent.com/81759607/133934742-fca63701-11a7-4940-90f7-815ae9be24cc.png)
[memcached-tool-ng.txt](https://github.com/memcached/memcached/files/7192458/memcached-tool-ng.txt)
[stats.txt](https://github.com/memcached/memcached/files/7192459/stats.txt)
[stats-items.txt](https://github.com/memcached/memcached/files/7192460/stats-items.txt)
[stats-settings.txt](https://github.com/memcached/memcached/files/7192461/stats-settings.txt)

**Comment by heyyo-droid** [comment]
Attaching also a memleax report with default settings, expire set to 10s not sure what best value i should set.
[memcached-memleak.txt](https://github.com/memcached/memcached/files/7192610/memcached-memleak.txt)

**Comment by dormando** [comment]
Hey,

I took a quick look at your logs and the screenshot, and can say for sure memcached hasn't leaked anything. The resident memory (that you highlighted) matches what mc thinks it's using. Please don't take this as rude: but you should take this to support forums for linux systems administration. Your memory can be used up elsewhere (other programs, filesystem buffers, etc) and I can't walk you through this as it's a common question and I'm trying to keep these issues for bugs in memcached itself.

Good luck.

**Comment by heyyoyo** [comment]
I understand completely. 
Regarding libevent do you recommend we should use a more up-to-date version ? In recent change log, I saw some elements related to leak and corrupted memory.

**Comment by dormando** [comment]
You don't have a memory leak, and we don't really use that much of libevent so the odds of triggering a problem with it are really low. If libevent were leaking memory the RES value would grow, but it's not.

**Comment by heyyo-droid** [comment]
Yes you were completly right, it's an issue related to vmware and ballooning and not related at all to Memcached.
