### ISSUE TITLE
slab_automove, slab_reassign, and LRU crawler parameters don't check for no_modern

### ISSUE THREAD

**Issue by QuChen88** [memcached/memcached#824]
Currently, the parameter `no_modern` is designed to disable `slab_automove`, `slab_reassign`, LRU crawler and LRU maintainer. see https://github.com/memcached/memcached/blob/master/memcached.c#L5431

However, the parameters `slab_automove, slab_reassign, lru_crawler, lru_maintainer` don't currently check the value of `no_modern` parameter (i.e. See https://github.com/memcached/memcached/blob/master/memcached.c#L5096). So if I start up memcached server by specifying those parameters after `no_modern` on the command line, then those parameters will override the previous setting of `no_modern`. Is this the intended behavior or a bug?

I confirmed this behavior locally in memcached. 

```
$ /usr/bin/memcached -p 11211 -o no_modern -o slab_reassign -o slab_automove=1 &
$ telnet localhost 11211
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
stats settings
.... 
STAT slab_reassign yes
STAT slab_automove 1
```

**Comment by dormando** [comment]
That's intentional. `no_modern` swaps the defaults around, then anything you specify after that enables things piecemeal. It's not meant to block features from being enabled.

**Comment by QuChen88** [comment]
Thanks!
