### ISSUE TITLE
Return value of delete() is wrong

### ISSUE THREAD

**Issue by j-schulz** [memcached/memcached#832]
Example:

import memcache
m = memcache.Client(["127.0.0.1:11211"])
m.set("foo", "bar")
print(m.delete("foo"))
print(m.delete("foo"))

Output:
1
1

telnet localhost 11211
set foo 0 0 3 data
bar
STORED
delete foo
DELETED
delete foo
NOT_FOUND

So returning 1 if the key does not exist is wrong. I expect 0 or False or None, but not 1.

**Comment by dormando** [comment]
Hey,

Sorry for the late reply; this is an issue with your client, not the daemon. You'll have to look at the source to your client or contact the author.
