### ISSUE TITLE
1.6.12 fails to build on FreeBSD when using libressl < 3.4

### ISSUE THREAD

**Issue by Nuadh** [memcached/memcached#833]
As per title, 1.6.12 fails to build with libressl < 3.4, as the checks for enabling TLS1_3 is checking the openssl version. For some reason, libressl has the OPENSSL_VERSION_NUMBER set so your check enables TLS1_3. By "cheating" a bit, and checking for LIBRESSL_VERSION_NUMBER >= 03040000fL (not 100% sure that's the right number to check for, as I don't know when they implemented the public interfaces for TLS1_3, but 3.4.1 does at least have them), the build works with a disabled TLS1_3..

Attached is my FreeBSD patches (remove .txt for paching to work automagically)
[patch-memcached.c.txt](https://github.com/memcached/memcached/files/7493179/patch-memcached.c.txt)
[patch-tls.c.txt](https://github.com/memcached/memcached/files/7493180/patch-tls.c.txt)
..

**Comment by dormando** [comment]
@LINKIWI poke :)

Libressl isn't a default on freebsd is it? how did you set this up?

**Comment by LINKIWI** [comment]
Thanks; the patch seems pretty reasonable to me. I wasn't aware that non-OpenSSL flavors were supported, so unfortunately I didn't regression-test my original change against LibreSSL or others.

(Perhaps there's an opportunity to update the docs to call out explicitly what SSL libraries are supported/validated against?)

**Comment by Nuadh** [comment]
LibreSSL is one of the (two, unless you count *-devel) flavours supported for the ports system in FreeBSD. You set it up by compiling your own packages with DEFAULT_VERSIONS+= ssl=libressl in make.conf.

Probably a stupid question, but; isn't there a possibility to check what TLS versions the library supports without resorting to bad "hacks" like checking version numbers (this is *not* the first project that does it this way)? In both libressl and openssl headers (at least on FreeBSD), there is TSL1_3_VERSION, TSL1_2_VERSION, TLS1_1_VERSION and TLS1_VERSION, plus in openssl there's the TLS_MAX_VERSION (too bad libressl doesn't have that..)

**Comment by LINKIWI** [comment]
Something like `#if defined(TLS1_3_VERSION)` seems reasonable to me. Can't quite remember why I didn't do that the first time around...

Can you try this against LibreSSL:

```
diff --git a/memcached.c b/memcached.c
index bf6617d..283e195 100644
--- a/memcached.c
+++ b/memcached.c
@@ -4047,7 +4047,7 @@ static void usage(void) {
     printf("   - ssl_session_cache:   enable server-side SSL session cache, to support session\n"
            "                          resumption\n"
            "   - ssl_min_version:     minimum protocol version to accept (default: %s)\n"
-#if OPENSSL_VERSION_NUMBER >= 0x10101000L
+#if defined(TLS1_3_VERSION)
            "                          valid values are 0(%s), 1(%s), 2(%s), or 3(%s).\n",
            ssl_proto_text(settings.ssl_min_version),
            ssl_proto_text(TLS1_VERSION), ssl_proto_text(TLS1_1_VERSION),
diff --git a/tls.c b/tls.c
index dcd7435..db3aaa7 100644
--- a/tls.c
+++ b/tls.c
@@ -257,7 +257,7 @@ const char *ssl_proto_text(int version) {
             return "tlsv1.1";
         case TLS1_2_VERSION:
             return "tlsv1.2";
-#if OPENSSL_VERSION_NUMBER >= 0x10101000L
+#if defined(TLS1_3_VERSION)
         case TLS1_3_VERSION:
             return "tlsv1.3";
 #endif
```

If this works well I'm happy to file a PR, but will defer to @dormando on what he thinks.

**Comment by Nuadh** [comment]
You missed:

@@ -5413,7 +5413,7 @@ int main (int argc, char **argv) {
                     case 2:
                         settings.ssl_min_version = TLS1_2_VERSION;
                         break;
-#if OPENSSL_VERSION_NUMBER >= 0x10101000L
+#if defined(TLS1_3_VERSION)
                     case 3:
                         settings.ssl_min_version = TLS1_3_VERSION;
                         break;


except for that, it built, installed and ran perfectly, and looks a lot more sensible. You could even add the same checks for TLS1_2_VERSION, and even TLS1_1_VERSION:)

**Comment by dormando** [comment]
Hey,

re: support policy. I support what people ask for, so long as the diffs aren't unreasonable. Extra bonus points for either supplying a buildbot or if it's easy to add one. Else it'll likely regress anyway. This is why we don't do windows but otherwise have a wide variety. So, unless I have an easy buildbot for libressl we might have issues again in the future.

re: version numbers vs flags. There are a couple cases in the code where we've had to test for versions, and/or compile test in `configure` because of certain versions of things having a feature advertised, but were buggy for a few versions, and some jerk like redhat shipped an LTS distro pinned to the broken version. So long as that's not the case with OpenSSL we should absolutely use the feature flags. I hadn't looked at the manual for them while reviewing the patch.

Thanks for hashing this out, folks!

**Comment by dormando** [comment]
out in 1.6.13
