### ISSUE TITLE
memcached get command returning exptime?

### ISSUE THREAD

**Issue by javierarilos** [memcached/memcached#835]
Hello there!

for some use cases, we need to move data from one memcached node to another.

We would like to be able to retrieve a value for a key and it's exptime, so that we can set a proper exptime in the second memcached node.

I didn't find in the memcached protocol how to do that and the solutions found in Stackoverflow of using Slab stats don't seem scalable or reliable: https://stackoverflow.com/questions/2558706/how-can-i-get-the-expire-time-for-the-particular-item-in-memcached/9970657

Am I missing some command or option to get a key with its exptime? Do you think this need might be shared by others? What options do we have?

**Comment by wake-up-neo** [comment]
You might consider storing metadata along with the actual data, e.g. timestamp + data.

**Comment by dormando** [comment]
There's no way to get the exptime back from a normal `get` command without putting it with the data, as noted above.

However, the new text protocol can do this: https://github.com/memcached/memcached/wiki/MetaCommands - you will need client support but the protocol is trivial to parse.

**Comment by dormando** [comment]
Another way people do this is with the lru crawler command (see protocol.txt for info). The dump includes exptime information which allows you to move data to another memcached.

**Comment by javierarilos** [comment]
Thank you very much @wake-up-neo and @dormando for your responses, very much appreciated.
I wasn't aware of the new text protocol, it's super cool!
I think for our use case using the new text protocol is more appropriate than the other proposals. The client part seems easy enough.
