### ISSUE TITLE
Number of queries to query top key

### ISSUE THREAD

**Issue by yehaotong** [memcached/memcached#839]
Can I have a command to query the query times or frequency of top keys? Memcached in production doubled the QPS in an instant, but I don't know which keys were queried and this problem occurred.This is very important to me. Thank you

**Comment by dormando** [comment]
There are no built in facilities for this, but you can use `watch fetchers` and `watch mutations` commands (see `doc/protocol.txt`) and some tooling to get an idea of what your top keys are.
