### ISSUE TITLE
Meta / ASCII protocol does not have equivalent to binary protocol flushq

### ISSUE THREAD

**Issue by petergoldstein** [memcached/memcached#840]
As I understand it, the meta protocol introduced in version 16 is supposed to provide all functionality that is available in the (now deprecated) binary protocol.  One gap I noticed is that the binary protocol has the `flushq` or "quiet" flush command.  This flushes the memcached server (optionally with a delay) and provides no response.

The Meta / ASCII equivalent of `flush` is `flush_all`, which does not take a quiet option.  It always generates a response.

**To Reproduce**

There's no reproduction steps per se, other than to note that this capability doesn't exist in Meta / ASCII

**System Information**

Any memcached version to date that supports the Meta protocol (v16.0+)

**Detail (please include!)**

Not really any relevant details.

**Comment by dormando** [comment]
Ah, `flush_all` does take noreply (the ascii-y semi broken quiet form):

```
set foo 0 0 2
hi
STORED
flush_all 0 noreply
get foo
END
flush_all 0
OK
flush_all
OK
```

At some point I want to meta-ize config and control commands, which I think flush_all probably lands under since it's a global op. I don't intend to do that until after the proxy stuff is settled though.

**Comment by petergoldstein** [comment]
@dormando Ah.  That's handy, thanks.  I'll update Dalli to do that.

**Comment by petergoldstein** [comment]
Closing, because the capability is present.
