### ISSUE TITLE
Use of the c flag in meta set requests unexpected returns the argument CAS in a number of cases

### ISSUE THREAD

**Issue by petergoldstein** [memcached/memcached#842]
**Describe the bug**

When using the c flag in a meta set request, the expected behavior is that memcached will return the CAS token in the response, prefixed by the 'c' flag.  For a number of cases this is not what happens.  Specifically:

1. For a meta set with a failing CAS, the failing CAS token is returned as opposed to the correct CAS token
2. For an append/prepend, the argument CAS token is returned, returning 0 if no CAS token was provided in the request

**To Reproduce**

The simple case, with expected behavior is here:

```
ms key1 2 c
ab

HD c1

mg key1 v f c
VA 2 f0 c1
ab
```

The CAS token is returned by meta set, and we can confirm its value with a subsequent meta get.  This also works as expected if we use a correct CAS token with the `C` flag in the meta set.  The returned value is the CAS token for the value after the set is executed.

But in other cases we get weird results.  For example, if we use a CAS token that DOESN'T match:

```
ms key1 2 c C1234
xy

EX c1234
```

We don't get the correct CAS token back, we instead get the nonmatching argument token back.  This isn't terribly helpful, since what we presumably want to know is the latest CAS token for that value.  We would expect the response to be `EX c1`

For an append or prepend operation, with a matching CAS token

```
ms key1 2 C1 c MA
ef

HD c1

mg key1 v f c
VA 4 f0 c2
abef
```

The argument CAS token is returned in this case.  The subsequent meta get shows that the CAS token has changed.  We would expect to have seen the response `HD c2`

When we use an append without a CAS token, the returned value is a zero

```
ms key1 2 c MA
ef

HD c0

mg key1 v f c
VA 4 f0 c2
abef
```

In all cases we would expect to see the CAS token that can be used by subsequent meta set operations.

**System Information**
 - OS/Distro: macOS, from homebrew
 - Version of OS/distro: Monterey 12.1
 - Version of memcached: 1.6.12
 - Hardware detail: N/A

**Detail (please include!)**
Always include the output of `stats`, `stats settings`, and optionally `stats items` and `stats slabs`. These can be provided to a maintainer privately if necessary. Please sanitize anything secret from the data.

```
stats
STAT pid 75701
STAT uptime 1393
STAT time 1639507526
STAT version 1.6.12
STAT libevent 2.1.12-stable
STAT pointer_size 64
STAT rusage_user 0.115513
STAT rusage_system 0.064456
STAT max_connections 1024
STAT curr_connections 2
STAT total_connections 3
STAT rejected_connections 0
STAT connection_structures 3
STAT response_obj_oom 0
STAT response_obj_count 1
STAT response_obj_bytes 16384
STAT read_buf_count 2
STAT read_buf_bytes 32768
STAT read_buf_bytes_free 0
STAT read_buf_oom 0
STAT reserved_fds 20
STAT cmd_get 5
STAT cmd_set 9
STAT cmd_flush 0
STAT cmd_touch 0
STAT cmd_meta 0
STAT get_hits 5
STAT get_misses 0
STAT get_expired 0
STAT get_flushed 0
STAT delete_misses 0
STAT delete_hits 0
STAT incr_misses 0
STAT incr_hits 0
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 3
STAT cas_badval 1
STAT touch_hits 0
STAT touch_misses 0
STAT auth_cmds 0
STAT auth_errors 0
STAT bytes_read 274
STAT bytes_written 143
STAT limit_maxbytes 67108864
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT time_in_listen_disabled_us 0
STAT threads 4
STAT conn_yields 0
STAT hash_power_level 16
STAT hash_bytes 524288
STAT hash_is_expanding 0
STAT slab_reassign_rescues 0
STAT slab_reassign_chunk_rescues 0
STAT slab_reassign_evictions_nomem 0
STAT slab_reassign_inline_reclaim 0
STAT slab_reassign_busy_items 0
STAT slab_reassign_busy_deletes 0
STAT slab_reassign_running 0
STAT slabs_moved 0
STAT lru_crawler_running 0
STAT lru_crawler_starts 7
STAT lru_maintainer_juggles 2817
STAT malloc_fails 0
STAT log_worker_dropped 0
STAT log_worker_written 0
STAT log_watcher_skipped 0
STAT log_watcher_sent 0
STAT log_watchers 0
STAT unexpected_napi_ids 0
STAT round_robin_fallback 0
STAT bytes 65
STAT curr_items 1
STAT total_items 6
STAT slab_global_page_pool 0
STAT expired_unfetched 0
STAT evicted_unfetched 0
STAT evicted_active 0
STAT evictions 0
STAT reclaimed 0
STAT crawler_reclaimed 0
STAT crawler_items_checked 6
STAT lrutail_reflocked 0
STAT moves_to_cold 7
STAT moves_to_warm 1
STAT moves_within_lru 0
STAT direct_reclaims 0
STAT lru_bumps_dropped 0
END

stats settings
STAT maxbytes 67108864
STAT maxconns 1024
STAT tcpport 11211
STAT udpport 0
STAT inter NULL
STAT verbosity 2
STAT oldest 0
STAT evictions on
STAT domain_socket NULL
STAT umask 700
STAT shutdown_command no
STAT growth_factor 1.25
STAT chunk_size 48
STAT num_threads 4
STAT num_threads_per_udp 4
STAT stat_key_prefix :
STAT detail_enabled no
STAT reqs_per_event 20
STAT cas_enabled yes
STAT tcp_backlog 1024
STAT binding_protocol auto-negotiate
STAT auth_enabled_sasl no
STAT auth_enabled_ascii no
STAT item_size_max 1048576
STAT maxconns_fast yes
STAT hashpower_init 0
STAT slab_reassign yes
STAT slab_automove 1
STAT slab_automove_ratio 0.80
STAT slab_automove_window 30
STAT slab_chunk_max 524288
STAT lru_crawler yes
STAT lru_crawler_sleep 100
STAT lru_crawler_tocrawl 0
STAT tail_repair_time 0
STAT flush_enabled yes
STAT dump_enabled yes
STAT hash_algorithm murmur3
STAT lru_maintainer_thread yes
STAT lru_segmented yes
STAT hot_lru_pct 20
STAT warm_lru_pct 40
STAT hot_max_factor 0.20
STAT warm_max_factor 2.00
STAT temp_lru no
STAT temporary_ttl 61
STAT idle_timeout 0
STAT watcher_logbuf_size 262144
STAT worker_logbuf_size 65536
STAT read_buf_mem_limit 0
STAT track_sizes no
STAT inline_ascii_response no
STAT ext_item_size 512
STAT ext_item_age 4294967295
STAT ext_low_ttl 0
STAT ext_recache_rate 2000
STAT ext_wbuf_size 4194304
STAT ext_compact_under 0
STAT ext_drop_under 0
STAT ext_max_frag 0.80
STAT slab_automove_freeratio 0.010
STAT ext_drop_unread no
STAT ssl_enabled no
STAT ssl_chain_cert (null)
STAT ssl_key (null)
STAT ssl_verify_mode 0
STAT ssl_keyformat 1
STAT ssl_ciphers NULL
STAT ssl_ca_cert NULL
STAT ssl_wbuf_size 16384
STAT ssl_session_cache no
STAT ssl_min_version tlsv1.2
STAT num_napi_ids (null)
STAT memory_file (null)
END
```

**Comment by dormando** [comment]
Hey,

Starting on this: in the binary protocol it looks like most error cases the return CAS value is cleared to zero. In the meta code I copied the way binary protocol was moving the CAS around. When returning, it always returns the CAS value of the item the connection has stashed.

Not sure what's going on with append/prepend yet. I think the underlying item is changing but `c->item` might point to the old item.

So I need to read this a little more carefully:

1) double check append/prepend/incr/decr. Also on looking at the incr/decr code it might not be reflecting the cas properly.
2) Have to make a decision on matching binprot vs meta-specific behavior here.

Matching binprot would mean zeroing out/removing the CAS token for error conditions. Something meta specific could be as you expect here: return what the actual cas value was if the item existed. That would be useful for re-submission, but I'm not sure that's a proper use case. If you're using CAS it means that you're setting some data back based on an expectation of what the data actually was. If you take the returned CAS from EX and re-submit that violates the pattern a bit. It's also not applicable if you're relying on the win/lose/stale tokens.

So at very least I need to blank it or remove it from errors. I'll give this some time to process on my end and if you have any further comments please add here. Thanks!

**Comment by petergoldstein** [comment]
Got it.

I see the argument for the "zero out" behavior on error, and frankly I'd be fine with a zeroed out or un-returned CAS on error.  I do think there's probably a case to be made for returning the CAS of the stored item, but I don't feel strongly enough about it to make it.

I do think that append/prepend (and incr/decr) should return the CAS value on success.  From a quick test it looks like incr/decr works as expected on the success case.  On the failure case (EX) no CAS value is returned at all.

**Comment by dormando** [comment]
Looks like for some reason I thought I couldn't use the `c->cas` item that binprot was using to communicate the CAS errors, but on audit I don't see why not.

I'll wire it up to match binprot more exactly then make a final decision on when to return non-zero. I _feel_ like it should return the cas of the underlying value when it can. This won't match binprot exactly, but between meta and binprot CAS return is already optional. All cases where binprot was zeroing its CAS return the status code should give enough information as to whether or not you should actually use that CAS value.

**Comment by dormando** [comment]
I think append/prepend are correct now. The CAS value should change when the item actually gets appended, and the return value should make sense?

**Comment by dormando** [comment]
out in 1.6.13
