### ISSUE TITLE
I want to know why After Memcache enables log output（-vv）, hexadecimal is printed

### ISSUE THREAD

**Issue by zhangchangwei** [memcached/memcached#846]
I want to know why After Memcache enables log output（-vv）, hexadecimal is printed
authenticated() in cmd 0x0b is true
>147 Writing bin response:
>147   0x81 0x0b 0x00 0x00
>147   0x00 0x00 0x00 0x00
>147   0x00 0x00 0x00 0x06
>147   0x00 0x00 0x00 0x00
>147   0x00 0x00 0x00 0x00
>147   0x00 0x00 0x00 0x00
<215 Read binary protocol data:
<215    0x80 0x0b 0x00 0x00
<215    0x00 0x00 0x00 0x00
<215    0x00 0x00 0x00 0x00
<215    0x00 0x00 0x00 0x00
<215    0x00 0x00 0x00 0x00
<215    0x00 0x00 0x00 0x00

![Uploading image.png…]()

**Comment by dormando** [comment]
Sorry, I missed this issue. The hex is the raw binary protocol output. Verbose mode is for debugging purposes mostly.
