### ISSUE TITLE
Runaway CPU usage on high memory servers (>1B items)

### ISSUE THREAD

**Issue by gvengel** [memcached/memcached#855]
After upgrading from memcached 1.5.6 on Ubuntu 18.04 to memcached 1.5.22 on Ubuntu 20.04, I started having issues where everything would be fine during initial cache fill, but then CPU usage would go crazy around 750GB of cached data. After a bunch of debugging, I finally figured out the tipping point was actually when switching from hashpower=31 to 32. Armed with information, I looked through the changes from 1.5.6 to 1.5.22, and discovered that dae3191 introduced an integer overflow which breaks the hash table.

With dae3191 reverted, performance is restored to normal, even with `hashpower=32` and greater than two billion items. 

**To Reproduce**
* Run memcached >= 1.5.14 with `-o hashpower=31`
* Generate a moderate amount of load with memslap (or similar)
* Everything is fine
* Rerun memcached `-o hashpower=32`
* Generate a moderate amount of load with memslap
* memcached will consume all available CPU

**System Information**
 - OS/Distro: Ubuntu Server
 - Version of OS/distro: 20.04
 - Version of memcached: 1.5.22
 - Hardware detail: AMD 7702P, 1TB DDR4

**Comment by dormando** [comment]
Thanks for the report and the fix/test! Golden! :)

Note mostly for me but maybe also for you: I thought I had capped the hashpower value to not go over 30 or 31 (and also tested it at 31), so I need to dig into why that failed. It's been long enough that I forgot what I did. There were other things that may start to fail or act odd when the hash table gets near or above 2^32 so I wanted to simply avoid it for a while. One major issue is surprise at runtime, as it allocates a new hashtable, and migrates before dropping the old one: that ends up being a lot of memory at the high end and causes people to OOM. That has been giving people a really bad time in production.

**Comment by gvengel** [comment]
Yeah, while debugging I realized how expensive increasing the hashpower could be. All my servers now start with hashpower preset to its expected max value to prevent runtime expansion. 

For what it's worth, I was running at hashpower 31 on memcached 1.5.6 for many years without issue, and haven't had any problems on my patched 1.5.22 build. If there are more bugs lurking out there, they must be subtle. :)

Memcache is an absolute workhorse. Thanks for being the bedrock we build on. ❤️

**Comment by dormando** [comment]
Great, thanks :)

I see the bug now, but haven't been able to reproduce the CPU runaway locally. A backtrace may have helped here. There's only one place where hashsize should actually cast through to a 64bit number.

**Comment by gvengel** [comment]
Note, mixed up that the problem actually happens at hashpower=32 not 31. Updated the original post to reflect that. More details in the PR.

**Comment by dormando** [comment]
released in 1.6.14
