### ISSUE TITLE
Building w/ PROXY mode but running without --proxy_config crashes

### ISSUE THREAD

**Issue by smukil** [memcached/memcached#860]
We noticed a crash when we built memcached with `./configure --enable-proxy` but do not provide the `proxy_config` startup flag.

On examining the core file, I found that it crashes here:
https://github.com/memcached/memcached/blob/894e4c16b5162e25ce649cf8a57dfad250965ab0/proto_proxy.c#L494

Which is called from here:
https://github.com/memcached/memcached/blob/894e4c16b5162e25ce649cf8a57dfad250965ab0/memcached.c#L3835

Since the proxy context was never initialized, `arg` is 0x0 and dereferencing it causes the crash.

I believe an appropriate fix would be to check if `proxy_enabled` is true at the beginning of `proxy_start_reload()`, as is similarly the case in `proxy_stats()`:
https://github.com/memcached/memcached/blob/894e4c16b5162e25ce649cf8a57dfad250965ab0/proto_proxy.c#L414-L416

Since `proxy_start_reload()` is not a hot function, the overhead of this check should be negligible.

If the fix seems reasonable, I can send in a patch.

**Comment by dormando** [comment]
Just pushed a fix for this to `next` myself. Was temporarily confused by a missing detail: Requires `SIGHUP` sent to cause the crash :) By the time I figured that out I'd already written it, trivial change.

thanks!

**Comment by dormando** [comment]
released in 1.6.14
