### ISSUE TITLE
configure: error: libevent2 is required

### ISSUE THREAD

**Issue by bobrowski** [memcached/memcached#866]
Fresh OS install, compiled libevent [libevent-2.1.12-stable].

During memcached configure i get the error:

`configure: error: libevent2 is required, libevent is in /usr/local/lib.`

Compiling memcached 1.6.7 error does not happen.

**System Information**
 - OS/Distro: Ubuntu
 - Version of OS/distro: 20.04.3 LTS (GNU/Linux 5.4.0-99-generic x86_64)
 - Version of memcached: 1.6.13
 - Hardware detail: Xeon

**Comment by LINKIWI** [comment]
On Ubuntu, you can `sudo apt-get install libevent-dev`

**Comment by gulmezmerve** [comment]
I faced with same error. Good to check with config.log. It shows actually where the error comes from. From my side, it couldn't find one of the shared library, not related to libevent
