### ISSUE TITLE
Issue while running make command

### ISSUE THREAD

**Issue by sforsendil** [memcached/memcached#867]
Issue while running make command

I am trying to install this Azure app service with OS Debian GNU/Linux 10  and nginix setup. I am using PHP 8 version.
While i am trying run the make command it failed and giving me below are the error:

/home/site/ini/memcached-1.6.12# make && make test
make[1]: Entering directory '/home'
make[1]: *** No rule to make target 'stamp-h1'.  Stop.
make[1]: Leaving directory '/home'
make: *** [Makefile:631: config.h] Error 2

**System Information**
 - OS/Distro: Debian GNU/Linux 10 - Azure App service 
 - Version of OS/distro:  Debian GNU/Linux 10 - Azure App service 
 - Version of memcached: memcached-1.6.12
 - Hardware detail: 200 GB HDD 4G RAM

**Comment by dormando** [comment]
did you run `./configure` first?

**Comment by sforsendil** [comment]
Hi @dormando 

Thanks for your response. 

Yes ./configure done and i am attaching the out the same 

`root@myserver:/home/site/ini/memcached-1.6.12# ./configure --prefix=/usr/local/memcached
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for icc in use... no
checking for clang in use... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether __SUNPRO_C is declared... no
checking for gcc option to accept ISO C99... none needed
checking sasl/sasl.h usability... yes
checking sasl/sasl.h presence... yes
checking for sasl/sasl.h... yes
checking for gcov... /usr/bin/gcov
checking for main in -lgcov... yes
checking size of void *... 8
checking for library containing clock_gettime... none required
checking for library containing socket... none required
checking for library containing gethostbyname... none required
checking for libevent directory... (system)
checking for library containing gethugepagesizes... no
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inttypes.h... (cached) yes
checking for sasl_callback_ft... yes
checking for print macros for integers (C99 section 7.8.1)... yes
checking for an ANSI C-conforming const... yes
checking for socklen_t... yes
checking whether byte ordering is bigendian... no
checking for htonll... no
checking for library containing pthread_create... none required
checking for mlockall... yes
checking for getpagesizes... no
checking for sysconf... yes
checking for memcntl... no
checking for clock_gettime... yes
checking for preadv... yes
checking for pread... yes
checking for eventfd... yes
checking for accept4... yes
checking for getopt_long... yes
checking for alignment... none
checking for GCC atomics... yes
checking for GCC 64bit atomics... yes
checking for setppriv... no
checking for pledge... no
checking for cap_enter... no
checking for xml2rfc... no
checking for xsltproc... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands

root@myserver:/home/site/ini/memcached-1.6.12# make && make test
make[1]: Entering directory '/home'
make[1]: *** No rule to make target 'stamp-h1'.  Stop.
make[1]: Leaving directory '/home'
make: *** [Makefile:631: config.h] Error 2

`

**Comment by dormando** [comment]
Sorry, I have no idea what's going on here. I don't know how `stamp-h1` is getting in there and the path prints don't make any sense. You shouldn't compile things as root as well.

This doesn't seem to be a bug on our side. there's something weird with your system or how you unpacked the source.
