### ISSUE TITLE
Deadlocking in start_item_crawler_thread

### ISSUE THREAD

**Issue by ryancaicse** [memcached/memcached#886]
Hi, there is a potential deadlock case between start_item_crawler_thread and item_crawler_thread. In the method start_item_crawler_thread, if the child thread created at Line565 first reaches `pthread_cond_signal(&lru_crawler_cond); `, the parent thread then reaches Line 573 and could wait forever due to the lost notify.  We should use a bool variable to ensure that the notification hasn't yet been executed, just like Line 418.

https://github.com/memcached/memcached/blob/c472369fed5981ba8c004d426cee62d5165c47ca/crawler.c#L558-L577

https://github.com/memcached/memcached/blob/c472369fed5981ba8c004d426cee62d5165c47ca/crawler.c#L408-L418

**Comment by dormando** [comment]
thanks! I'm not sure that's true though; the item crawler thread can't send the signal until the lru_crawler_lock is released, which it isn't until the main thread is waiting on the condition.

**Comment by ryancaicse** [comment]
Oh, I ignore the holding lock. I think your explanation is right, so I close this issue. Thank you very much.
