### ISSUE TITLE
memcached rejects meta-get commands with no flags

### ISSUE THREAD

**Issue by tdyas** [memcached/memcached#906]
**Describe the bug**
A meta-get command without any flags is rejected (probably by the check at https://github.com/memcached/memcached/blob/046c4bb5d8498420c13e5357c8299b60952b2595/proto_text.c#L1067).

**To Reproduce**
Send a meta-get without any flags. E.g., `mg foo`.

**Detail (please include!)**
A meta-get command without any flags is rejected (probably by the check at https://github.com/memcached/memcached/blob/046c4bb5d8498420c13e5357c8299b60952b2595/proto_text.c#L1067) which checks to see if at least three tokens are in the command. This does not work when the command looks like `mg foo` which only has two tokens. The docs seem to suggest this is valid.

The context is that I am implementing an existence check for keys and am not passing the `v` flag to this `mg` command (nor any other flag for that matter). Thus, I will either get an `HD` or `EN` response from which I can determine existence of a value for the key.

I have worked around the problem by passing an unused `O` flag, but I would have expected this to work given the documentation.

**Comment by dormando** [comment]
Hey, thanks!

I remember this being a deliberate decision, but I can't remember offhand anymore why I had done that. So I'll review the situation.

**Comment by dormando** [comment]
https://github.com/memcached/memcached/pull/938 for a fix

**Comment by dormando** [comment]
released in 1.6.18
