### ISSUE TITLE
Clarification about libmemcached/pylibmc

### ISSUE THREAD

**Issue by pythonmobile** [memcached/memcached#907]
One of our projects uses memcached, which is accessed using pylibmc (which in turn depends on libmemcached). It looks like both pylibmc and libmemcached need updates to keep up with changes in memcache. Is there any plans to do this by the community? Or perhaps one should migrate out of using pylibmc at this point? (https://github.com/lericson/pylibmc/issues/278) - Please let me know.

**Comment by dormando** [comment]
Hey,

I'll say first that we won't be doing anything that makes libmemcached incompatible with memcached; the only thing we've deprecated is the binary protocol and odds are I could leave that in there for another 5+ years (though I make no promises!). So you're missing out on the meta protocol and the features it provides.

I've been delayed on but am experimenting with having a very lightweight C lib that does text and meta protocol (https://github.com/dormando/mcmc). Once I get a chance to flesh that out a bit I'll look at options for getting broader client support, or getting existing libraries updated. Some library authors are waking up and porting to meta already so it might just be a matter of time.
I'm trying to take the same opportunity to thin out the thousands of options clients have (we don't need 10+ hash functions, for instance).

If you want meta sooner look around for some other python folks who might be writing a meta client, or porting an existing one might be pretty trivial. libmemcached is complex so not sure it would be easy to add meta there.

These things just take a while and I wasn't able to be making the noise I wanted and finish `mcmc` soon enough. This process takes a while as the software is old/stable.

**Comment by pythonmobile** [comment]
@dormando this looks fantastic. Perhaps mcmc can get a nice CI/CD which tests it against memcached? Do you think it will be production ready anytime soon?

**Comment by dormando** [comment]
`mcmc` will get a lot of things; an actual test suite, added to the CI tests (it's used in the proxy project internally to memcached as well). I unfortunately don't have an estimate on production readyness; it was supposed to be over a year ago but pandemic and so on. Work should be picking up this month so just keep an eye on it if you're curious.
