### ISSUE TITLE
Meta delete with no flags returns HD \r\n... silly, but why the space?

### ISSUE THREAD

**Issue by zenbones** [memcached/memcached#909]
Will return NF r\n on a not found, again with an extra space before the terminator. If there are no flags is seems to me there should be no space between the return op code and the terminator. I know this is miniscule, but I thought I'd point it out.

**Comment by dormando** [comment]
legit bug. I fixed that in a few other places but looks like I missed this one, thanks!

**Comment by dormando** [comment]
dunno why this got closed before getting fixed, mind if I leave it open until I actually fix it? :)

Looking at the code briefly it looks like meta delete has a WANT_TOKENS_MIN of 3, the same as mset and mget, so it was assuming a flag but that check doesn't work for some reason.

I don't _think_ the final version was intending to require a flag on meta delete, so some of the print logic just needs to rewire to get rid of that space before the carriage return.

**Comment by dormando** [comment]
https://github.com/memcached/memcached/pull/938 for a fix

**Comment by dormando** [comment]
released in 1.6.18
