### ISSUE TITLE
In the below case, is the memcached hardware(CPU/LAN card) the limit or some software issue?

### ISSUE THREAD

**Issue by digirave** [memcached/memcached#910]
In the below case, is the memcached hardware(CPU/LAN card) the limit or some software issue?

We noticed at over 300,000 memcached requests per second and at about 2.5~3 Gbps traffic memcached suspected problems occur.
memcached server hardware(and hardware connecting to it) is
Intel Corporation Ethernet Controller 10-Gigabit X540-AT2 (rev 01)
with 10GBASE-T, short less than 5 m cat 7 cable hooked up to Cisco Nexus switch as layer 2 network.
CPU for memcached server: Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz
OS for memcached server: Redhat Enteprise Linux 8.5

memcached config:
MAXCONN="600000"
CACHESIZE="30000"
OPTIONS="-l {internalip_redacted} -t 8"

memcached version:
memcached-1.6.14-1.el8.remi.x86_64

debug information:
Regarding: https://github.com/memcached/memcached/wiki/Timeouts
listen_disabled_num -> normal
Is the machine in swap? no
Is the machine overloaded? it seems so in below graph but these are servers dedicated fully to memcached

Unfortunately could not run [mc_conn_tester.pl](http://mc_conn_tester.pl/) when problems occurred. Also timeouts were not noted, only memcached requests and connections slowing down.

Memcached CPU graph %:
![image](https://user-images.githubusercontent.com/6678253/178736989-51237d34-7521-4bde-b67e-8a0f0e4b906b.png)

Memcached CPU graph detailed:
![image](https://user-images.githubusercontent.com/6678253/178737011-6ba12e1c-ba49-4563-8cd6-95fb590c7049.png)

Memcached requests per second:
![image](https://user-images.githubusercontent.com/6678253/178737031-441c4a7d-6198-44a3-8a09-b3465561fdd6.png)

App profiler showing although other portions slowing down, mostly memcached is slowing down severely:
![image](https://user-images.githubusercontent.com/6678253/178737059-2b79e68b-2c7b-4b1a-a470-874171e6f058.png)

Thank you.

**Comment by dormando** [comment]
Unfortunately there are a lot of dimensions of system performance that aren't easy to see from a few graphs.

I'd push on getting conn_tester running over localhost to figure out if the issue is network or not, which at least cuts the problem in half.

If the issue is in the server configuration, there are a lot of more general guides to tuning performance on network servers which will get you what you need. I'd also consider looking at performance second-to-second via htop/top/something to see if you're micro bursting to capacity which would get averaged out over graphs.

have you used any of the available memcached benchmark programs to test the hardware outside of production traffic?

**Comment by digirave** [comment]
Thank you for your response.

Regarding dormando's reply "push on getting conn_tester running over localhost":
When we recently had about 10~15% memcached response time increase in APP profiler I got mc_conn_tester.pl running on the internal network, I will try using localhost next time(our memcached instances aren't listening to localhost at this time so we will need to restart them all).
These conditions may or may not be the same as when we got the severe response time increases.
I averages 150 values of mc_conn_tester.pl output.
When response time was slightly increased:
Averages
Elapsed 0.000744826, Connection 0.000309134, Set 0.000262018, Get 0.000142491

When response time was normal:
Averages
Elapsed 0.000651147, Connection 0.000274482, Set 0.000233992, Get 0.000114999

It seems everything slows down a bit.
Of note this are dedicated memcached instance.

When the responses increase, software IRQ cpu usage increases 
![image](https://user-images.githubusercontent.com/6678253/178896523-447d829d-11f3-4d42-9d86-06ef301182a7.png)

Regarding dormando's reply "consider looking at performance second-to-second via htop/top/something to see if you're micro bursting to capacity which would get averaged out over graphs":
I do this often, the cpu usage itself seems stable on memcached servers.

Regarding dormando's reply "available memcached benchmark programs to test the hardware outside of production traffic":
I am not familiar with such tools, is there a specific benchmark program you would recommend?

**Comment by dormando** [comment]
I use mc-crusher for development testing but it might not be that easy to use. If you just give a google and try a few of them something's bound to work.

A lot of what could be going on or tuned here is unfortunately outside the realm of support I can give; if you're hitting a specific bottleneck or bug with the daemon we can work that out, but it's likely you just have to do some OS tuning. Memcached has pretty good defaults, so all I'd recommend from the daemon side of things is that you have enough worker threads (`-t`). They can be 1:1 with the number of CPU's on a dedicated system, but I'd advise cpus minus one or two for overhead.

Using a benchmark tool to reproduce your problem and a systems expert you should be able to figure out any tuning required.

**Comment by digirave** [comment]
Thank you for your reply.
I will close this issue.
