### ISSUE TITLE
rejected_connections and total_connection are almost the same

### ISSUE THREAD

**Issue by victorburgos12** [memcached/memcached#918]
**Bug description**
In Memcached running in socket mode, rejected_connections and total_connection are almost the same all the time.

**System Information**
 - OS/Distro: Ubuntu
 - Version of OS/distro: 20.04.3 LTS
 - Version of Memcached: 1.5.22
 - Hardware detail: 64Gi RAM, 16 core intel vm

**Detail (please include!)**
I am running some web servers with apache and Memcached, I suspect something is not working because Memcached is not using almost any RAM on my systems.

Trying to debug I used memcstat and I noticed that memcached current bytes are very low.
```
memcstat --servers /tmp/memcached.sock
         bytes: 2205093
```

I also noticed that rejected_connections are almost the same as total_connections:  
```
         total_connections: 134864
         rejected_connections: 134863
```
I suspected there were many connections and that was the problem, however, current connections never exceed 12 and max connections is set to 1000:
```
         max_connections: 1000
         curr_connections: 7
```

I wanted to check if maybe I was hitting max_connections when I wasn't monitoring the stats, and I found that listen_disabled_num would let you know if this is the case, however it reports 0:

```
listen_disabled_num: 0
```

I found out that rejected_connections is related to maxconns_fast
This is what I found:
```
maxconns_fast: Manages how Memcached processes new connections when the maximum number of clients is reached. 
When maxconns-fast is set to false, connections exceeding the maximum connection limit are added to a queue. 
When maxconns-fast is set to true, connections exceeding the maximum connection limit are dropped and served an error message.
```

If I add the optional parameter `-o no_maxconns-fast` to `/etc/memcached.con`, rejected_connections disappears but I am not sure if they are on queue.

I would like to know if this is a bug or else why I'm getting rejected_connections even when my curr_connections is so low.

Thanks for your help.

**memcached debug output**
```
>42 STORED
<41 connection closed.
<42 connection closed.
<46 set dso6qcxxxxxxxthckh2l 0 3600 0
>46 STORED
<46 connection closed.
<38 new auto-negotiating client connection
38: Client using the ascii protocol
<38 get d79xxxxxxxx4d0vor2
>38 END
<38 get 8a6a5dd1c240
>38 END
<38 set 8a6a5dd1c240 1 300 461
>38 STORED
<38 get v1.xxxxxx.xxxxxx
>38 END
<38 get baxxxxxxxi-V1
>38 sending key babxxxxxxxxx-V1
>38 END
<38 set babxxxxxxxxxV1 1 0 1147
>38 STORED
<38 get cxxxxxxxx2
>38 END
<38 set cxxxxxxxxxxxxt 0 3600 2489
>38 STORED
<41 new auto-negotiating client connection
41: Client using the ascii protocol
<41 get ldjexxxxxxxxxi1bu0p763par
>41 END
<41 get 37xxxxxxxxbe
>41 END
<38 get 23fdb0xxxxxxxxxxxxx5a330ef6
38 sending key 23fdxxxxxxxxxxxx30ef6
>38 END
```

**stats**
```
         pid: 2093515
         uptime: 19649
         time: 1660081325
         version: 1.5.22
         libevent: 2.1.11-stable
         pointer_size: 64
         rusage_user: 28.168456
         rusage_system: 23.093686
         max_connections: 2500
         curr_connections: 7
         total_connections: 134864
         rejected_connections: 134863
         connection_structures: 28
         reserved_fds: 20
         cmd_get: 286476
         cmd_set: 164564
         cmd_flush: 0
         cmd_touch: 0
         cmd_meta: 0
         get_hits: 123195
         get_misses: 163281
         get_expired: 763
         get_flushed: 0
         delete_misses: 0
         delete_hits: 0
         incr_misses: 0
         incr_hits: 0
         decr_misses: 0
         decr_hits: 0
         cas_misses: 0
         cas_hits: 0
         cas_badval: 0
         touch_hits: 0
         touch_misses: 0
         auth_cmds: 0
         auth_errors: 0
         bytes_read: 33466574
         bytes_written: 96817193
         limit_maxbytes: 18899533824
         accepting_conns: 1
         listen_disabled_num: 0
         time_in_listen_disabled_us: 0
         threads: 4
         conn_yields: 0
         hash_power_level: 16
         hash_bytes: 524288
         hash_is_expanding: 0
         slab_reassign_rescues: 0
         slab_reassign_chunk_rescues: 0
         slab_reassign_evictions_nomem: 0
         slab_reassign_inline_reclaim: 0
         slab_reassign_busy_items: 0
         slab_reassign_busy_deletes: 0
         slab_reassign_running: 0
         slabs_moved: 0
         lru_crawler_running: 0
         lru_crawler_starts: 16131
         lru_maintainer_juggles: 1054275
         malloc_fails: 0
         log_worker_dropped: 0
         log_worker_written: 0
         log_watcher_skipped: 0
         log_watcher_sent: 0
         bytes: 2205093
         curr_items: 23145
         total_items: 164564
         slab_global_page_pool: 0
         expired_unfetched: 131730
         evicted_unfetched: 0
         evicted_active: 0
         evictions: 0
         reclaimed: 127264
         crawler_reclaimed: 9953
         crawler_items_checked: 26189653
         lrutail_reflocked: 236
         moves_to_cold: 160637
         moves_to_warm: 5418
         moves_within_lru: 13111
         direct_reclaims: 0
         lru_bumps_dropped: 0
```

**Comment by dormando** [comment]
It sounds like for whatever reason the file descriptor limit is extremely low. It should be at least 1024. check `ulimit -a` in the same context as the memcached daemon's user? Based on the number of reserved fds and a few other things it smells like you might have a limit of 32 or 64 somehow, which is absurd.

Sorry it's a little convoluted: if you disable maxconns then you pay attention to listen_disabled_num instead. If that's zero then you're probably not maxing out anymore.

how was memcached installed on here?

**Comment by victorburgos12** [comment]
Hi dormando, thanks for your help.
If I run ulimit in the same context as memcache, I get nothing back (I think that if I don't get anything back, it means that there are no limits set):
```
runuser -l memcache -c 'ulimit -SHa'
```

If I run ulimit as root, I can see that open files is set at 1024:
```
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 253860
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 253860
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

I have disabled maxconns on another server and this is what I get on listen_disabled_num:
```
listen_disabled_num: 0
```

These are other checks on the system:
```
more /proc/sys/fs/file-nr
25536   0       9223372036854775807

cat /proc/sys/fs/file-max
9223372036854775807
```

**Comment by dormando** [comment]
I don't honestly have any good ideas as to how you're ending up in that situation.

If you wouldn't mind testing, please check the commandline for memcached (out of ps), stop the service, then manually run it from root using that command line (it'll drop into the specified user). don't add the `no_maxconns` stuff so it's the same as when you first had a problem. That would rule out any weirdness in the start environment. That config file just gets translated to commandline arguments so it isn't hard to start it manually.

Also if you're up for it you can script up something to make a bunch of connections and see if you're able to get more than a few dozen running.

**Comment by victorburgos12** [comment]
Started memcached directly with command:
```
/usr/bin/memcached -v -m 18024 -u memcache -s /tmp/memcached.sock -a 777 -c 1000 -P /var/run/memcached/memcached.pid
```
Same behavior, rejected_connections, and total_connection are almost the same.
I have a graph to monitor these 2 stats, and this is how they look (they overlap):

![image](https://user-images.githubusercontent.com/37320468/183815962-b3a7dc68-9eb2-4888-81fb-62140268e494.png)

Maybe the script test will give me more information, I found [this script](https://gist.github.com/maartendekeizer/29fb0135c97943f2014a69397620ce46) but only works with TCP sockets and not UNIX sockets (I don't know how to change it).
I will search for other script and will post any findings here.

If someone else has some more ideas to test, please let me know.

Thanks dormando.

**Comment by dormando** [comment]
Ahhh wait. I hate these old versions. I think the rejected_connections counter was actually bugged for a while.

Any chance you could build latest from tarball and try? or at least one from a few versions newer. Broke my own rule by not asking for a test on a newer version, and it doesn't seem like you said your app is actually seeing errors

**Comment by victorburgos12** [comment]
dormando, it was the version, I really appreciate your help, I learned a lot debugging this problem.
New stats:
      ```
         max_connections: 1024
         curr_connections: 48
         total_connections: 63919
         rejected_connections: 0
```
