### ISSUE TITLE
[question] What is the limit size of key and value with extstore

### ISSUE THREAD

**Issue by ilixiaocui** [memcached/memcached#931]
I want to know what is the limit size of key and value with **extstore**

**Comment by dormando** [comment]
Key and value limits are the same as normal memcached, except that value cannot be larger than the extstore write buffer. By default this is 2 or 4 megabytes.

I think that's what you're asking. Sorry if I don't understand.

**Comment by ilixiaocui** [comment]
This answered my questio. Thanks a lot!
