### ISSUE TITLE
How to get all keys with SASL enabled?

### ISSUE THREAD

**Issue by RobiNN1** [memcached/memcached#933]
I created a Memcached tool in php, and without SASL I can view all keys (using `lru_crawler metadump all`). I am using the PECL Memcached extension. And `fsockopen()` to get all keys because the builtin `getAllKeys()` doesn't work correctly.

However, when I enable SASL, `getAllKeys()` returns false, which is not at all surprising since this extension has a lot of bugs. But when I want to use `fsockopen()` and SASL I need to send binary data. That's not a problem, authentications works well as well as other commands like stats with `0x10` opcode.

The only problem is that the `lru_crawler` command probably cannot be used or is not documented correctly. I assume that this is a problem directly in Memcached and not in the client.

Is there any way to achieve this?

Memcached server 1.6.17 in Docker.

**Comment by dormando** [comment]
Sorry, there's no way to do this (and sorry for the late response, I didn't see this somehow). SASL requires the binary protocol, and the binary protocol doesn't have the "get all keys" debug command or the lru crawler commands.

The text protocol has an authentication mode that can be enabled as well; see doc/protocol.txt for explanation. If that's sufficient you can stick to the text protocol and run the lru crawler commands again.

**Comment by RobiNN1** [comment]
The question is: Is it compatible with a server where SASL is enabled? Because the authentication mode you mentioned seems to be something else.

https://github.com/memcached/memcached/blob/597645db6a2b138710f01ffe5e92e453117b987a/doc/protocol.txt#L186-L202

**-Y option**

```
-Y, --auth-file=<file>    (EXPERIMENTAL) enable ASCII protocol authentication. format:
                          user:pass\nuser2:pass2\n
```

**Comment by dormando** [comment]
As I said in the original comment, SASL requires the binary protocol, and the binary protocol does not have the lru_crawler commands. I did not port SASL to text protocol since it was a source of common user error and other similar software never used it.

**Comment by RobiNN1** [comment]
Ok, thanks for the response. I assume it won't be added so I closing this.

**Comment by dormando** [comment]
Yeah; sorry. Binprot is in maintenance mode and won't be getting new commands. User requests can drive changes in the text protocol but I've not gotten a single request for SASL support yet.
