### ISSUE TITLE
enabling ktls offloading

### ISSUE THREAD

**Issue by neelpatelbiz** [memcached/memcached#940]
directions specified in doc/tls.txt:
"Kernel TLS offload (kTLS): when compiled with OpenSSL 3.0.0+ with the `enable-ktls` build-time
option set, and running on Linux with kernel version 4.17+ with `CONFIG_TLS` enabled, memcached can
transparently offload cryptography operations to the kernel. Depending on a variety of factors"

Following these steps not seem to utilize the hardware accelerator in the Mellanox adapter on our server (at least counters are not updating when running memcached over tls)

Before running memcached/memtier benchmark:
$ethtool -S enp2s0f0  | grep -e 'rx_tls_decrypted_packets' \
-e 'tx_tls_encrypted_packets' \
-e 'tx_tls_ctx' \
-e 'rx_tls_ctx' \
-e 'rx_tls_decrypted_bytes' \
-e 'tx_tls_encrypted_bytes'
tx_tls_encrypted_packets: 205840
tx_tls_encrypted_bytes: 17066236
tx_tls_ctx: 210
rx_tls_decrypted_packets: 30505501
rx_tls_decrypted_bytes: 45801379927
rx_tls_ctx: 210

After running memcached/memtier benchmark:
$ethtool -S enp2s0f0  | grep -e 'rx_tls_decrypted_packets' \
-e 'tx_tls_encrypted_packets' \
-e 'tx_tls_ctx' \
-e 'rx_tls_ctx' \
-e 'rx_tls_decrypted_bytes' \
-e 'tx_tls_encrypted_bytes'
tx_tls_encrypted_packets: 205840
tx_tls_encrypted_bytes: 17066236
tx_tls_ctx: 210
rx_tls_decrypted_packets: 30505501
rx_tls_decrypted_bytes: 45801379927
rx_tls_ctx: 210

**Comment by dormando** [comment]
Hey,

unfortunately the person who contributed the ktls change no longer works on memcached. I don't have any system which can use the KTLS stuff and have no way of validating or supporting it right now. All we do is enable the flag once you pass the start time option and there were no other code changes. You did add `-o ssl_kernel_tls` right?
