### ISSUE TITLE
item_size_max upper limit is mentioned incorrectly

### ISSUE THREAD

**Issue by nshetty15** [memcached/memcached#941]
The item size upper limit is mentioned to be 1MB here - https://github.com/memcached/memcached/blob/master/memcached.c#L258

However the actual upper limit is 1GB.

**Comment by dormando** [comment]
I don't see anything particularly wrong with this specific comment. it's referring to the default size limit, which is being set on that line?

**Comment by nshetty15** [comment]
@dormando Thanks! That makes sense. 1MB being default value.

**Comment by nshetty15** [comment]
The comment is confusing.  Probably could have been something like `/* The famous 1MB default value */`

**Comment by dormando** [comment]
Sorry, thanks for reaching out.
