### ISSUE TITLE
Build failure using clang-15

### ISSUE THREAD

**Issue by debohman** [memcached/memcached#942]
Specifically, using clang-15.0.2.

There are missing prototype errors and one instance of an unused variable.

Would you like a PR? I have built the changes against both next and master.

**Comment by dormando** [comment]
Go ahead? This is a pretty common thing for people to PR. Note there's already at least one pending: https://github.com/memcached/memcached/pull/928 - not sure if these are the same you're seeing, but it'll get merged soon.

**Comment by debohman** [comment]
Note that #928 has some changes which match mine, but I have additional ones. Any idea when #928 will be merged?

**Comment by dormando** [comment]
it's merged to `next` branch now.

**Comment by debohman** [comment]
Thanks. I will check it out.

**Comment by dormando** [comment]
released in 1.6.18
