### ISSUE TITLE
BSD advertisement clause from ancient libevent

### ISSUE THREAD

**Issue by bgermann** [memcached/memcached#944]
memcached.c still has the BSD advertisement clause from pre-libevent-0.7b versions that was removed with
https://github.com/libevent/libevent/commit/98af43a351fe571c5d562a8c63de5b3839a0e897
Please correct this to reflect its current BSD-3-Clause license.

**Comment by dormando** [comment]
unfortunately you can't license software unless you own the copyright to all of it; and I don't, so I can't.

**Comment by dormando** [comment]
oh I think I get it.. in the usage license bit... think I'll just remove that since it's a library anyway.

**Comment by dormando** [comment]
released in 1.6.18
