### ISSUE TITLE
memcached support getrange ？

### ISSUE THREAD

**Issue by lidaohang** [memcached/memcached#953]
redis: 
GETRANGE key start end

**Comment by lidaohang** [comment]
@dormando  hi

**Comment by lurkook** [comment]
this package is not maintained for years. i can recommend to read memcached wiki.

https://github.com/memcached/memcached/wiki

**Comment by lidaohang** [comment]
> this package is not maintained for years. i can recommend to read memcached wiki.
> 
> https://github.com/memcached/memcached/wiki

Seen, not supported。  Can we support getrange?

**Comment by dormando** [comment]
No, it's not supported. memcached is a distributed hash table, getrange wouldn't work.

Sorry.

**Comment by lidaohang** [comment]
memcopy substring ?

**Comment by lidaohang** [comment]
> you're looking for getting a byte range within a key? not a range of keys, etc?

Object Storage Add Cache，  get(key, off, limit)     Read 4k from 4M，  Network card full。
