### ISSUE TITLE
Question / Feature request to delete a group / channel of keys

### ISSUE THREAD

**Issue by adrianTNT** [memcached/memcached#956]
Hello.
I don't think ther is an existent feature that allows you to delete a predefined group of keys, is it ?
Maybe something like this can be added ?! ...

So that when creating values, you can optionally specify a group, e.g "User Names Cache":

`$memcached->set('name_of_user_120', 'John Smith', 60*60*24, 'User Names Cache');`

Then later you can delete a group of keys with: `$memcached->delete-group('User Names Cache');`

When having many different values in memcached, the only way to reset all the data is to restart memcached, but I would find it usefull to drop large groups of values like above.

**Comment by sapairsun** [comment]
Em,,,why not use redis?

**Comment by adrianTNT** [comment]
I didn't use Redis at all, but I did see a similar function when I looked at some samples days ago. 
Will need to look more into that if it has functions like these.

**Comment by sapairsun** [comment]
> I didn't use Redis at all, but I did see a similar function when I looked at some samples days ago. 
> Will need to look more into that if it has functions like these.

I think redis could be suitable for you. But note that if the value of the key is very large, it may cause stopping the world.

**Comment by dormando** [comment]
Sorry I missed this. Since memcached is a distributed system that command doesn't make sense; keys are distributed across N servers.

https://github.com/memcached/memcached/wiki/ProgrammingTricks#namespacing

namespacing is the common workaround.
