### ISSUE TITLE
“Background Items Added” notifications loop

### ISSUE THREAD

**Issue by philsherry** [memcached/memcached#967]
### The bug
The new-ish macOS “Background Items Added” notification adds multiple notifications for memcached, regardless of acceptance, not stopping until turned off in “Allow in the background” in Login Items. (Not the preferred outcome.)

### To Reproduce
Install (via `brew install memcached`) and watch the notifications pile up, like the attached screenshot.

### System Information
 - OS/Distro: macOS Ventura
 - Version of OS/distro: macOS 13.1 (22C65)
 - Version of memcached: 1.6.17 (via `brew install memcached`)
 - Hardware detail: 3 GHz 6-Core Intel Core i5

### Detail
![memcached-homebrew](https://user-images.githubusercontent.com/272769/208872224-859a59ac-5647-4a6e-a45d-b9812dc471ef.png)

**Comment by dormando** [comment]
Thanks, unfortunately I have no idea who maintains the brew script and thus cannot help you. Is there an author/maintainer tag inside brew somewhere?

**Comment by philsherry** [comment]
Ahh, many apologies. 

In that case… \**checks the [memcached.rb](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/memcached.rb) formula*\*

I shall take it to the correct place and close this. 🫡
