### ISSUE TITLE
Windows Memcached got error 0xc0000005

### ISSUE THREAD

**Issue by marcolungo** [memcached/memcached#975]
Hi,
I've installed Windows Memcached on Windows Server 2022 - Apache 2.54 - PHP 8.1.5
I got this error: [https://prnt.sc/hZuzzXPqNn9i](url) [https://prnt.sc/ogQbC4H1zaGF](url)
Could anyone help me to understand and resolve the error?
Thank you!

**Comment by dormando** [comment]
Sorry, windows isn't supported by the official repository. You might have better luck at windows-centric support forums.
