### ISSUE TITLE
File descriptor leak in version 1.5.16

### ISSUE THREAD

**Issue by himanshusahu06** [memcached/memcached#984]
**Describe the bug**
It seems memcache is leaking file descriptor and active connection keeps increasing till it hit the limit. We are running the memcached with 25K connections limit. We've around 180 unique clients connected to single node. Each client is generating ~ 1-10 connections. Normally, active number of connection fluctuates b/w 500 to 2000 but within span of 1-5 minutes, number of connection spikes to 25K and after that it stopped accepting new connections.

Initially, we though client might've opened these many connections but this was not the case. When I looked at the `netstat`, there were **zero established connections**, **25K open FDs** and memcache `stat` also reported **25K active connections**. It seems kernel has closed the connection  but due to some internal issue, memcache doesn't get callback and didn't get close fds and reduced connection count.

During the impact, cpu utilization reduced to zero, get & set operation were dropped to zero, cache eventually expired after 10 mins (we've set cache TTL as 10 mins), unused memory dropped to almost zero. Issue remain persisted till we restart the node. We've tried setting the idle_timeout as 2s but that too didn't work.

**System Information**
 - OS/Distro: Linux
 - Version of memcached: 1.5.16
 - Hardware detail: 8cpu, 10gb, x86_64 Intel(R) Xeon(R) CPU @ 2.80GHz

**Detail (please include!)**
Currently we don't have setup where we can run these commands. I'll update the bug if I could repro the issue again.  I've already included most of the detail above.

**Comment by dormando** [comment]
Thanks for the report! I'm certainy interested in figuring this out. You didn't leave much detail besides a description of the symptoms though. Would you mind answering a few more things?

- OS/Distro: "linux" - can you provide something like `cat /etc/lsb-release` and `uname -a` ?
- How often is this happening? Just once or multiple times?
- Did this happen with previous versions?
- Did you do any recent upgrades or any other changes?
- Can you provide the start arguments to memcached?
- `stats` and `stats settings` output from your instance under normal circumstances is still very helpful, so I can see which features are in use.

**Comment by himanshusahu06** [comment]
Hi @dormando, Please find the details

1. Linux version: `GCP's Container-Optimized OS, 93-16623.102.8 LTS`
2. It's happening frequently but when that's unpredictable.
3. Did this happen with previous versions  - I don't think so.
4. Did you do any recent upgrades or any other changes? - No
5. Start argument: `-p 11211 -m 29492 -t 8 -c 65000 -v`

stats setting
```
STAT maxbytes 30924603392
STAT maxconns 65000
STAT tcpport 11211
STAT udpport 0
STAT inter NULL
STAT verbosity 1
STAT oldest 0
STAT evictions on
STAT domain_socket NULL
STAT umask 700
STAT growth_factor 1.25
STAT chunk_size 48
STAT num_threads 8
STAT num_threads_per_udp 9
STAT stat_key_prefix :
STAT detail_enabled no
STAT reqs_per_event 20
STAT cas_enabled yes
STAT tcp_backlog 1024
STAT binding_protocol auto-negotiate
STAT auth_enabled_sasl no
STAT auth_enabled_ascii no
STAT item_size_max 1048576
STAT maxconns_fast yes
STAT hashpower_init 0
STAT slab_reassign yes
STAT slab_automove 1
STAT slab_automove_ratio 0.80
STAT slab_automove_window 30
STAT slab_chunk_max 524288
STAT lru_crawler yes
STAT lru_crawler_sleep 100
STAT lru_crawler_tocrawl 0
STAT tail_repair_time 0
STAT flush_enabled yes
STAT dump_enabled yes
STAT hash_algorithm murmur3
STAT lru_maintainer_thread yes
STAT lru_segmented yes
STAT hot_lru_pct 20
STAT warm_lru_pct 40
STAT hot_max_factor 0.20
STAT warm_max_factor 2.00
STAT temp_lru no
STAT temporary_ttl 61
STAT idle_timeout 0
STAT watcher_logbuf_size 262144
STAT worker_logbuf_size 65536
STAT track_sizes no
STAT inline_ascii_response no
```

stats
```
STAT pid 1
STAT uptime 608950
STAT time 1674460193
STAT version UNKNOWN
STAT libevent 2.0.21-stable
STAT pointer_size 64
STAT rusage_user 2770.289165
STAT rusage_system 3234.604832
STAT max_connections 65000
STAT curr_connections 25000
STAT total_connections 671148
STAT rejected_connections 0
STAT connection_structures 25005
STAT reserved_fds 45
STAT cmd_get 0
STAT cmd_set 211114895
STAT cmd_flush 0
STAT cmd_touch 0
STAT get_hits 0
STAT get_misses 0
STAT get_expired 0
STAT get_flushed 0
STAT delete_misses 0
STAT delete_hits 0
STAT incr_misses 0
STAT incr_hits 0
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT touch_hits 0
STAT touch_misses 0
STAT auth_cmds 0
STAT auth_errors 0
STAT bytes_read 12469541590
STAT bytes_written 5947573321
STAT limit_maxbytes 30924603392
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT time_in_listen_disabled_us 0
STAT threads 8
STAT conn_yields 0
STAT hash_power_level 18
STAT hash_bytes 2097152
STAT hash_is_expanding 0
STAT slab_reassign_rescues 32283463
STAT slab_reassign_chunk_rescues 0
STAT slab_reassign_evictions_nomem 10893
STAT slab_reassign_inline_reclaim 1340991
STAT slab_reassign_busy_items 714238
STAT slab_reassign_busy_deletes 0
STAT slab_reassign_running 0
STAT slabs_moved 3399
STAT lru_crawler_running 0
STAT lru_crawler_starts 72336
STAT lru_maintainer_juggles 2424355
STAT malloc_fails 0
STAT log_worker_dropped 0
STAT log_worker_written 0
STAT log_watcher_skipped 0
STAT log_watcher_sent 0
STAT bytes 22500000
STAT curr_items 250000
STAT total_items 243398358
STAT slab_global_page_pool 4
STAT expired_unfetched 210150749
STAT evicted_unfetched 0
STAT evicted_active 0
STAT evictions 0
STAT reclaimed 174303391
STAT crawler_reclaimed 35847358
STAT crawler_items_checked 4230370755
STAT lrutail_reflocked 0
STAT moves_to_cold 211060434
STAT moves_to_warm 0
STAT moves_within_lru 0
STAT direct_reclaims 0
STAT lru_bumps_dropped 0
```

**Comment by dormando** [comment]
Hey,

How was memcached installed on here? Is it from source or provided by GCP? I notice the `version` is broken in stats output.

What was your previous version? Have you attempted to downgrade at all?

**Comment by dormando** [comment]
@himanshusahu06 - haven't herad back in a month. I'm going to close this issue soon. I've not seen or heard of anything like this and I do a lot of testing.
