### ISSUE TITLE
Should expiry timestamp be a 32-bit integer

### ISSUE THREAD

**Issue by QuChen88** [memcached/memcached#993]
Currently, the expiration timestamp is a signed 32-bit integer value. See https://github.com/memcached/memcached/blob/master/proto_text.c#L1938

Should this be 64-bit instead? Signed 32-bit integer can go up to 2147483648. The current epoch timestamp is 1676405493. Seems like this is something that is reasonable to do?

**Comment by dormando** [comment]
Sadly I cannot expand the item header by a single byte; it can cost people hundreds of thousands of dollars if they use small items.

The timestamp is relative to the start time of the proxy, so it's not really a problem in practice. It would only fail if your cache node were running uninterrupted for 30 something years.

TTL's are supposed to be relative as well: "30" for 30 seconds from now. The only time they're used as a timestamp is when you're trying to set a specific date to time out at, which the server then converts to a relative TTL.

There are some PR's for allowing timestamp-based TTL's past 2038 but I haven't had time to verify them yet. All we need to do is accept the larger number and clamp it so you can't break things by setting an expiration 100 years out.

**Comment by QuChen88** [comment]
Right. Seems like the TTL timestamp is intended to be relative time in seconds from now. It is only used as unix epoch timestamp when people set it to be greater than 1 month in code. This should be relatively rare use-case.
